### ISSUE TITLE
[SuperEditor] - Toggling an attribution is not possible on first selection of document

### ISSUE THREAD

**Issue by robertodoering** [superlistapp/super_editor#1007]
### Description

When trying to toggle an attribution either through a keyboard shortcut (like the default `cmd + b` for **bold**) or by calling `ComposerPreferences.toggleStyle(boldAttribution)` directly, the attribution doesn't become active if it was called on the first selected that a user made.

i.e.
1. User focuses the document
2. User presses `cmd + b`
3. User writes text
-> actual: written text has no attribution
-> expected: text is written in **bold**

Tested on the latest stable `3.7.0` using super_editor `0.2.3+1`

### Details

What might be the cause of this issue:
When `ComposerPreferences.toggleStyle(boldAttribution)` is called it causes `SuperEditorState._updateComposerPreferencesAtSelection` to be called, which in turn calls `_composer.preferences.clearStyles();` and immediately clears the attribution that we just enabled.

### Showcase:

<details><summary>minimal example</summary><p>

```dart
import 'package:flutter/material.dart';
import 'package:super_editor/super_editor.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  late final DocumentComposer _composer;
  late final DocumentEditor _editor;

  @override
  void initState() {
    super.initState();

    _composer = DocumentComposer();
    _editor = DocumentEditor(
      document: MutableDocument(
        nodes: [
          ParagraphNode(
            id: '1',
            text: AttributedText(text: 'example text'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          children: [
            ElevatedButton(
              onPressed: () {
                setState(() {
                  _composer.preferences.toggleStyle(boldAttribution);
                });
              },
              child: const Text('toggle attribute bold'),
            ),
            Expanded(
              child: SuperEditor(
                editor: _editor,
                composer: _composer,
                inputSource: DocumentInputSource.ime,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</p></details>

https://user-images.githubusercontent.com/20045287/214872670-374060f6-7c00-4c4b-8059-f34ed046ea35.mov

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll
