### ISSUE TITLE
[SuperEditor]Can you give me a sample of how to customize the toolbar?

### ISSUE THREAD

**Issue by nrikiji** [superlistapp/super_editor#1020]
Can you give me a sample of how to customize the toolbar?

Here is what I want to do
- I want to hide all items except the ones I need.
- I want to add my own buttons.

![screen](https://user-images.githubusercontent.com/4780752/217405838-4098bc59-a84c-4b7a-af75-fd2ae03cd0fd.png)

**Comment by nrikiji** [comment]
Is it correct to copy the [KeyboardEditingToolbar](https://github.com/superlistapp/super_editor/blob/main/super_editor/lib/src/default_editor/document_ime/mobile_toolbar.dart) and customize it?

**Comment by isaacadariku** [comment]
@nrikiji your question is best suited under discussions. As this is not an issue.

<img width="448" alt="Screenshot 2023-02-09 at 08 58 25" src="https://user-images.githubusercontent.com/46024202/217751644-7cac1874-79ed-4658-be1a-b408a832ef5e.png">

**Comment by matthew-carroll** [comment]
The example app includes all sorts of code that can be inspected, copied, and adjusted. That's currently the extent of our guides. I'm going to close this issue because there's nothing actionable with regard to Super Editor code.
