### ISSUE TITLE
[SuperEditor]If you have sample code to add a node, could you please let me know?

### ISSUE THREAD

**Issue by nrikiji** [superlistapp/super_editor#1021]
What you want to do is as follows

1. the user selects an image from a photo gallery, etc.
2. create an ImageNode based on the selected image
3. add an ImageNode at the caret position

**Comment by nrikiji** [comment]
Resolved.

```dart
commonOps.insertImage(url);
```

**Comment by nrikiji** [comment]
Is it possible to display local images in ImageNode?

**Comment by ngjoni** [comment]
@nrikiji I think your questions are well suited under discussions and not as issues 😅

**Comment by matthew-carroll** [comment]
We don't currently support asset images. We can look into that if a funding company wants that feature.

I'm going to close this issue because it seems to be a series of questions.
