### ISSUE TITLE
[SuperEditor][SuperReader] - Make links clickable, and also other attributions

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#1024]
Make it possible for users to tap/click on links to open a link. Also make it possible to the same with any other attribution that the developer might choose.

**Comment by matthew-carroll** [comment]
@jmatth is there anything more that you think we should capture in this ticket?

Also, what are your thoughts on clickable linked images and other non-text components?

**Comment by matthew-carroll** [comment]
This ticket supersedes https://github.com/superlistapp/super_editor/issues/832 and we should close both at the same time.

**Comment by jmatth** [comment]
For gesture handling, we're specifically looking for Cmd+tap (or Ctrl+tap on non-Apple platforms) in super_editor. This was specified in #832 but didn't get copied over into the description of this ticket, so just calling it out here.

Clickable images and such makes sense is not something we need right now, so I'd vote to skip it unless it ends up being a trivial addition once clickable text spans are implemented.

**Comment by matthew-carroll** [comment]
@jmatth - I've got the behavior working and tested for desktop use-cases.

What're your thoughts on mobile? In a typical mobile experience, the key-to-tap situation doesn't make much sense, but in the situation where a bluetooth keyboard is connected to a tablet, it would.

I'm wondering what you think the key binding check should be for mobile hardware keyboards? I imagine that Apple keyboards for iPad have CMD keys, but I'm wondering if 3rd party iPad keyboards might come with CTRL keys instead?

Also, do you think there should be some affordance to open links on mobile devices without a hardware keyboard? If so, what're your thoughts on that?

**Comment by jmatth** [comment]
In my limited testing the best interface I've seen so far is Google Docs, which requires switching between reading and edit modes via a UI button. In edit mode tapping in a link moves the caret and summons a toolbar that includes a series of options (`Open`, `Edit link`, `Remove link`). In reading mode tapping a link pulls up a card from the bottom of the screen containing a preview of the link target and buttons to copy or navigate to it, though I would find just triggering navigation in that case reasonable as well.

What would you think of just leaving interaction mode off by default on mobile and leaving the tap-to-open behavior as an exercise for the programmer? Looking at the PR, it should be simple to tie a UI toggle to `DocumentComposer.isInInteractionMode`.

In general I think it would make sense for mobile devices with hardware keyboards connected to behave the same as desktop devices. Not sure how feasible that is though, last time I experimented with Flutter on an iPad w/ magic keyboard the results were discouraging. Maybe the last year of updates has improved the situation though.

**Comment by matthew-carroll** [comment]
Ok. So it sounds like we should probably add the tap gesture deference to the mobile interactors, but then leave it at that. I'll update the PR.
