### ISSUE TITLE
Emoji Delete Error - Only Android

### ISSUE THREAD

**Issue by ibrahimdevs** [superlistapp/super_editor#1031]
Hi,

Firstly, thanks for this awesome package and extensive work.

I'm using latest main branch with this code:

```
            SuperTextField(
              controlsColor: AppColors.appPink,
              selectionColor: AppColors.appPink50,
              textAlign: TextAlign.center,
              textController: viewModel.textController,
              focusNode: viewModel.focusNode,
              lineHeight: viewModel.lineHeight,
              textStyleBuilder: (Set<Attribution> attributions) {
                return viewModel.textStyleBuilder(attributions, viewModel.textStyle, false);
              },
              maxLines: null,
            ),
```

It is working on iOS without a problem, but on Android when you type an emoji and click delete, displays unknown square character. If you click delete again, it fixes and completes emoji delete.

Example video:

https://user-images.githubusercontent.com/2773578/219391055-b800483d-d794-4023-90d1-0ad0cd14d70a.MOV

Is there any workaround or fix you can provide?

Thanks,

**Comment by ibrahimdevs** [comment]
cc @matthew-carroll

**Comment by matthew-carroll** [comment]
@angelosilvestre can you try to reproduce and fix? I'm guessing that we're deleting a single codepoint for a glyph with two codepoints. We've seen that before, but the `characters` package was supposed to fix that. Maybe we missed one?

**Comment by angelosilvestre** [comment]
@matthew-carroll  We had a similar issue when navigating using the keyboard. I'll take a look.
