### ISSUE TITLE
[SuperEditor] Pasting text in list items throws exception

### ISSUE THREAD

**Issue by simonbengtsson** [superlistapp/super_editor#1051]
Tried out the demo app and noticed that nothing happens when you paste text in a list item (ordered or unordered). Verified to not be supported in clearful etc as well.

**Steps to reproduce**
1. Copy some text for example with `cmd + c` on mac
2. Create an unordered or ordered list item
3. Paste using for example with `cmd + v` on mac

Looking at the logs it outputs the following unhandled exception ([code line](https://github.com/superlistapp/super_editor/blob/main/super_editor/lib/src/default_editor/common_editor_operations.dart#L2313))

```
Exception: Can't handle pasting text within node of type: [TextNode]
```

Are there any plans to support this?

**Comment by olavemil** [comment]
Seeing the same on mobile.
By loosening the check in https://github.com/superlistapp/super_editor/blob/e4eceea4a72706410a1e910ad0ce01b815c63a8e/super_editor/lib/src/default_editor/common_editor_operations.dart#L2312 from `is! ParagraphNode`  to `is! TextNode` I was able to paste in lists without issue, but there could be other issues I'm not aware of.

**Comment by angelosilvestre** [comment]
@matthew-carroll I tested and this issue seems to be solved. Also, there is a test ensuring we can paste text in list items:

`SuperEditor copy and paste > pastes within a list item`

I think we can close this one.

**Comment by matthew-carroll** [comment]
Sounds good. Thanks.
