### ISSUE TITLE
[SuperEditor][SuperReader] Support Dynamic Type font scaling

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#1055]
`TextField` and `CupertinoTextField` will scale font sizes based on the system-level Dynamic Type accessibility settings. super_editor doesn't seem to scale at all.

In the following screenshots, the top text is part of a `CupertinoTextField` and the bottom text is part of super_editor.

### Standard-sized text
![IMG_1238](https://user-images.githubusercontent.com/6467808/224091867-8e54b4ae-b85e-4b6c-b3bd-c8e839b103cc.jpg)

### Scaled text
![IMG_1239](https://user-images.githubusercontent.com/6467808/224091898-d54ef829-f68f-4338-84e1-033b67fea6f0.jpg)

### Dynamic Type settings
![IMG_1240](https://user-images.githubusercontent.com/6467808/224091949-cb6aaeea-b01e-4795-ab01-c68c29054a79.PNG)

I noticed that `RenderLayoutAwareParagraph` in `super_text.dart` has `textScaleFactor` set to 1.0, which I think *might* be disabling dynamic type:

```
/// A [RenderParagraph] that publicly reports whether or not its
/// layout is valid, and also accepts a callback to notify a listener
/// when the layout is marked invalid.
class RenderLayoutAwareParagraph extends RenderParagraph {
  RenderLayoutAwareParagraph(
    InlineSpan text, {
    TextAlign textAlign = TextAlign.start,
    required TextDirection textDirection,
    bool softWrap = true,
    TextOverflow overflow = TextOverflow.clip,
    double textScaleFactor = 1.0,
    int? maxLines,
    Locale? locale,
    StrutStyle? strutStyle,
    TextWidthBasis textWidthBasis = TextWidthBasis.parent,
    TextHeightBehavior? textHeightBehavior,
    List<RenderBox>? children,
    VoidCallback? onMarkNeedsLayout,
  })  : _onMarkNeedsLayout = onMarkNeedsLayout,
        super(
          text,
          textAlign: textAlign,
          textDirection: textDirection,
          softWrap: softWrap,
          overflow: overflow,
          textScaleFactor: textScaleFactor,
          maxLines: maxLines,
          locale: locale,
          strutStyle: strutStyle,
          textWidthBasis: textWidthBasis,
          textHeightBehavior: textHeightBehavior,
          children: children,
        );
...
```

@matthew-carroll Is there a way to support dynamic type in super_editor?

**Comment by matthew-carroll** [comment]
@Jethro87 are you OK with funding this?

@miguelcmedeiros would Superlist like dynamic font scaling? It's probably relevant for mobile where users like to adjust it system-wide.

**Comment by Jethro87** [comment]
@matthew-carroll Do you have an estimate on how long this will take? We're ok funding <= ~10 hours, but if it will be significantly more we'd like a heads up first.

**Comment by matthew-carroll** [comment]
Sounds good.

@angelosilvestre can you try using the OS text scale factor in super_text_layout? I think we may have tried this before, and had problems, but let's try it again and see if we can make it work with super_text_layout and super_editor.

**Comment by miguelcmedeiros** [comment]
> @miguelcmedeiros would Superlist like dynamic font scaling? It's probably relevant for mobile where users like to adjust it system-wide.

@matthew-carroll yes we can help funding this work, but at the moment it would be limited  from our side as well, given other work in progress like atomic commands which might still require significant effort.
