### ISSUE TITLE
Bold and Italics doesn't serialize correctly

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#107]
Reportedly, italics text with a space at the end is serialized back to normal text.

EDIT:
Repro steps:
 - select a word that is followed by a space
 - apply bold or italics

Buggy result:
The bold/italics includes the trailing space. The trailing space should appear after the bold/italics.

**Comment by salihgueler** [comment]
After #114 still reproducable. I will share videos.

**Comment by ismail-go** [comment]
In my case, still exist a problem in the serialization of the markdown styling.

If the markdown styled text has a space in the begining or end of the text it does not apply markdown styling to the text correctly.

For example;
**bold text**  -> applyed bold styling correctlty but,
**bold text ** -> it seems as it is in the markdown displaying. Cannot applying the markdown styling.

as it is in bold styling, it is also works wrong in the italic, strikethrough etc..

How can we solve the problem? @matthew-carroll @salihgueler @jezell @domesticmouse @bk-one

**Comment by matthew-carroll** [comment]
@ismail-go please provide a set of reproduction steps and please provide your exact version of super_editor and super_editor_markdown
