### ISSUE TITLE
IME Error after insert: Couldn't map an IME position to a document position

### ISSUE THREAD

**Issue by transcendr** [superlistapp/super_editor#1081]
We are running into this new issue on the latest stable SE and Flutter.

Repro steps:

1. Enter some text into a new document (a sentence or so)
2. Insert text into the document via `CommonEditorOperations.insertPlainText`
3. Tap and place cursor just before the inserted text, press enter (new line) once
4. Tap and place cursor just after the inserted text (now on a new line), press enter (go to next line) once
5. Attempt to enter additional text into the document, throws with aforementioned error

Logs:

══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: Couldn't map an IME position to a document position. IME position: TextPosition(offset:
80, affinity: TextAffinity.downstream)

When the exception was thrown, this was the stack:
#0      DocumentImeSerializer._imeToDocumentPosition (package:super_editor/src/default_editor/document_ime/document_serialization.dart:271:5)
#1      DocumentImeSerializer.imeToDocumentSelection (package:super_editor/src/default_editor/document_ime/document_serialization.dart:164:18)
#2      TextDeltasDocumentEditor._applyNonTextChange (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:180:7)
#3      TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:58:9)
#4      DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:213:30)
#5      DeltaTextInputClientDecorator.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:119:14)
#6      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1867:63)
#7      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1753:20)
#8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:555:55)
#9      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:548:34)
#10     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:393:35)
#11     _invoke2.<anonymous closure> (dart:ui/hooks.dart:186:15)
#15     _invoke2 (dart:ui/hooks.dart:185:10)
#16     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#17     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#18     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#19     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664:22)
#20     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
(elided 3 frames from dart:async)

call:
  MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{oldText: It works. Now I
  add one prompt and a new line and it breaksWho was your first true friend?
  , deltaText:
  , deltaStart: 79, deltaEnd: 79, selectionBase: 80, selectionExtent: 80, composingBase: -1,
  composingExtent: -1}, {oldText: It works. Now I add one prompt and a new line and it breaks
  Who was your first true friend?
  , deltaText: , deltaStart: -1, deltaEnd: -1, selectionBase: 80, selectionExtent: 80,
  composingBase: -1, composingExtent: -1}, {oldText: It works. Now I add one prompt and a new line and it breaks
  Who was your first true friend?
  , deltaText: , deltaStart: -1, deltaEnd: -1, selectionBase: 80, selectionExtent: 80,
  composingBase: 80, composingExtent: 83}]}])
════════════════════════════════════════════════════════════════════════════════════════════════════
I/TRuntime.CctTransportBackend(24996): Making request to: https://firebaselogging-pa.googleapis.com/v1/firelog/legacy/batchlog
I/TRuntime.CctTransportBackend(24996): Status Code: 200
D/InputMethodManager(24996): showSoftInput() view=io.flutter.embedding.android.FlutterView{6d84cc8 VFED..... .F...... 0,0-1080,2287 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController(24996): show(ime(), fromIme=true)

Another exception was thrown: Exception: Couldn't map an IME position to a document position. IME position: TextPosition(offset: 81, affinity: TextAffinity.downstream)

**Comment by matthew-carroll** [comment]
When you say "latest stable" do you mean the Pub release, or the `stable` branch of this repo?

**Comment by transcendr** [comment]
@matthew-carroll  yes the stable branch of this repo.

**Comment by matthew-carroll** [comment]
@angelosilvestre can you take a look at this?

**Comment by transcendr** [comment]
@matthew-carroll  I understand via the PR comments that it's not a straightforward fix, it seems. Do you possibly have any update or ETA on when this issue? In our testing, this is the only remaining blocker for us on android.  ios has been working beautifully in production now for quite a while. Many thanks for your efforts on this project and for your quick response.

**Comment by matthew-carroll** [comment]
@transcendr we've released a new Super Editor version, which includes this fix
