### ISSUE TITLE
[SuperEditor] - Add new `Editor` framework

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#1087]
For #748 we're replacing the `DocumentEditor` system with a new edit pipeline. At the center of that pipeline is a class called `Editor`, which essentially replaces `DocumentEditor`.

For this ticket, add `Editor` to the codebase without altering the existing system. We'll do this to get eyeballs on the core API without breaking anything.

**Comment by Dboy233** [comment]
When will the next version be updated? I find that there is now a big difference between the stable version and the main branch. The main branch has fixed some stable releases and is still updating, so I'm worried that when I'm coding from the last release, a new version will be released and I won't be able to fit in well.

**Comment by matthew-carroll** [comment]
@Dboy233 this ticket isn't the appropriate place to ask general questions about project releases or policies. If you're running into specific issues, please file a new ticket.
