### ISSUE TITLE
When is the next release planned?

### ISSUE THREAD

**Issue by Dboy233** [superlistapp/super_editor#1091]
When will the next version be updated? I find that there is now a big difference between the stable version and the main branch. The main branch has fixed some stable releases and is still updating, so I'm worried that when I'm coding from the last release, a new version will be released and I won't be able to fit in well.

**Comment by matthew-carroll** [comment]
We don't have scheduled releases, but we will likely release another Pub version very soon, before we start breaking things for #748 

As for your comment about `main` vs `stable` - there shouldn't be any functional difference between `main` and `stable`. We cherry pick every commit that we can from `main` to `stable`. What differences are you seeing between those two branches?

**Comment by Dboy233** [comment]
> We don't have scheduled releases, but we will likely release another Pub version very soon, before we start breaking things for #748
> 
> As for your comment about `main` vs `stable` - there shouldn't be any functional difference between `main` and `stable`. We cherry pick every commit that we can from `main` to `stable`. What differences are you seeing between those two branches?

Sorry, I'm talking about the last release of super_editor, which is somewhat different from the current main branch.

**Comment by matthew-carroll** [comment]
Ok. I expect us to release another version, probably within the next couple of weeks.
