### ISSUE TITLE
Device soft keyboard not working

### ISSUE THREAD

**Issue by fayeed** [superlistapp/super_editor#110]
Hi, I am integrating this package into our mobile app and it seems that this package doesn't work with the device soft-keyboard, I see that you guys are using `RawKeyboardListener` to registers key presses which doesn't work with the soft-keyboard.

**Comment by salihgueler** [comment]
Our main focus is on Desktop and Web right now. We will check the mobile implementations in the following weeks.

**Comment by matthew-carroll** [comment]
#121 is tracking mobile support. I'm going to close this issue in favor of that one.
