### ISSUE TITLE
Emoji & Symbols panel doesn't snap to caret position

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1105]
Steps to reproduce:
* Place the selection on a `SuperEditor` or `SuperTextField`
* Press CONTROL+COMMAND+SPACE shortcut

**Expected:** opens the Emoji & Symbols panel close to the caret position

![Screenshot 2023-04-27 at 09 32 40](https://user-images.githubusercontent.com/31278849/234806124-c3191ce5-4476-4c04-b072-aaa7a48a2c3f.png)

**Actual:** opens the Emoji & Symbols panel in the middle of the window

![Screenshot 2023-04-27 at 09 33 30](https://user-images.githubusercontent.com/31278849/234806322-b8a64df0-725f-4026-8371-16228027386f.png)

**Comment by matthew-carroll** [comment]
@miguelcmedeiros - was this ever working? Is this something you need us to fix before the next release?

**Comment by miguelcmedeiros** [comment]
> was this ever working?

There was an issue on our side that prevented our app from showing the panel using the shortcut. That got fixed this week and then we noticed this issue.

> Is this something you need us to fix before the next release?

If it's not a heavy lift, then it would be great to take it along.
