### ISSUE TITLE
[SuperTextField][Android] - Predictive Text Strange Behaviors

### ISSUE THREAD

**Issue by ibrahimdevs** [superlistapp/super_editor#1113]
Super Editor - stable branch
Samsung Galaxy S21 FE
Android 13
One UI 5.1

There are weird responses from super text field, when user's predictive text is enabled. When you play a few minutes, you would notice a couple of bugs. @matthew-carroll @angelosilvestre @miguelcmedeiros  

1. When I delete the word's last character and put the same character again. Curser is not at the end, it is 1 character left.
It is happening current word. If I write new word look 2:

<details>
  <summary>Cursor Position - Logs Fine</summary>
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-6aad8d2f-7fff-a7b6-94bb-f379bcf88d0b"><div dir="ltr" style="margin-left:0pt;" align="left">

I  Initializing logger: textfield
I  (31.948) textfield.android > INFO: Attaching TextInputClient to TextInput
I  (31.949) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy├, selection: TextSelection.collapsed(offset: 16, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (31.950) textfield.ime > FINE: Is attached to input client? true
I  (33.686) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning gu├, selection: TextSelection.collapsed(offset: 15, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (34.944) textfield.ime > FINE: Received text editing deltas from platform...
I  (34.945) textfield.ime > FINE: Processing selection/composing change: TextEditingDeltaNonTextUpdate#88c2a(oldText: Good morning gu, selection: TextSelection.collapsed(offset: 15, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (34.945) textfield.ime > FINE: Processing selection/composing change: TextEditingDeltaNonTextUpdate#03871(oldText: Good morning gu, selection: TextSelection.collapsed(offset: 15, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 0, end: 15))
I  (34.948) textfield.ime > FINE: Processing selection/composing change: TextEditingDeltaNonTextUpdate#d15b5(oldText: Good morning gu, selection: TextSelection.collapsed(offset: 15, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (34.949) textfield.ime > FINE: Processing selection/composing change: TextEditingDeltaNonTextUpdate#c86a4(oldText: Good morning gu, selection: TextSelection.collapsed(offset: 15, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (34.950) textfield.ime > FINE: Processing selection/composing change: TextEditingDeltaNonTextUpdate#faaef(oldText: Good morning gu, selection: TextSelection.collapsed(offset: 15, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 13, end: 15))
I  (34.953) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning gu├, selection: TextSelection.collapsed(offset: 15, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 13, end: 15))
I  (34.954) textfield.ime > FINE: Received text editing deltas from platform...
I  (34.955) textfield.ime > FINE: Processing insertion: TextEditingDeltaInsertion#cc7fd(oldText: Good morning gu, textInserted: y, insertionOffset: 15, selection: TextSelection.collapsed(offset: 16, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 13, end: 16))
I  (34.956) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy├, selection: TextSelection.collapsed(offset: 16, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 13, end: 16))
I  (34.965) textfield.ime > FINE: Received text editing deltas from platform...
I  (34.966) textfield.ime > FINE: Processing selection/composing change: TextEditingDeltaNonTextUpdate#b7ac1(oldText: Good morning gu, selection: TextSelection.collapsed(offset: 15, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 13, end: 15))
I  (34.968) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy├, selection: TextSelection.collapsed(offset: 15, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 13, end: 15))
I  (34.976) textfield.ime > FINE: Received text editing deltas from platform...
I  (34.977) textfield.ime > FINE: Processing selection/composing change: TextEditingDeltaNonTextUpdate#22c4d(oldText: Good morning guy, selection: TextSelection.collapsed(offset: 15, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 13, end: 15))

</div><br /></b>
</details>

https://user-images.githubusercontent.com/2773578/236177474-4128bc6b-5244-4276-925e-ce1f0e39e5eb.mp4

2. If I write a new word, press space, then press backspace twice, then put the word's original last character, then press space and this word disappears. 

<details>
  <summary>Delete Word - Logs Fine</summary>
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-e633bd63-7fff-3e85-e402-6f8f5d25d7e7"><div dir="ltr" style="margin-left:0pt;" align="left">

I  (52.179) textfield.android > FINE: User tapped down
I  (52.236) textfield.android > FINE: User released a tap
I  (52.242) textfield.android > INFO: Attaching TextInputClient to TextInput
I  (52.243) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy├, selection: TextSelection.collapsed(offset: 16, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (52.243) textfield.ime > FINE: Is attached to input client? true
I  (52.537) textfield.android > FINE: Intercepting single tap
I  (5.016) textfield.ime > FINE: Received text editing deltas from platform...
I  (5.016) textfield.ime > FINE: Processing selection/composing change: TextEditingDeltaNonTextUpdate#23670(oldText: Good morning guy, selection: TextSelection.collapsed(offset: 16, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (5.017) textfield.ime > FINE: Processing insertion: TextEditingDeltaInsertion#399ab(oldText: Good morning guy, textInserted:, insertionOffset: 16, selection: TextSelection.collapsed(offset: 17, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (5.018) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy ├, selection: TextSelection.collapsed(offset: 17, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (6.277) textfield.ime > FINE: Received text editing deltas from platform...
I  (6.277) textfield.ime > FINE: Processing insertion: TextEditingDeltaInsertion#1a872(oldText: Good morning guy, textInserted: h, insertionOffset: 17, selection: TextSelection.collapsed(offset: 18, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 17, end: 18))
I  (6.281) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy h├, selection: TextSelection.collapsed(offset: 18, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 17, end: 18))
I  (6.813) textfield.ime > FINE: Received text editing deltas from platform...
I  (6.814) textfield.ime > FINE: Processing insertion: TextEditingDeltaInsertion#211c7(oldText: Good morning guy h, textInserted: e, insertionOffset: 18, selection: TextSelection.collapsed(offset: 19, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 17, end: 19))
I  (6.815) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy he├, selection: TextSelection.collapsed(offset: 19, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 17, end: 19))
I  (7.577) textfield.ime > FINE: Received text editing deltas from platform...
I  (7.578) textfield.ime > FINE: Processing insertion: TextEditingDeltaInsertion#578fa(oldText: Good morning guy he, textInserted: y, insertionOffset: 19, selection: TextSelection.collapsed(offset: 20, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 17, end: 20))
I  (7.584) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy hey├, selection: TextSelection.collapsed(offset: 20, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 17, end: 20))
I  (8.582) textfield.ime > FINE: Received text editing deltas from platform...
I  (8.583) textfield.ime > FINE: Processing insertion: TextEditingDeltaInsertion#fef5c(oldText: Good morning guy hey, textInserted:, insertionOffset: 20, selection: TextSelection.collapsed(offset: 21, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (8.584) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy hey ├, selection: TextSelection.collapsed(offset: 21, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (9.534) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy hey├, selection: TextSelection.collapsed(offset: 20, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (10.552) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy he├, selection: TextSelection.collapsed(offset: 19, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (11.494) textfield.ime > FINE: Received text editing deltas from platform...
I  (11.495) textfield.ime > FINE: Processing selection/composing change: TextEditingDeltaNonTextUpdate#10887(oldText: Good morning guy he, selection: TextSelection.collapsed(offset: 19, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (11.495) textfield.ime > FINE: Processing selection/composing change: TextEditingDeltaNonTextUpdate#ab047(oldText: Good morning guy he, selection: TextSelection.collapsed(offset: 19, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 17, end: 19))
I  (11.496) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy he├, selection: TextSelection.collapsed(offset: 19, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 17, end: 19))
I  (11.498) textfield.ime > FINE: Received text editing deltas from platform...
I  (11.498) textfield.ime > FINE: Processing insertion: TextEditingDeltaInsertion#3311c(oldText: Good morning guy he, textInserted: y, insertionOffset: 19, selection: TextSelection.collapsed(offset: 20, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 17, end: 20))
I  (11.499) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy hey├, selection: TextSelection.collapsed(offset: 20, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 17, end: 20))
I  (11.500) textfield.ime > FINE: Received text editing deltas from platform...
I  (11.500) textfield.ime > FINE: Received text editing deltas from platform...
I  (12.340) textfield.ime > FINE: Processing replacement: TextEditingDeltaReplacement#b7103(oldText: Good morning guy hey, textReplaced: hey, replacementText:, replacedRange: TextRange(start: 17, end: 20), selection: TextSelection.collapsed(offset: 18, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (12.341) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy  ├, selection: TextSelection.collapsed(offset: 18, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
 

</div><br /></b>
</details>

https://user-images.githubusercontent.com/2773578/236179038-e1bd4ccd-3ce5-4360-b000-f8202880fe42.mp4

**Comment by matthew-carroll** [comment]
Are you able to reproduce this problem with the example app in the super_editor repository? If so, can you please share the minimal code needed to that, and let us know the exact steps you took to recreate the issue?

**Comment by ibrahimdevs** [comment]
@matthew-carroll 
Yes, you can reproduce this with the example app too.

**For the 1. case;**
1. Run example > demo_superandroidtextfield.dart
2. Be sure that you "Predictive Text" setting is enabled on keyboard.
3. Scroll to end of text.
4. There is "ullamcorper." word there, delete "." and "r". Now, it is: "ullamcorpe"
5. Put "r"
-> There should be "ullamcorper" but cursor position not at the end, it is before "r". ullamcorpe{cursor}r

** If you try it a couple of times, it starts to work normally. I think because of predictive text learns this text. If it won't work.
- You can put "xyz" end of the last word.
- Click bottom right done to close keyboard and focus
- Touch end of text and open the keyboard again.
- Delete "z", then put "z"
-> You should see ....xy{cursor}z

**For the 2. case;**
1. Run example > demo_superandroidtextfield.dart
2. Be sure that you "Predictive Text" setting is enabled on keyboard.
3. Scroll to end of text.
4. Put space, put "you", put space
5. Backspace to delete space, backspace to delete "u"
6. Put "u", put space
-> It should cause to disappear "you" completely.

** This steps should do exactly, because predictive text works complicated, even the same steps sometimes I can't get the same error. And It differs to put new words or change them in terms of Predictive Text work mechanism. So we click "Done" to close keyboard and change the state of Predictive Text.

Do you need more info?
