### ISSUE TITLE
[SuperTextField][Android] - Cursor Jumps

### ISSUE THREAD

**Issue by ibrahimdevs** [superlistapp/super_editor#1114]
When I touch middle of the text cursor comes there(with extra pointer), then I touch end of sentence cursor goes there(with extra pointer). Then I'm typing some characters and cursor jumps very fast into middle of the sentence, then end and put the character without a problem. But it feels that something jumpy and not stable. @matthew-carroll @angelosilvestre 

I mean (with extra pointer):
![Screenshot 2023-05-04 at 13 58 18](https://user-images.githubusercontent.com/2773578/236185217-8123c3bf-dee0-4740-995b-fb398f919f11.png)

- Cursor actually at end, I touch a character
![Screenshot 2023-05-04 at 14 04 17](https://user-images.githubusercontent.com/2773578/236186673-ee472251-e02e-4274-bb64-f086f4d3422a.png)
- Then extra pointer jumps to old position very fast
![Screenshot 2023-05-04 at 14 04 07](https://user-images.githubusercontent.com/2773578/236186739-631ed181-ac92-4b19-a048-9aa8e24fa967.png)
- Then put my inserted character
![Screenshot 2023-05-04 at 14 04 32](https://user-images.githubusercontent.com/2773578/236186848-d30961be-f10f-4800-9013-5e55c4786bf0.png)

<details>
  <summary>Logs Fine</summary>
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-f3244cb0-7fff-0863-eef4-3a53beae20f1"><div dir="ltr" style="margin-left:0pt;" align="left">

I  (40.162) textfield.android > INFO: Attaching TextInputClient to TextInput
I  (40.163) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy├, selection: TextSelection.collapsed(offset: 16, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (40.164) textfield.ime > FINE: Is attached to input client? true
I  (42.535) textfield.android > FINE: User tapped down
I  (42.536) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy├, selection: TextSelection.collapsed(offset: 8, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (42.590) textfield.android > FINE: User released a tap
I  (42.592) textfield.android > FINE: _onPanCancel()
I  (42.592) textfield.android > FINE: _onHandleDragEnd()
I  (42.899) textfield.android > FINE: Intercepting single tap
I  (47.602) textfield.android > FINE: User tapped down
I  (47.603) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy├, selection: TextSelection.collapsed(offset: 16, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (47.664) textfield.android > FINE: User released a tap
I  (47.666) textfield.android > FINE: _onPanCancel()
I  (47.666) textfield.android > FINE: _onHandleDragEnd()
I  (47.966) textfield.android > FINE: Intercepting single tap
I  (48.535) textfield.ime > FINE: Received text editing deltas from platform...
I  (48.535) textfield.ime > FINE: Processing insertion: TextEditingDeltaInsertion#06e62(oldText: Good morning guy, textInserted: h, insertionOffset: 16, selection: TextSelection.collapsed(offset: 17, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (48.537) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guyh├, selection: TextSelection.collapsed(offset: 17, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (49.167) textfield.ime > FINE: Received text editing deltas from platform...
I  (49.168) textfield.ime > FINE: Processing insertion: TextEditingDeltaInsertion#bba8f(oldText: Good morning guyh, textInserted: g, insertionOffset: 17, selection: TextSelection.collapsed(offset: 18, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (49.169) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guyhg├, selection: TextSelection.collapsed(offset: 18, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (51.801) textfield.ime > FINE: Received text editing deltas from platform...
I  (51.801) textfield.ime > FINE: Processing insertion: TextEditingDeltaInsertion#9d4b4(oldText: Good morning guyhg, textInserted: b, insertionOffset: 18, selection: TextSelection.collapsed(offset: 19, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (51.803) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guyhgb├, selection: TextSelection.collapsed(offset: 19, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
</div><br /></b>
</details>

https://user-images.githubusercontent.com/2773578/236185769-4744ab91-a7eb-49a8-91a4-2c7989eaf530.mp4

**Comment by matthew-carroll** [comment]
@ibrahimdevs it's not entirely clear which specific issue you're describing. You mentioned the drag handle multiple times. Is there a problem with the drag handle? Or are you trying to describe a bug with caret placement while you're typing?

**Comment by ibrahimdevs** [comment]
@matthew-carroll it is about to placement of caret's bottom drop. I've done too much test and finally found what is related;
textAlign: TextAlign.center,

You can reproduce it examples > demo_superandroidtextfield.dart file and put "textAlign: TextAlign.center," to "SuperAndroidTextField" then run it.
- Delete all text to see better
- Put "hello world"
- Touch to end of text to appear bottom drop of caret, because it is related with caret's bottom drop. (I mentioned it: (with extra pointer), see the first picture)
- Put any character from keyboard
> You can see that bottom drop of caret jumps to center and come back to end.

If you need any more info?

And I don't know what is the correct word for bottom drop, do you know it?
There are two object;
cursor: blinking line of where you type
cursor's bottom drop: ?? :)

**Comment by matthew-carroll** [comment]
@ibrahimdevs It's called a drag handle. It's there to help you press and drag the caret somewhere else in the field.

@angelosilvestre Can you take a look at this when you get a minute?
