### ISSUE TITLE
Gesture recognition bug, gesture competition is not performed correctly

### ISSUE THREAD

**Issue by Dboy233** [superlistapp/super_editor#1126]
super_editor: ^0.2.5

I added a button to the custom ComponentView when I custom ComponentBuilder, but clicking the button always triggers the SuperEditor cursor shift. I tried to intercept gesture events, but failed. Is there any way that ComponentView can intercept gestures?

I tried to emulate SuperEditor's gesture nesting scene, but ultimately failed.

<img width="353" alt="图片" src="https://github.com/superlistapp/super_editor/assets/37604230/ea43721c-215c-4aa8-ab90-5868bb9313e6">

```dart

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: DemoApp(),
      ),
    ),
  );
}

class DemoApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final gestureSettings = MediaQuery.maybeOf(context)?.gestureSettings;
    return Center(
      child: RawGestureDetector(
        behavior: HitTestBehavior.translucent,
        gestures: {
          TapSequenceGestureRecognizer: GestureRecognizerFactoryWithHandlers<
              TapSequenceGestureRecognizer>(
            () => TapSequenceGestureRecognizer(),
            (TapSequenceGestureRecognizer instance) {
              instance.onTapDown = (d) => print('parent onTapDown');
              instance.onTapUp = (d) => print('parent onTapUp');
              instance.onDoubleTap = () => print("parent onDoubleTap");
              instance.onTripleTapDown =
                  (d) => print("parent onTripleTapDown");
              instance.gestureSettings = gestureSettings;
            },
          )
        },
        child: Stack(
          children: [
            GestureDetector(
              behavior: HitTestBehavior.opaque,
              onTapDown: (d) {
                print("Child 1 onTapDown");
              },
              onTapUp: (d) {
                print("Child 1 onTapUp");
              },
              onTap: () {
                print("Child 1 onTap");
              },
              onDoubleTapDown: (details) {
                print("Child 1 onDoubleTapDown");
              },
              onDoubleTapCancel: () {
                print("Child 1 onDoubleTapCancel");
              },
              onDoubleTap: () {
                print("Child 1 onDoubleTap");
              },
              child: Container(
                color: Colors.blueAccent,
                height: 300,
              ),
            ),
            RawGestureDetector(
              behavior: HitTestBehavior.opaque,
              gestures: {
                TapSequenceGestureRecognizer:
                    GestureRecognizerFactoryWithHandlers<
                        TapSequenceGestureRecognizer>(
                  () => TapSequenceGestureRecognizer(),
                  (TapSequenceGestureRecognizer instance) {
                    instance.onTap = () => print('Child 2 onTap');
                  },
                )
              },
              child: Container(
                color: Colors.yellowAccent,
                width: 100.0,
                height: 100.0,
              ),
            ),
            Positioned(
              bottom: 0,
              right: 0,
              width: 100,
              height: 100,
              child: RawGestureDetector(
                behavior: HitTestBehavior.opaque,
                gestures: {
                  TapSequenceGestureRecognizer:
                      GestureRecognizerFactoryWithHandlers<
                          TapSequenceGestureRecognizer>(
                    () => TapSequenceGestureRecognizer(),
                    (TapSequenceGestureRecognizer instance) {
                      instance.onTap = () => print('Child 3 onTap');
                      instance.onTapDown = (d) => print('Child 3 onTapDown');
                      instance.onTapUp = (d) => print('Child 3 onTapUp');
                      instance.onDoubleTap =
                          () => print("Child 3 onDoubleTap");
                      instance.onTripleTap=() => print("Child 3 onTripleTap");
                    },
                  )
                },
                child: Container(
                  color: Colors.black87,
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}

```

These three containers, no matter which one I click on, trigger SuperEditor's gesture detection

**Click yellow**
<img width="363" alt="图片" src="https://github.com/superlistapp/super_editor/assets/37604230/b57b0716-861f-4dee-98e8-99841ea9a88e">

**Click blue**
<img width="317" alt="图片" src="https://github.com/superlistapp/super_editor/assets/37604230/747bbf67-b5a1-443a-8ed3-07e850be1e13">

**Click black**
<img width="310" alt="图片" src="https://github.com/superlistapp/super_editor/assets/37604230/78bac11a-497f-4ec4-8ca2-b58c111a7ddb">

**Comment by Dboy233** [comment]
Is it possible to deal with gestures with reference to flutter 3.10.0

`flutter/lib/src/widgets/text_selection.dart:2852`


![1 sqmvK_z8gkQw-eFNur6PIQ](https://github.com/superlistapp/super_editor/assets/37604230/7850a666-5a53-420e-bd41-1ac6b93b088c)

**Comment by Dboy233** [comment]
I fixed the problem by forcing the TapGestureRecognizer to accept；

```dart

class PriorityTapGestureRecognizer extends TapGestureRecognizer {
  PriorityTapGestureRecognizer({super.debugOwner, super.supportedDevices});

  @override
  void addAllowedPointer(PointerDownEvent event) {
    super.addAllowedPointer(event);
    //Whatever it is, just accept it, okay
    resolve(GestureDisposition.accepted);
  }
}


```

**Comment by Dboy233** [comment]
Black piece using ` PriorityTapGestureRecognizer `, parent widget no trigger up and tap, so that when I click on child widgets SuperEditor won't accept to up event.
<img width="731" alt="no_tap_mark" src="https://github.com/superlistapp/super_editor/assets/37604230/c0487e20-3f8e-4581-bbe6-b9b6dbc875ac">


The blue block uses GestureDetector. When the blue block is clicked, the parent widget also receives down and up, causing both the blue widget and the parent widget to execute the tap event. This causes the SuperEditor cursor to move when I click on the WIdget.

<img width="741" alt="tap_mark" src="https://github.com/superlistapp/super_editor/assets/37604230/c68720f8-6c8c-4906-b1e4-33f1b1c442fb">

> I don't know how correct this implementation is, but it seems to work where it's used.

example code:

```dart


import 'package:flutter/material.dart';
import 'package:gesture_test/priority_tap_gesture.dart';

import 'multi_tap_gesture.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: DemoApp(),
      ),
    ),
  );
}

class DemoApp extends StatefulWidget {
  @override
  State<DemoApp> createState() => _DemoAppState();
}

class _DemoAppState extends State<DemoApp> {
  @override
  Widget build(BuildContext context) {
    return const ParentGestureWidget(
      child: Center(
        child: Stack(
          children: [
            GestureDetectorWidget(),
            CustomGestureWidget(),
          ],
        ),
      ),
    );
  }
}

class ParentGestureWidget extends StatelessWidget {

  const ParentGestureWidget({Key? key, this.child}) : super(key: key);

  final Widget? child;

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.black54,
      child: RawGestureDetector(
        behavior: HitTestBehavior.translucent,
        gestures: {
          TapSequenceGestureRecognizer: GestureRecognizerFactoryWithHandlers<
                  TapSequenceGestureRecognizer>(
              () => TapSequenceGestureRecognizer(debugOwner: "parent"),
              (instance) {
            instance.onTapDown = (d) => print('parent tap down');
            instance.onTapUp = (details) => print('parent tap up');
            instance.onTap = () => print('parent tap');
          }),
        },
        child: child,
      ),
    );
  }
}

class CustomGestureWidget extends StatelessWidget {

  const CustomGestureWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 200,
      width: 200,
      child: RawGestureDetector(
        gestures: {
          PriorityTapGestureRecognizer: GestureRecognizerFactoryWithHandlers<
                  PriorityTapGestureRecognizer>(
              () => PriorityTapGestureRecognizer(debugOwner: "child black"),
              (instance) {
            instance.onTapDown = (d) => print('child black tap down');
            instance.onTapUp = (details) => print('child black tap up');
            instance.onTap = () => print("cild black tap");
          }),
        },
        child: Container(
          color: Colors.black,
        ),
      ),
    );
  }
}

class GestureDetectorWidget extends StatelessWidget {
  const GestureDetectorWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTapDown: (d) {
        print("child blue onTapDown");
      },
      onTapUp: (d) {
        print("child blue onTapUp");
      },
      onTap: () {
        print("child blue onTap");
      },
      child: Container(
        color: Colors.blueAccent,
        height: 300,
      ),
    );
  }
}


```

**Comment by Dboy233** [comment]
That's a little bit more correct, maybe

```dart
class PriorityTapGestureRecognizer extends TapGestureRecognizer {
  PriorityTapGestureRecognizer({super.debugOwner, super.supportedDevices});
  @override
  void handlePrimaryPointer(PointerEvent event) {
    //maybe need to check cancel
    if (event is PointerUpEvent) {
      resolve(GestureDisposition.accepted);
    }
    super.handlePrimaryPointer(event);
  }
}
```

**Comment by Dboy233** [comment]
`TapSequenceGestureRecognizer` _firstTap event trigger should not be put inside _handleEvent, because double ` DoubleTapGestureRecognizer ` implementation logic is: It doesn't trigger the first click, it just records the first click, so it doesn't 'accept' down and up.
So when it comes to single click and double click and triple click recognition. You need to make an 'accept' judgment on the first click. 


In 'BaseTapGestureRecognizer'

<img width="495" alt="图片" src="https://github.com/superlistapp/super_editor/assets/37604230/d85cf422-a8bc-4249-be5a-8091b484ae61">

**Comment by matthew-carroll** [comment]
> TapSequenceGestureRecognizer _firstTap event trigger should not be put inside _handleEvent, because double DoubleTapGestureRecognizer implementation logic is: It doesn't trigger the first click, it just records the first click, so it doesn't 'accept' down and up.

But our recognizer isn't a double-tap recognizer. Our recognizer recognizes single, double, and triple taps, and it recognizes multiple of them in a row, and it recognizes both down and up events.

Have you tried making your proposed change and then run all the tests?

Can you provide a user-interaction test that fails with the current implementation, but succeeds with your proposed implementation?

**Comment by Dboy233** [comment]
> > TapSequenceGestureRecognizer _firstTap event trigger should not be put inside _handleEvent, because double DoubleTapGestureRecognizer implementation logic is: It doesn't trigger the first click, it just records the first click, so it doesn't 'accept' down and up.
> 
> But our recognizer isn't a double-tap recognizer. Our recognizer recognizes single, double, and triple taps, and it recognizes multiple of them in a row, and it recognizes both down and up events.
> 
> Have you tried making your proposed change and then run all the tests?
> 
> Can you provide a user-interaction test that fails with the current implementation, but succeeds with your proposed implementation?

I am trying to separate the functions of "single click" and " multi click", Combine two gestures。

<img width="636" alt="图片" src="https://github.com/superlistapp/super_editor/assets/37604230/3af6a6fb-f1d4-4e98-9621-6e79ca2da4d1">


The single click function is implemented by the TapGestureRecognizer。

"Multi click" function on the basis of "DoubleTapGestureRecognizer" complete。

I think the minimum priority of the "click" incident. The "up" incident shall be allocated by "GestureArenaManager". 

Can notify user onTap only if GestureArenaManager agrees。

If I can repair this problem, I will try to PR

**Comment by Dboy233** [comment]
@matthew-carroll 
I found that I only needed to modify the detection widget.

TextSelectionGestureDetector It's a perfect solution to this problem。

`stable/packages/flutter/lib/src/widgets/text_selection.dart:2892` , `TextSelectionGestureDetector`

The Widget inside flutter v3.10.0，I mentioned that in my previous answer。

`TextSelectionGestureDetector` There are several methods that need to be implemented, even if they are not used.

I don't think I need PR because the changes are too small. You can replace the widget directly.

> Is it possible to deal with gestures with reference to flutter 3.10.0
> 
> `flutter/lib/src/widgets/text_selection.dart:2852`
> 
> ![1 sqmvK_z8gkQw-eFNur6PIQ](https://user-images.githubusercontent.com/37604230/237629964-7850a666-5a53-420e-bd41-1ac6b93b088c.gif)

<img width="708" alt="图片" src="https://github.com/superlistapp/super_editor/assets/37604230/dd2d69bd-30a6-4bb4-8e1c-172076d9bb57">

https://github.com/superlistapp/super_editor/assets/37604230/841db349-2eac-4387-bc6e-ac0f75e77872

**Comment by matthew-carroll** [comment]
There's a lot of content being posted to this thread. It's difficult to follow what's going on and why.

Can you please describe a singular problem, and provide reproductions for it? A failing test would be nice, too.
