### ISSUE TITLE
DropdownButton fails in Example toolbar

### ISSUE THREAD

**Issue by DouglasWard351** [superlistapp/super_editor#1139]
Running the example application on windows (desktop and edge browser) I find a problem:

In the editor demo: Selecting a word gives you a popup toolbar which shows the current style (e.g. header2). Clicking the down arrow should give a list of styles available. However, I get nothing - the toolbar disappears and I cannot change the style.

What am I doing wrong?

**Comment by matthew-carroll** [comment]
Thanks for filing this. Please let me know if #689 is the problem you're describing.

**Comment by matthew-carroll** [comment]
We haven't received any update on this issue, so I'm going to assume it's the same as #689 and close this as a duplicate.
