### ISSUE TITLE
[SuperEditor][Mobile][Bug] Two consecutive dashes throws Exception

### ISSUE THREAD

**Issue by raulmabe-labhouse** [superlistapp/super_editor#1147]
# Expected behaviour

On Mobile, when I type two consecutive dashes `-` on an empty node, I expect the editor to write these 2 dashes. 

# Actual behaviour

On Mobile, when I type two consecutive dashes `-` on an empty node, the editor removes the first one when the second one is typed. The final result is an empty node.

# Branch

Reproduced on `main`, `stable` on iOS. It works well on desktop.

# Output

This is the error thrown on `main` branch
```
════════ Exception caught by services library ══════════════════════════════════
The following _TypeError was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      TextDeltasDocumentEditor._applyInsertion
document_delta_editing.dart:138
#1      TextDeltasDocumentEditor.applyDeltas
document_delta_editing.dart:69
#2      DocumentImeInputClient.updateEditingValueWithDeltas
document_ime_communication.dart:215
#3      DeltaTextInputClientDecorator.updateEditingValueWithDeltas
ime_decoration.dart:129
#4      TextInput._handleTextInputInvocation
text_input.dart:1857
#5      TextInput._loudlyHandleTextInputInvocation
text_input.dart:1746
#6      MethodChannel._handleAsMethodCall
platform_channel.dart:547
#7      MethodChannel.setMethodCallHandler.<anonymous closure>
platform_channel.dart:540
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
binding.dart:479
#9      _invoke2 (dart:ui/hooks.dart:174:13)
#10     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#11     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#12     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#13     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:686:22)
#14     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{selectionBase: 1, oldText: , selectionAffinity: TextAffinity.downstream, deltaEnd: 0, deltaText: —, deltaStart: 0, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 1, composingBase: -1}]}])
════════════════════════════════════════════════════════════════════════════════
```

**Comment by matthew-carroll** [comment]
@raulmabe-labhouse can you please move this to the PR that you're testing against? Issues with that PR should only be filed in the PR.

**Comment by raulmabe-labhouse** [comment]
@matthew-carroll Last time I tested on `stable` didn't work either, that's why I posted it here

**Comment by matthew-carroll** [comment]
Ok. I'll re-open this ticket. Can you adjust the description of this ticket to focus on the `stable` branch? Also, can you mention if the problem occurs on `main`, too?

And then can you replicate an appropriate description of the problem in the atomic commands PR?

**Comment by raulmabe-labhouse** [comment]
@matthew-carroll Of course, I updated the original issue to include this information

- the bug is present only with the IME
- Replicated on `main` and `stable`

**Comment by angelosilvestre** [comment]
@matthew-carroll This is what I've found so far:

The issue only occurs if we are in a paragraph with a prepended placeholder (any empty paragraph, except the first node).

On iOS, typing two consecutive dashes causes them to be replaced by an "em dash". The OS deletes the first dash and inserts an em dash. This is causing us to be out of sync with the IME.

Here's the detailed sequence of steps:

1. We press enter to create a new paragraph. The selection is placed into the empty paragraph.
2. We send the placeholder ". " to the IME as the current editing value.
3. The user types "-". The IME sends us an insertion delta:
```dart
TextEditingDeltaInsertion(
  oldText: ". ", 
  textInserted: "-", 
  insertionOffset: 2, 
  selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false), 
  composing: TextRange(start: -1, end: -1)
)
```
4. We remove the placeholder and send the update editing value to the IME ("-").
5. The IME seems to sends us an ack:
```dart
TextEditingDeltaNonTextUpdate(
  oldText: "-", selection: 
  TextSelection(baseOffset: 0, extentOffset: 1, isDirectional: false), 
  composing: TextRange(start: -1, end: -1)
)
```
6. The user types the second "-". Instead of sending an insertion, the IME attempts to replace the "-" with an em dash. I'm not sure why, but instead of receiving a replacement delta we receive a deletion delta followed by an insertion delta (in separate delta lists)
7. The IME dispatches the deletion delta:
```dart
TextEditingDeltaDeletion(
  oldText: "-", 
  textDeleted: "-", 
  deletedRange: TextRange(start: 0, end: 1), 
  selection: TextSelection.collapsed(offset: 0, affinity: TextAffinity.downstream, isDirectional: false), 
  composing: TextRange(start: -1, end: -1)
)
```
8. We apply the deletion delta and now our text is empty. We send the placeholder ". " again to the IME as the current editing value. Now we are out of sync, because we think the editing value is ". " but the IME thinks it's "—" (the em dash).
9. The IME completes the replacement operation by sending us an insertion delta:
```dart
TextEditingDeltaInsertion(
 oldText: "", 
 textInserted: "—", 
 insertionOffset: 0, selection: TextSelection.collapsed(offset: 1, affinity: TextAffinity.downstream, isDirectional: false), 
 composing: TextRange(start: -1, end: -1)
 )
```
10. We fail to map the ime position to the document position because we are out of sync and crash.

I was able to write a test demonstrating this issue:

```dart
testWidgetsOnIos('handles two dashes to insert an em dash', (tester) async {
  // Pumps an editor we two paragraphs because we need to simulate the situation
  // where we prepend a placeholder to the node's text.
  await tester //
      .createDocument()
      .withTwoEmptyParagraphs()
      .withInputSource(TextInputSource.ime)
      .pump();

  // Place caret at the start of second paragraph.
  await tester.placeCaretInParagraph('2', 0);

  // Send initial delta inserting a "-".
  // As we are in an empty paragraph, our current editing text on the IME
  // is the placeholder ". ".
  await tester.ime.sendDeltas(
    const [
      TextEditingDeltaInsertion(
        oldText: '. ',
        textInserted: '-',
        insertionOffset: 2,
        selection: TextSelection.collapsed(offset: 3),
        composing: TextRange(start: -1, end: -1),
      ),
    ],
    getter: imeClientGetter,
  );

  // We change the IME text editing value and get an ack back.
  // Simulate the ack from the platform.
  await tester.ime.sendDeltas(
    const [
      TextEditingDeltaNonTextUpdate(
        oldText: '-',
        selection: TextSelection(baseOffset: 0, extentOffset: 1),
        composing: TextRange(start: -1, end: -1),
      ),
    ],
    getter: imeClientGetter,
  );

  // After pressing the second "-", the OS deletes the previous "-" and inserts an em dash.

  // Simulate the first delta removing the "-".
  await tester.ime.sendDeltas(
    const [
      TextEditingDeltaDeletion(
        oldText: '-',
        deletedRange: TextRange(start: 0, end: 1),
        selection: TextSelection.collapsed(offset: 0),
        composing: TextRange(start: -1, end: -1),
      ),
    ],
    getter: imeClientGetter,
  );

  // Simulate the delta inserting the em dash.
  await tester.ime.sendDeltas(
    const [
      TextEditingDeltaInsertion(
        oldText: '',
        textInserted: '—', // This is an em dash, not a regular dash.
        insertionOffset: 0,
        selection: TextSelection.collapsed(offset: 1),
        composing: TextRange(start: -1, end: -1),
      ),
    ],
    getter: imeClientGetter,
  );

  // Ensure that the text of the second paragraph is an em dash.
  expect(SuperEditorInspector.findTextInParagraph('2').text, '—');
});
```

**Comment by angelosilvestre** [comment]
@matthew-carroll Yes. We are receiving separate batches for insertion and deletion.

**Comment by matthew-carroll** [comment]
@angelosilvestre can you raise this with Renzo if you haven't already? This is another example of this problem with non-transactional deltas.

**Comment by angelosilvestre** [comment]
Filed https://github.com/flutter/flutter/issues/129061

**Comment by angelosilvestre** [comment]
This was fixed by https://github.com/flutter/engine/pull/43267. I'm going to close this.
