### ISSUE TITLE
ios soft kbd paste button not usable 

### ISSUE THREAD

**Issue by biancashouse** [superlistapp/super_editor#1149]
If you make a selection, normally you can tap the paste icon that appears at the top-left of the ios soft keyboard.
None of the icons are enabled: cut, copy, paste, undo/redo.
And super-editor has its own kbd hider icon. Why ?
I took a look at appflowy, and that isn't even comilable atm.
Back to SelectableText and contemplating wheel reinvention, sigh...

**Comment by biancashouse** [comment]
Actually, it looks like the issue is with iOS 16, because I just notice it with an ordinary TextField.

**Comment by matthew-carroll** [comment]
Hi @biancashouse if you'd like for us to take action when you file a ticket, please follow standard practices for doing so. This ticket isn't productive as it stands right now. I'll wait a couple days for you to update it. If you don't, then I'll close it.

BTW, we have no association with AppFlowy

**Comment by matthew-carroll** [comment]
Closing this ticket due to inactivity and non-actionable.
