### ISSUE TITLE
[SuperEditor] - Convert leading hashes to headers (like markdown)

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#1159]
When the user begins a paragraph with a series of hashes, followed by a space, convert that paragraph into a header.

```
# Header 1

## Header 2

### Header 3

etc.
```

**Comment by jmatth** [comment]
We already added this in our fork a while back when this functionality was baked into the common editor operations code. Here's the diff: https://github.com/BringingFire/super_editor/commit/c14dc7fb19cf7d053e55c04912681aee18d31c73. I'm going to end up porting it to the new commands system anyway. If you'd like I can send a PR.

**Comment by matthew-carroll** [comment]
@jmatth there's already a PR up for this. Is that PR missing anything?

**Comment by jmatth** [comment]
Sorry, didn't realize that existed. Just looked it over and LGTM.

**Comment by matthew-carroll** [comment]
Implemented with https://github.com/superlistapp/super_editor/pull/1164
