### ISSUE TITLE
[super_editor][IOS]When the software keyboard automatically completes the text, it causes the loss of the text style.

### ISSUE THREAD

**Issue by Dboy233** [superlistapp/super_editor#1167]
super_editor: 0.2.6

As the title suggests, if I set the text to bold before entering text, and then after entering some content, the software keyboard pops up the recommended content, clicking on the recommended text content will cause the previously set bold effect to be lost.

https://github.com/superlistapp/super_editor/assets/37604230/ec610720-acb2-49e9-beae-c0f19b436934

**Comment by matthew-carroll** [comment]
Can you confirm whether this problem happens on `main`?

**Comment by Dboy233** [comment]
> Can you confirm whether this problem happens on `main`?

@matthew-carroll  Yes, there are also issues in the main branch.
