### ISSUE TITLE
Only List Elements in editors cause the elements to be gathered at the first item

### ISSUE THREAD

**Issue by salihgueler** [superlistapp/super_editor#117]
Steps to reproduce

- Create an empty editor
- Add a list (ordered or unordered) 
- Add items to it
- Save it (serialize it)
- It gathers all the items at first item

**Comment by matthew-carroll** [comment]
@salihgueler I tried reproducing this in the demo app by removing all content from the markdown demo and then starting a list. I tried both an unordered list and ordered list, both of those lists serialize fine.

Can you clarify the reproduction steps?

**Comment by salihgueler** [comment]
This was caused by a problem on the app. Closing it.
