### ISSUE TITLE
[super_editor][IOS]Error occurs when using the iOS software keyboard to suggest text.

### ISSUE THREAD

**Issue by Dboy233** [superlistapp/super_editor#1171]
verison:0.2.6

Although the state of TextInput has been modified when using suggested text, when receiving data changes for the second time, TextInput still retains its previous state."

Replication process for the bug, please watch the video.

https://github.com/superlistapp/super_editor/assets/37604230/f5f0856f-38f3-466f-96fa-ba679a9ffd20

**Comment by matthew-carroll** [comment]
Can you please see if this problem occurs on `main`? Also which version was https://github.com/superlistapp/super_editor/issues/1174 logged against? If that was also 0.2.6 can you check that one on `main` too?

**Comment by Dboy233** [comment]
I am testing in the main branch, and #1171 cannot be reproduced anymore, but the issue with #1174 still persists.

**Comment by matthew-carroll** [comment]
Thanks. I'll close this issue and leave #1174 open.
