### ISSUE TITLE
[SuperEditor] Support for em dash (—)

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1177]
When the user types 2 dashes ("--") it should convert to a an em dash ("—").
This should work as well when the user types 3 dashes at the beginning of a paragraph. The first 2 dashes would first be converted to an em dash and then the third dash would convert the paragraph into an horizontal rule.

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by matthew-carroll** [comment]
I'm curious about saying this "should" happen. Is this expected to be an automatic IME conversion? Or is this purely a preference about content changes, and underlying input systems won't otherwise try to enforce this? If it's purely preference, I'm curious if you can add an `EditReaction` that does this for Superlist, rather than automatically doing it for everyone?

**Comment by miguelcmedeiros** [comment]
> Is this expected to be an automatic IME conversion?

I honestly don't know.

The idea behind this ticket is to mimic that same behavior we see in many other apps (Apple Notes, Apple Reminders, Slack, Linear, etc.).

Sure, we can implement this on Superlist, but I guessed other apps that use SuperEditor would benefit from it as well.

**Comment by matthew-carroll** [comment]
How about we start with it in Superlist and then if others ask for it, we can migrate that into super_editor as an opt-in reaction?

**Comment by matthew-carroll** [comment]
@miguelcmedeiros can you let me know what you think about my comment above?

**Comment by Jethro87** [comment]
FWIW, this is a "nice to have" feature for Clearful, and I would enable it if it were available as an opt-in reaction.

**Comment by matthew-carroll** [comment]
Should "--" become "—" anywhere in text, or only at the beginning of a paragraph?

**Comment by miguelcmedeiros** [comment]
> can you let me know what you think about my comment above?

@matthew-carroll, I built a reaction for this within Superlist at the time that atomic where being worked on. I'm gonna message you the location in our repo of the reaction.

> Should "--" become "—" anywhere in text, or only at the beginning of a paragraph?

That is correct.

In Superlist's implementation, at the start of the text the first 2 dashes get converted into an em-dash and the third then converts the paragraph into a horizontal rule. This only happens on an empty paragraph.

Additionally, if the 3 dashes are typed at the start of a non-empty paragraph, then it could insert a horizontal rule above it, remove the dashes from the paragraph and place the selection at the start of the paragraph. This is not implemented on Superlist.
