### ISSUE TITLE
[SuperEditor][Mobile] Magnifying glass does not work properly

### ISSUE THREAD

**Issue by raulmabe-labhouse** [superlistapp/super_editor#1186]
Magnifying glass is working well on the main example, however, when navigating to `Mobile Editing - Android` and `Mobile Editing - iOS` examples, the magnifying glass becomes almost useless as it constantly fails to magnify

I have attached a video which hopefully explains the issue better:

https://github.com/superlistapp/super_editor/assets/114908263/4fe0dfd1-f7a3-40dc-a72f-ee11cfa2ddab

### Branch

Reproduced on `main`

I have tried to solve it but I can not find where the code is failing... although it should be easy to fix. Any hint? Values like `magnifierFocalPointOffset` are reasonable every time I check them.

**Comment by matthew-carroll** [comment]
Have you used this feature on a real device? I'm wondering if this is a simulator issue...

**Comment by raulmabe-labhouse** [comment]
I tested it on iPhone 11 (iOS 16.3.1) and iPhone 14 Pro (iOS 16.4) and does not work well neither

**Comment by matthew-carroll** [comment]
@angelosilvestre I think we have two tickets for this. I've assigned both of them to you. If they're duplicates, please close one.

**Comment by Jethro87** [comment]
Can confirm this is happening on a real iOS device targeting stable.

**Comment by angelosilvestre** [comment]
This is a duplicate of https://github.com/superlistapp/super_editor/issues/1329, which has an ongoing PR.

I'm closing this one.
