### ISSUE TITLE
[super_reader] Allow long-press to initiate selection

### ISSUE THREAD

**Issue by maxkrieger** [superlistapp/super_editor#1203]
Right now, in a `SuperReader` instance, you have to double-tap and finnick with grab handles to select text ranges. I'd like to be able to long-tap and drag as supported in most mobile apps.

**Comment by matthew-carroll** [comment]
When you long-tap and drag, what defines the selection bounds? Does the selection begin where you long-pressed, and then extend to wherever you drag? Or does the long-press do something more sophisticated like select the word under your finger?

Feel free to include a video.

**Comment by maxkrieger** [comment]
Whatever the native system does! On my iPhone it starts with the whole word under the finger and follows your finger word-by-word.

**Comment by matthew-carroll** [comment]
@Jethro87 would you like to opine with regard to expected long press behaviors on various platforms? Your app is probably the one that's making the most use of `SuperReader`.

**Comment by Jethro87** [comment]
@matthew-carroll  Here's a demo on iOS:

https://github.com/superlistapp/super_editor/assets/6467808/c2ff7ea2-1091-489d-98ba-ac6b3669fb57

It looks like it tries to select the closest word/node. If you let go after long pressing, you can grab the selection handles and drag as normal. If you do not let go, you can drag and select in either direction.

The functionality looks the same on Android:

https://github.com/superlistapp/super_editor/assets/6467808/3f6aea98-708d-47ca-a400-ee1c871c836b

I think this functionality would be nice in super reader. As it stands now, the user has to double-tap to select the closest node, and then drag the handles to change the selection.

**Comment by matthew-carroll** [comment]
@Jethro87 is there any reason that this shouldn't also be the behavior in `SuperEditor`?

**Comment by matthew-carroll** [comment]
I looked at Android long-pressing behavior and noticed the following:

- Selects the word near the long-press.
- Chooses the base and extent based on the first direction the user selects new content. Once the base/extent are chosen, the selection expands by the word in the direction of the selection affinity, and then by character when selecting in the reverse direction.
- When initial long-press selects text, the toolbar is displayed.
- A magnifier is shown while long-press dragging.
- No handles are shown while selecting via long-press.

I also verified behavior on iPhone and found the following:

- Selects word near the long-press.
- The handles animate in almost immediately, even without moving the finger or releasing.
- Selection moves by word in both directions. There's no way to select by the character while dragging after long-press.
- Magnifier shows up immediately and stays present while dragging.
- Toolbar appears after releasing.

**Comment by Jethro87** [comment]
@matthew-carroll I don't see a reason why this shouldn't be the case in super reader.

**Comment by matthew-carroll** [comment]
@Jethro87 I get a haptic response every time the selection moves to another word or character when I'm long-pressing on Android. Does your device do the same thing?

**Comment by Jethro87** [comment]
@matthew-carroll Yes, I also get this on my Pixel.

**Comment by matthew-carroll** [comment]
@Jethro87 Do you happen to have any other Android devices to test on? I realize that mine is also a Pixel. So I'm wondering if it's a universal Android thing we should add, or if we should leave it out because it's only for Pixels/Google?

**Comment by Jethro87** [comment]
@matthew-carroll I have a really old Samsung Galaxy and it only did the haptic response on the initial long press. Continuing to drag did not have any haptic feedback.

**Comment by jmatth** [comment]
@matthew-carroll I have a Galaxy Fold 4 running One UI 5.1.1 based on Android 13. I get haptic feedback on the initial long press + each time the selection updates as I move my finger. It also seems to be applying some heuristic to determine whether to jump by word or single character based on how much the offset moved, though that should probably be out of scope for this specific issue.

https://github.com/superlistapp/super_editor/assets/1316184/5e858c21-8207-48c2-926c-bb471f1401f0

**Comment by matthew-carroll** [comment]
I also noticed that different selection behavior. We can probably get something similar by always selecting by word moving away from the initial selection, and then by character when moving back toward the initial selection.

**Comment by matthew-carroll** [comment]
FYI - I've implemented long press for iOS in SuperEditor and SuperReader. I'm now working on Android.
