### ISSUE TITLE
[SuperEditor] Image issues (atomic commands)

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#1209]
@matthew-carroll I've found several image issues since the atomic commands branch was merged. All issues are present on Android (I will test iOS shortly), and one is present on Mac.

All of the following were run on the `stable` branch of the example app. The only change I made to the code was to add an icon button that calls the following:

```
  void _insertImage() {
    commonOps.insertImage('https://storage.googleapis.com/cms-storage-bucket/c823e53b3a1a7b0d36a9.png');
  }
```

### 1. When an image is first added, the carat doesn't move to the ParagraphNode inserted below the image
Present on **Android**

However, if the same image is added again, this doesn't occur. I'm assuming it has something to do with fetching the image from the network the first time.

https://github.com/superlistapp/super_editor/assets/6467808/146372b4-dd8a-4f09-91f3-647bcbb1db08

### 2. When the carat is to the right of an image and enter/return is pressed, new ParagraphNode's are inserted below (as expected), but the carat does not move
Present on **Android**

https://github.com/superlistapp/super_editor/assets/6467808/0c3cb5f3-dfb1-4dd6-add8-5e8ce7b6d0d5

### 3. Can't add an image in a non-empty paragraph *after a previous image was removed*
Present on **Android** and **Mac**

Add an image, remove it, then add it again where the carat now rests. The following error occurs:

```
════════ Exception caught by foundation library ════════════════════════════════
The following _TypeError was thrown while dispatching notifications for PausableValueNotifier<DocumentSelection?>:
type 'UpstreamDownstreamNodePosition' is not a subtype of type 'TextPosition' in type cast

When the exception was thrown, this was the stack
#0      SuperEditorState._updateComposerPreferencesAtSelection
super_editor.dart:468
#1      ChangeNotifier.notifyListeners
change_notifier.dart:403
#2      ValueNotifier.value=
change_notifier.dart:530
#3      PausableValueNotifier.resumeNotifications
pausable_value_notifier.dart:49
#4      MutableDocumentComposer.onTransactionEnd
document_composer.dart:156
#5      Editor.execute
editor.dart:164
#6      CommonEditorOperations._insertBlockLevelContent
common_editor_operations.dart:1787
#7      CommonEditorOperations.insertImage
common_editor_operations.dart:1711
#8      KeyboardEditingToolbar._insertImage
mobile_toolbar.dart:193
#9      _InkResponseState.handleTap
ink_well.dart:1154
#10     GestureRecognizer.invokeCallback
recognizer.dart:275
#11     TapGestureRecognizer.handleTapUp
tap.dart:654
#12     BaseTapGestureRecognizer._checkUp
tap.dart:311
#13     BaseTapGestureRecognizer.acceptGesture
tap.dart:281
#14     GestureArenaManager.sweep
arena.dart:167
#15     GestureBinding.handleEvent
binding.dart:469
#16     GestureBinding.dispatchEvent
binding.dart:445
#17     RendererBinding.dispatchEvent
binding.dart:331
#18     GestureBinding._handlePointerEventImmediately
binding.dart:400
#19     GestureBinding.handlePointerEvent
binding.dart:363
#20     GestureBinding._flushPointerEventQueue
binding.dart:320
#21     GestureBinding._handlePointerDataPacket
binding.dart:293
#22     _invoke1 (dart:ui/hooks.dart:158:13)
#23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:382:7)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
The PausableValueNotifier<DocumentSelection?> sending notification was: PausableValueNotifier<DocumentSelection?>#9983b([DocumentSelection] - 
  base: ([DocumentPosition] - node: "44a3dbf9-65c6-4068-98dd-a585c901ea50", position: ([UpstreamDownstreamNodePosition] - TextAffinity.downstream)),
  extent: ([DocumentPosition] - node: "44a3dbf9-65c6-4068-98dd-a585c901ea50", position: ([UpstreamDownstreamNodePosition] - TextAffinity.downstream)))
════════════════════════════════════════════════════════════════════════════════
```

https://github.com/superlistapp/super_editor/assets/6467808/9965ccb2-d20c-4995-8755-defb9657af07

https://github.com/superlistapp/super_editor/assets/6467808/8dd8ad71-292e-4ea1-9f2a-c50266ebdfa7

**Comment by matthew-carroll** [comment]
@angelosilvestre some of this might be related to the caret position ticket you're already working on. After we get that fixed, then please take a look at these issues.

**Comment by angelosilvestre** [comment]
Update:

> 1. When an image is first added, the carat doesn't move to the ParagraphNode inserted below the image

This seems to be happening because, after being fetched from the network, the image is being resized, and this doesn't cause the editor to rebuild. We probably want to integrate `ContentLayers` in the mobile interactors. There is an open ticket to refactor the mobile widget tree structure: https://github.com/superlistapp/super_editor/issues/647

I was able to fix the other two issues. We have tests for image insertion, I'll investigate to see why these tests didn't fail.
