### ISSUE TITLE
[Web] Paragraph new line via Enter key duplication

### ISSUE THREAD

**Issue by millerovv** [superlistapp/super_editor#1219]
Reproduces on `super_editor 0.2.6`

### Steps to reproduce

- Launch example app on web
- Put cursor on any paragraph
- Press "Enter" on the keyboard

#### Actual result

- New line gets created inserted twice

https://github.com/superlistapp/super_editor/assets/31796433/5da3c616-a860-4142-8936-210b54636843

**Comment by millerovv** [comment]
Here is a workaround I tried.

In `document_delta_editing.dart` method `_applyInsertion` I **removed kIsWeb from the condition** in this segment:
```dart
// On iOS, newlines are reported here and also to performAction().
// On Android and web, newlines are only reported here. So, on Android and web,
// we forward the newline action to performAction.
if (defaultTargetPlatform == TargetPlatform.android || kIsWeb) {
```

Additionally I had to remove `enterToInsertBlockNewline` from `defaultKeyboardActions`.

It helped. But **the downside is** that while editing paragraphs entering and removing text I quickly encounter an assertion failure, which completely blocks the editing: 
 ```
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:434:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 434:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 545:30                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1312:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39  dcall
 ```
 
 I suppose the workaround conflicts with some text deltas tracking, but I actually have no clue where do dig next.

**Comment by brian-superlist** [comment]
We're seeing the same thing on Superlist

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by brian-superlist** [comment]
I think this one should be reopened. I am still able to reproduce this behavior.

**Comment by brian-superlist** [comment]
**Reproduction Steps:**

  1. Check out super_editor main & flutter main
  2. Run example app (`super_editor/super_editor/example/lib/main.dart`) with Chrome (flutter run -d chrome)
  3. Navigate to Sliver Editor Demo
  4. Place Cursor at end of Paragraph
  5. Press Return Key

**Expected:** New paragraph is created
**Actual:** Extra paragraph is created

https://github.com/superlistapp/super_editor/assets/90610075/18707e06-f455-4208-b4cc-f8204be24863

**Comment by matthew-carroll** [comment]
CC @angelosilvestre
