### ISSUE TITLE
Example editor bugs.

### ISSUE THREAD

**Issue by MichalNemec** [superlistapp/super_editor#1223]
Hello, i just downloaded stable source and ran /super_editor/example/lib/main.dart.
whenever i try to select a text and try text align -> toolbar disappears and nothing happens.
whenever i try to select type (paragraph, heading,...) -> toolbar disappears and nothing happens.

if its any help: macOS M1 13.4.1 (22F82)

EDIT: whoops, im sorry, i didnt notice these issues #1139 #731 #689

**Comment by matthew-carroll** [comment]
Thanks for filing. I'm going to close this in favor of those other tickets.
