### ISSUE TITLE
Paragraph does not take entire width for short sentences

### ISSUE THREAD

**Issue by osaxma** [superlistapp/super_editor#123]
Paragraph does not take entire width for short sentences which breaks the alignment of the paragraph.

### To demonstrate:
<p align="center">
<img width="522" alt="Screen Shot 2021-04-14 at 3 19 43 PM" src="https://user-images.githubusercontent.com/46427323/114709104-d9086b80-9d34-11eb-888b-fafcb823906e.png"></p>

Though, if the first sentence of the paragraph is long enough to fit the entire width, the problem disappears. That can be observed by typing on the second node until the entire line is covered, then insert new lines using `shift+enter`. 

### To reproduce: 
- Using the `example_editor` demo, replace the mutable document with: 
```dart
Document _createInitialDocument() {
  return MutableDocument(
    nodes: [
      ParagraphNode(
        id: DocumentEditor.createNodeId(),
        text: AttributedText(
          text:
              'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sed sagittis urna. Aenean mattis ante justo, quis sollicitudin metus interdum id. Aenean ornare urna ac enim consequat mollis. In aliquet convallis efficitur. Phasellus convallis purus in fringilla scelerisque. Ut ac orci a turpis egestas lobortis. Morbi aliquam dapibus sem, vitae sodales arcu ultrices eu. Duis vulputate mauris quam, eleifend pulvinar quam blandit eget.',
        ),
        metadata: {'textAlign': 'center'},
      ),
      ParagraphNode(
          id: DocumentEditor.createNodeId(),
          text: AttributedText(
            text: ' Lorem ipsum dolor.       ',
          ),
          metadata: {'textAlign': 'center'}),
      ParagraphNode(
          id: DocumentEditor.createNodeId(),
          text: AttributedText(
            text: ' Lorem ipsum dolor sit amet..     ',
          ),
          metadata: {'textAlign': 'right'}),
       ParagraphNode(
          id: DocumentEditor.createNodeId(),
          text: AttributedText(
            text: ' Multi-line paragraph \nsecond \nthird \n4th  ',
          ),
          metadata: {'textAlign': 'center'}),
    ],
  );
}
```

### Additional Context:
In the image above:
- Light Red color is a `Container` wrapped around:
https://github.com/superlistapp/super_editor/blob/78556f359dbe2425e58ccc03676c345091cda9a3/super_editor/lib/src/default_editor/paragraph.dart#L538

- Blue Grey color is a `Container` wrapped around:
https://github.com/superlistapp/super_editor/blob/78556f359dbe2425e58ccc03676c345091cda9a3/super_editor/lib/src/infrastructure/selectable_text.dart#L454

<details><summary>I used MacOS for the demo above, here's the `flutter doctor` output:</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)
```
</details>

**Comment by matthew-carroll** [comment]
Thanks. I'll add this issue to the v0.1 priority list.

**Comment by osaxma** [comment]
Hi @matthew-carroll and @salihgueler,

This issue appeared again in the latest main: 

<p align="center"> <img width="482" alt="Screen Shot 2021-05-07 at 8 16 45 PM" src="https://user-images.githubusercontent.com/46427323/117485558-28773b80-af71-11eb-9859-da472b0837bf.png"></p>

**Comment by matthew-carroll** [comment]
Looks like you're right. `SelectableText` was blowing up due to the infinite `SizedBox` and I couldn't remember why I put them there. I'll figure out how to bring it back.

**Comment by matthew-carroll** [comment]
Here's a refix: https://github.com/superlistapp/super_editor/pull/156
