### ISSUE TITLE
[SuperEditor][IOS]The input text disappeared.

### ISSUE THREAD

**Issue by Dboy233** [superlistapp/super_editor#1230]
SuperEditor Version: 0.2.6 

Test video using the main branch code for demonstration.

1. Choose an iOS device.
2. Use Chinese full keyboard input method.
3. Edit at the beginning of an empty document.
4. Continuously input 'aaaa'.
5. **Click the '换行(Enter)' or '确认(Done)' button.**
6. Repeat steps 4 and 5.

The second scenario of disappearing.

1. Choose an iOS device.
2. Use Chinese full keyboard input method.
3. Edit at the beginning of an empty document.
4. Continuously input 'aaaa'.
5. **Click on the suggested text, and it disappears from the screen after being output.**
6. Repeat steps 4 and 5.

https://github.com/superlistapp/super_editor/assets/37604230/d984c2d3-26ef-48c1-8e91-8e1bfb138f76

**Comment by matthew-carroll** [comment]
Can you please verify whether this happens on `main`?

**Comment by Dboy233** [comment]
> Can you please verify whether this happens on `main`?

Yes, the bug has also been reproduced in the code of the main branch. The probability of this bug occurring is highest when the document is empty.

flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
[✓] VS Code (version 1.80.1)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by Dboy233** [comment]
@angelosilvestre I retested the current issue on the main branch and found that it is no longer reproducible after the merge of #1245.

**Comment by angelosilvestre** [comment]
@Dboy233 Thanks for letting me know.

**Comment by angelosilvestre** [comment]
@matthew-carroll Even though this is working now, should we try to write some tests reproducing the same deltas to make sure Chinese input is working?

**Comment by matthew-carroll** [comment]
> should we try to write some tests reproducing the same deltas to make sure Chinese input is working?

Yeah, we should write tests for anything that we don't want to change.
