### ISSUE TITLE
The comment in the source code makes me feel like it is a issues.

### ISSUE THREAD

**Issue by Dboy233** [superlistapp/super_editor#1235]
I saw this comment in 'SuperEditor', and my understanding is that this portion of code should be removed when ['flutter#118759'](https://github.com/flutter/flutter/issues/118759) is resolved. However, it seems that it has not been removed at present.

When I tried removing this piece of code, it seemed to have resolved the issue raised in #1230.

I tried using an English keyboard and a Chinese keyboard for text input and editing. I observed the logs in the console and didn't encounter any infinite loop logs. The editor was also functioning properly.

<img width="860" alt="Snipaste_2023-07-14_09-45-33" src="https://github.com/superlistapp/super_editor/assets/37604230/21c32e4a-d65b-4ba2-93e3-8a045eb32cd0">

**Comment by matthew-carroll** [comment]
@angelosilvestre can you check whether we should remove this frame callback or not?
