### ISSUE TITLE
TextDirection for new paragraph should be set based on the first character's language

### ISSUE THREAD

**Issue by osaxma** [superlistapp/super_editor#124]
In a typical Text Editors, or Text Fields for that matter, the text direction is set based on the first character of the input language. 

- Example from Twitter Web
<p align="center"><img width="400" alt="Screen Shot 2021-04-05 at 1 53 20 AM" src="https://user-images.githubusercontent.com/46427323/113523718-27d63880-95b2-11eb-887c-1e2a452ffd26.png"></p>

**Comment by matthew-carroll** [comment]
I've added this ticket to the 1.0 requirements. We won't have time to address this for the initial release.

**Comment by osaxma** [comment]
Thanks @matthew-carroll. 

If it's possible in the near future, please consider exposing `textDirection` on `TextComponent` (consequently, passed down to both `SelectableText` and `RichText` respectively). 

This way one can create their own `paragraphBuilder` or `Components` until directionality is supported and without having to fork/modify the infrastructure code.

**Comment by matthew-carroll** [comment]
I filed #235 to add `TextDirection` to `SuperSelectableText`.
