### ISSUE TITLE
[SuperEditor] On Android pressing RETURN on a ListItemNode or TaskNode is broken

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1241]
Steps to reproduce:
* Open demo app
* Place the selection on a `ListItemNode` (ordered or unordered) or a `TaskNode`
* Press RETURN on the software keyboard

**Expected:** introduce a new line below and move selection there
**Actual:** does nothing if the selection is at the end of the node or moves the selection by one character otherwise

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by miguelcmedeiros** [comment]
> Don't we already have multiple tickets for this?

Could be but I didn't find one.

**Comment by angelosilvestre** [comment]
This seems to be a duplicate of https://github.com/superlistapp/super_editor/issues/1157.

**Comment by miguelcmedeiros** [comment]
Thanks for finding it @angelosilvestre.
Closing this ticket in favour of #1157
