### ISSUE TITLE
[bug] Inserting horizontal divider in the same line as a paragraph deletes the whole paragraph

### ISSUE THREAD

**Issue by osaxma** [superlistapp/super_editor#126]
https://user-images.githubusercontent.com/46427323/114781017-c9af0f80-9d80-11eb-8a54-a2f543304c1a.mov

### To reproduce:
- Using `example_editor.dart` 
- place cursor at the beginning of the paragraph
- type three dashes '-' then a space. 

### Expected Behavior:
- The text should not be deleted. 
- Either the paragraph has to move below the divider, or the divider should not be inserted when there's a text after it.

**Comment by matthew-carroll** [comment]
Thanks for filing this. I appreciate the video reference. I'll prioritize this bug to be fixed.

@osaxma in your opinion, what should happen when those dashes are added before existing text?

@salihgueler I'd also like to get your opinion on this. What should happen when 3 dashes are added before existing text?

**Comment by osaxma** [comment]
I believe the divider should be inserted in that line and the paragraph should move one line below.

Here's an example from Notion:

https://user-images.githubusercontent.com/46427323/115938628-0cb96300-a4a4-11eb-9009-c5afc6dded6a.mov
