### ISSUE TITLE
Accent panel is not closed when the composing character is deleted

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1274]
Steps to reproduce:
* Setup the keyboard with a language that has accents (e.g. Portuguese or German)
* Run `SuperEditor` or `SuperTextField` demos
* Press and hold letter "a" (wait for the accent panel to be shown)
* Press backspace to delete the "a"

**Expected:** the accent panel is closed
**Actual:** the accent panel remains open

https://github.com/superlistapp/super_editor/assets/31278849/6c872d94-3462-4b89-b738-511beb5afef4

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by angelosilvestre** [comment]
The accent panel should be closed automatically by the OS. However, when we handle the BACKSPACE key event (`deleteUpstreamContentWithBackspace`), we prevent the OS from doing so. I haven't found any way to close the panel.

It's possible that we need to avoid handling the BACKSPACE key event, and instead implement the `performSelector` method. https://api.flutter.dev/flutter/services/TextInputClient/performSelector.html 

I filed https://github.com/flutter/flutter/issues/132272#issue-1844169343.

**Comment by angelosilvestre** [comment]
It seems that we need to implement `performSelector` to fix this.

https://github.com/superlistapp/super_editor/issues/836
