### ISSUE TITLE
[SuperEditor] Pressing ENTER at end of LinkAttribution adds it to newly created node

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1276]
Steps to reproduce:
* Run the empty document demo
* Type or paste a link (e.g. www.google.com)
* Remove any space at the end of the node 
* Press ENTER

**Expected:** new paragraph node is added without any attribution
**Actual:** new paragraph node is added with the same `LinkAttribution` as the previous node

The document after pressing ENTER looks like this:
```
[TextNode] - text: [AttributedText] - "google.com"
[AttributedSpans] (1 spans):
 - [SpanMarker] - attribution: [LinkAttribution]: https://google.com, offset: 0, type: SpanMarkerType.start
 - [SpanMarker] - attribution: [LinkAttribution]: https://google.com, offset: 9, type: SpanMarkerType.end, metadata: {blockType: [NamedAttribution]: paragraph}
[TextNode] - text: [AttributedText] - ""
[AttributedSpans] (1 spans):
 - [SpanMarker] - attribution: [LinkAttribution]: https://google.com, offset: 0, type: SpanMarkerType.start
 - [SpanMarker] - attribution: [LinkAttribution]: https://google.com, offset: 0, type: SpanMarkerType.end, metadata: {blockType: [NamedAttribution]: paragraph}
```

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by matthew-carroll** [comment]
@angelosilvestre I'm gonna take this over because it has some deeper implications for attribution processing that I need to work out.

**Comment by matthew-carroll** [comment]
Some thoughts on this. This ticket demonstrates that some attributions are expected to expand, whether into new characters, or into new paragraphs. But others are expected to stay where they are.

More accurately, this expectation is per app. It's possible that an app wants to expand a link across paragraphs, or to prevent bold from expanding across paragraphs. These are specific examples of a generic problem. It begs the question, which attributions should expand, or not, and who decides?

I think it would make sense for `EditReaction`s to decide which attributions to expand, or not, and to implement the expansion behavior. By using `EditReaction`s, we can easily provide sane defaults, but also make it easy to replace those defaults with a specific app's unusual needs.

**Comment by matthew-carroll** [comment]
@angelosilvestre I was unable to reproduce this issue in the example app. Were you able to reproduce it?

**Comment by matthew-carroll** [comment]
Nevermind. It looks like this issue is specific to a new paragraph BEFORE typing any new characters. The moment the user types new characters, the link attribution is removed. So we just need to deal with the situation where a new paragraph is inserted but no text is typed.

**Comment by matthew-carroll** [comment]
After digging into this more, I'm going to put up a PR that solves the specific issue in this ticket, because a larger overhaul of attribution extensions is a much bigger effort. It requires taking another look at what we ask `AttributedText` to do on behalf of an editor. That's much more work than should probably happen for this ticket.

Filed: https://github.com/superlistapp/super_editor/issues/1296
