### ISSUE TITLE
example broken, also add lint rules

### ISSUE THREAD

**Issue by sgehrman** [superlistapp/super_editor#1293]
Launching lib/main.dart on Chrome in debug mode...
: Error: Type 'TextScaler' not found.
  final TextScaler? textScaler;
        ^^^^^^^^^^
: Error: Type 'TextScaler' not found.
  final TextScaler? textScaler;
        ^^^^^^^^^^
: Error: Type 'TextScaler' not found.
    TextScaler textScaler = TextScaler.noScaling,

    ^^^^^^^^^^
: Error: Type 'TextScaler' not found.
    TextScaler textScaler = TextScaler.noScaling,
    ^^^^^^^^^^
: Error: Type 'TextScaler' not found.
  final TextScaler? textScaler;
        ^^^^^^^^^^
: Error: Type 'TextScaler' not found.
  final TextScaler textScaler;
        ^^^^^^^^^^
: Error: Type 'TextScaler' not found.

  TextScaler get textScaler => _renderParagraph.textScaler;
  ^^^^^^^^^^
: Error: Type 'TextScaler' not found.
  TextScaler get _textScaler => MediaQuery.textScalerOf(context);
  ^^^^^^^^^^
: Error: Type 'TextScaler' not found.
  TextScaler? _lastTextScaleFactor;
  ^^^^^^^^^^
: Error: Type 'TextScaler' not found.
  double calculate(TextStyle style, TextScaler textScaler) {

                                    ^^^^^^^^^^
: Error: Undefined name 'TextScaler'.
    TextScaler textScaler = TextScaler.noScaling,
                            ^^^^^^^^^^
: Error: Undefined name 'TextScaler'.
    TextScaler textScaler = TextScaler.noScaling,
                            ^^^^^^^^^^
: Error: Undefined name 'TextScaler'.
    this.textScaler = TextScaler.noScaling,
                      ^^^^^^^^^^
: Error: Member not found: 'MediaQuery.textScalerOf'.
    final textScaler = MediaQuery.textScalerOf(context);
                                  ^^^^^^^^^^^^
: Error: Member not found: 'MediaQuery.textScalerOf'.
    final textScaler = MediaQuery.textScalerOf(context);
                                  ^^^^^^^^^^^^
: Error: 'TextScaler' isn't a type.
  final TextScaler? textScaler;
        ^^^^^^^^^^
: Error: Member not found: 'MediaQuery.textScalerOf'.
        textScaler: widget.textScaler ?? MediaQuery.textScalerOf(context),
                                                    ^^^^^^^^^^^^
: Error: 'TextScaler' isn't a type.
  final TextScaler? textScaler;
        ^^^^^^^^^^
: Error: Member not found: 'MediaQuery.textScalerOf'.

        textScaler: widget.textScaler ?? MediaQuery.textScalerOf(context),
                                                    ^^^^^^^^^^^^
: Error: 'TextScaler' isn't a type.
    TextScaler textScaler = TextScaler.noScaling,
    ^^^^^^^^^^
: Error: No named parameter with the name 'textScaler'.
          textScaler: textScaler,
          ^^^^^^^^^^
: Error: The getter 'textScaler' isn't defined for the class 'LayoutAwareRichText'.
- 'LayoutAwareRichText' is from 'package:super_text_layout/src/super_text.dart' ('../../super_text_layout/lib/src/super_text.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'textScaler'.

      textScaler: textScaler,
                  ^^^^^^^^^^
: Error: The getter 'textScaler' isn't defined for the class 'LayoutAwareRichText'.
- 'LayoutAwareRichText' is from 'package:super_text_layout/src/super_text.dart' ('../../super_text_layout/lib/src/super_text.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'textScaler'.
      ..textScaler = textScaler
                     ^^^^^^^^^^
: Error: The setter 'textScaler' isn't defined for the class 'RenderLayoutAwareParagraph'.
- 'RenderLayoutAwareParagraph' is from 'package:super_text_layout/src/super_text.dart' ('../../super_text_layout/lib/src/super_text.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'textScaler'.

      ..textScaler = textScaler
        ^^^^^^^^^^
: Error: 'TextScaler' isn't a type.
    TextScaler textScaler = TextScaler.noScaling,
    ^^^^^^^^^^
: Error: No named parameter with the name 'textScaler'.
          textScaler: textScaler,
          ^^^^^^^^^^
: Error: 'TextScaler' isn't a type.
  final TextScaler? textScaler;
        ^^^^^^^^^^
: Error: Member not found: 'MediaQuery.textScalerOf'.
      textScaler: widget.textScaler ?? MediaQuery.textScalerOf(context),
                                                  ^^^^^^^^^^^^
: Error: 'TextScaler' isn't a type.
  final TextScaler textScaler;
        ^^^^^^^^^^
: Error: The getter 'textScaler' isn't defined for the class 'RenderLayoutAwareParagraph'.
- 'RenderLayoutAwareParagraph' is from 'package:super_text_layout/src/super_text.dart' ('../../super_text_layout/lib/src/super_text.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'textScaler'.
  TextScaler get textScaler => _renderParagraph.textScaler;
                                                ^^^^^^^^^^
: Error: Member not found: 'MediaQuery.textScalerOf'.
        textScaler: MediaQuery.textScalerOf(context),
                               ^^^^^^^^^^^^
: Error: Member not found: 'MediaQuery.textScalerOf'.
  TextScaler get _textScaler => MediaQuery.textScalerOf(context);
                                           ^^^^^^^^^^^^
: Error: 'TextScaler' isn't a type.
  TextScaler? _lastTextScaleFactor;
  ^^^^^^^^^^
: Error: 'TextScaler' isn't a type.
  double calculate(TextStyle style, TextScaler textScaler) {
                                    ^^^^^^^^^^

: Error: No named parameter with the name 'textScaler'.
      ..pushStyle(style.getTextStyle(textScaler: textScaler))
                                     ^^^^^^^^^^
: Error: Member not found: 'MediaQuery.textScalerOf'.
        textScaler: MediaQuery.textScalerOf(context),
                               ^^^^^^^^^^^^
Failed to compile application.
Exited (sigterm)

**Comment by matthew-carroll** [comment]
You're running the `main` branch against Flutter `stable`. You need to run our `stable` branch against Flutter `stable`. Please see the README.

**Comment by amejiarosario** [comment]
This got me as well! 

Is it possible to add some automated tests/checks to prevent submitting things that breaks example in main branch? This the first interaction with the library and being broken add some frustration

**Comment by matthew-carroll** [comment]
@amejiarosario nothing was broken. We maintain two parallel branches for two different versions of Flutter. You need to use the right Super Editor branch with the right Flutter branch. This is described in the README.

**Comment by amejiarosario** [comment]
Thanks @matthew-carroll for your answer! It's working now!

Now, I'm trying to make it work on a new project. 

I ran into some issue in the [README](https://github.com/superlistapp/super_editor/blob/main/super_editor/README.md#display-an-editor). The `SuperEditor.standard` nor SuperEditor.custom` seems to exists. 

Trying another approach by copying `EmptyDocumentDemo()` widget from example/demo to new project. But getting a bunch of errors like `Error: Type 'BlinkTimingMode' not found.`. Could you please let me know if you any idea what could I be missing?

Here are more details about the errors I'm seeing:
<img width="786" alt="image" src="https://github.com/superlistapp/super_editor/assets/418605/23ffe2cb-e8ba-4583-9f02-90d6a73fc6ea">

Using the dep as 
```yml
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor
      ref: stable
```

**Comment by matthew-carroll** [comment]
@amejiarosario at the moment we've made changes to multiple of our packages. I think the problem you're seeing is that the latest `super_editor` from GitHub also depends on the latest `super_text_layout` and `attributed_text` from GitHub, too. Can you try adding those two packages under your `dependency_overrides`, point them to GitHub as well, and see if that works?

**Comment by amejiarosario** [comment]
That worked! 🎉 🎉 🎉 
Thanks a lot @matthew-carroll!

Just for reference in case anyone else run into this issue:
```yml
dependencies:
  flutter:
    sdk: flutter

  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor
      ref: stable

dependency_overrides:
  super_text_layout:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_text_layout
      ref: stable

  attributed_text:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: attributed_text
      ref: stable
```
