### ISSUE TITLE
[SuperEditor] Inserting a newline when cursor is at the end of a node causes text attributions to be copied

### ISSUE THREAD

**Issue by robertodoering** [superlistapp/super_editor#1312]
When pressing enter and the cursor is at the end of a `ParagraphNode`, the new node will contain a 0 length long `AttributedText` with attributions from the end of the previous node.

Instead, I expect the new node to not contain any previous text attributions on a 0 length text.

Cause:
When `insertBlockLevelNewline` is called after pressing enter, it will execute a `SplitParagraphRequest` (even when the cursor is placed at the end of the node.
The `SplitParagraphCommand` then splits the text and places the endText in the new node (which is length 0 but the attributions got copied over).

Instead, when the length if the end text is 0 we shouldn't copy over any attributions. This case is properly handled in `SplitListItemCommand`.

**Comment by matthew-carroll** [comment]
WRT the statement "I expect the new node to not contain any previous text attributions on a 0 length text" - I don't think that's the expectation that most people have in most situations. Typically, users are writing headers and paragraphs. When starting a new paragraph, a user expects bold, italics, strikethrough, and underline to continue. Essentially any stylistic attribution is expected to continue.

Also, I'm unclear as to the specific problem this ticket is meant to describe. This ticket simultaneously mentions block nodes, paragraph nodes, and list item nodes. The associated PR makes a minor modification to just one scenario. So which problem, exactly, is being capture here?

As for the solution, I just recently addressed this for paragraphs. Please use https://github.com/superlistapp/super_editor/pull/1297 as a guide to analyze the root problem.

**Comment by robertodoering** [comment]
The issue I tried to solve is fixed with #1297, which is that the `LinkAttribution` got carried over.

My assumption was that no attributions should be carried over, because this is the way `SplitListItemCommand` works. Hence my reference to it and my 'fix' to mirror that behavior.
