### ISSUE TITLE
[TextField] Replace a custom selection with text

### ISSUE THREAD

**Issue by venkatd** [superlistapp/super_editor#134]
In the situation where someone clicks on a mention, we may have a replacement such as `MessageReplacement(start: 5, extent: 10, text: "@John Wick")`. Clicking on that, we would want to replace the characters from 5-10 with "@John Wick" and set the cursor to one space after this.

With a regular TextField, we would do this via setting the `value` property (https://api.flutter.dev/flutter/services/TextEditingValue-class.html)

**Comment by matthew-carroll** [comment]
I'm going to close this because it seems like the goal can be accomplished on the app side.
