### ISSUE TITLE
[SuperEditor] - Spike: Spell check and autocorrection on Mac

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#1349]
We have a long-standing request for spell check and autocorrection on Mac: https://github.com/superlistapp/super_editor/issues/388

This ticket is to do a spike into the world of IME spell check and autocorrection. We'd like to answer all the important questions about what an implementation might look like and how long it might take.

**Comment by angelosilvestre** [comment]
Flutter doesn't seem to support spellcheck for macOS:

```
Spell check was enabled with spellCheckConfiguration, but the current platform does not have a supported spell check service, and none was provided. Consider disabling spell check for this platform or passing a SpellCheckConfiguration with a specified spell check service.
```

**Comment by matthew-carroll** [comment]
I opened this from an email update. Is this issue missing a comment?

**Comment by matthew-carroll** [comment]
@angelosilvestre you mentioned autocorrection on Mac with the `autocorrect` flag. Does it work on iOS? If so, what tool does that flag use on iOS?

**Comment by angelosilvestre** [comment]
Autocorrection works on iOS. On iOS, the autocorrection just generates text deltas, we don't need to do anything different on our side.

**Comment by matthew-carroll** [comment]
What's happening on the platform side?

**Comment by angelosilvestre** [comment]
@matthew-carroll  The flutter engine just sets the autocorrection flag when connecting to the IME.

**Comment by matthew-carroll** [comment]
@Jethro87 please take a look at Angelo's writeup on spell check and autocorrection and let us know if you'd like for us to dig any deeper.

**Comment by Jethro87** [comment]
Thanks @matthew-carroll. Let's leave this issue as is for now.

**Comment by matthew-carroll** [comment]
I'm closing this spike as complete. The information gained in this spike has been added to the original spell check and autocorrection ticket.
