### ISSUE TITLE
[SuperEditor][web] Browser text selection toolbar is displayed

### ISSUE THREAD

**Issue by angelosilvestre** [superlistapp/super_editor#1390]
We use our own text selection toolbar. However, when running on mobile web, the native text selection toolbar is also displayed. We probably shouldn't set the editing position when running on mobile web.

Also, tapping seems to select the wrong text. This might be related to the browser address bar, as tapping on "OK" stops the issue.

https://github.com/superlistapp/super_editor/assets/7597082/9bde2cbd-ec8c-436c-b557-e6617e79277f

**Comment by matthew-carroll** [comment]
CC @brian-superlist @Jethro87 WRT web support

**Comment by angelosilvestre** [comment]
@matthew-carroll 

> Also, tapping seems to select the wrong text. This might be related to the browser address bar, as tapping on "OK" stops the issue.

I tried this with https://github.com/superlistapp/super_editor/pull/1418 and this issue doesn't seem to be happening anymore.

However, it seems we cannot disable the text selection toolbar. On web, Flutter `TextField` doesn't display its own toolbar and lets the browser display the default toolbar.

Flutter has `BrowserContextMenu.disableContextMenu` to disable the context menu for the whole app, but this isn't ideal as we don't want to force users to disable it for the entire application. Also, calling `disableContextMenu` doesn't seem to prevent the toolbar from being displayed.

The browser also displays a grey rectangle where it thinks the selection is.

I filed https://github.com/flutter/flutter/issues/134358 and  https://github.com/flutter/flutter/issues/134359

https://github.com/superlistapp/super_editor/assets/7597082/b5751d8f-e7bf-49ff-aaf6-3c2919b13b04

**Comment by matthew-carroll** [comment]
@angelosilvestre was this compiled in HTML mode or Canvas Kit mode? I'm asking because the magnifier looks broken.

@miguelcmedeiros @Jethro87 do you have a preference for how we resolve this? Should we hide our toolbar on the web and defer to the browser?

**Comment by angelosilvestre** [comment]
@matthew-carroll This is in HTML mode. Flutter `TextField` magnifier also looks broken with this mode.

**Comment by Jethro87** [comment]
@matthew-carroll Are we able to pass our cut/copy methods to the native toolbar? Would it work as expected?

If so, I'd actually prefer the native toolbar. It's still a much nicer - and expected - experience for the user, in my opinion, than super editor's toolbar right now. 

This is out of the scope of this issue, but if we could show the native toolbar on mobile, too, and have it work as expected, I'd even be in favor of that.

**Comment by matthew-carroll** [comment]
@Jethro87 can you file an issue for showing the native toolbar on mobile? In that issue can you also explain the ways in which the platform toolbar surpasses the UX of the Super Editor toolbar?

**Comment by matthew-carroll** [comment]
@angelosilvestre can you try running with canvas kit and see if everything works? I expect that most Flutter apps will run with canvas kit on web because the HTML renderer has so many known issues.

**Comment by angelosilvestre** [comment]
It still looks broken. I suspect that is because, at some moments, the native magnifier is being displayed together if our magnifier.

https://github.com/superlistapp/super_editor/assets/7597082/cacb9fea-4906-4b10-801e-9101f1fc0817

**Comment by matthew-carroll** [comment]
Ok. Then I guess we should hide our magnifier along with hiding our toolbar.

**Comment by Jethro87** [comment]
> @Jethro87 can you file an issue for showing the native toolbar on mobile? In that issue can you also explain the ways in which the platform toolbar surpasses the UX of the Super Editor toolbar?

Issue created: #1432

**Comment by angelosilvestre** [comment]
> Are we able to pass our cut/copy methods to the native toolbar? Would it work as expected?

@Jethro87  On web, the toolbar would be entirely controlled by the browser, we won't be able to customize it.

**Comment by matthew-carroll** [comment]
@angelosilvestre I think what @Jethro87 was asking is whether or not cut and copy would work. That answer might be yes, or no, but I don't think it's answered by saying "we won't be able to customize it". Does the browser's native bar have a "cut" and "copy" and "paste" button? If so, can they be made to work?

**Comment by angelosilvestre** [comment]
@matthew-carroll Yes, the browser's native bar has those buttons and they will work with the editor. Here's a video of super_editor using the browser's toolbar and magnifier:

https://github.com/superlistapp/super_editor/assets/7597082/0f4ec0b2-291c-4538-966a-8ee417df267a

**Comment by angelosilvestre** [comment]
@matthew-carroll I was experimenting with this, but I'm not sure anymore that we should defer the toolbar to the browser on mobile.

On the video, there is a grey box that is visible behind the text selection. This is the browser selection color. On most of the major browsers it's possible to override this color by using the css pseudo element [::selection](https://developer.mozilla.org/pt-BR/docs/Web/CSS/::selection), but it seems it isn't supported at all on iOS Safari: https://caniuse.com/css-selection

So far I haven't found a way to change that...

If we don't need to interact with IME panels on mobile web, another option we have is to avoid reporting visual information (size, transform and text style) to the IME on mobile web. That way, the browser toolbar won't be visible and we won't have those grey boxes.

**Comment by matthew-carroll** [comment]
> If we don't need to interact with IME panels on mobile web

Is there some reason that you think we wouldn't need to interact with those panels on mobile web?

**Comment by angelosilvestre** [comment]
I'm not aware if there are any IME panels on mobile. The only situation I can think of is when using a hardware keyboard, but I don't know if Android or iOS display any panels when using a hardware keyboard.

**Comment by matthew-carroll** [comment]
@Jethro87 what are your thoughts on this?

**Comment by Jethro87** [comment]
@matthew-carroll What do we mean by IME panels? Are we talking about an overlay like this?

<img width="410" alt="Screenshot 2023-09-30 at 11 46 41 AM" src="https://github.com/superlistapp/super_editor/assets/6467808/15288260-dfc1-43b9-9c29-c1d69a0b0ba7">

**Comment by matthew-carroll** [comment]
@Jethro87 IME panels are the various OS-level popups: emoji, other language compound character selection, etc.

Our assumption is that on mobile those are always presented through the software keyboard. But we're not entirely sure of that.

I think our understanding as of this moment is that the one thing the OS pops up is the edit toolbar, but that's resulting in the visual issues that Angelo mentioned above.

**Comment by Jethro87** [comment]
@matthew-carroll I'm leaning towards still showing the browser/native toolbar on mobile web and ignoring the grey box on mobile web Safari for now.

**Comment by matthew-carroll** [comment]
@angelosilvestre based on @Jethro87's response, let's go ahead and try to use the built-in toolbar on mobile.
