### ISSUE TITLE
[SuperEditor] [SuperReader] Widget is grey in profile and release mode

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#1424]
On Web, macOS, and iOS, in debug mode, the editor looks normal:

<img width="530" alt="Screenshot 2023-09-10 at 1 51 45 PM" src="https://github.com/superlistapp/super_editor/assets/6467808/6cea0bb2-f421-404d-9cd2-3a9da4837891">

In profile or release mode, the editor is covered by a grey box:

<img width="501" alt="Screenshot 2023-09-10 at 1 49 51 PM" src="https://github.com/superlistapp/super_editor/assets/6467808/d71cfa79-bcdc-4425-8c64-1b2cd545c8f4">

**To reproduce**: run the example app in profile or release mode.

This was recently introduced, as I have been working on our Flutter web app for the past few weeks (in both debug and release mode) and didn't notice this issue until today.

cc @matthew-carroll @angelosilvestre

**Comment by matthew-carroll** [comment]
@Jethro87 can you please post your current Flutter version?

**Comment by matthew-carroll** [comment]
Also, are we seeing the editor covered by a gray box? Or are we seeing an absence of the editor altogether, and seeing through to the background?

**Comment by Jethro87** [comment]
@matthew-carroll 3.13.2 stable
