### ISSUE TITLE
[SuperEditor] Paragraphs with multiple links only open the first link when tapped

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#1426]
If a ParagraphNode contains more than one LinkAttribution, tapping any of the links in interaction mode will open the first link's URL in the browser. For example, the first link in the following video's URL is google.com, while the second link's URL is yahoo.com.

https://github.com/superlistapp/super_editor/assets/6467808/37be616c-e734-4e17-b5e1-e8a6118cf048

These lines in `_getLinkAtPosition` in `super_editor.dart` return the first LinkAttributon's URL, rather than the url that was tapped:

```
    final tappedAttributions = textNode.text.getAllAttributionsAt(nodePosition.offset);
    print('tappedAttributions: $tappedAttributions');
    for (final tappedAttribution in tappedAttributions) {
      if (tappedAttribution is LinkAttribution) {
        return tappedAttribution.url;
      }
    }
```

cc @matthew-carroll

**Comment by Jethro87** [comment]
Update: this seems to work as expected on iOS.

**Comment by matthew-carroll** [comment]
@Jethro87 how did you apply those links?

**Comment by Jethro87** [comment]
@matthew-carroll I modified `_toolbar.dart`'s `_buildUrlField` in `example_editor`:

```
            IconButton(
              icon: const Icon(Icons.close),
              iconSize: 20,
              splashRadius: 16,
              padding: EdgeInsets.zero,
              onPressed: () {
                setState(() {
                  _urlFocusNode.unfocus();
                  _showUrlField = false;
                  _urlController!.clear();
                });
                final attr = LinkAttribution(url: Uri.parse('https://www.yahoo.com'));
                widget.commonOps.addAttributionsToSelection({attr});
              },
            ),
```

Basically, I call `addAttributionsToSelection` located in `CommonEditorOperations`.
