### ISSUE TITLE
[SuperEditor] Consider showing native text selection toolbar on mobile

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#1432]
This is related to #1390, where we're forced to hide super_editor's text selection toolbar in favor of the native text selection toolbar. In that issue, I [mentioned](https://github.com/superlistapp/super_editor/issues/1390#issuecomment-1714838770) that if we could show the native toolbar on mobile (without sacrificing cut/copy/paste functionality), I would prefer that.

In general, we've heard lots of feedback from our users about the current super_editor toolbar. It's simply not what they expect. The size, color, animations, shadows, and tap effects are "not normal," in the words of our users, and it gives them pause. 

Here's a few comparison screenshots:

Super Editor
![IMG_1719](https://github.com/superlistapp/super_editor/assets/6467808/d74aee48-9826-4824-93e7-17f1379915de)
Native
![IMG_1718](https://github.com/superlistapp/super_editor/assets/6467808/6b19810a-15dc-4025-b265-df155abf6700)
Super Editor
![IMG_1716](https://github.com/superlistapp/super_editor/assets/6467808/7395f1f9-4be0-4014-9d59-95ac04872745)
Native
![IMG_1717](https://github.com/superlistapp/super_editor/assets/6467808/6cfc7c22-4cd3-45cb-8691-653589bf55d8)

In my view, if we could give users a native toolbar that they've come to expect, it would improve the user's experience in Clearful.

The vast majority of the feedback we've received has come from iOS.

**Comment by Jethro87** [comment]
@matthew-carroll Bumping this, as we've received more feedback from users frustrated with the non-native toolbar experience. If we're able to show the native toolbar on mobile, would it also use the native selection handles? Or would we still have to use super_editor's selection handles? Our users very often find it difficult to grab super_editor's selection handles.

**Comment by matthew-carroll** [comment]
@angelosilvestre does the OS show its own selection handles when we report bounds, or just the platform toolbar?

**Comment by angelosilvestre** [comment]
On Android, it shows the drag handles as well. I'll test on iOS.

**Comment by angelosilvestre** [comment]
@matthew-carroll I didn't notice this was the native ticket...

On native mobile, I don't think the OS shows anything. I'll need to check.

**Comment by angelosilvestre** [comment]
@matthew-carroll On mobile iOS and Android, the OS doesn't show any toolbar, handles, etc. I don't think we have a way to trigger the native text selection toolbar from Flutter.

**Comment by matthew-carroll** [comment]
@Jethro87 please see @angelosilvestre's message above. It looks like we still need to deliver those controls for native apps.

There's no reason that we need to have controls that look a lot different from the platform controls. We just need to prioritize the creation of more accurate handles, carets , and toolbars.

If that's worth it, then I'm sure we can prioritize that work with funding from you, split with Superlist.
