### ISSUE TITLE
Text selection handle size for iOS

### ISSUE THREAD

**Issue by AlexandroKurchenko** [superlistapp/super_editor#1435]
I implemented super_reader and faced with the fact that on iOS devices text selection handle is too small.

![image](https://github.com/superlistapp/super_editor/assets/12192429/c95486d9-9095-46eb-b51d-4473ba22205c)

I didn't find parametrs to configure it.

What I found (it is not configurable) - https://github.com/superlistapp/super_editor/blob/be21f119fc0b9506110410eda18ea110804ef088/super_editor/lib/src/super_textfield/ios/_editing_controls.dart#L527-L542 

This is very inconvenient, would be great to have possible to customize this element for iOS?

**Comment by matthew-carroll** [comment]
Can you please describe what you mean by "too small"? Are you saying that the handle line is too short? The circle at the end is too small? The touch area is too small?

If it's a visual issue, do you have a screenshot of a standard iOS handle that shows the difference?

**Comment by AlexandroKurchenko** [comment]
@matthew-carroll I mean "circle at the end is too small" and also "touch area is too small". In comparison circle at the end of caret selection in the standard notes app on iPhone looks bigger
![IMG_1BF47F5CCA82-1](https://github.com/superlistapp/super_editor/assets/12192429/293570be-fa5c-40e1-a4d6-271720760ef1)

As far as i understand  the handle line is adapted to text size, so it should be adjusted depending on text size, but touch area and circle in the end of caret is too small, and no way to configure it

**Comment by matthew-carroll** [comment]
@rutvik110 for this ticket the critical starting point is a bit of research. Can you please check a few different iOS apps, take some screenshots, and document the dimensions of these handles? Please include examples where the caret sits near large text, small text, images, etc. We want to capture the full sizing behavior.

After that, if you think you have a clear picture of the desired behavior, then you can take a stab at updating our iOS handle positioning and sizing logic. Otherwise, please update this ticket with the clearest specification you were able to come up with.

**Comment by rutvik110** [comment]
Made [this](https://docs.google.com/document/d/1Azp7IKH7hbwV2H77N1b8Z1g9zY-aH_NG9BurhCDQJ-U/edit) doc detailing the native ios text selection handle sizing across different sizes of texts, images and how it compares to the super_editor's handle sizing.

I couldn't find the exact sizing of the drag handle circle or dimensions of the native handles. But, they appear to be somewhat 2-3x larger than the current sizings within the super_editor.

**Comment by rutvik110** [comment]
@matthew-carroll Here are the final specs for text selection handle sizing based on apple's own design specs and what Flutter uses for its Cupertino experience.
https://docs.google.com/document/d/1g7qHcknab9Av4kxw78145wyVrj5wF5_UEGyzt8Exhzk/edit

Also, with regard to the changes mentioned in the doc, do we intend to also add an option for users to customize sizing for selection handle and the circles as this issue suggests? Seems unnecessary though till we follow the actual native design specs to keep the native experience, but for users who wish to change it, exposing this api could be helpful. Though, not sure how practical it's.

**Comment by rutvik110** [comment]
@matthew-carroll Updated the inspection doc with text selection handle sizing under native text font scaling,
https://docs.google.com/document/d/1Azp7IKH7hbwV2H77N1b8Z1g9zY-aH_NG9BurhCDQJ-U/edit?pli=1#heading=h.9089lcljlc6r

Also, noted down some design changes for [the handle interaction area](https://docs.google.com/document/d/1g7qHcknab9Av4kxw78145wyVrj5wF5_UEGyzt8Exhzk/edit#heading=h.ku4h3g92ni41) and [the handle bar and circle layout](https://docs.google.com/document/d/1g7qHcknab9Av4kxw78145wyVrj5wF5_UEGyzt8Exhzk/edit#heading=h.cefu8wyhfn2s). We would want to make this changes along with other changes I proposed earlier to match the native iOS experience.

**Comment by matthew-carroll** [comment]
@angelosilvestre will this issue end up being covered by your active PR for iOS handles?

**Comment by matthew-carroll** [comment]
Closing this in favor of Angelo's ongoing handle work which will solve this.
