### ISSUE TITLE
[SuperEditor/SuperTextField] OS sound when using up/down arrow keys in Japanese IME popover

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1437]
Steps to reproduce:
* setup keyboard to use Japanese input method
* Place selection in SuperEditor or SuperTextField
* Type characters until the Japanese IME popover is shown next to the caret
* Use up/down arrow keys to move the selection in the IME popover

**Expected:** selection moves accordingly and the OS does not emit any sound on every key press
**Actual:** selection moves followed by the OS sound that indicates that the key event was not handled

This was tested using the demo app on Mac.

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll @angelosilvestre

**Comment by angelosilvestre** [comment]
I tested with Flutter `TextField` and it also happens, which suggests this is a Flutter issue. I filed https://github.com/flutter/flutter/issues/134699
