### ISSUE TITLE
[SuperTextField] Parent scroll view with SuperTextField does not scroll when Page Up/Down keys are pressed

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1438]
Steps to reproduce:
* Place a `SuperTextField` (or several) on a scrollable widget (e.g. `CustomScrollView`)
* The view should have enough content to make it scrollable
* Place the focus on the text field
* Press Page Down

**Expected:** the scrollable view should scroll down
**Actual:** nothing happens

This used to work on a scrollable page with multiple text fields, which would scroll when Page Up/Down were pressed.

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll @angelosilvestre

**Comment by rutvik110** [comment]
It seems that rn we don't have key handlers defined to scroll the parent scroll view from within the `SuperTextField` when those two particular keys are pressed. Also, I can't find a mention of this being handled there previously.

@miguelcmedeiros Any idea on when was the last time this was working? If it was working previously, then either this is being handled somewhere else other than within `SuperTextField` which is unlikely tbh or `SuperDesktopTextField` had been modified at some point which removed this feature.

If this was never handled, we should be able to implement this easily in the same way as we are doing within `SuperEditor`.

**Comment by miguelcmedeiros** [comment]
@rutvik110 I am not sure sure why this was working before, but my guess is that it regressed when https://github.com/superlistapp/super_editor/pull/1339 got merged, since these non-content-changing key events are now defined as selectors and for `SuperTextField` we don't handle the page up/down.

**Comment by angelosilvestre** [comment]
This might be related to https://github.com/superlistapp/super_editor/pull/1430

**Comment by matthew-carroll** [comment]
@rutvik110 can you please coordinate here with @angelosilvestre to determine the root the cause? We may need to alter something in how we ignore keys on Mac to let the OS send us selectors. Please see if you two can figure that out.

**Comment by rutvik110** [comment]
yah, will check on that today.

**Comment by matthew-carroll** [comment]
Some clarification on this, if a text field has enough content to scroll, page up/down should apply to the text field. If the text field doesn't have any scrollable content, then the text field should let the page up/down keys bubble up.
