### ISSUE TITLE
[SuperEditor] [Web] Cannot enter spaces

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#1446]
Repro: Run the example app targeting web and try to enter spaces. Nothing happens. This occurs in debug and profile mode.

I'm running Flutter 3.13.3 stable and super_editor stable.

cc @matthew-carroll @angelosilvestre

**Comment by angelosilvestre** [comment]
This should be caused by https://github.com/superlistapp/super_editor/pull/1430. I might have missed some intent related to the spacebar.
