### ISSUE TITLE
[SuperTextField] SHIFT+ENTER adds 2 new lines

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1468]
Steps to reproduce:
* Run interactive SuperTextField demo 
* Place the selection somewhere in the content
* Press SHIFT+ENTER

**Expected:** a single new line is added
**Actual:** 2 new lines are added

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll @angelosilvestre

**Comment by miguelcmedeiros** [comment]
I noticed that this does not happen if we use a `ImeAttributedTextEditingController` and set `onPerformActionPressed`.

**Comment by manoletre** [comment]
> I noticed that this does not happen if we use a `ImeAttributedTextEditingController` and set `onPerformActionPressed`.

Hey, could you maybe add more detail to this? I am trying to find a workaround for this issue, but don't understand where to add the `ImeAttributedTextEditingController` 😅

**Comment by matthew-carroll** [comment]
@manoletre there's a PR open to resolve this. You're probably better off waiting for that to merge and then updating.
