### ISSUE TITLE
[SuperTextField][iOS/Android] Not possible to show the text selection toolbar when the field is empty 

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1472]
Steps to reproduce:
* Open the SuperTextField demo
* Remove all text in the field
* Tap twice on the empty field

**Expected:** the text selection toolbar is shown
**Actual:** nothing happens besides the field gaining focus

Having the ability to show the toolbar when the field is empty, is important for being able to paste text (e.g. an email during login flow) on a mobile device.

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll @angelosilvestre

**Comment by matthew-carroll** [comment]
I checked a native Android text field. When the field is empty, a long-press opens the toolbar with "paste". Single, double, and triple taps seem to have no effect on an empty field.

On iOS, using the Settings search field as a reference, a single tap opens the toolbar. I'm not completely sure what the heuristic is here, but I think that if the user taps on the field, and the selection doesn't change, the toolbar pops up. That heuristic would of course include the case where a user taps on an empty field where a caret is visible.
