### ISSUE TITLE
Action tags don't work on web

### ISSUE THREAD

**Issue by knopp** [superlistapp/super_editor#1478]
Reproducible with the example. Upon selection the document node does not change type, instead new line is inserted.

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by matthew-carroll** [comment]
This is likely related to the IME and selector work. We should check this again after https://github.com/superlistapp/super_editor/pull/1469 is merged.

**Comment by knopp** [comment]
After spending some time on this I believe this needs to be fixed in Flutter. The problem is that both raw keyboard and IME are handling the DOM event, separately. The IME event subscription fires first and it invokes the text field input action regardless of whether the keyboard event has been handled by Flutter. Actually, because the event handler is registered on the text field DOM elementitself and not the window, it fires the input action even before the normal keyboard handling had chance to look at event, let alone mark it as handled. 

I'll try to put together a test case and report this. I'm wondering why the window keydown handler is not registered in capturing mode the prevent the event reaching the textfield if handled.

**Comment by knopp** [comment]
https://github.com/flutter/flutter/issues/136460

**Comment by matthew-carroll** [comment]
@knopp do you know if this issue is now resolved, given the flutter issue was marked resolved?

**Comment by knopp** [comment]
It is resolved.
