### ISSUE TITLE
[SuperEditor][SuperReader][iOS] - Magnifier focuses at slightly wrong offset

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#1496]
The iOS magnifier focuses on an area that's a bit away from the handle that the user is dragging.

The magnifier `Leader` is placed at the `_globalDragOffset`, which is set to `_globalDragOffset = details.globalPosition;` on every pan update.

Therefore, at first glance, it seems that the reported pan offset isn't where the finger initially touches. My guess is that this problem is an issue of gesture slop. But there might be more to it.

Get the magnifier to focus on the content beneath the user's finger, which should also be where the dragging handle sits.

**Comment by dominikkeller** [comment]
Any updates on this?

**Comment by hannutho** [comment]
Hey SuperEditor team. When will this be targeted. The magnifier is currently unusable on IOS.

**Comment by matthew-carroll** [comment]
I think this issue must have been resolved at some point because I'm not seeing a mis-alignment.


https://github.com/superlistapp/super_editor/assets/7259036/c24fce5b-98c0-4c70-8f79-b2537b89be50

@BazinC - Can you please confirm that your magnifier position is correct now?

**Comment by BazinC** [comment]
@matthew-carroll I confirm the offset is good now

**Comment by matthew-carroll** [comment]
Closing this as done. If you're still seeing a mis-aligned magnifier, please check your Super Editor version. You need to either use the version on GitHub, or you need to use a `0.3.0` pre-release version.
