### ISSUE TITLE
[SuperEditor] Tab does not change the indent of a list item node

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1497]
Steps to reproduce:
* Run demo app of `SuperEditor`
* Place the selection on a list item node
* Press Tab key

**Expected:** the indentation of the list item node changes
**Actual:** the editor loses focus

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll @angelosilvestre

**Comment by miguelcmedeiros** [comment]
@angelosilvestre SHIFT+TAB should un-indent but it moves focus as well.
Should we reopen this ticket or create a new one?

**Comment by matthew-carroll** [comment]
I'll re-open this one. @angelosilvestre can you put up another PR for SHIFT+TAB?

**Comment by angelosilvestre** [comment]
@matthew-carroll Yep.
