### ISSUE TITLE
[bug] pasting across multiple nodes throws an exception in some narrow cases

### ISSUE THREAD

**Issue by osaxma** [superlistapp/super_editor#151]
When pasting across multiple nodes, the exception below occurs sometimes. Though, despite the exception, the content is pasted correctly.

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following _Exception was thrown building DefaultDocumentLayout-[GlobalKey#3e0fa](dirty, state: _DefaultDocumentLayoutState#fa058):
Exception: No such position in document: [DocumentPosition] - node: "5ead3881-5513-4592-b041-47a65a634ad2", position: (TextPosition(offset: 20, affinity: TextAffinity.upstream))

The relevant error-causing widget was
DefaultDocumentLayout-[GlobalKey#3e0fa]
../…/default_editor/editor.dart:284
When the exception was thrown, this was the stack
#0      MutableDocument.getNodesInside
package:super_editor/…/core/document_editor.dart:179
#1      _DefaultDocumentLayoutState._buildDocComponents
package:super_editor/…/default_editor/layout.dart:339
#2      _DefaultDocumentLayoutState.build
package:super_editor/…/default_editor/layout.dart:317
#3      StatefulElement.build
package:flutter/…/widgets/framework.dart:4612
#4      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4495
...
════════════════════════════════════════════════════════════════════════════════
```

### Steps to Reproduce:
It may not be easily reproducible since the exception doesn't occur all the time. But I believe following the exact selections in the video below will reproduce using `example/lib/demos/example_editor.dart`: 

https://user-images.githubusercontent.com/46427323/117160789-15763700-adca-11eb-8129-8bffa528490b.mov

The behavior is observed on the latest `main` as of today with Flutter `(Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-x64)`.

**Comment by matthew-carroll** [comment]
@osaxma at first I was able to repro this, then I went back and now I can't cause the error any more. Can you try to recreate this error on the following PR branch:

https://github.com/superlistapp/super_editor/pull/150

If you're able to consistently cause the error, please update this issue with the relevant steps. Thanks.

**Comment by osaxma** [comment]
Hi @matthew-carroll 

It still happens on `multiple-v0.1.0-issues` branch but I'm unable to reproduce it consistently. I've tried multiple times for the exact same copied text and the exact same pasted region, and the exception would occur at times and it wouldn't at others.

There must be another factor causing the error to happen but I'm unable to pin point the root cause. I speculate that it's a race condition due to the `paste` operation being asynchronous.  

Looking at the log, and using the video as a reference, it appears that `_buildDocComponents()` is being called after  the `block quote` node was deleted and before the `paste` operation is performed. Given that `_buildDocComponents()` is called on an outdated `selection`, `getNodesInside` fails to locate the `block quote` node and hence the exception occur. 

```
flutter: [multi_node_editing.dart] - DeleteSelectionCommand:  - deleting last node
flutter: [multi_node_editing.dart] - DeleteSelectionCommand:  - done with selection deletion
flutter: [DocumentLayout] - _buildDocComponents: _buildDocComponents()

════════ Exception caught by widgets library ═══════════════════════════════════
The following _Exception was thrown building DefaultDocumentLayout-[GlobalKey#b1311](dirty, state: _DefaultDocumentLayoutState#990e0):
Exception: No such position in document: [DocumentPosition] - node: "03008256-0752-4919-acd0-bed1157229b6", position: (TextPosition(offset: 16, affinity: TextAffinity.upstream))

The relevant error-causing widget was
DefaultDocumentLayout-[GlobalKey#b1311]
../…/default_editor/editor.dart:306
When the exception was thrown, this was the stack
#0      MutableDocument.getNodesInside
package:super_editor/…/core/document_editor.dart:173
#1      _DefaultDocumentLayoutState._buildDocComponents
package:super_editor/…/default_editor/layout.dart:405
#2      _DefaultDocumentLayoutState.build
package:super_editor/…/default_editor/layout.dart:383
#3      StatefulElement.build
package:flutter/…/widgets/framework.dart:4612
#4      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4495
...
════════════════════════════════════════════════════════════════════════════════

flutter: [document_keyboard_actions.dart] - _paste: Content from clipboard:
flutter: [document_keyboard_actions.dart] - _PasteEditorCommand: Split content:
flutter: [document_keyboard_actions.dart] - _PasteEditorCommand:  - "Cras vitae sodales nisi. Vivamus dignissim vel purus vel aliquet. Sed viverra diam vel nisi rhoncus pharetra. Donec gravida ut ligula euismod pharetra. Etiam sed urna scelerisque, efficitur mauris vel, semper arcu. Nullam sed vehicula sapien. Donec id tellus volutpat, eleifend nulla eget, rutrum mauris.
"
```


Here's the full log (~6k lines): 

https://gist.github.com/osaxma/5e73c2d4c62ac9deaf1f19a3fb059c93

**Comment by matthew-carroll** [comment]
@osaxma let me know if this branch solves the problem for you: https://github.com/superlistapp/super_editor/pull/159

**Comment by osaxma** [comment]
It doesn't appear to happen anymore.
