### ISSUE TITLE
[feature] characters with multiple codeUnits are not being handled properly  (e.g. flag emojis)

### ISSUE THREAD

**Issue by osaxma** [superlistapp/super_editor#152]
I'm not sure if this is considered a bug or unsupported feature, but I thought I should bring this to your attention. Also, I'm not certain if there are any keyboard character that contains multiple codeUnits, so I assume this problem will only occur if an external text was pasted into the editor.  

### Current Behavior 
Taking the US flag emoji `🇺🇸` as an example which has 4 code Units (i.e., `[55356, 56826, 55356, 56824]`), you can observe in the following video that it'll take `4` arrow presses to move the caret across the character. In addition, modifying the codeUnits (inserting a character in between the codeUnits or deleting any using the backspace) will causes the entire paragraph to disappear due to an `ArgumentError` in `RichText` (provided below the video).

https://user-images.githubusercontent.com/46427323/117168272-acde8880-add0-11eb-87d5-848dd0b863c4.mov

<details> <summary>Exception when modifying codeUnits</summary>

```
════════ Exception caught by rendering library ═════════════════════════════════
The following ArgumentError was thrown during performLayout():
Invalid argument(s): string is not well-formed UTF-16

The relevant error-causing widget was
RichText-[GlobalKey#8fa21]
../…/infrastructure/selectable_text.dart:463
When the exception was thrown, this was the stack
#0      ParagraphBuilder.addText (dart:ui/text.dart:2178:7)
#1      TextSpan.build
package:flutter/…/painting/text_span.dart:204
#2      TextPainter.layout
package:flutter/…/painting/text_painter.dart:569
#3      RenderParagraph._layoutText
package:flutter/…/rendering/paragraph.dart:515
#4      RenderParagraph._layoutTextWithConstraints
package:flutter/…/rendering/paragraph.dart:538
...
The following RenderObject was being processed when the exception was fired: RenderParagraph#415d2 relayoutBoundary=up15 NEEDS-LAYOUT
RenderObject: RenderParagraph#415d2 relayoutBoundary=up15 NEEDS-LAYOUT
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=548.0, 0.0<=h<=Infinity)
    size: Size(548.0, 109.0)
    textAlign: left
    textDirection: ltr
    softWrap: wrapping at box width
    overflow: clip
    locale: en_US

```
</details>

It's worth noting that an official Dart package exists for handling `user-perceived characters` that may be of use when dealing with the given issue: 

> https://pub.dev/packages/characters  
Characters are strings viewed as sequences of user-perceived characters, also known as Unicode (extended) grapheme clusters.
The Characters class allows access to the individual characters of a string, and a way to navigate back and forth between them using a CharacterRange.

**Comment by matthew-carroll** [comment]
Thanks for filing this with all the support info. I believe I've solved this in some unrelated work in the editor. I'll port that fix over to the editor soon.

**Comment by matthew-carroll** [comment]
@osaxma do you know how to differentiate between a multi-codepoint character vs the names like "Shift" and "Alt" that are currently being put in the "character" property on web?

**Comment by osaxma** [comment]
@matthew-carroll I cannot think of a way except for manually checking against the name. 

By the way, I've already filed an issue (https://github.com/flutter/flutter/issues/81940) if you like to keep it as a reference until it's fixed.
