### ISSUE TITLE
Is there a binary somewhere to try this out?

### ISSUE THREAD

**Issue by nuttyartist** [superlistapp/super_editor#1528]
Hi there! Cool project.

Is there a binary I can use to try this out on macOS/Windows/Linux?

**Comment by matthew-carroll** [comment]
No. This is a toolkit, not a product. This project includes an example project that you can build and run on any desktop platform, but it's not a binary.

Are you interested in using Super Editor for your Get Notes product?

**Comment by nuttyartist** [comment]
Gotcha. No, I'm building a block editor as well (a rebrand of my existing note-taking app) but in Qt C++ and QML (https://www.get-plume.com) and wanted to check how's Flutter for that. I know https://github.com/AppFlowy-IO/AppFlowy exists but I'm not very impressed by it.

My code is also open-source in this branch: https://github.com/nuttyartist/notes/tree/block-editor

**Comment by matthew-carroll** [comment]
@nuttyartist Super Editor currently isn't optimized for block editing. However, our goal is to provide appropriate building blocks for any and all editors, including block editors.

Given that you've had some experience with AppFlowy, and there are things you don't like, we're happy to consider building better solutions in those areas, so long as they remain roughly within our mission. Would you like to mention some of the things you don't like about AppFlowy?

**Comment by matthew-carroll** [comment]
> You can't select text backward

Do you mean across blocks? Or even within a single paragraph? Also, did that happen on web, or did that happen on desktop/mobile?

> No drag-and-drop support

Drag and drop for blocks? Or are there are other drag and stop use-cases you care about?

> It's slow

I'll admit that we don't have any performance metrics. Our clients simply haven't needed us to focus on that side of things. They've used `SuperEditor` without issue despite us not focusing on performance metrics. That said, I'm open to beginning to engrain some performance goals. I'm not family with the "Moby Dick Workout" or the "War and Peace Workout" - are these a part of some quasi-standard? Would you care to elaborate

> I don't like many of their UX and UI decisions

Would you like to elaborate? We aim for as much customization as we can possibly provide. That's because we're trying to ship a toolkit, not a drop-in-editor. But it's probably worth hearing the specifics that are on your mind.

**Comment by nuttyartist** [comment]
> Do you mean across blocks? Or even within a single paragraph? Also, did that happen on web, or did that happen on desktop/mobile?

Well actually, both forward and backward selection don't work as expected, in the same block.

https://github.com/superlistapp/super_editor/assets/16375940/27fe51fe-379a-49cc-af86-1f8e38c9bc28

> Drag and drop for blocks? Or are there are other drag and stop use-cases you care about?

Yes, for blocks.

> I'm not family with the "Moby Dick Workout" or the "War and Peace Workout" - are these a part of some quasi-standard? Would you care to elaborate

Well, Bike Outliner's (https://www.hogbaysoftware.com/bike/) developer came up with this form of test, to test wether a text editor can handle text well. I think in 2023 any text editor should be able to pass this test, if it's not, it's probably not designed well or made up using some bloated technology like React. You can read in the blog I linked about the test is performed. He gives there the files to replicate such a test.

> Would you like to elaborate? We aim for as much customization as we can possibly provide. That's because we're trying to ship a toolkit, not a drop-in-editor. But it's probably worth hearing the specifics that are on your mind.

I think if you give it a spin you'll notice just bad design and lack of attention to detail.

This one hurts my eyes.
![Screen Shot 2023-10-18 at 12 19 55 AM](https://github.com/superlistapp/super_editor/assets/16375940/efa79665-8f79-42f5-a129-6f69646c3c8d)

Also, they don't support columns, an important feature in Notion's editor, in my opinion.

**Comment by matthew-carroll** [comment]
We definitely support bi-directional selection within, and across nodes. Though, again, we don't have a concept of blocks the way some other editors do these days. But we're open to adding the concept of blocks.

We also support expected double and triple click on all platforms, and we support long-press drags on mobile.

I can't speak to "bloated technology" - seems very much a personal judgement. I don't know what makes React bloated, and if you think React is fundamentally bloated then perhaps you'll feel the same way about Flutter.

I'm also sure we have various visual details that aren't perfect. But, as with anything else, we're open to fixing discrepancies that are clearly identified.

**Comment by nuttyartist** [comment]
> I can't speak to "bloated technology" - seems very much a personal judgement. I don't know what makes React bloated, and if you think React is fundamentally bloated then perhaps you'll feel the same way about Flutter.

How is this a personal judgment if we can **measure** this? 
- Import moby_dick.txt and start a timer. Stop it when the full text is loaded. 
- Scroll the text. Is there a lag?
- Type in the middle of the text. Is there a lag?
- Resize the window. Resizes immediately or halts your computer?
- Etc...

> I don't know what makes React bloated, 

Just try this test with any block editor based on react. I'm using a 2017 MacBook Air for these tests. Most of these apps crash or just can't load it. Notion, Anytype, MarkText, etc... Not to mention loading War and Peace. 

> and if you think React is fundamentally bloated then perhaps you'll feel the same way about Flutter.

I'm not **feeling**. I want to measure, to test, to verify. This is why I wanted to try to SupoerEditor. Flutter looks like a cool technology. I wanted to see how it compares to Qt's QML.

**Comment by matthew-carroll** [comment]
Understood.

I'm going to close this issue because it's not actionable from a development standpoint.

If you decide to use Super Editor, you're welcome to file tickets for features and bug fixes.

I filed https://github.com/superlistapp/super_editor/issues/1531 to look into adding standard performance examples/tests.

**Comment by nuttyartist** [comment]
Awesome. Would love to check it out some day.
