### ISSUE TITLE
[SuperEditor][Example App] - TextComponent renders Checkbox component with the markdown 

### ISSUE THREAD

**Issue by abidex4yemi** [superlistapp/super_editor#1560]
# Description:

I have encountered an unusual bug when working with the Task component. I'm trying to render the TaskComponent with a custom Checkbox, but the checkmark doesn't appear as expected. I have attached a screenshot to illustrate the issue.

Screenshot:
![screen](https://github.com/superlistapp/super_editor/assets/23571838/0ce0bff1-6547-4ef4-8d38-220e3f47fc26)

Possible Solution:
Any ideas about how to fix or work around this issue @matthew-carroll @angelosilvestre

**Comment by matthew-carroll** [comment]
Please provide a minimal reproduction. I can't propose a solution when I can't see the technical problem.

**Comment by abidex4yemi** [comment]
Here's an example code

`class TaskComponent extends StatelessWidget {
  const TaskComponent({
    Key? key,
    required this.textKey,
    required this.viewModel,
    required this.readOnly,
    this.showDebugPaint = false,
  }) : super(key: key);

  final GlobalKey textKey;
  final bool readOnly;
  final TaskComponentViewModel viewModel;
  final bool showDebugPaint;

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Checkbox(
          visualDensity: VisualDensity.compact,
          splashRadius: 0.0,
          fillColor: MaterialStateProperty.resolveWith<Color>((states) {
            if (states.contains(MaterialState.selected)) {
              return readOnly ? AppColors.text3 : AppColors.greenColor;
            }
            return readOnly ? AppColors.text3 : AppColors.greenColor;
          }),
          materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
          value: viewModel.isComplete,
          onChanged: (newValue) {
            if (!readOnly) viewModel.setComplete(newValue!);
          },
        ),
        Expanded(
          child: Align(
            alignment: Alignment.topLeft,
            child: TextComponent(
              key: textKey,
              text: viewModel.text,
              textStyleBuilder: (attributions) {
                final style = viewModel.textStyleBuilder(attributions);
                return style;
              },
              textSelection: viewModel.selection,
              selectionColor: viewModel.selectionColor,
              highlightWhenEmpty: viewModel.highlightWhenEmpty,
              showDebugPaint: showDebugPaint,
            ),
          ),
        ),
      ],
    );
  }
}`

`documentBuilders`

`componentBuilders: [
          ...defaultComponentBuilders,
          TaskComponentBuilder(_docEditor, readOnly: widget.readOnly),
        ],`
        
        
 `serializing to markdown`
 `if (node is TaskNode) {
      String text = node.text
          .toMarkdown()
          .replaceAll('[]', '')
          .replaceAll('[x]', '')
          .trim();

      buffer.write('- [${node.isComplete ? 'x' : ''}] ${text}');

      final nodeBelow = i < doc.nodes.length - 1 ? doc.nodes[i + 1] : null;
      if (nodeBelow != null && (nodeBelow is! TaskNode)) {
        // This list item is the last item in the list. Add an extra
        // blank line after it.
        buffer.writeln('');
      }
    }`
    
    @matthew-carroll hopefully you can reproduce the issue with the above code sample.

**Comment by matthew-carroll** [comment]
@abidex4yemi and what exactly are the reproduction steps? What action does a user need to take to see the problem? What's the expected result? What's the actual result?
