### ISSUE TITLE
Add support for other document format (quill)

### ISSUE THREAD

**Issue by BazinC** [superlistapp/super_editor#1565]
Have you considered providing serializer/parser like `super_editor_markdown` but for other document type?

In our company we use Quill on web FE and we have to deal with it in our flutter app.
We tried `flutter_quill` but it's not convincing for now.

Super Editor looks very promising and we would be interested in contributing to a quill adapter.

**Comment by matthew-carroll** [comment]
We're open to building any document format that one or more funding clients would like to support. Any company can become a funding supporter.

Early on we thought we might need HTML support. Our clients found that they were fine without it. One format we discovered that was important to many clients was Markdown, so we built it.

Superlist (not the same thing as Super Editor) has built their own internal document representation that includes delta-based editing, similar to Quill. So it's also technically possible for any client of Super Editor to do the same.
