### ISSUE TITLE
[SuperEditor & SuperTextField] ColorAttribution support

### ISSUE THREAD

**Issue by Sh4dord** [superlistapp/super_editor#1579]
Hello, 

Is text coloring for SuperEditor, SuperReader and SuperTextField under development? 

ColorAttribution doesn't seem to be working at the moment.

Thank you.

```
ParagraphNode(
  id: Editor.createNodeId(),
  text: AttributedText(
    'My text colored in orange',
    AttributedSpans(
      attributions: const [
        SpanMarker(
          attribution: boldAttribution,
          offset: 0,
          markerType: SpanMarkerType.start,
        ),
        SpanMarker(
          attribution: ColorAttribution(
            Colors.orange,
          ),
          offset: 0,
          markerType: SpanMarkerType.start,
        ),
        SpanMarker(
          attribution: ColorAttribution(
            Colors.orange,
          ),
          offset: 24,
          markerType: SpanMarkerType.end,
        ),
        SpanMarker(
          attribution: boldAttribution,
          offset: 24,
          markerType: SpanMarkerType.end,
        ),
      ],
    ),
  ),
),
```

<img width="368" alt="Capture d’écran 2023-10-30 à 10 43 43" src="https://github.com/superlistapp/super_editor/assets/117819190/b77af6d8-8a41-47e3-a0bc-5530d51d4aa1">

**Comment by rutvik110** [comment]
@Sh4dord I'm testing this against `main` on iphone simulator and macOS desktop, and I'm not able to reproduce the issue you're describing.

Could you please share a reproducible example where this issue is occurring?

**Comment by Sh4dord** [comment]
Okey, what is the difference between stable and main ?
I currently use stable and on stable is not working. Does I in development feature ?

**Comment by Sh4dord** [comment]
> @Sh4dord I'm testing this against `main` on iphone simulator and macOS desktop, and I'm not able to reproduce the issue you're describing.
> 
> <img alt="Screenshot 2023-11-05 at 6 01 50 PM" width="540" src="https://user-images.githubusercontent.com/65209850/280526259-f51382f1-005e-4393-a65c-ee8c3df226eb.png">
> 
> Could you please share a reproducible example where this issue is occurring?

Okey, what is the difference between `stable` and `main` ?
I currently use `stable` and on this is not working.

**Comment by rutvik110** [comment]
> I currently use stable and on stable is not working. Does I in development feature ?

By stable, are you referring to the `super_editor` package hosted on pub.dev? and is that what you're using in your pubspec rn?

**Comment by rutvik110** [comment]
@Sh4dord Could you please share the Flutter version you're using and a reproducible example for this issue? 

For `super_editor`, `stable` branch is tested against Flutter `stable` channel, and `main` against Flutter `master` channel. So far on both of this branches with latest Flutter `stable` 3.13.9 and `master` updates, I'ven't been able to reproduce this issue.

**Comment by Sh4dord** [comment]
@rutvik110 Sorry for response delay

I use Flutter branch `stable`
```bash
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.5.1 22G90 darwin-arm64, locale fr-FR)
```
I use also super_editor on branch `stable`
pubspec.yaml
```yaml

dependencies:
  flutter:
    sdk: flutter
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor
      path: super_editor
      ref: stable

dependency_overrides:
  super_text_layout:
    git:
      url: https://github.com/superlistapp/super_editor
      path: super_text_layout
      ref: stable
  attributed_text:
    git:
      url: https://github.com/superlistapp/super_editor
      path: attributed_text
      ref: stable

dev_dependencies:
  flutter_test:
    sdk: flutter
```

Then I use SuperReader : 
super_reader.dart
```dart
SuperReader(
              document: MutableDocument(
                nodes: [
                  ParagraphNode(
                    id: Editor.createNodeId(),
                    text: AttributedText(
                      'My text colored in orange',
                      AttributedSpans(
                        attributions: const [
                          SpanMarker(
                            attribution: boldAttribution,
                            offset: 0,
                            markerType: SpanMarkerType.start,
                          ),
                          SpanMarker(
                            attribution: ColorAttribution(
                              Colors.orange,
                            ),
                            offset: 0,
                            markerType: SpanMarkerType.start,
                          ),
                          SpanMarker(
                            attribution: ColorAttribution(
                              Colors.orange,
                            ),
                            offset: 24,
                            markerType: SpanMarkerType.end,
                          ),
                          SpanMarker(
                            attribution: boldAttribution,
                            offset: 24,
                            markerType: SpanMarkerType.end,
                          ),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
            ),
```

I that case, I have the problem of the orange text not colored in orange but in black

**Comment by rutvik110** [comment]
I was able to reproduce this issue with `SuperReader` but not `SuperEditor`.  

@Sh4dord Could you please confirm if this is an issue with `SuperReader` only or if `SuperEditor` also has similar issue on your side?

**Comment by rutvik110** [comment]
@Sh4dord Could you please check if the linked PR resolves your issue?
