### ISSUE TITLE
[SuperEditor] - Error: Type 'BlinkTimingMode' not found

### ISSUE THREAD

**Issue by abidex4yemi** [superlistapp/super_editor#1580]
I'm getting `Error: Type 'BlinkTimingMode' not found` during installation of super_editor using GitHub path.

> super_editor:
>     git:
>       url: https://github.com/superlistapp/super_editor.git
>       ref: main
>       path: super_editor

      
see screenshot for error log
<img width="1054" alt="Screenshot 2023-11-02 at 2 54 23 AM" src="https://github.com/superlistapp/super_editor/assets/23571838/d11fbdd1-a6de-4bb5-99de-a3b8a27744ad">

@matthew-carroll @angelosilvestre any idea?

**Comment by matthew-carroll** [comment]
Please see the README about overriding the versions of our packages in your pubspec

**Comment by abidex4yemi** [comment]
It works fine, thank you.
