### ISSUE TITLE
[SuperReader] - How do I disable text highlight and copy floating toolbar.

### ISSUE THREAD

**Issue by abidex4yemi** [superlistapp/super_editor#1585]
I'm looking for ways to disable text highlight and copy the floating toolbar but after looking at the docs no clear explanation or key on how to achieve this. I want to disable the toolbar and text selection completely @matthew-carroll

**Comment by abidex4yemi** [comment]
see screenshot: 
![super_reader](https://github.com/superlistapp/super_editor/assets/23571838/7a8c68a2-f585-4459-9899-842e887cce21)

**Comment by matthew-carroll** [comment]
What does "disable text highlight and copy the floating toolbar" mean?

**Comment by abidex4yemi** [comment]
I want to render the SuperReader widget and disable the text selection option such that the user can't select or copy the text.

**Comment by abidex4yemi** [comment]
@matthew-carroll

**Comment by Jethro87** [comment]
@abidex4yemi Try wrapping your `SuperReader` widget in an `IgnorePointer`

```
    return IgnorePointer(
      ignoring: widget.ignorePointer,
      child: SuperReaderIosControlsScope(
        controller: _iosControlsController,
        child: SuperReader(
          document: widget.document,
          selectionStyle: SelectionStyles(
            selectionColor: Theme.of(context).textSelectionTheme.selectionColor ?? themes.primary.withOpacity(0.15),
          ),
...
```

Also, you can choose to not build the selection toolbars, as such:

```
_iosControlsController = SuperReaderIosControlsController(
      toolbarBuilder: widget.enableSelectionToolbar ? _buildIosToolbar : null,
      magnifierBuilder: widget.enableSelectionToolbar ? _buildIosMagnifier : null,
    );
```

and

```
androidToolbarBuilder: widget.enableSelectionToolbar
              ? (_) => AndroidTextEditingFloatingToolbar(
                    onCopyPressed: _copy,
                    onSelectAllPressed: _selectAll,
                  )
              : null,
```

**Comment by matthew-carroll** [comment]
Thanks for posting that @Jethro87 - I hadn't gotten around to reviewing the API again. 

@abidex4yemi please let us know if that solves your issue.

**Comment by abidex4yemi** [comment]
Thank you @Jethro87, @matthew-carroll the second approach is a better option for me but it's still not working as expected, see the code snippet below.

``late SuperReaderIosControlsController _iosReaderControlsController;``


```
@override
  void initState() {
    _iosReaderControlsController = SuperReaderIosControlsController(
        toolbarBuilder: null,
        magnifierBuilder: null,
        createOverlayControlsClipper: null);
  }
```

```
Container(
          child: SuperReaderIosControlsScope(
            controller: _iosReaderControlsController,
            child: SuperReader(
              document: _document,
              selection: _selection,
              selectionLayerLinks: _selectionLayerLinks,
              componentBuilders: [
                ...defaultComponentBuilders,
              ],
              androidToolbarBuilder: (_) => AndroidTextEditingFloatingToolbar(
                onCopyPressed: null,
                onSelectAllPressed: null,
              ),
            ),
          ),
        ),
```

**Comment by Jethro87** [comment]
@abidex4yemi You should say what's not working. From the code you pasted, you should return null in `androidToolbarBuilder` rather than pass null to its functions.

```
androidToolbarBuilder: null,
...
```

**Comment by matthew-carroll** [comment]
It looks like we've been unable to obtain a clear description of the problem. I'm going to close this issue. If you can better describe what's wrong, or what you've tried that isn't working, then you can open a new issue.

**Comment by paurakhsharma** [comment]
@matthew-carroll  @Jethro87  I am trying to achieve the same thing. But it is still not resolved.

I don't want user to be able to select and or copy the text inside `SuperReader`.

I cannot wrap `SuperReader` inside `IgnorePointer` because I want to handle `contentTapDelegateFactory`

Here is what I have tried.
```dart
class MySuperReader extends StatefulWidget {
  final List<DocumentNode> nodes;
  const MySuperReader({super.key, required this.nodes});

  @override
  State<MySuperReader> createState() => _MySuperReaderState();
}

class _MySuperReaderState extends State<MySuperReader> {
  late MutableDocument _doc;
  late SuperReaderIosControlsController _iosReaderControlsController;

  @override
  Widget build(BuildContext context) {
    return SuperReaderIosControlsScope(
      controller: _iosReaderControlsController,
      child: SuperReader(
        document: _doc,
        contentTapDelegateFactory: (readerContext) => bibleLinkHandlerFactory(
          readerContext,
          context,
        ),
      ),
    );
  }

  MutableDocument _createDocument() {
    return MutableDocument(nodes: widget.nodes);
  }


  @override
  void initState() {
    super.initState();

    _doc = _createDocument();
    _iosReaderControlsController = SuperReaderIosControlsController(
      toolbarBuilder: (_, __, ___) => const SizedBox(),
      magnifierBuilder: (_, __, ___, ____) => const SizedBox(),
    );
  }

  @override
  void dispose() {
    _doc.dispose();
    _iosReaderControlsController.dispose();
    super.dispose();
  }
}
```

But the user is still able to select the text but not copy it because I have removed the toolbars by returning `SizedBox()`.

I even tried removing `SuperReaderIosControlsScope` but it is still the same (the user can select the text & copy text).
