### ISSUE TITLE
Changing text alignment doesn't reflect the alignment change on the text node within the document immediately.

### ISSUE THREAD

**Issue by rutvik110** [superlistapp/super_editor#1587]
**The Issue:**

Changing text alignment of a paragraph node doesn't reflect the alignment change immediately in the document. This change is reflected only after I make any other edits to the document.

To reproduce: 

1. Select any text within `SuperEditor`.
2. Change text alignment through alignment dropdown within toolbar.
3. Make any arbitrary edits to the document to see the text alignment change.

Demo:

https://github.com/superlistapp/super_editor/assets/65209850/47c44e02-5988-4922-a3e5-17f3c1eeb780

**Expected behaviour:**

Change in text alignment should be reflected immediately in the document.

**Comment by rutvik110** [comment]
It seems that rn when we want to update the text alignment of the selection through the toolbar, the alignment change callback from the dropdown only updates the metadata on the node with the new alignment value, 

```
/_toolbar.dart
 
// on alignment changed callback from dropdown
// updates selection node metadata
selectedNode.putMetadataValue('textAlign', newAlignmentValue);
```

This call doesn't trigger a `SuperEditor` rebuild that should've reflected the change. Likely due to the fact that only changing the metadata on the node here, isn't notifying any document listeners that the document has changed. So, this change isn't reflected across parts of `SuperEditor` which are responsible for updating themselves on document change.

And this doesn't seem like the correct way to change the alignment on text selection. What I mean by that is the process for changing text attributions usually starts with making a change request to the `Editor`, for e.g. request to toggle bold on text selection looks like follow,

```
widget.editor!.execute([
      ToggleTextAttributionsRequest(
        documentRange: widget.composer.selection!,
        attributions: {boldAttribution},
      ),
]);
```

That isn't the case for changing alignment on node. 

**Proposed solution:** 

What we want is the ability to change the text alignment in similar manner as for the other attributions as shown in the example above.  We could achieve this in two ways, 

1. Update existing `ToggleTextAttributionsCommand`, `AddTextAttributionsCommand` and `RemoveTextAttributionsCommand` to handle changing alignment on the text node itself.  Right now, they only update the attributions on the `AttributedText` text present within node, with the received attributions.

For the alignment change, we want to update the node's metadata itself. For this, we could check the incoming attributions,  if one of the changed attribution is alignment then update the alignment on the node.  

2. Create a separate `EditRequest` and `EditCommand` responsible for dealing with changing alignment on node.  This will separate the alignment handling on node from handling of `AttributedText` updates. 

Both of this approaches will require us to introduce 4 new `NamedAttribution`'s,  `textAlignLeft`, `textAlignRight`, `textAlignCenter`, `textAlignJustify` which can used to identify the incoming attribution within the request.

@matthew-carroll What are your thoughts on this issue?

**Comment by angelosilvestre** [comment]
I think we should create a new request/command to change the alignment, but I don't think the alignment should be an attribution.

An attribution can be applied to a portion of the paragraph. However, the alignment is applied to the whole paragraph.

**Comment by rutvik110** [comment]
ok, I'll push the working solution I've rn for this where the alignment passed in this request is just a string, and we can take it from there in the PR.
