### ISSUE TITLE
[SuperEditorMarkdown] & changes to &amp; when serialized to markdown

### ISSUE THREAD

**Issue by alterhuman** [superlistapp/super_editor#1591]
When data is serialized using `serializeDocumentToMarkdown`, `&` changes to `&amp;`

**Comment by Mijawel** [comment]
Also seen that. And the < and > symbols also become "&lt;" and "&gt;" respectively.

**Comment by matthew-carroll** [comment]
Can you please provide reproduction steps?

I just wrote the following test and it passes:

```dart
      test('paragraph with special characters', () {
        final doc = MutableDocument(nodes: [
          ParagraphNode(
            id: '1',
            text: AttributedText('This is a <paragraph> & specials symbols.'),
          ),
        ]);

        expect(serializeDocumentToMarkdown(doc), 'This is a <paragraph> & specials symbols.');
      });
```

**Comment by Mijawel** [comment]
Sorry I realised that unlike the OP, I am getting this error with:

MutableDocument deserializeMarkdownToDocument(
  String markdown, {
  MarkdownSyntax syntax = MarkdownSyntax.superEditor,
  List<md.BlockSyntax> customBlockSyntax = const [],
  List<ElementToNodeConverter> customElementToNodeConverters = const [],
})

Although, having tested it again now, the error is still occurring.

**Comment by matthew-carroll** [comment]
@Mijawel can you please provide reproduction steps? What exactly are you calling that method with? What error is being reported?

**Comment by Mijawel** [comment]
```
String markdownText = "Please note that the user prefers the use of ampersands (&) instead of the full word 'and'.";
    print(markdownText);
    var markdownDocument = deserializeMarkdownToDocument(markdownText);
    // print out the document
    for (DocumentNode node in markdownDocument.nodes) {
      print(node);
    }
```

Output:
Please note that the user prefers the use of ampersands (&) instead of the full word 'and'.
[TextNode] - text: [AttributedText] - "Please note that the user prefers the use of ampersands (&amp;) instead of the full word 'and'."
[AttributedSpans] (0 spans):, metadata: {textAlign: null, blockType: [NamedAttribution]: paragraph}

**Comment by matthew-carroll** [comment]
This issue has been solved by this PR: https://github.com/superlistapp/super_editor/pull/1674
