### ISSUE TITLE
[SuperEditor] Triple dot on iOS removes text and throws error

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#1592]
This is happening on super_editor stable + Flutter stable. 

https://github.com/superlistapp/super_editor/assets/6467808/577a7655-c5e2-41ad-b211-50c787642c78

This is the error: 

```
════════ Exception caught by services library ══════════════════════════════════
The following _TypeError was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      TextDeltasDocumentEditor._applyInsertion
document_delta_editing.dart:152
#1      TextDeltasDocumentEditor.applyDeltas
document_delta_editing.dart:79
#2      DocumentImeInputClient.updateEditingValueWithDeltas
document_ime_communication.dart:220
#3      TextInput._handleTextInputInvocation
text_input.dart:1864
#4      TextInput._loudlyHandleTextInputInvocation
text_input.dart:1753
#5      MethodChannel._handleAsMethodCall
platform_channel.dart:547
#6      MethodChannel.setMethodCallHandler.<anonymous closure>
platform_channel.dart:540
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
binding.dart:567
#8      _invoke2 (dart:ui/hooks.dart:202:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:331:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:736:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [6, {deltas: [{selectionBase: 1, oldText: , selectionAffinity: TextAffinity.downstream, deltaEnd: 0, deltaText: ., deltaStart: 0, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 1, composingBase: -1}]}])
════════════════════════════════════════════════════════════════════════════════
```

cc @matthew-carroll

**Comment by matthew-carroll** [comment]
@angelosilvestre my uneducated guess is that what we're seeing in this video is an IME interaction where iOS is trying to replace triple dots with something and its failing. It might be failing due to existing IME communication problems that we know we have with Flutter. Or perhaps the special triple dot character isn't supported by the font. In any event, please take a look. If it's a Flutter bug, please add it to the appropriate existing Flutter ticket and tag @Jethro87 so he can tell the Flutter team that their IME problems continue to hold back his company.

**Comment by angelosilvestre** [comment]
@matthew-carroll This seems to be the same of https://github.com/flutter/flutter/issues/129061

Typing three dots causes the three dots to be replaced by a single character. However we are getting deletion and insertion deltas in separate calls to `updateEditingValueWithDeltas`,  leaving us out of sync with the IME.

On Flutter master channel this doesn't happen, so I guess the fix isn't on Flutter stable yet.

**Comment by angelosilvestre** [comment]
As of Flutter 3.16 this doesn't seem to happen anymore on the stable branch.

@Jethro87 Could you please try ?

**Comment by Jethro87** [comment]
@angelosilvestre It looks like this is fixed on stable. Thanks.
