### ISSUE TITLE
[SuperReader] - Customize user tag, and link ontap/select handler in read mode.

### ISSUE THREAD

**Issue by abidex4yemi** [superlistapp/super_editor#1595]
I have checked around to see if there's any documentation on how to use stable and pattern tags but none exist in the docs. 

My question is how do I listen to the selection/onTap of @mention, #tag, link, or custom pattern tag in SuperReader such that I can control the selection/tap handler? @angelosilvestre @matthew-carroll 

I have tried the below code but not working.

```
_composer
      ..selectionNotifier.addListener(() {});
```

**Comment by abidex4yemi** [comment]
@angelosilvestre any idea?

**Comment by matthew-carroll** [comment]
You posted a line of code but you didn't describe why and how that doesn't help you....

If you listen for selection changes, then upon a selection change you can do the following:

- Check if the selection is expanded, if it is, return
- Check if the extent selects text, if not, return
- Check the attributes in the text at the extent, if it contains a tag attribution that you care about, then do something

**Comment by abidex4yemi** [comment]
The `_composer..selectionNotifier.addListener(() {});` is not returning selected text see my `SuperReader` setup below. 

Note: this same method works fine when using `SuperEditor`.

```
@override
  void initState() {
    _iosReaderControlsController = SuperReaderIosControlsController(
        toolbarBuilder: null,
        magnifierBuilder: null,
        createOverlayControlsClipper: null);
    _composer = MutableDocumentComposer();
    _doc = createInitialDocument();
    _document =
        deserializeMarkdownToDocument(content);
    _docEditor =
        createDefaultDocumentEditor(document: _doc, composer: _composer);

    _composer
      ..selectionNotifier.addListener(() {
        final selection = _composer.selection; 
        print("selection: $selection");
        if (selection?.base == selection?.extent && selection != null) {
          var sel = _doc.getNodeById(selection.extent.nodeId);

          if (sel is TextNode) {
            var selectedText = sel.text
                .copyText(0,
                    (selection.extent.nodePosition as TextNodePosition).offset)
                .text;
          }
        }
      });
    super.initState();
  }

  @override
  void dispose() {
    _iosReaderControlsController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SuperReaderIosControlsScope(
      controller: _iosReaderControlsController,
      child: SuperReader(
        document: _document,
        selection: _selection,
        selectionLayerLinks: _selectionLayerLinks,
        androidToolbarBuilder: null,
        stylesheet: EditorConfig.createStyles(
            context: context),
      ),
    );
  }
```

@matthew-carroll

**Comment by matthew-carroll** [comment]
> The _composer..selectionNotifier.addListener(() {}); is not returning selected text

This statement doesn't make any sense. Why would calling `addListener()` ever return selected text? Again, you're not providing sufficient information for us to help you.

**Comment by matthew-carroll** [comment]
It seems that we've been unable to get a clear description of a problem in this ticket. I'm going to close this issue. When/if you're able to clearly describe the issue you're facing in a way that we can reproduce the issue, or clearly understand your goal, you're welcome to open another issue ticket with those details.
