### ISSUE TITLE
[Web] [Windows] Japanese Hiragana / Katagana input duplicated on new line

### ISSUE THREAD

**Issue by brian-superlist** [superlistapp/super_editor#1601]
**Reproduction Steps**

1. Add Japanese Language Pack to windows
2. Open super editor demo on windows (flutter `master`, super editor `main`)
3. Use Windows Language Bar to select Japanese Input -> Hiragana
4. Type at end of regular line. IME display is correct.
5. Create new paragraph, start typing. First character is duplicated, therefore IME suggestions are incorrect.

https://github.com/superlistapp/super_editor/assets/90610075/206a4760-2e71-4b2d-8c55-bc5cb371ca23

**Comment by brian-superlist** [comment]
A similar thing happens on MacOS and web, but slightly different. Please let me know if I should file a separate issue, but perhaps they both have a similar underlying cause?

**Reproduction Steps**

1. Add Japanese Language Pack to MacOS
2. Open super editor demo on mac web (flutter master, super editor main)
3. Use Mac Menu Bar to select Japanese Input -> Hiragana
4. Type at end of regular line. IME display is correct.
5. Create new paragraph, start typing. Only second character is detected for IME suggestions.


https://github.com/superlistapp/super_editor/assets/90610075/44e0eba7-6806-448a-b245-f6cc86b2bd09

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll @angelosilvestre

**Comment by brian-superlist** [comment]
Looks to be, and it's fixed with the latest changes.
