### ISSUE TITLE
[SuperEditor][SuperTextField][Mobile] Unable to change `TextCapitalization` of the text field

### ISSUE THREAD

**Issue by robertodoering** [superlistapp/super_editor#1617]
Changes to the `textCapitalization` in the `imeConfiguration` of a `SuperTextField` seem to have no effect.
The virtual keyboard always shows lower case characters and disregards any text capitalization setting.
Tested on the latest main. This happens both on Android and iOS.

I assume this is a bug because it works with the default Flutter TextField. Let me know if I've got something wrong.

### Showcase (with `TextCapitalization.characters`):
<img width=300 src=https://github.com/superlistapp/super_editor/assets/20045287/1f0c437a-63c0-41be-a121-5f42278efa05 />

### How to reproduce:
In the super_editor example, modify the `demo_superiostextfield.dart` and add any `textCapitalization` to the `imeConfiguration` of the `SuperIOSTextField`.
```dart
imeConfiguration: TextInputConfiguration(
  textCapitalization: TextCapitalization.characters,
),
```

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll
