### ISSUE TITLE
[SuperEditor][SuperReader][iOS] - CMD key isn't reported correctly on iOS

### ISSUE THREAD

**Issue by MSimone12** [superlistapp/super_editor#1625]
When on iPad, when trying to use keybindings, the `isPrimaryShortcutKeyPressed` getter does not return true whatsoever, making it incompatible with iOS devices.

The fix is quite simple, just add the TargetPlatform.iOS check when meta is pressed inside the getter.

From this:
```dart
(defaultTargetPlatform == TargetPlatform.macOS && isMetaPressed)
```
To this:
```dart
([TargetPlatform.macOS, TargetPlatform.iOS].contains(defaultTargetPlatform) && isMetaPressed)
```

**Comment by angelosilvestre** [comment]
This was resolved in https://github.com/superlistapp/super_editor/pull/1678.
