### ISSUE TITLE
[SuperEditor][SuperReader][SuperTextField] - Manually verify key press behaviors

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#1629]
We just merged Greg's replacement of `RawKeyEvent` with `KeyEvent` throughout this repo. All tests pass, but we know there are some things that aren't effectively covered by tests.

For this ticket, please run the various example apps and see if you're able to break anything. This investigation should include testing against IME mode, as well as pure keyboard mode. We'd like to make sure that all key presses still work as expected.

If you find any issues, please describe the repo steps in this ticket.

**Comment by angelosilvestre** [comment]
[SuperReader] I'm not sure if this is expected or if it's a bug related to `KeyRepeatEvent`. Pressing an arrow key scrolls the document, but if I hold the arrow key, the document doesn't continue to scroll.

https://github.com/superlistapp/super_editor/assets/7597082/287c06b3-50e7-4038-89a7-b1483c522dc0

**Comment by angelosilvestre** [comment]
Another thing I've noticed, but should be unrelated, is that cmd + x does nothing in the `SuperTextField` demo.

**Comment by angelosilvestre** [comment]
@matthew-carroll I've found another unrelated issue: https://github.com/superlistapp/super_editor/issues/1632

The other interactions seem to be working as expected.

**Comment by rutvik110** [comment]
Not sure if this is related or not but pressing Shift+Cmd+ right/left arrow to expand the selection doesn't seem to work after initial two/three presses. 

What's expected is if I keep pressing Shift+Cmd+ right/left arrow, selection should continue expanding until I stop but that doesn't seem to be happening. 


https://github.com/superlistapp/super_editor/assets/65209850/0b41ab51-11b1-4ffb-8fe3-5b9f75926081

**Comment by rutvik110** [comment]
> Not sure if this is related or not but pressing Shift+Cmd+ right/left arrow to expand the selection doesn't seem to work after initial two/three presses.
> 
> What's expected is if I keep pressing Shift+Cmd+ right/left arrow, selection should continue expanding until I stop but that doesn't seem to be happening.
> 
>  Screen.Recording.2023-12-01.at.12.22.49.PM.mov

All good. I assumed the wrong behaviour here. This is working as expected.

**Comment by angelosilvestre** [comment]
@matthew-carroll I think we can already close this.
