### ISSUE TITLE
[SuperEditor] Applying a link attribution doesn't update layout immediately

### ISSUE THREAD

**Issue by angelosilvestre** [superlistapp/super_editor#1632]
### Steps to reproduce:

1. Double tap to select a word
2. Select the link button in the toolbar
3. Type an url and press enter

### Expected result

The layout is updated immediately, applying the style to the link

### Actual result

The layout doesn't update until pressing another key or tapping somewhere else

https://github.com/superlistapp/super_editor/assets/7597082/ec2eb472-e447-4c88-8d64-5444acdb40eb

**Comment by rutvik110** [comment]
@angelosilvestre Could this be related to the caret not being updated on paragraph alignment change issue that we're discussing? #1587

**Comment by angelosilvestre** [comment]
@rutvik110 I'm not sure. Until recently this was working correctly.
