### ISSUE TITLE
[SuperTextField] Text color with text field doesn't respect app theme.

### ISSUE THREAD

**Issue by rutvik110** [superlistapp/super_editor#1633]
### **Description:** 

Text within `SuperTextField` is colored white by default, and doesn't seem to be respecting text color set in the global app theme. 

To reproduce: 

1. Add `SuperTextField`.
2. Start typing.
3. You'll noticed the text within `SuperTextField` is colored white.

Demo: 

https://github.com/superlistapp/super_editor/assets/65209850/23b609c6-769a-4b21-b30c-f372966c15d2

### **Expected behaviour:** 

By default in light mode, the text should be colored black. And `SuperTextField` should respect the text color from the global app theme. 

Passing a custom `textStyleBuilder` to `SuperTextField` that creates a text style with appropriate color resolves the issue. But, users shouldn't need to pass it to just get the text rendered properly. 

### **Proposed solution:** 

The issues seems to be arising from the fact that the `super_editor`s text rendering system at the very low level extends to the `RichText` widget. And `RichText` widget isn't affected by the global app theme as mentioned [here](https://github.com/flutter/flutter/issues/61452#issuecomment-658219360). 

`SuperEditor` and `SuperReader` handle this by passing in default text color through their default style sheet builders i.e used for styling text within document. For the `SuperTextField` we could do the same, and pass a default text color black to its `defaultTextFieldStyleBuilder` that constructs the text style applied to text.

**Comment by rutvik110** [comment]
@matthew-carroll Fix should be a very small change to the `SuperTextField`'s `defaultTextFieldStyleBuilder` where we pass a default text color black. I could make this update in this PR #1579 which seems to overlap in this area.

**Comment by matthew-carroll** [comment]
@rutvik110 sure, feel free to fix that. However, you're proposed snippet seems like it still doesn't take into account the brightness. So that's just inverting the problem, right?

**Comment by rutvik110** [comment]
Atm, I made that decision based on how `SuperEditor` and `SuperReader` seems to tackle this issue. They default the text color to black right now. 

If we've to adjust this to brightness, then I think we should apply this change across `SuperEditor` and `SuperReader` as well. These changes then are probably better handled in a separate PR.  Wdyt?

**Comment by matthew-carroll** [comment]
Closing in favor of #1663
