### ISSUE TITLE
[SuperEditorMarkdown] Index out of range

### ISSUE THREAD

**Issue by jeprojects** [superlistapp/super_editor#1640]
I am getting the following error when using this function `serializeDocumentToMarkdown` in a certain scenario.

```
Error: RangeError (index): Index out of range: no indices are valid: 0
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3     throw_
dart-sdk/lib/_internal/js_dev_runtime/private/js_string.dart 478:7              _get]
packages/super_editor_markdown/src/document_to_markdown_serializer.dart 264:33  visitAttributions
packages/attributed_text/src/attributed_text.dart 404:14                        visitAttributions
```

**To reproduce:**

1. In a blank document, click Enter one or two times (leaving two blank lines)
2. Select all of the document
3. Enable bold, strikethrough or italics
4. serializeDocumentToMarkdown the doc

The function I am using to enable bold, strikethrough or italics is:

```
  void _toggleAttributions(Set<Attribution> attributions) {
    final selection = composer.selection;
    if (selection == null) {
      return;
    }

    selection.isCollapsed
        ? _commonEditorOperations.toggleComposerAttributions(attributions)
        : _commonEditorOperations.toggleAttributionsOnSelection(attributions);
  }
```

Here is out output of the document nodes when it fails:

```
[[TextNode] - text: [AttributedText] - ""
[AttributedSpans] (1 spans):
 - [SpanMarker] - attribution: [NamedAttribution]: bold, offset: 0, type: SpanMarkerType.start
 - [SpanMarker] - attribution: [NamedAttribution]: bold, offset: 0, type: SpanMarkerType.end, metadata: {blockType: [NamedAttribution]: paragraph}, [TextNode] - text: [AttributedText] - ""
[AttributedSpans] (0 spans):, metadata: {blockType: [NamedAttribution]: paragraph}]
```

**Comment by rutvik110** [comment]
Hey @jeprojects thanx for filing the issue. Could you also please share a complete reproducible example for this issue for me to test things out?

**Comment by angelosilvestre** [comment]
@matthew-carroll When exporting empty a document containing two empty paragraphs with bold attribution, should the result markdown be like the following?

```
****

****
```

**Comment by matthew-carroll** [comment]
@angelosilvestre I have no idea. I would suggest trying a few other Markdown editors to see how they handle it.
