### ISSUE TITLE
[Web/Windows] [SuperEditor] First character in paragraph is duplicated when using Japanese keyboard layout

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1642]
Setup:
* Windows 11
Browser: Chrome 119.0.6045.200
Keyboard: Japanese

Steps to reproduce:
* Run the demo app on a browser
* In a SuperEditor demo, add a new paragraph
* Place the caret in the empty paragraph and type "k"

Expected: "の"
Actual: ”のの”

Notes:
* Could not reproduce this issue when running on macOS native
* Could not reproduce this issue on macOS, but found a different one (filled a separate ticket)
* Could not reproduce this issue with SuperTextField

**Comment by angelosilvestre** [comment]
This looks like a Flutter web issue. When we send our editing value to the IME, we receive an insertion delta again. I filed https://github.com/flutter/flutter/issues/139603

**Comment by miguelcmedeiros** [comment]
@angelosilvestre since I couldn't reproduce this issue with SuperTextField, did we manage to workaround this flutter issue for SuperTextField? If so, can we apply the same for SuperEditor?

**Comment by matthew-carroll** [comment]
@angelosilvestre this issue might only be happening at the beginning of a paragraph. If that's the case then the problem might be with the hidden ". " at the beginning of each paragraph.

**Comment by angelosilvestre** [comment]
@matthew-carroll Yes, it looks related to the hidden characters. The issue seems to only happen when we send the value back to the IME. I'll dig deeper to see if I missed something.

**Comment by angelosilvestre** [comment]
@matthew-carroll Here's what's happening:

1. The user selects an empty paragraph and we send ". " to the IME as the editing value.
2. When the user types "k", the IME inserts the character and the editing value is ". k"
3. SuperEditor changes the editing value to "k" and sends it back to the IME
4. The IME seems to be confused and send another insertion delta

Currently, we prepend the invisible characters when the selection is collapsed and sits at the beginning of a node. A possible workaround could be to always prepend the placeholder (`DocumentImeSerializer` has an option to do that). That way, SuperEditor editing value would be equal to the IME editing value.
