### ISSUE TITLE
[feature-request][SuperTextField] Have SuperTextField expose popover builders

### ISSUE THREAD

**Issue by jellynoone** [superlistapp/super_editor#1645]
Could the `SuperTextField` be made to expose the popover builders for the ios text field and android text fields?

The main reason for me here is to provide a custom unified toolbar for both platforms.

In addition, the default toolbar builders hardcode the action labels which means that if an individual is to build a localized version of the toolbars, they need to build it and provide it themselves. (Although, this is a separate issue which providing individual builders simultaneously addresses.)

Similarly since the `SuperEditor` exposes similar builders I think a consumer would expect the `SuperTextField` to do the same.

Thank you for the great work on super_editor,... and the entire toolkit.

**Comment by matthew-carroll** [comment]
I found these existing issues, which I believe cover the same goal:

https://github.com/superlistapp/super_editor/issues/1572
https://github.com/superlistapp/super_editor/issues/1571

I'm going to close this ticket in favor of those.

**Comment by jellynoone** [comment]
> Yeah, we'll probably make the same change to `SuperTextField` that we did to `SuperEditor` where you'll be able to configure and control the overlay details through widget compositions.

Awesome to hear. Apologies for not seeing those issues.
