### ISSUE TITLE
Not-scrollable document reader widget

### ISSUE THREAD

**Issue by aloisdeniel** [superlistapp/super_editor#1677]
**User Behavior**

We would like to use the same rendering logic to display multiple rich content on the screen. This means that we would have multiple `SuperReader` in a `ListView`, but each one of these readers would shrink-wrap and wouldn't require scrolling support.

**Feature Value**

We need it to display the content of multiple comments in a thread on a single screen. The content of a comment can be edited with a SuperEditor.

**Additional context**

<img width="565" alt="image" src="https://github.com/superlistapp/super_editor/assets/7687231/2ef5c117-e3d2-4d59-baea-d08855e48da8">

**Comment by matthew-carroll** [comment]
`SuperEditor` (and I think `SuperReader`) should already defer to an ancestor `Scrollable`. You can see this in the Example app under the Slivers example.

**Comment by matthew-carroll** [comment]
@aloisdeniel please let me know if there's anything in your use-case that isn't covered by examples in the Example app.

**Comment by matthew-carroll** [comment]
I'm going to close this due to non-response. Please open a new issue with clarifications if the problem continues.
