### ISSUE TITLE
[SuperEditor][SuperTextField][Android] Underline highlight remains after moving selection elsewhere

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1689]
**Package Version**
Using https://github.com/superlistapp/super_editor/commit/0a58e704469ccaffe5ab14620a56afe75bee6574 in main.

**To Reproduce**
1. Go to SuperEditor or SuperTextField demos
2. Tap on the text to place the selection
3. Tap elsewhere in the content to move the selection

**Actual behavior**
Caret and handle move to the new selection, but the composing region underline highlight remain in the previous place

**Expected behavior**
Caret, handles and composing region underline highlight are painted in the selection position.

**Platform**
Android.

**Flutter version**
Flutter master commit e278279a48f0479386c249cf18f26b29c6f9018f.

**Screenshots**

[Screen_recording_20231214_161411.webm](https://github.com/superlistapp/super_editor/assets/31278849/995d288f-36f5-4d0d-adff-1ac9dc24de05)

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by matthew-carroll** [comment]
@miguelcmedeiros that's the composing region. Apparently, Android places a composing region around whatever word has the caret.

It does look like a bug that the composing region doesn't leave when you change nodes, but the underline is going to follow you around if we underline the composing region. 

Please advise.

**Comment by miguelcmedeiros** [comment]
@matthew-carroll I'm not an Android user and while testing the upgrade in Superlist, I thought that showing the underline highlight when the selection is collapsed was a bug. 

The fact that composing region is not cleared when selection changes, seems like a duplicate of https://github.com/superlistapp/super_editor/issues/1685. To make sure we check both cases, leave this one open and update the title and description.

**Comment by matthew-carroll** [comment]
@miguelcmedeiros I don't think typical Android apps show the underline as aggressively as we do now. But I'm not sure what the operative difference might be. We're blindly underlining the composing region. I'm not sure if built-in Android text views have some additional heuristic on top.

**Comment by miguelcmedeiros** [comment]
> I don't think typical Android apps show the underline as aggressively as we do now.

I tested this using an emulator (not sure if it matters) and tried on Google Keep and another notepad app and both showed the underline like super_editor is now showing. Not sure if there's some setting for this or not.

**Comment by matthew-carroll** [comment]
Ok, if other mainstream apps do it, then I think we're fine. But we can leave this open until the related issue is resolved.

**Comment by angelosilvestre** [comment]
I think this will probably be fixed by https://github.com/superlistapp/super_editor/pull/1693

**Comment by miguelcmedeiros** [comment]
@angelosilvestre this issue is fixed in some cases, but when the user taps outside a text field and the field is unfocused, then the underline remains:

https://github.com/superlistapp/super_editor/assets/31278849/ed204ea7-16fa-4f0b-bf1b-035f303a4c22

This was captured without making any changes to the demo code.

**Comment by angelosilvestre** [comment]
@miguelcmedeiros Thanks for letting me know. I'll take a look at this situation.
