### ISSUE TITLE
[SuperEditor] [Android] Editor loses focus when dragging selection handles when using TapRegion to unfocus the editor when tapped outside

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1692]
**Package Version**
Using 0a58e704469ccaffe5ab14620a56afe75bee6574 in `main`.

**To Reproduce**
The pre-condition is to have a `TapRegion` above `SuperEditor` that unfocuses the editor when tapped outside. See the code snippet below.

1. Go to the altered SuperEditor demo
2. Double-tap on a word
3. Drag one of the selection handles to extend the seleciton

**Minimal Reproduction Code**

In `example_editor.dart`, wrap `SuperEditor` with `TapRegion`:

<details>
  <summary>Minimal, Runnable Code Sample</summary>

  ```dart
  TapRegion(
    onTapOutside: (_) {
      _editorFocusNode.unfocus();
    },
    child: SuperEditor(...),
  ),
  ```
</details>

**Actual behavior**
Document loses focus.

**Expected behavior**
Selection changes as the handle is dragged.

**Platform**
Android.

**Flutter version**
Flutter `master` commit e278279a48f0479386c249cf18f26b29c6f9018f.

**Screenshots**

https://github.com/superlistapp/super_editor/assets/31278849/6459944d-251a-48cf-8697-87b02720ec32

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by matthew-carroll** [comment]
FYI @miguelcmedeiros @angelosilvestre this issue that I filed with Flutter might be relevant to this bug: https://github.com/flutter/flutter/issues/138190
