### ISSUE TITLE
[SuperTextField][Android][iOS] - Caret blinks during a drag

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#1705]
As of the time that this ticket is filed, `SuperTextField` on Android and iOS continue to blink the caret even as the caret is in the middle of a drag.

The problem can be seen in the video in this other ticket: https://github.com/superlistapp/super_editor/issues/1704

We should check standard Android and iOS behavior, but I don't think the caret is supposed to blink while it's being dragged.

**Comment by rutvik110** [comment]
> We should check standard Android and iOS behavior, but I don't think the caret is supposed to blink while it's being dragged.

That seems to be the right behaviour for both android and ios. Caret shouldn't blink when dragging but only after dragging is stoped or user's no longer interacting with the text in any manner.
