### ISSUE TITLE
[SuperEditor] [Android] Drag handle is painted at the top-left corner of the editor when selection is collapsed by dragging an handle

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1736]
**Package Version**
`main` branch with commit hash 5304a3c2294dfa7ae2742539a5e9f2d3e05a3d16.

**To Reproduce**
1. Go to SuperEditor demo
2. Double tap on a word to get an expanded selection
3. Drag the left-handle till the offset of the right handle => selection is collapsed

**Actual behavior**
The Android selection handle is painted on the top-left corner of the editor.

**Expected behavior**
The Android selection handle is painted below the caret.

**Platform**
Android.

**Flutter version**
Flutter master commit e278279a48f0479386c249cf18f26b29c6f9018f.

**Screenshots**

https://github.com/superlistapp/super_editor/assets/31278849/69bf3eab-b2ef-41e5-8b89-ccff68a141c9

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll @angelosilvestre

**Comment by angelosilvestre** [comment]
@matthew-carroll @miguelcmedeiros I tried some Android apps and most seem to prevent the user from collapsing the selection using the expanded handles. The selection is changed only if it will result in another expanded selection:

https://github.com/superlistapp/super_editor/assets/7597082/cb5afad0-4504-49f1-8c01-cf7c7e449c18

Is this what we need?

**Comment by matthew-carroll** [comment]
@angelosilvestre I think you're identifying a slightly different user interaction, but Miguel reported a bug. Can we fix the bug without currently altering the UX? We can look into UX later.
