### ISSUE TITLE
[SuperTextField] Filter out unknown key

### ISSUE THREAD

**Issue by venkatd** [superlistapp/super_editor#174]
@matthew-carroll 

We have a user with an international keyboard. When he hits a shortcut, he has the following key show up:

```RawKeyDownEvent#5fcf8(logicalKey: LogicalKeyboardKey#5676a(keyId: "0x1b55676a", keyLabel: "", debugName: "Unknown Web code "Unidentified""), physicalKey: PhysicalKeyboardKey#00000(usbHidUsage: "0x00000000", debugName: "None"))```

We may want to add this to the blacklist too.

Related issue here:
https://github.com/flutter/flutter/issues/72275

**Comment by matthew-carroll** [comment]
@venkatd should this issue be closed in favor of #193?

**Comment by venkatd** [comment]
@matthew-carroll yes. Our solution in #193 has resolved this issue.
