### ISSUE TITLE
[SuperTextField][Dsktop] Text field does not automatically scroll as soon the caret when it leaves the viewport

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1762]
**Package Version**
Which package and version are you using? E.g., "super_editor, GitHub, stable branch"

**To Reproduce**
1. On macOS, go to SuperTextfield demo and open the "Single-line demo"
2. Wait for all the content to be typed by the "demo robot"

**Actual behavior**
Text field does not automatically scroll as soon the caret when it leaves the viewport.

**Expected behavior**
Text field automatically scrolls when typing a character and the caret is not in view port anymore.

**Platform**
All.

**Flutter version**
Flutter master commit e278279a48f0479386c249cf18f26b29c6f9018f.

**Screenshots**

https://github.com/superlistapp/super_editor/assets/31278849/2a219088-fc4b-4673-b63f-a23c9e55ec54

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll @angelosilvestre

**Comment by miguelcmedeiros** [comment]
@matthew-carroll on iOS (potentially also on Android as well, but I didn't test yet) this issue still happens.

As soon as the single-line text field has a padding defined and the user types at the end of the viewport, part of the new content will be hidden (how much depends on the padding).

**Comment by matthew-carroll** [comment]
@miguelcmedeiros it looks like the issues on mobile single-line text fields are different than the desktop issue demonstrated in this original ticket. I'm going to close this issue in favor of: https://github.com/superlistapp/super_editor/issues/1776
