### ISSUE TITLE
Pressing "Cmd + B"  or "Cmd + I" crashes the editor

### ISSUE THREAD

**Issue by roughike** [superlistapp/super_editor#177]
I noticed the Flutter grey box of death in release mode when trying to toggle bold and italics in the editor.

It seems that in #167, when migrating to the `Attribution` classes, the `document_keyboard_actions.dart` file was not updated to use `boldAttribution` in favor of `'bold'` and `italicsAttribution` in favor of `'italics'`.

I [fixed it for myself here](https://github.com/superlistapp/super_editor/commit/ea14ad447f9f7379f701a6424ee49d943e129305) on a separate branch as I don't have the time to make a PR with proper tests right now.

I guess we'll want to fix this before merging the marketing website to main, with proper tests?

**Comment by matthew-carroll** [comment]
I've verified the bug. It specifically happens when using the shortcuts to toggle the text entry mode, as opposed to toggling styles for a selection span.
