### ISSUE TITLE
[SuperEditor] Can't type a space character on web when SuperEditor is the child of a SingleChildScrollView

### ISSUE THREAD

**Issue by michaelnew** [superlistapp/super_editor#1784]
**Package Version**
super_editor, git main branch, `304e778`

**To Reproduce**
Wrap the SuperEditor in a SingleChildScrollView in demo_empty_document (see below), run in chrome and attempt to type spaces into the editor.

**Minimal Reproduction Code**
  ```dart
--- a/super_editor/example/lib/demos/demo_empty_document.dart
+++ b/super_editor/example/lib/demos/demo_empty_document.dart
@@ -35,13 +35,13 @@ class _EmptyDocumentDemoState extends State<EmptyDocumentDemo> {
   @override
   Widget build(BuildContext context) {
     return SafeArea(
-      child: SuperEditor(
+      child: SingleChildScrollView(child: SuperEditor(
         editor: _docEditor,
         document: _doc,
         composer: _composer,
         gestureMode: DocumentGestureMode.mouse,
       ),
-    );
+    ));
   }
 }
  ```

**Actual behavior**
Normal characters appear fine as you type, but hitting spacebar results in nothing happening. Itlookslikethis.

**Platform**
Chrome and Firefox both have this issue. Works fine in Android and as a desktop Linux app. Haven't tested other platforms.

**Flutter version**
Flutter 3.19.0-4.0.pre.36 • channel master

**Additional context**
This looks similar to [this issue](https://github.com/superlistapp/super_editor/issues/1446) and [this corresponding PR](https://github.com/superlistapp/super_editor/pull/1455). Could be an edge case that wasn't handled, or just a regression.

It seems like other odd things are happening around this, but I haven't really nailed them down. I can't seem to brink up the developer tools with ctl-shift-i when the editor is focused, for example.

**Comment by manoletre** [comment]
I just had this same issue. But to me it only happens in Windows PCs in flutter Web. In MacOS it works fine. My theory is that it has something to do with the default Windows behaviour of scrolling down when pressing space.
