### ISSUE TITLE
ScrollBar usage

### ISSUE THREAD

**Issue by ismailgzn** [superlistapp/super_editor#1786]
Hello,

I've integrated the super_editor package into my project using its latest stable version from GitHub. However, I'm encountering an issue with the default scrollbar. When the editor is used in landscape orientation mode, this scrollbar appears with its own padding. I've been trying to customize or even disable this default scrollbar, but without success.

Could you provide guidance on how to either customize or completely disable the default scrollbar in super_editor, especially in landscape orientation? What are your thoughts or suggestions on this matter?

Thank you.
![IMG_0448](https://github.com/superlistapp/super_editor/assets/84643105/8953c7a5-050e-47ce-969b-4968f42e7bb9)

**Comment by angelosilvestre** [comment]
@matthew-carroll We could change the editor to look for an ancestor `ScrollConfiguration`. Users would be able to wrap the editor with a `ScrollConfiguration` set to don't display the scrollbars, then we wouldn't install our own `Scrollbar` if that's the case.

**Comment by angelosilvestre** [comment]
@matthew-carroll I'm surprised to find out that we can't query this information.

`ScrollBehavior` itself doesn't have a `scrollbars` property.  When we call `copyWith(scrollbars: false)` it returns a `_WrappedScrollBehavior`, which is the class that holds the `scrollbars` property.

The only thing we could do is an ugly hack:

```dart
final scrollBehavior = ScrollConfiguration.of(context);

final maybeScrollBar = scrollBehavior.buildScrollbar(
  context,
  child,
  ScrollableDetails.vertical(controller: _scrollController),
);
if (maybeScrollBar is! Scrollbar) {
  // The scroll behavior is configured to NOT show scrollbars.
  return child;
}

// wrap with ScrollbarWithCustomPhysics
```

I wish there is another way...

**Comment by matthew-carroll** [comment]
If that's the case, then go ahead and implement the hack, make sure it's commented appropriately, then file an issue with Flutter explaining the motivation and issue, and reference that issue number in our Super Editor comments.

**Comment by angelosilvestre** [comment]
Filed https://github.com/flutter/flutter/issues/141508

**Comment by ismailgzn** [comment]
Thank you very much for effective resolution. I’m grateful for your support. @angelosilvestre and @matthew-carroll
