### ISSUE TITLE
[SuperTextField][mobile] Multi-line textfield doesn't allow drag to scroll vertically

### ISSUE THREAD

**Issue by angelosilvestre** [superlistapp/super_editor#1795]
**Package Version**
super_editor - main

**To Reproduce**
1. Open Example app with iOS or Android SuperTextField example
2. Run the short demo
3. Drag to scroll vertically

**Actual behavior**
The content doesn't scroll

**Expected behavior**
The content should scroll, like Flutter `TextField`

**Platform**
iOS and Android

**Flutter version**
3.17.0-19.0.pre.16 • channel master •

**Screenshots**

Flutter `TextField`:

[scroll_android.webm](https://github.com/superlistapp/super_editor/assets/7597082/4a144478-cd03-4955-b8b4-3dae110b2faf)

`SuperTextField`:

[supertextfield_scroll.webm](https://github.com/superlistapp/super_editor/assets/7597082/55ad2cc8-2a0d-43eb-b846-56194987c7fe)

**Comment by angelosilvestre** [comment]
Cc @matthew-carroll

**Comment by matthew-carroll** [comment]
I think this is now being worked on here: https://github.com/superlistapp/super_editor/pull/2139
