### ISSUE TITLE
[SuperEditor] [Android] Magnifier position is broken when Editor in a CustomScrollView 

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1810]
**Package Version**
`main` branch with commit hash https://github.com/superlistapp/super_editor/commit/2cb93e23ba2442e911c1bfcaf107c247adc6d131

**To Reproduce**
1. Go to Sliver Editor demo
2. Scroll down a bit
3. Place the selection in the content
4. Start dragging the drag handle upwards

**Actual behavior**
Initially the magnifier is not visible and as the drag handle is moved towards the top of the editor, then we see the magnifier coming from the bottom and getting closer to the selection.

**Expected behavior**
The magnifier is visible above the selection.

**Platform**
Android.

**Flutter version**
Flutter master commit e278279a48f0479386c249cf18f26b29c6f9018f.

**Screenshots**

https://github.com/superlistapp/super_editor/assets/31278849/bba51f3a-6ca4-4f2a-b29c-91c31e6f00e1

**Comment by BazinC** [comment]
Hey super editor team, Is it possible to kill 2 birds with one stone, fixing the ios magnifier position? :)
https://github.com/superlistapp/super_editor/issues/1496
![image](https://github.com/superlistapp/super_editor/assets/6229343/216712c6-57b1-43e9-a1cb-3c16528088d0)

**Comment by matthew-carroll** [comment]
@BazinC this work is already done. Can you please file a new ticket? Btw, we'll need more than just a screenshot. Please show where the magnifier should appear vs where it actually appears. You might want to place an iOS screeshot next to a `SuperEditor` screenshot for comparison.
