### ISSUE TITLE
[web] [bug] Pressing option keys (Control, Options or CMD) removes highlighted text

### ISSUE THREAD

**Issue by bk-one** [superlistapp/super_editor#182]
Steps to reproduce (MacOS, latest Chrome):
1. Start the sample editor for web
2. Mark any word or sequence of characters
3. Press the CMD button (or control, option, or even caps lock. Shift is fine, though)
4. The marked word is removed, behaves like if I pressed backspace

It works fine on MacOS, so this only applied to web.

**Comment by Jethro87** [comment]
Also getting this issue. As such any attempted keyboard formatting operation (bold, italicize, etc), removes the selected text.

**Comment by matthew-carroll** [comment]
@bk-one @Jethro87 are you still seeing this behavior with v0.1.0?

**Comment by bk-one** [comment]
Yes, at least on https://superlist.com/SuperEditor/ - where I believe it is the latest version.
