### ISSUE TITLE
When parsing an empty sublist, `deserializeMarkdownToDocument` makes everything crash (probably because of an infinite loop)

### ISSUE THREAD

**Issue by manoletre** [superlistapp/super_editor#1822]
**Package Version**
I am on the stable branch. I also just checked to be using the last commit (c69abd)

**To Reproduce**
1. Copy this string:

```
final test_string = """- hey there friend
    - """;
```

2. Run `deserializeMarkdownToDocument(test_string)`
3. Armageddon 💥

**Actual behavior**
The whole flutter app crashes. Probably due to an infinite loop

**Expected behavior**
The string should be parsed as this: (just without the dot on the sub list)

---

- hey there friend
     - .

---

**Platform**
I am on flutter web, on a MacOS. I am using Chrome.

**Flutter version**
```
Flutter 3.16.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2e9cb0aa71 (6 weeks ago) • 2023-12-11 14:35:13 -0700
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4
```

**Additional context**
- #1711 and #1821 might be related

**Comment by angelosilvestre** [comment]
@manoletre I've found the reason of the crash, but this input doesn't look like it generates a sublist. Most of the markdown readers I tried generate a single list item, with a "header 2" style. This also happens with the github comments:

Input:

```
- list item 1
    - 
```

Output:

- list item 1
    -

**Comment by manoletre** [comment]
Yes you are right, most don't generate a sublist. I might have been wrong in expecting the sublist. I guess you can choose here what makes the most sense.

To me the main issue is the crash, how the string is actually parsed matters less. I stream markdown generated from OpenAI and sometimes it crashed. So as long as it does not crash anymore we are good 😁
