### ISSUE TITLE
Typing spanish "tildes" and german "umlaute" causes issues using `SuperEditor` in Web in MacOS

### ISSUE THREAD

**Issue by manoletre** [superlistapp/super_editor#1823]
**Package Version**
I am on the stable branch. I also just checked to be using the last commit (c69abd)

**To Reproduce**
1. Initialize a SuperEditor
2. Using an english keyboard, type a word that uses "tildes" or "umlaute". In MacOS, this is done by pressing `option-u` before a vowel (for "umlaute") or `option-e` for "tildes". 

Similar issues happen with `option-n`, `option-i`, ... (don't know all combinations for typing special characters in an english keyboard - but for example `option-s` for ß works well.

3. The vowel and the symbol appear repated: ´óó

**Actual behavior**
The vowel and the symbol appear repated: ´óó

https://github.com/superlistapp/super_editor/assets/8203735/ee9b889f-add2-4a79-b3ee-888995d5d758

**Expected behavior**
The special character should just be added:

https://github.com/superlistapp/super_editor/assets/8203735/a40ad40c-082f-4f2f-bd3b-505aa00a566a

**Platform**
I am on flutter web, on a MacOS. I am using Chrome.

**Flutter version**
```
Flutter 3.16.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2e9cb0aa71 (6 weeks ago) • 2023-12-11 14:35:13 -0700
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4
```

**Additional context**
I am aware of issue #1382 

But I thought this was different because:
- It is not safari-only. It happened to me on Chrome. And when I test this on safari, I cannot reproduce what #1382 describes.
- The characters that get added in #1382 are different than those that get added here.

**Comment by matthew-carroll** [comment]
@angelosilvestre I assume this is a duplicate of an existing umlaute issue. Can you confirm?

**Comment by angelosilvestre** [comment]
@manoletre I'm not able to reproduce this issue. Are you able to reproduce it on the example app? If not, could you share the `SuperEditor` configuration used to trigger this issue?

**Comment by manoletre** [comment]
Hey sorry for the delay. I just go the time to look into this. You are right, the issue was not with `SuperEditor` but with my configuration. 

I was not using `defaultkeyboardActions` in my `SuperEditor` configuration. Once I started using it again, it started working. 

Maybe something a bit weird to note, which might be interesting:

These were the keyboard actions I was using:

```
[
  toggleInteractionModeWhenCmdOrCtrlPressed,
  doNothingWhenThereIsNoSelection,
  scrollOnPageUpKeyPress,
  scrollOnPageDownKeyPress,
  scrollOnCtrlOrCmdAndHomeKeyPress,
  scrollOnCtrlOrCmdAndEndKeyPress,
  pasteWhenCmdVIsPressed,
  copyWhenCmdCIsPressed,
  cutWhenCmdXIsPressed,
  collapseSelectionWhenEscIsPressed,
  selectAllWhenCmdAIsPressed,
  moveLeftAndRightWithArrowKeys,
  moveUpAndDownWithArrowKeys,
  moveToLineStartWithHome,
  moveToLineEndWithEnd,
  tabToIndentListItem,
  shiftTabToUnIndentListItem,
  backspaceToUnIndentListItem,
  backspaceToConvertTaskToParagraph,
  backspaceToClearParagraphBlockType,
  cmdBToToggleBold,
  cmdIToToggleItalics,
  shiftEnterToInsertNewlineInBlock,
  enterToInsertNewTask,
  moveToLineStartOrEndWithCtrlAOrE,
  deleteToStartOfLineWithCmdBackspaceOnMac,
  deleteWordUpstreamWithAltBackspaceOnMac,
  deleteWordUpstreamWithControlBackspaceOnWindowsAndLinux,
  deleteUpstreamContentWithBackspace,
  deleteToEndOfLineWithCmdDeleteOnMac,
  deleteWordDownstreamWithAltDeleteOnMac,
  deleteWordDownstreamWithControlDeleteOnWindowsAndLinux,
  deleteDownstreamContentWithDelete,
  blockControlKeys,
  anyCharacterOrDestructiveKeyToDeleteSelection,
  anyCharacterToInsertInParagraph,
  anyCharacterToInsertInTextContent,
],
```

Comparing that to the default keyboard actions:
```
[
  toggleInteractionModeWhenCmdOrCtrlPressed,
  doNothingWhenThereIsNoSelection,
  scrollOnPageUpKeyPress,
  scrollOnPageDownKeyPress,
  scrollOnCtrlOrCmdAndHomeKeyPress,
  scrollOnCtrlOrCmdAndEndKeyPress,
  pasteWhenCmdVIsPressed,
  copyWhenCmdCIsPressed,
  cutWhenCmdXIsPressed,
  collapseSelectionWhenEscIsPressed,
  selectAllWhenCmdAIsPressed,
  moveLeftAndRightWithArrowKeys,
  moveUpAndDownWithArrowKeys,
  moveToLineStartWithHome,
  moveToLineEndWithEnd,
  tabToIndentListItem,
  shiftTabToUnIndentListItem,
  backspaceToUnIndentListItem,
  backspaceToConvertTaskToParagraph,
  backspaceToClearParagraphBlockType,
  cmdBToToggleBold,
  cmdIToToggleItalics,
  shiftEnterToInsertNewlineInBlock,
  enterToInsertNewTask,
  enterToInsertBlockNewline,
  moveToLineStartOrEndWithCtrlAOrE,
  deleteToStartOfLineWithCmdBackspaceOnMac,
  deleteWordUpstreamWithAltBackspaceOnMac,
  deleteWordUpstreamWithControlBackspaceOnWindowsAndLinux,
  deleteUpstreamContentWithBackspace,
  deleteToEndOfLineWithCmdDeleteOnMac,
  deleteWordDownstreamWithAltDeleteOnMac,
  deleteWordDownstreamWithControlDeleteOnWindowsAndLinux,
  deleteDownstreamContentWithDelete,
  blockControlKeys,
  anyCharacterOrDestructiveKeyToDeleteSelection,
  anyCharacterToInsertInParagraph,
  anyCharacterToInsertInTextContent,
]
```

The only action I was missing was this: `enterToInsertBlockNewline`. Adding it fixed the issue for me. 

Just leaving that here for the sake of documentation.

Thanks for having taken a look into this! 

Cheers!
Manu
