### ISSUE TITLE
Hello World fail to compile

### ISSUE THREAD

**Issue by JannieT** [superlistapp/super_editor#1824]
I realise there has been API changes with both the latest stable Flutter and with the latest Super Editor, but it I can't figure out any combination of versions that will compile.

**Package Version**
GitHub main branch

**To Reproduce**
1. Clone the repo: https://github.com/JannieT/super-editor-sample
2. Get vendor packages: `flutter pub get`
3. Run the app: `flutter run`

**Minimal Reproduction Code**
https://github.com/JannieT/super-editor-sample

**Actual behavior**
Building for either iOS or Android gives compile errors like this:
> Failed to build iOS app
> Error (Xcode): ../../.pub-cache/git/super_editor-091b17b20f8c80dcc5e387b166382597ef96131f/super_editor/lib/src/default_editor/text.dart:70:69: Error: The getter 'length' isn't defined for the class 'AttributedText'

Error: The getter 'isAltPressed' isn't defined for the class 'HardwareKeyboard'.
Error: The getter 'isShiftPressed' isn't defined for the class 'HardwareKeyboard'.
Error: The getter 'isControlPressed' isn't defined for the class 'HardwareKeyboard'
Error: Too many positional arguments: 0 allowed, but 2 found.
Error: The method 'substring' isn't defined for the class 'AttributedText'

**Expected behavior**
The app will compile and run and show "Hello World" on launch.

**Platform**
Build machine: MacBook Pro with macOS Sonoma 14.2.1
Build Targets: 
- Android 13 (API 33) (emulator)
-  com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)

**Flutter version**
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.2.1 23C71 darwin-arm64, locale en-ZA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.85.2)
[✓] Connected device (3 available)
[✓] Network resources

**Additional context**
I also tried various other tags in the repo, without success:
```yml
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor
      ref: super_editor_v0.2.6-dev.1
```

**Comment by JannieT** [comment]
I realise there has been API changes with both the latest stable Flutter and with the latest Super Editor, but it I can't figure out any combination of versions that will compile.

**Comment by angelosilvestre** [comment]
@JannieT Please try overriding the dependencies as explained here: https://github.com/superlistapp/super_editor?tab=readme-ov-file#mono-repo-versioning

**Comment by JannieT** [comment]
🤦 of course.
Thanks a lot sir.
