### ISSUE TITLE
[iOS] Korean characters are not composed

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1825]
**Package Version**
`main` branch with commit hash https://github.com/superlistapp/super_editor/commit/2cb93e23ba2442e911c1bfcaf107c247adc6d131

**To Reproduce**
1. Go to a SuperEditor or SuperTextField demo
2. Type "ㅅㅛ"

**Actual behavior**
The result is both characters.

**Expected behavior**
Those 2 characters should be replaced by "쇼".

**Platform**
iOS.

**Flutter version**
Flutter master commit e278279a48f0479386c249cf18f26b29c6f9018f.

**Screenshots**

https://github.com/superlistapp/super_editor/assets/31278849/e6959a4f-653d-4d31-9814-8b60a0d9229f

As an example, on Android:

https://github.com/superlistapp/super_editor/assets/31278849/9f1beeed-a8aa-4555-8f51-23a2ef081418

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll @angelosilvestre

**Comment by angelosilvestre** [comment]
@miguelcmedeiros Is there any configuration needed to enable the Korean composition?  I added the Korean keyboard but it doesn't seem to compose even on safari:

https://github.com/superlistapp/super_editor/assets/7597082/d5733d19-9bfb-46e2-b98f-6047d34a3170

**Comment by miguelcmedeiros** [comment]
Interesting. I just tested on a real device and there it seems to work. It's only reproducible on an iOS simulator.
