### ISSUE TITLE
[iOS/Android] Content inserted at end of the line above when typing Korean

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1826]
**Package Version**
`main` branch with commit hash https://github.com/superlistapp/super_editor/commit/2cb93e23ba2442e911c1bfcaf107c247adc6d131

**To Reproduce**
1. Go to the iOS/Android SuperTextField demo or SuperEditor demo
2. Place the selection of a line (but not the first line of the content)
3. Type something in Korean

**Actual behavior**
Characters are inserted at the end of the line above and caret remains in the same position.

**Expected behavior**
For each character added, it is inserted where the selection is and then move the caret by 1.

**Platform**
iOS and Android

**Flutter version**
Flutter master commit e278279a48f0479386c249cf18f26b29c6f9018f.

**Screenshots**

https://github.com/superlistapp/super_editor/assets/31278849/50ea1004-1c40-4d84-b37f-defe4276c51b

**Comment by angelosilvestre** [comment]
@miguelcmedeiros This doesn't look like an issue. The text is being inserted at the correct offset and pushing the selection by 1. What seems to be happening is that there is room to render the newly inserted character in the previous line.

https://github.com/superlistapp/super_editor/assets/7597082/3bfc946e-1f45-4244-97c9-f46c627c58e2

https://github.com/superlistapp/super_editor/assets/7597082/0397c788-dd85-407b-b284-452e7e450439
