### ISSUE TITLE
[SuperReader] - SuperReader Swipe to pop Gesture not working when wrapped with "DismissiblePage" widget

### ISSUE THREAD

**Issue by abidex4yemi** [superlistapp/super_editor#1832]
**Package Version**
Which package and version are you using?  stable branch

**Discription**
I have encountered a couple of issues with the SuperReader widget, It appears that the SuperReader does not behave as expected when trying to swipe right, especially when wrapped with DismissiblePage. Additionally, when wrapped with GestureDetector, it does not respond to onTap gestures as intended.

Note: I prefer not to wrap the SuperReader with IgnorePointer because it would disable the ability to click on the image within the editor to expand and view it in full.

**To Reproduce**
1. Navigate to the SuperReader widget.
2. Attempt to swipe right within the SuperReader.
3. Wrap the SuperReader with GestureDetector and try to trigger an onTap gesture.

**Minimal Reproduction Code**

**Actual behavior**
- When swiping right within the SuperReader, it scrolls instead of performing the expected behavior.
- Wrapping the SuperReader with GestureDetector does not trigger onTap gestures.

**Expected behavior**
- Swiping right within the SuperReader should navigate or perform a specific action.
- Wrapping the SuperReader with GestureDetector should respond to onTap gestures.

**Additional context**
Thank you for addressing these concerns promptly. Let me know if any further details or clarification is required.

**Comment by matthew-carroll** [comment]
Please include reproducible code. Swiping right doesn't do anything by default, so it sounds like you're implying other widgets that you haven't mentioned.

**Comment by abidex4yemi** [comment]
```import 'package:flutter/material.dart';
import 'package:super_editor/super_editor.dart';
import 'package:dismissible_page/dismissible_page.dart';

class NotePage extends StatefulWidget {
  @override
  _NotePageState createState() => _NotePageState();
}

class _NotePageState extends State<NotePage> {
  late final Document _document;
  final _selection = ValueNotifier<DocumentSelection?>(null);
  final _selectionLayerLinks = SelectionLayerLinks();

  @override
  void initState() {
    _document = deserializeMarkdownToDocument('This is a sample note body');
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Note Page'),
      ),
      body: Center(
        child: SizedBox(
          height: 400,
          child: GestureDetector(
            onTap: () {
              Navigator.pushNamed(context, '/fullpageroute');
            },
            child: SuperReader(
              document: _document,
              selection: _selection,
              selectionLayerLinks: _selectionLayerLinks,
              documentOverlayBuilders: [],
              selectionStyle: SelectionStyles(
                selectionColor: Colors.transparent,
              ),
              componentBuilders: [
                ...defaultComponentBuilders,
              ],
              androidToolbarBuilder: (_) => AndroidTextEditingFloatingToolbar(
                onCopyPressed: null,
                onSelectAllPressed: null,
              ),
            ),
          ),
        ),
      ),
    );
  }
}

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'My App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => Scaffold(
              body: GestureDetector(
                onTap: () {
                  Navigator.pushNamed(context, '/fullpageroute');
                },
                child: Container(
                  height: 400,
                  color: Colors.grey.withOpacity(0.2),
                  child: Center(
                    child: Text(
                      'Tap to open full page',
                      style: TextStyle(fontSize: 20),
                    ),
                  ),
                ),
              ),
            ),
        '/fullpageroute': (context) => NotePage(),
      },
    );
  }
}

@matthew-carroll here's the snippet as requested, thanks.

**Comment by abidex4yemi** [comment]
@matthew-carroll here's the snippet as requested, thanks.

**Comment by matthew-carroll** [comment]
@abidex4yemi your sample code is not runnable by itself. You need to include the code necessary for us to run an app and reproduce the issue. That reproduction code cannot include external packages (your above includes an external package).

**Comment by abidex4yemi** [comment]
@matthew-carroll I apologize for the delayed response. I have investigated the code and identified that the bug I encountered was caused by using the IgnorePointer widget. Upon removing the IgnorePointer, I could swipe right on the superReader as intended. Please take a look at the screenshot below for confirmation.

**Comment by abidex4yemi** [comment]
I'm closing this as I was able to figure out a workaround. Thanks!

**Comment by abidex4yemi** [comment]
> @matthew-carroll I apologize for the delayed response. I have investigated the code and identified that the bug I encountered was caused by using the IgnorePointer widget. Upon removing the IgnorePointer, I could swipe right on the superReader as intended. Please take a look at the screenshot below for confirmation.
> 
> <img alt="Screenshot 2024-02-29 at 10 15 12 PM" width="797" src="https://private-user-images.githubusercontent.com/23571838/309080048-8a43492c-8229-4a46-af46-f1b99523771a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTIwOTksIm5iZiI6MTcxMzc5MTc5OSwicGF0aCI6Ii8yMzU3MTgzOC8zMDkwODAwNDgtOGE0MzQ5MmMtODIyOS00YTQ2LWFmNDYtZjFiOTk1MjM3NzFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDEzMTYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmMjVkY2I2MTY1YTM1N2E4OGQ0ZmJiOTVmNzIzNDA0NzA1YjE0ODRiNGViYjgyNzk4OWUxZTdiNTBkMjg5YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VpqL2ZaXFJIz9FKgbESJ14Fq515EGgHKhNl_757pRWs">

After removing the IgnorePointer, I find it hard to click on URLs, and sometimes I have to double-tap on URLs multiple times before they open correctly.

**Comment by abidex4yemi** [comment]
@rutvik110  @angelosilvestre any idea?

**Comment by matthew-carroll** [comment]
@abidex4yemi please provide a minimal reproducible sample, as requested twice before.

**Comment by matthew-carroll** [comment]
We still haven't received a usable reproduction sample so I'm going to close this.
