### ISSUE TITLE
[SuperReader] - Serializer Not Recognizing Bold or Italics Formatting on Trailing Space.

### ISSUE THREAD

**Issue by abidex4yemi** [superlistapp/super_editor#1833]
**Package Version**
Which package and version are you using?  stable branch.

**Description:**
I'm experiencing a bug in the SuperReader widget related to the serializer when attempting to apply bold or italics formatting to a trailing space that follows the end of a sentence. Specifically, when I type "Jake is a boy" and try to highlight the space after "boy" (i.e., the trailing space with no character after it) and apply bold or italics formatting, the serializer does not recognize the formatting as expected.

**Steps to Reproduce:**

1. Open the SuperEditor.
2. Create a sentence, e.g., "Jake is a boy."
3. Highlight the space after "boy" (i.e., the trailing space with no character after it).
4. Attempt to apply bold or italics formatting to the selected sentence with trailing space.
5. Verify the formatting status in SuperReader.

**Expected Behavior:**
The bold or italics formatting should be successfully applied to the trailing space after the sentence, displaying the expected formatting in Read mode using SuperReader.

**Actual Behavior:**
When applying bold or italics formatting to the space after the sentence, the serializer may not recognize the formatting correctly, leading to unexpected behavior or no formatting applied.

**Comment by matthew-carroll** [comment]
@abidex4yemi your reproduction steps doesn't include any code or specific instructions. What do you mean "Open the SuperEditor"? What do you mean "Attempt to apply bold or italics"? What do you mean "Verify the formatting status in SuperReader"?

**Comment by matthew-carroll** [comment]
@abidex4yemi any update? Can you please address my comment above?

**Comment by abidex4yemi** [comment]
I have successfully resolved this issue, and we can proceed to close it.
