### ISSUE TITLE
[SuperTextEditor] vertical alignment of list items incorrect when settings line height

### ISSUE THREAD

**Issue by quaaantumdev** [superlistapp/super_editor#1834]
**Package Version**
super_editor: git main branch (at the time at 091b17b20f8c80dcc5e387b166382597ef96131f)

**To Reproduce**
Display a list of items, use the stylesheet to set all nodes to a custom line height. Check the display output, the item indicators will not align with the content of the list item.

**Minimal Reproduction Code**
If the bug is reproducible in the Example app, you can delete this section. Otherwise, please provide a minimal, runnable code reproduction.

<details>
  <summary>Stylesheet</summary>

  ```dart
  Stylesheet(
    rules: <StyleRule>[
      StyleRule(
        BlockSelector.all,
        (doc, docNode) {
          return {
            "textStyle": TextStyle(
              height: 3.0, // <- extreme case to show the issue, but even setting it to 1.25 is already enough
              //leadingDistribution: TextLeadingDistribution.proportional, // <- setting this fixes it for the ordered list item but not for the unordered item
            ),
          };
        },
      ),
  ])
  ```
</details>

**Actual behavior**
List numbers and bullets do not align with list item text

**Expected behavior**
List indicators should align with the text in the list item

**Platform**
any

**Flutter version**
Flutter 3.16.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 41456452f2 (11 days ago) • 2024-01-25 10:06:23 -0800
Engine • revision f40e976bed
Tools • Dart 3.2.6 • DevTools 2.28.5

**Screenshots**
![image](https://github.com/superlistapp/super_editor/assets/94001411/60e22af4-db6f-4b11-af1a-b188c45f5854)

**Additional context**
While the alignment is incorrect for both ordered and unordered items, the actual cause seems different. I looked into it a bit and found the following causes:

*The problem for the unordered list item seems to be,* that the Text() Widget in _defaultOrderedListItemNumeralBuilder
https://github.com/superlistapp/super_editor/blob/091b17b20f8c80dcc5e387b166382597ef96131f/super_editor/lib/src/default_editor/list_items.dart#L504
defaults to ```TestStyle(leadingDistribution: TextLeadingDistribution.even)``` while the TextComponent at
https://github.com/superlistapp/super_editor/blob/091b17b20f8c80dcc5e387b166382597ef96131f/super_editor/lib/src/default_editor/list_items.dart#L468
defaults to ```TestStyle(leadingDistribution: TextLeadingDistribution.even)```. Explicitly setting the ```leadingDistribution``` in the stylesheet bypasses the issue, as this value is copied in both places.

*The problem for the unordered list item seems to be, that simply centering the dot widget is just not enough. There should be some consideration of the baseline. I guess something with a ```Baseline``` or ````RichText / WidgetSpan``` would do the trick.
https://github.com/superlistapp/super_editor/blob/091b17b20f8c80dcc5e387b166382597ef96131f/super_editor/lib/src/default_editor/list_items.dart#L374

And here is a fix for the unordered list item (my version, maybe ugly but effective): https://github.com/quaaantumdev/super_editor/commit/e55111d97432aa4cbf91e4072dd0a8ef04a1aa82

**Comment by angelosilvestre** [comment]
Hi @alterhuman. I haven't been able to work on this yet, but I expect to work on it in a couple days.

**Comment by angelosilvestre** [comment]
@alterhuman Could you please set `leadingDistribution: TextLeadingDistribution.even`  in the `TextStyle` and see if it fixes the issue for paragraphs?

**Comment by angelosilvestre** [comment]
@matthew-carroll @alterhuman 

This is what we have now with the default line height multiplier:

![image](https://github.com/superlistapp/super_editor/assets/7597082/1f3a31dc-9cc4-41db-8c9c-d7b28a4613ea)

This is what we have now with a line height multiplier of `6.0` (with `TextLeadingDistribution.even`):

![image](https://github.com/superlistapp/super_editor/assets/7597082/1a9c379d-5f28-4a28-801b-62eb7107e407)

The unordered list item applies a fixed `3.0` pixels margin from the top. If we remove the margin, this is what we get:

![image](https://github.com/superlistapp/super_editor/assets/7597082/32ca8ca7-ac15-4cd6-903e-cafc9dabd6bd)

![image](https://github.com/superlistapp/super_editor/assets/7597082/b138f5f6-dcdc-46ed-98db-dd473df22c3e)

If we place the dot inside a `WidgetSpan` with a middle alignment, without the margin, this is what we get:

![image](https://github.com/superlistapp/super_editor/assets/7597082/4dbc4245-9968-4c9e-9530-789833a9c40f)

![image](https://github.com/superlistapp/super_editor/assets/7597082/0ae45b4c-583b-4fb3-b853-8485c4724ea2)

Is any of those the expected output?

**Comment by angelosilvestre** [comment]
@alterhuman Currently you'll need to create a custom `ListItemComponentBuilder` that creates a `UnorderedListItemComponent` using  a `dotBuilder` that creates a bigger dot for bigger fonts.

We can make it simpler to just customize the size, but we'll need to investigate how we should expose this configuration. Could you please file a separate issue for that?

**Comment by matthew-carroll** [comment]
@angelosilvestre can you post a code snippet that shows how to configure that component?

**Comment by angelosilvestre** [comment]
@alterhuman You can create a component builder with the following snippet:

```dart
class MyListItemComponentBuilder extends ComponentBuilder {
  @override
  Widget? createComponent(
      SingleColumnDocumentComponentContext componentContext, SingleColumnLayoutComponentViewModel componentViewModel) {
    if (componentViewModel is! ListItemComponentViewModel) {
      // We don't care about this kind of component.
      return null;
    }

    if (componentViewModel.type == ListItemType.ordered) {
      // We don't want to modify ordered list items.
      return null;
    }

    return UnorderedListItemComponent(
      componentKey: componentContext.componentKey,
      text: componentViewModel.text,
      styleBuilder: componentViewModel.textStyleBuilder,
      indent: componentViewModel.indent,
      textSelection: componentViewModel.selection,
      selectionColor: componentViewModel.selectionColor,
      highlightWhenEmpty: componentViewModel.highlightWhenEmpty,
      composingRegion: componentViewModel.composingRegion,
      showComposingUnderline: componentViewModel.showComposingUnderline,
      dotBuilder: (context, component) {
        // TODO: customize the bullet point.

        final texStyle = component.styleBuilder({});

        return Align(
          alignment: Alignment.centerRight,
          child: Text.rich(
            WidgetSpan(
              alignment: PlaceholderAlignment.middle,
              child: Container(
                width: 20,
                height: texStyle.fontSize! * texStyle.height!,
                margin: const EdgeInsets.only(right: 10),
                decoration: const BoxDecoration(
                  shape: BoxShape.circle,
                  color: Colors.red,
                ),
              ),
            ),
          ),
        );
      },
    );
  }

  @override
  SingleColumnLayoutComponentViewModel? createViewModel(Document document, DocumentNode node) {
    // Return null so we use the viewmodel from the standard list item component.
    //
    // We don't need to add custom properties, so we can use the same viewmodel that
    // the standard list item component uses.
    return null;
  }
}
```

And apply the component builder to the editor with the following snippet:

```dart
SuperEditor(          
  // other properties
  componentBuilders: [
    MyListItemComponentBuilder(),
    ...defaultComponentBuilders,
  ],
)
```
