### ISSUE TITLE
Auto assigned new tasks to user

### ISSUE THREAD

**Issue by Cabbagge** [superlistapp/super_editor#1856]
**User Behavior**
A checkbox somewhere in the settings to automatically set the user as the owner of the task or something similar where unassigned tasks will be shown by default to the user for personal use

**Feature Value**
This is not that important but it may be a good feature to add for users that uses this as a personal checklist/reminder list

**Additional context**

**Comment by matthew-carroll** [comment]
It looks like the filed issue is requesting an application feature, which falls well outside the stated purpose of `super_editor`. I'm going to close this issue. If you find that `super_editor` is lacking a behavior within it's stated mission, please open a new ticket that provides all relevant information.
