### ISSUE TITLE
[SuperReader] - Error: The getter 'isAltPressed' isn't defined for the class 'HardwareKeyboard'.

### ISSUE THREAD

**Issue by abidex4yemi** [superlistapp/super_editor#1872]
I'm encountering an error while attempting to build my app after changing the "dependency_overrides" to a forked version. 

The error specifically points to a missing definition for the 'isAltPressed' getter within the 'HardwareKeyboard' class in the file "read_only_document_keyboard_interactor.dart".

<img width="545" alt="Screenshot 2024-03-03 at 1 02 26 PM" src="https://github.com/superlistapp/super_editor/assets/23571838/b93cbe3d-62bb-4e4b-8bb7-6a3634e5581b">

see screenshot for error log
<img width="1107" alt="Screenshot 2024-03-03 at 1 01 52 PM" src="https://github.com/superlistapp/super_editor/assets/23571838/1b373143-6c1e-4ee6-8078-01485bb48f12">

@matthew-carroll @angelosilvestre @rutvik110  any idea?

**Comment by abidex4yemi** [comment]
@rutvik110  Here's my flutter version: `Flutter 3.16.0 • channel stable `, if i point it to `super_editor` it works fine.

**Comment by rutvik110** [comment]
Could you try doing a `flutter clean` on the project? and then retry building it. Might be a caching issue and  also, make sure your fork is up-to-date with latest changes from `super_editor` repo.

**Comment by abidex4yemi** [comment]
I have done all that yet it is not working, I have also cleared pub-cache still the same error.

**Comment by rutvik110** [comment]
Could you please share your complete pubspec.yaml? Please add it as an code within the description instead of screenshot by doing
 \```dart 
 Your code
 \```

**Comment by rutvik110** [comment]
@abidex4yemi  It seems like that api change was introduced in Flutter `v3.19.0` and you're currently on `v3.16.0` which doesn't support that change. You could either upgrade to latest Flutter version or us an earlier version of `super_editor` that works with Flutter `v3.16.0` .

**Comment by rutvik110** [comment]
Closing this as the issue can be resolve by updating to latest flutter version.
