### ISSUE TITLE
Need more information what changed in a TextNode when adding/removing/modifying attributions

### ISSUE THREAD

**Issue by roughike** [superlistapp/super_editor#1884]
Blocker for #1883.

When a user adds/removes/modifies attributions such as bold/italic/strikethrough in a paragraph in a document, I get `NodeChangeEvent (<node id>)` and that's it.

I'd like to get more context what changed:
* When a new attribution is added, I need to know the attribution itself + the range of text in a given text node that the attribution applies to.
* When an existing attribution is removed, I need to know the attribution itself + the range of text that the attribution was removed from.

The reason is that I need to construct a Quill Delta for adding/removing the attribution here: https://github.com/superlistapp/super_editor/blob/22ca94897427070a7eba8c62017af1523e52924a/super_editor_quill/lib/src/delta_document_change_listener.dart#L42

Sample on how the Quill Deltas I need to construct would look like:
* abc -> a**b**c = `Delta()..retain(1)..retain(1, {'bold': true})`
* a**b**c -> abc = `Delta()..retain(1)..retain(1, {'bold': null})`

**Comment by matthew-carroll** [comment]
@roughike can you clarify the difference between the information that's already made available and the information you need?

For example, here's one of the existing events:

```dart
class TextInsertionEvent extends NodeChangeEvent {
  TextInsertionEvent({
    required String nodeId,
    required this.offset,
    required this.text,
  }) : super(nodeId);

  final int offset;
  final AttributedText text;
}
```

This event reports the ID of the node where the insertion took place, the offset in the node where the insertion began, the text that was inserted, and the attributions attached to that inserted text.

Other text change events similarly report contextual details.

Can you list the events that don't provide enough information, and can you let me know the specific information that you'd like to have added?

**Comment by roughike** [comment]
@matthew-carroll TextInsertionEvents and such work fine - no need to do anything there.

However, when adding/removing/modifying attributions, I get no other event than `NodeChangedEvent` with the `nodeId` of the node.

For example, adding bold and italic attribution to character "b" and then removing the attributions:

https://github.com/superlistapp/super_editor/assets/13744304/56d8aba2-81e9-4015-99c1-67f08ddc23ef

What I expect to get is:
* `AttributionsAddedEvent(range: DocumentRange(..), attributions: { .. })`
* `AttributionsRemovedEvent(range: DocumentRange(..), attributions: { .. })`

The specifics don't matter - it can be `DocumentRange`, `TextRange`, `SpanRange`, whatever is the best representation for this. It's just that `NodeChangeEvent(id: ..)` loses the information what attributions were added/removed.
