### ISSUE TITLE
[SuperEditor] Numbered list doesn't work on manual addition of items and when number is not 1

### ISSUE THREAD

**Issue by alterhuman** [superlistapp/super_editor#1894]
If you type
```dart
1. List Item
```
and press enter/return, the result is as follows:
```dart
1. List Item
2. 
```

This is correct behaviour. But if you type:
```dart
1. List Item

```
and then manually enter `2.` below it, the attribution doesn't change.
Ideally it should change it to the second list item, resulting in:
```dart
1. List Item
2. 
```

> In some text editors, even typing any other number other than one greater than the previous list item, changes the list item correctly. For example, 
 if you type:
```dart
1. List Item

```
and then manually enter `4.` below it, it changes it to:
```dart
1. List Item
2. 
```

#### Video Example

https://github.com/superlistapp/super_editor/assets/92245694/b2d3afb5-81af-4926-a15f-c52a9eae8ef4

#### Related Issue

If you type `1. `, it changes to list attribution, but typing any other number `2. ` or `12. ` etc. doesn't change the attribution to numbered list attribution.

Ideally it should start a list from that very number. For example, `2. ` should start a list from 2.

https://github.com/superlistapp/super_editor/assets/92245694/a8c0c774-f693-4e42-bbca-2dc0e2b3c553

**Comment by rutvik110** [comment]
@alterhuman The example demos you shared, what app are they captured from? And could you please share a demo of what happens in Super Editor when you try to do the same?

**Comment by rutvik110** [comment]
Tested this across google docs as we're trying to follow it for certain editor features and their behaviours. I can see some of the things you mentioned are supported in google docs and there are few key differences between how Super Editor vs google docs work with numbered lists. 

@matthew-carroll We probably wanna re-visit how Super Editor handles numbered list and try to match the google docs experience for them. Though this missing behaviours aren't critical enough for us to work on this immediately but nice to have improvements that we can work on later down the line.

**Comment by matthew-carroll** [comment]
@miguelcmedeiros @brian-superlist - Can you two let us know if this is a desirable default behavior? It seems like a fine thing to support, but we don't want to make it the default if you don't want it.

**Comment by brian-superlist** [comment]
Yes, this makes sense for sure.
