### ISSUE TITLE
[SuperEditor] Task indentation implementation is missing

### ISSUE THREAD

**Issue by alterhuman** [superlistapp/super_editor#1895]
Unable to indent checkboxes using tab key, similar to ordered and unordered lists.

### Similar Issue
Pressing enter on an empty checkbox does not make it disappear,. This also works correctly in case of ordered and unordered lists.

**Comment by rutvik110** [comment]
@alterhuman Could you please describe what you mean when you say, "Unable to indent checkboxes using tab key, similar to ordered and unordered lists."? What's the expected and the actual behaviour you're encountering here? Please share any demos or reproducible example, makes things easier to understand for reviewers. 

Also, if there are multiple issues you're encountering, please file a separate issue for each unless they're directly related to each other and fixing one could fix the other. Keeping a single issue scoped to a specific thing makes it easy to make decisions around it.

**Comment by rutvik110** [comment]
Thanx a lot for the info. I think I understand the issue more clearly now. I just checked that the numbered and bullet lists in Super Editor support this where items are moved to a sub-list as part of the primary list item on shift press and reverted back on tab + shift press. This will be nice to have addition for checkbox list.

**Comment by matthew-carroll** [comment]
@miguelcmedeiros @brian-superlist - Can you two let us know if this is a desirable default behavior? It seems like a fine thing to support, but we don't want to make it the default if you don't want it.

**Comment by matthew-carroll** [comment]
@alterhuman we still haven't heard back if this is desirable behavior. Therefore, if you implement it, at least for now, it needs to be opt-in behavior.

That said, if you want a hardware keyboard key to do something, the first thing you typically want to do is to create a key handler which implements the desired behavior. When you create a `SuperEditor` widget, it automatically includes a default list of key handlers. You can pass your own desired list of key handlers, instead. You probably want to create a new key handler that recognizes the tab key and indents the task.

If you want users to be able to press tab on a software keyboard then you'll need to look at where we handle IME messages. That's where we handle all text input on mobile, and some things from desktop, too.

You said that list items already handle indentation the way you want. Therefore, you can probably track down where list item indentation is handled to figure out what to do for tasks.

I'm guessing that `TaskComponent` also currently has no concept of indentation. Here again, you can probably borrow the approach from list items. The component needs to add the desired amount of space to the left side, depending on the lever of indentation.

Once you implement hardware key input, IME input, and visual indentation rendering, you should have a completed feature.

Please be sure to add appropriate tests, too.

**Comment by brian-superlist** [comment]
Nope, we'd need to implement this one ourselves since we have custom TaskComponents and functionality.

**Comment by matthew-carroll** [comment]
@alterhuman would you like to try implementing this?
