### ISSUE TITLE
[SuperEditor] Empty task doesn't get removed on pressing enter/return

### ISSUE THREAD

**Issue by alterhuman** [superlistapp/super_editor#1898]
Empty task should be removed if enter/return key is pressed when the caret is on it. Similar to ordered and unordered lists.

#### Expected and actual behavior

https://github.com/superlistapp/super_editor/assets/92245694/4bc70193-3d9a-46ff-ae63-6d9738f89572

**Comment by toseefkhan403** [comment]
Can I take up this issue? @alterhuman
