### ISSUE TITLE
[SuperEditor] Upgrade uuid dependency

### ISSUE THREAD

**Issue by KevinBrendel** [superlistapp/super_editor#1899]
**User Behavior**
Currently SuperEditor depends on uuid 3.0.3, which was released 3 years ago. Many packages today require uuid with major version 4, resulting in dependency conflicts. Upgrading this dependency would solve this problem and make SuperEditor more compatible.

**Feature Value**
Without this, SuperEditor is only usable with dependency_overrides in many projects, making it more likely to scare users off and making it possible that dependency_overrides cause unforeseen issues, in case SuperEditor is broken by breaking changes of uuid 4. Upgrading the dependency would increase adoption of this package and reduce risk.

**Comment by matthew-carroll** [comment]
@KevinBrendel would you like to put up a PR that increments the dependency?

**Comment by KevinBrendel** [comment]
> @KevinBrendel would you like to put up a PR that increments the dependency?

Done.
