### ISSUE TITLE
[SuperIOSTextField] Update text selection handles sizing and layout to match native iOS design spec

### ISSUE THREAD

**Issue by rutvik110** [superlistapp/super_editor#1924]
`SuperIOSTextField` text selection handles doesn't follow the native iOS design specs as documented [here](https://docs.google.com/document/d/1g7qHcknab9Av4kxw78145wyVrj5wF5_UEGyzt8Exhzk/edit). This includes the text selection handle bar and the circle that is shown above/below the handle.

Need to update following things to match the native behaviour: 
* iOS uses handle circle radius of 6px under all circumstances. `SuperIOSTextField` currently uses 4px. Update that. [read](https://docs.google.com/document/d/1g7qHcknab9Av4kxw78145wyVrj5wF5_UEGyzt8Exhzk/edit#heading=h.vtp4ztibjjz)
* On iOS, the drag handle rectangles are exactly as tall as the selection highlight rectangle for a given line, and the top and bottom of those handle rectangles match the selection rectangle. Update the handle bar layout to match the native behaviour.  [read](https://docs.google.com/document/d/1g7qHcknab9Av4kxw78145wyVrj5wF5_UEGyzt8Exhzk/edit#heading=h.cefu8wyhfn2s)
* On iOS, the drag handle circle sits completely above/below the very top/bottom edge of the handle. `SuperIOSTextField` circle overlaps with the selection area. Update it. [read](https://docs.google.com/document/d/1g7qHcknab9Av4kxw78145wyVrj5wF5_UEGyzt8Exhzk/edit#heading=h.cefu8wyhfn2s)

**Comment by angelosilvestre** [comment]
There are some statements that doesn't seem to be true for iOS 17.5. Screenshot from Safari:

![image](https://github.com/superlistapp/super_editor/assets/7597082/a0a1c5e4-d214-4a4b-b617-c711f64b7cf8)

- The ball radius looks to be 8px instead of 6px.
- There is an overlap between the ball and the selected area, which seems to be approximately half of the ball radius.
