### ISSUE TITLE
Demo Example Broken on Web

### ISSUE THREAD

**Issue by rayliverified** [superlistapp/super_editor#1925]
**Package Version**
The web demo at https://editor.superlist.com is broken.
- Cannot enter spaces.
- No toolbar with formatting controls popup when selecting text.
- Cannot delete text after pasting text.

https://github.com/superlistapp/super_editor/assets/19896174/b2d8bb45-e974-453c-86bc-b3ae9d69abd2

**Platform**
Windows 11
Opera

**Comment by angelosilvestre** [comment]
> Cannot delete text after pasting text.

@rayliverified Could you please give us more details about this specific issue?

**Comment by rayliverified** [comment]
To reproduce:

Paste text.
Delete no longer works and text cannot be deleted.

**Comment by angelosilvestre** [comment]
@rayliverified Would you mind sharing a video showing how you are triggering this issue?

**Comment by rayliverified** [comment]
I cannot delete or type new text after pasting. 

https://github.com/superlistapp/super_editor/assets/19896174/24029d30-d53c-420e-85cb-03970bfa1620

**Comment by rayliverified** [comment]
Great, everything works now!
