### ISSUE TITLE
Can't create LinkAttributions with invalid URLs

### ISSUE THREAD

**Issue by roughike** [superlistapp/super_editor#1927]
**Package Version**
super_editor, main branch

**To Reproduce**
Try creating a `LinkAttribution` with an invalid url. Since `Uri` only allows valid urls, a `LinkAttribution` can't be created.

**Minimal Reproduction Code**
`LinkAttribution(url: Uri.parse('https://tel:+12%20345%20678%209'));`

**Actual behavior**
Can't create a `LinkAttribution` with invalid URL.
```
FormatException: Invalid port (at character 13)
https://tel:+12%20345%20678%209
            ^
```

**Expected behavior**
Changing `url` parameter in `LinkAttribution` to `String` instead, which would allow for invalid URLs:

`LinkAttribution(url: 'https://tel:+12%20345%20678%209');`

**Additional context**
We're taking an email in HTML format and converting that to a SuperEditor document.

Because an email is user generated content, we want to avoid modifying anything and just display it as-is. The problem is that the email contains an invalid link. SuperEditor does not let us render the document at all, because the `Uri` required by `LinkAttribution` does not allow us pass invalid URIs to it.

Apple Mail allows displaying the invalid link, but clicking on the link shows an error dialog:
![image](https://github.com/superlistapp/super_editor/assets/13744304/cd995014-9b6b-440d-9cfe-48cb34296a03)

**Comment by matthew-carroll** [comment]
The request for invalid links seems reasonable based on the use-case. We'll want to take steps to minimize the opportunity for the other use-cases to inadvertently allow invalid URLs, if they don't want to. I'll take a look at the APIs and see what makes sense.
