### ISSUE TITLE
[super_editor] Pub package name

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [superlistapp/super_editor#194]
I assume you intend to publish this as a Pub package once the MVP is done. If that is the case, I think it might make sense to "reserve" the package name :)

Hint: you have the ability to publish a version `0.0.0` (:

---

Side note: if you need any feedback for the public API, we do have a use case that fits this very well and I can help with that if you are interested. We do have some of our own functionality built already, but I think this makes it even more valuable to see if this can easily be covered by the public-facing API of the published Pub package.

**Comment by bk-one** [comment]
This is not live at https://pub.dev/packages/super_editor. Thanks for the heads up :)
