### ISSUE TITLE
Selection colour of components with custom view models

### ISSUE THREAD

**Issue by kasyrm** [superlistapp/super_editor#1944]
Fist of all super editor is an amazing tool, thanks for creating it 🚀

**User Behavior**
I would like to be able to provide a selection colour for my custom components. For the view models provided by package the selection colour seems to be assigned inside a private function _applySelection in SingleColumnLayoutSelectionStyler, but other components do not change colour when selected.  (I also noticed horizontal ruler selection colour differs from the rest. Would be great to be able to override it)

**Feature Value**
It provides proper feedback to user that the element is selected. 

**Additional context**
If this is achievable already in a different way please let me know 🙏

**Comment by matthew-carroll** [comment]
To make sure that we understand exactly what you're requesting, can you provide a specific UI goal that you're trying to achieve, and let us know what you've tried, and where you're getting stuck?

I understand there's a general desire for selection control, but it would be more effective to work from a specific goal.

**Comment by kasyrm** [comment]
I would like for the component to appear selected. 
In my button component I added a SelectableBox that accepts selection and selection color.  Selection information  is provided from view model mirroring for example the HorizontalRulerComponent.  From what I found selection is assigned in SingleColumnLayoutSelectionStyler but only to 3 particular ViewModels (Text, Image and HorizotalRuler). I would like there to be a way to pass the information also to custom ViewModels.
```  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Positioned.fill(
          child: SelectableBox(
            selection: selection,
            selectionColor: selectionColor,
            child: BoxComponent(key: componentKey, child: Container()),
          ),
        ),
        _buildButton(),
      ],
    );
  }```
  
  
<img width="577" alt="Button component that is selected but does not appear selected" src="https://github.com/superlistapp/super_editor/assets/13262745/b9406d86-ac5a-403f-b2a8-75d54ac0d243">

Button component that is selected but does not appear selected

**Comment by matthew-carroll** [comment]
@angelosilvestre can you look into this and see if we have an existing extension point for this? I thought we had mechanisms for 3rd party components to render a selection UI, but maybe not.

**Comment by angelosilvestre** [comment]
@matthew-carroll I don't think we have an easy extension point for this.

Our `SingleColumnLayoutSelectionStyler` looks specifically for `TextComponentViewModel`, `ImageComponentViewModel` and `HorizontalRuleComponentViewModel`.

Developers can add their own `SingleColumnLayoutStylePhase` to apply selection styling to custom components, but I think it is a lot of work to accomplish a simple task...

Maybe we could introduce something like `SelectionAwareViewModelMixin`, where we would expose the selection and the selection color. Any thought on this?

**Comment by angelosilvestre** [comment]
With this approach I was able to write a component with a custom view model with selection color support:

https://github.com/superlistapp/super_editor/assets/7597082/b6cf70d1-91b0-4a37-88ec-ab04add715e3

**Comment by matthew-carroll** [comment]
@angelosilvestre I noticed that there's a different selection color in your selectable button. Was that on purpose? Can that component use the standard selection color if it wants? Is the standard selection color obtainable from that component?

**Comment by angelosilvestre** [comment]
@matthew-carroll The `SelectableBox` automatically applies 50% opacity to the selection color.
