### ISSUE TITLE
Caret offset can be wrong around certain emojis for non-left-aligned paragraphs

### ISSUE THREAD

**Issue by KevinBrendel** [superlistapp/super_editor#1960]
**Package Version**
super_editor, GitHub, stable branch

**To Reproduce**
1. Open the example app
2. Go to the "Paragraphs" demo
3. Replace the center aligned or the right aligned paragraphs each with one of the broken emojis (like ☁️ or ⭕️)
4. Try to position the caret to the left of the emoji

**Actual behavior**
- For the center aligned emoji, the cursor is within the emoji
- For the right-aligned emoji, the cursor is to the right of the emoji (visually the same as being actually positioned to the right)

**Expected behavior**
The cursor should be correctly to the left of the emoji, as it is for other emojis, like ❌ or 🎉

**Platform**
- macOS 14.4.1
- Windows 11, 23H2

**Flutter version**
Flutter 3.19.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68bfaea224 (5 weeks ago) • 2024-03-20 15:36:31 -0700
Engine • revision a5c24f538d
Tools • Dart 3.3.2 • DevTools 2.31.1

**Screenshots**
<img width="62" alt="Screenshot 2024-04-22 at 15 54 27" src="https://github.com/superlistapp/super_editor/assets/55455206/ced3008d-3ba6-4726-a4bc-a04eee81503a">

<img width="50" alt="Screenshot 2024-04-22 at 15 54 43" src="https://github.com/superlistapp/super_editor/assets/55455206/9f399ca5-a586-4d2c-928f-b38ca710e560">

**Comment by angelosilvestre** [comment]
@matthew-carroll @KevinBrendel This looks like a Flutter issue, since it's not working correctly on Flutter stable, but it's working on Flutter master:

https://github.com/superlistapp/super_editor/assets/7597082/c1474716-2f40-4d1d-9fe5-7d98ca01b36b

**Comment by KevinBrendel** [comment]
Good find! Then this issue can be closed from my perspective.

Thanks!
