### ISSUE TITLE
Keyboard overlaps SuperEditor 

### ISSUE THREAD

**Issue by hawkkiller** [superlistapp/super_editor#1975]
When SuperEditor has an ancestor Scrollable (for example ListView) and is wrapped in a SingleChildScrollView, on mobile devices the keyboard overlaps the editor itself (it doesn't scroll like TextField does).

If SuperEditor is not wrapped in a SingleChildScrollView then it works, but the editor then treats the listview viewport as its own, which is incorrect and leads to overflow.

Sample code:

```dart
ListView(
  children: [
    ...,
    SizedBox(height: 300, child: SingleChildScrollView(child: SuperEditor))),
  ],
);
```

**Comment by hawkkiller** [comment]
cc: @angelosilvestre @matthew-carroll

**Comment by matthew-carroll** [comment]
@hawkkiller have you looked at the sliver example in the demo app?

**Comment by hawkkiller** [comment]
Oh, thank you. I will check it out, slivers should solve the problem!
