### ISSUE TITLE
Why no new releases on pub

### ISSUE THREAD

**Issue by escamoteur** [superlistapp/super_editor#2003]
Hi,
why hasn't there been any new release pushed to pub when there has been so many changes?

Cheers
Thomas

**Comment by matthew-carroll** [comment]
Because we've been reworking the core of the editor for a long time. There's no point in releasing while so many APIs are in flux. Please use the GitHub version in your apps for now.

**Comment by escamoteur** [comment]
The big problem is that without a release management with a change log and at least Tags with versions it is difficult to know when a breaking change has happened. So you only can pin to a certain commit and every update of is a gamble if nothing will break.
Am 21. Mai 2024, 02:13 +0200 schrieb Matt Carroll ***@***.***>:

**Comment by matthew-carroll** [comment]
The point is that we're regularly breaking lots of APIs because it isn't clear what these new APIs should be. This is the nature and purpose of unstable versions. I understand it's not ideal, but there's no obvious alternative. Rather than release dozens of versions that all break each other on Pub, we're working on GitHub where we can all recognize, as you did, that things are unstable.

**Comment by escamoteur** [comment]
I totally understand the motivation, but at least a maintained changelog with either git tags or commit hashes would be extremely helpful to know what to expect when trying to switch to a newer version.

**Comment by matthew-carroll** [comment]
I'm not sure what you're asking for. Pub has a change log. The change log for GitHub is the commit history.

**Comment by escamoteur** [comment]
as a pure user of your package it is difficult to follow all the changes that you frequently make, even more difficult to understand the impact that every change has on the API and the behavior of the package. So an internal changelog that makes it easier for users to understand which commit to target would be extremely helpful

**Comment by matthew-carroll** [comment]
I understand the frustration. The effort to keep a secondary log (in addition to the commit history) that holds every change to every API is time prohibitive. We'd spend half of our time doing that accounting.

I know that you maintain packages, so you're experienced with this. If you'd like to join our effort and help us organize that information, we'd welcome the help. However, without more people chipping in to do that, we simply don't have the time to spend on such an effort.

**Comment by escamoteur** [comment]
What I ask is not to document every change, but there should be some understanding in your team when you merge some bigger change into stable what that means to the API and behavior. I know you have limited resources but at the same time this is an extremely important package as there are not many alternatives. Every time I ask in our team if we should update super_editor I get the response, better not, it might break. Which isn't good in any way. 
I was honestly shocked to see how old the version on pub is while there have been so many changes. At least some explanation about the current state and planned near future in the readme would be helpful.

**Comment by matthew-carroll** [comment]
Ok. I guess all I can say is that your concerns are heard and we're aware of the issue. Staying up to date with Super Editor at the moment will require careful attention, and adopters with production apps should make sure to write lots of tests to help catch regressions.

**Comment by escamoteur** [comment]
maybe exact this should be currently at the top of the readme on github

**Comment by matthew-carroll** [comment]
BTW, if your company would like to provide funding to the Flutter Bounty Hunters for this specific purpose, we will assign that documentation work to a member of the team.

**Comment by escamoteur** [comment]
I already started the discussion on funding internally. however er probably would like to see funding progress to new stable versions :-)

**Comment by matthew-carroll** [comment]
Chicken and egg - the quickest road to higher stability is a wider portfolio of funders. 

When you become a funder, you get to call the shots. If you want documentation, or a specific feature, you get it with funding. 

Not every team is capable of funding, and that's fine, but for teams that are capable of funding, it certainly doesn't help to wait while others fund what you need.

**Comment by escamoteur** [comment]
As said, I already started the discussion on funding

**Comment by BazinC** [comment]
How about using pub prereleases versions? @matthew-carroll @escamoteur 
https://dart.dev/tools/pub/publishing#publishing-prereleases
example: https://pub.dev/packages/freezed

It could give better visibility on pub.dev that the package is still active.
Currently the Super Editor pub home page can scare people
<img width="349" alt="image" src="https://github.com/superlistapp/super_editor/assets/6229343/e634de56-1a8c-4b8c-9eff-6fd125e3ad2e">

**Comment by matthew-carroll** [comment]
I just published a prerelease version to try to help with this. Unfortunately, it looks like Pub doesn't update the README file when publishing a prerelease, so we're stuck with the current messaging until we're willing to declare the new APIs stable. Unfortunate.

**Comment by escamoteur** [comment]
Readme is now updated. Maybe pub does it after processing
Am 11. Juni 2024, 07:43 +0100 schrieb Matt Carroll ***@***.***>:
