### ISSUE TITLE
[SuperTextField][Mobile] - Popover toolbar appears when it shouldn't

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#2005]
**Package Version**
main

**To Reproduce**
1. Tap on an empty SuperTextField on mobile

**Minimal Reproduction Code**
Run the SuperTextField demo

**Actual behavior**
A popover toolbar appears.

**Expected behavior**
No popover toolbar should appear because there isn't any content to interact with.

If iOS and Android show a similar behavior to what we have, then feel free to correct me, but this seems wrong. 

**Platform**
Repro'd on iOS, but probably on Android, too.

**Flutter version**
v.3.22

**Screenshots**

https://github.com/superlistapp/super_editor/assets/7259036/fa51726c-6c3d-4a89-a653-7e52e0eb3f21

**Comment by angelosilvestre** [comment]
@matthew-carroll I think the toolbar should be visible so the user can tap the "Paste" button. Should we just hide the "Cut" and "Copy" buttons when there isn't an expanded selection?

**Comment by matthew-carroll** [comment]
@angelosilvestre can you check iOS and Android and check whether a toolbar appears the moment you place the caret or not? I don't think I remember ever seeing a toolbar upon first tap.
