### ISSUE TITLE
[iOS] Support native edit menu + Secure Paste

### ISSUE THREAD

**Issue by BazinC** [superlistapp/super_editor#2032]
Recently Flutter team worked on [[ios_edit_menu]add native edit menu](https://github.com/flutter/engine/pull/50095/files#top),
unlocking [Flutter should support iOS 15's Secure Paste feature](https://github.com/flutter/flutter/issues/103163#top)

I think SuperEditor should aim feature parity here. Currently, everytime you paste something from another app you will get a pop up. End user is annoyed.

<img src="https://github.com/superlistapp/super_editor/assets/6229343/7be10882-1471-46c5-ac96-2ad7184230dc" width="300">

**Comment by angelosilvestre** [comment]
I think @Jethro87 also mentioned something about using the native context menu a while ago.

**Comment by Jethro87** [comment]
@angelosilvestre Yes, we would also like this.

**Comment by matthew-carroll** [comment]
I did some investigation into the design doc and merged PR. I also started poking around Flutter's built-in text field to see where this behavior is exposed.

It looks like the referenced PR may have been reverted in Flutter (undone). If that's the case, then we're back to waiting on a lasting merge of that behavior.

**Comment by alvindrakes** [comment]
> I did some investigation into the design doc and merged PR. I also started poking around Flutter's built-in text field to see where this behavior is exposed.
> 
> It looks like the referenced PR may have been reverted in Flutter (undone). If that's the case, then we're back to waiting on a lasting merge of that behavior.

Hey Matthew, I am currently looking into the secure paste implementation too. 

Running Flutter 3.22.2 atm, but looks like `SystemContextMenu` is not exposed atm?
