### ISSUE TITLE
[web] CMD+Z causing exception and blocking the editor

### ISSUE THREAD

**Issue by szpaqq** [superlistapp/super_editor#2060]
**Package Version**
super_editor, GitHub, stable branch

**To Reproduce**
1. Run the super-editor in chrome `flutter run -d chrome`
2. Remove part of the text in first block
3. Press CMD + Z

**Actual behavior**
Exception is logged, the editor is blocked/stuck, user cannot write, after changing block the cursor position is different that chosen when writing

**Expected behavior**
Best: Erased text is restored, user able to write text, cursor position set to chosen position
Minimum: Nothing happens, user able to write text, cursor position set to chosen position

**Platform**
Macbook pro M1 2020
Sonoma Version 14.5

**Flutter version**
Flutter 3.22.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision a14f74ff3a (7 days ago) • 2024-05-22 11:08:21 -0500
Engine • revision 55eae6864b
Tools • Dart 3.4.1 • DevTools 2.34.3

**Screenshots**

https://github.com/superlistapp/super_editor/assets/12150396/9c43c799-9992-43ec-8584-4a5520f3c7de

**Additional context**
Log:
`Another exception was thrown: Assertion failed: file:///Users/knips/Dev/flutter/packages/flutter/lib/src/services/text_editing_delta.dart:129:14
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Assertion failed:
file:///Users/knips/Dev/flutter/packages/flutter/lib/src/services/text_editing_delta.dart:129:14
_debugTextRangeIsValid(newSelection, oldText)
"The selection range: TextSelection(baseOffset: 32, extentOffset: 115, isDirectional: false) is not
within the bounds of text: . Now, you're off to the races!  of length: 32"

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3        assertFailed
packages/flutter/src/services/text_editing_delta.dart 129:58                      fromJSON
packages/flutter/src/services/text_input.dart 1902:59                             _handleTextInputInvocation
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                _async
packages/flutter/src/services/text_input.dart 1809:45                             [_handleTextInputInvocation]
packages/flutter/src/services/text_input.dart 1794:20                             _loudlyHandleTextInputInvocation
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                _async
packages/flutter/src/services/text_input.dart 1792:51                             [_loudlyHandleTextInputInvocation]
packages/flutter/src/services/platform_channel.dart 571:55                        _handleAsMethodCall
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                _async
packages/flutter/src/services/platform_channel.dart 568:40                        [_handleAsMethodCall]
packages/flutter/src/services/platform_channel.dart 564:34                        <fn>
packages/flutter/src/services/binding.dart 581:35                                 <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                _async
packages/flutter/src/services/binding.dart 578:98                                 <fn>
lib/_engine/engine/platform_dispatcher.dart 1435:5                                invoke2
lib/ui/channel_buffers.dart 25:12                                                 invoke
lib/ui/channel_buffers.dart 65:7                                                  push
lib/ui/channel_buffers.dart 131:16                                                push
lib/_engine/engine/platform_dispatcher.dart 468:10                                invokeOnPlatformMessage
lib/_engine/engine/text_editing/text_editing.dart 2216:30                         updateEditingStateWithDelta
lib/_engine/engine/text_editing/text_editing.dart 2323:11                         <fn>
lib/_engine/engine/text_editing/text_editing.dart 1410:7                          handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 426:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:39  dcall

call:
  MethodCall(TextInputClient.updateEditingStateWithDeltas, [2, {deltas: [{oldText: . Now, you're off
  to the races! , deltaText: , deltaStart: -1, deltaEnd: -1, selectionBase: 32, selectionExtent:
  115, composingBase: -1, composingExtent: -1}]}])
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Exception: Couldn't map an IME position to a document position. `

**Comment by matthew-carroll** [comment]
@angelosilvestre my question for this issue is why CMD+Z is doing anything? I don't think we've shipped anything for that shortcut yet, have we? If not, is the browser trying to do something on its own? Or maybe Flutter is automatically trying to do something?

**Comment by angelosilvestre** [comment]
The text input on web relies on the HTML input, maybe the shortcut is triggering an undo of the HTML input. We probably need to prevent this key combination to bubble up to the browser. I'll take a look.
