### ISSUE TITLE
【Question】Is there more demo for this awesome editor?

### ISSUE THREAD

**Issue by hwk42** [superlistapp/super_editor#2062]
Appreciate for this great work.I want to try to save document in code from the editor,but not found a way to go in wiki.Is there any guide or docs for beginner？

**Comment by angelosilvestre** [comment]
We have built-in support for markdown conversion: https://supereditor.dev/super-editor-guides/document-from-markdown/

But you can iterate over the document nodes to save them in any format you want, e.g., JSON, XML, etc.
