### ISSUE TITLE
[SuperEditor] [iOS] Vertical scrolling occurring during horizontal drag gestures

### ISSUE THREAD

**Issue by jakeett** [superlistapp/super_editor#2081]
**Package Version**
stable branch

In iOS apps, views containing a Super Editor can be scrolled vertically even when dragging horizontally. Once a horizontal drag gesture is initiated, only movement along the x-axis is consumed, and y-axis movements are ignored until a new drag gesture is started.

https://github.com/superlistapp/super_editor/assets/172330941/e45f555f-91a5-4d36-98bf-8bafbd40a163

**Comment by matthew-carroll** [comment]
@jakeett what's the expected behavior here? Are you saying that when you start dragging horizontally, the editor shouldn't ever move vertically no matter how far up/down you move your finger?

If so, can you please include a video of some other iOS app with a document that behaves the way you describe?

**Comment by jakeett** [comment]
No sorry, I am saying that horizontal drag gestures should not be mapped to vertical scroll movements. In the video I was trying to demonstrate that when you scroll left/right, then the screen is getting scrolled vertically. Also, when the user initiates a horizontal drag gesture, then all vertical movement is getting ignored.

I have taken some videos with clicks highlighted, hopefully that makes it a bit clearer to see.

| Current behaviour | Expected behaviour |
|--|--|
| <video src="https://github.com/superlistapp/super_editor/assets/172330941/b927250c-87bf-40e5-b518-cf697fd6198a" ></video> | <video src="https://github.com/superlistapp/super_editor/assets/172330941/831bc413-0f49-4a01-8a22-90ab9b9acdea" ></video> |


Also this doesn't happen on android
