### ISSUE TITLE
[SuperEditor][SuperTextField][Android] - Selection extent handle movement on drag should select per-word downstream, per-character upstream

### ISSUE THREAD

**Issue by BazinC** [superlistapp/super_editor#2112]
Currently, as the user drags the downstream selection handle on Android, `SuperEditor` and `SuperTextField` moves the selection per-character.

On Android, the selection is **per-word** when handle moves downstream and **per-character** when handle moves upstream.
This behavior seems to be correctly implemented on SuperEditor for on long press with **AndroidDocumentLongPressSelectionStrategy**, but not when user is dragging the selection handle when the selection is expanded.

**Comment by matthew-carroll** [comment]
@angelosilvestre I know I've implemented some amount of per-word selection behavior. Maybe I missed this particular interaction, but have a look at what's already available before you dive too deep. You might be able to redirect some touch interactions to existing behavior.

**Comment by angelosilvestre** [comment]
@matthew-carroll It looks like all of the per-word selection behavior lives in `AndroidDocumentLongPressSelectionStrategy`. In the drag handle logic we always expand the selection to the character closest to the finger.

**Comment by matthew-carroll** [comment]
@angelosilvestre Ok, sounds good.
