### ISSUE TITLE
[BUG] - Example not working.

### ISSUE THREAD

**Issue by Ansh-Rathod** [superlistapp/super_editor#2124]
Hello! I tried to use the super_editor example but it didn't work. here is the video of the behavior: 

https://github.com/superlistapp/super_editor/assets/67627096/9ba58a5a-82db-4ce9-8488-55ee803a59eb

**Package Version**
Default branch

**User Info**
  individual

**Platform**
  macOS Sonoma 14.3

**Flutter version**
<img width="790" alt="Screenshot 2024-06-23 at 11 34 57 AM" src="https://github.com/superlistapp/super_editor/assets/67627096/2f8434a2-a385-4b7b-836b-0e758b84e3d1">

**Comment by britannio** [comment]
Which commit of super_editor are you running the example from?

**Comment by Ansh-Rathod** [comment]
sorry for posting the update late. I did flutter clean and ran it again, it worked. but the first time when I ran, it was completely broken shown in the video. it was very strange bug! you can close this issue or maybe try to investigate it, and yeah I'm unable to reproduce it.
