### ISSUE TITLE
[BUG] - Exception when pressing space after cancelling action tag

### ISSUE THREAD

**Issue by KevinBrendel** [superlistapp/super_editor#2177]
**Package Version**
super_editor, GitHub, stable branch

**User Info**
coneno, QuikFlow

**To Reproduce**
1. Go to the action tags demo in the example app
2. Write an action tag which does not match any of the options (so that "NO ACTIONS" is displayed)
3. Cancel using escape
4. Press space

**Actual behavior**
An exception is thrown.
<img width="1282" alt="Screenshot 2024-07-19 at 20 43 53" src="https://github.com/user-attachments/assets/f6510616-1d71-4220-aecf-630fe5041272">

**Expected behavior**
A space is inserted and no exception is thrown.

**Platform**
macOS

**Flutter version**
Flutter 3.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0850beeb2 (3 days ago) • 2024-07-16 21:43:41 -0700
Engine • revision 235db911ba
Tools • Dart 3.4.4 • DevTools 2.34.3

**Comment by KevinBrendel** [comment]
This can also happen when the matched tag list was not empty when cancelling.

**Comment by KevinBrendel** [comment]
I have noticed that when this occurs, an `actionTagCancelledAttribution` is added to the end of the composed tag. This attribution is not added there when cancelling the action tag by just continuing to type using space, in which case the exception is also not triggered.

<img width="369" alt="image" src="https://github.com/user-attachments/assets/b199811b-3ebc-4ce3-9acf-f0cba26e0483">

**Comment by matthew-carroll** [comment]
@KevinBrendel can you confirm that this PR solves your problem: https://github.com/superlistapp/super_editor/pull/2191

**Comment by KevinBrendel** [comment]
Yes, I can confirm that it solves the issue, thanks.
