### ISSUE TITLE
[BUG] - MutableDocument.firstOrNull returns lastOrNull

### ISSUE THREAD

**Issue by JostSchenck** [superlistapp/super_editor#2187]
**Package Version**
super_editor, GitHub, stable and main branch

**User Info**
individual, hobby project

**To Reproduce**
To be honest, I did not encounter an error attributable to this yet, but the following code found in super_editor/lib/src/core/editor.dart returns lastOrNull for firstOrNull. If this for some reason is intended, it at least looks like a strange behavior that should be explained in a comment:

https://github.com/superlistapp/super_editor/blob/9bf2d84078f8c79b034e38e7342644701578a140/super_editor/lib/src/core/editor.dart#L1089-L1093

**Comment by matthew-carroll** [comment]
Thanks for filing this. I'll get that switched.
