### ISSUE TITLE
[SuperEditor][Android][iOS] - Add tooling to more easily create keyboard toolbar experiences

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#2209]
Editing text on mobile typically requires a toolbar that sits on top of the keyboard. For more sophisticated editors, it's also common to switch between the software keyboard and a panel with buttons. The panel with buttons takes larger-scale actions on the document - things that don't always apply when editing, and things that might need more room than a little icon on the toolbar.

Let's evaluate what kind of tooling we could provide that makes it faster and easier for apps to setup mobile keyboard editing toolbars and panels.

@angelosilvestre let's begin with ~1hr of investigation into the value we can provide here, the way others are already doing this, how we can/should interact with the keyboard, etc. Then let's use the remaining time to work on the tools.

**Comment by matthew-carroll** [comment]
@Jethro87 do you have any input on this? I know you have a more sophisticated editing toolbar than our demo app.

**Comment by Jethro87** [comment]
@matthew-carroll Much of the original work you did on our "behind keyboard panel" was allowing selection when the keyboard isn't up. As for now, there are a few areas that have become a bit complex:
- Calculating viewInsets in `didChangeDependencies`. This is more boilerplate than complex.
- Sizing the "panel" can get complex with different devices and hardware keyboards. For example, the iPad has a concept of the "mini" keyboard that can be shown when a hardware keyboard is attached. Learning if a software keyboard is visible isn't as simple as looking for bottom viewInsets > 0 in this case. 
- To size our panel correctly, we have to keep track of `Orientation` (portrait or landscape), bottomInsets, maxBottomInsets, and the keyboardState and nonKeyboardState. Again, not necessarily complex, but there are a fair amount of variables to keep track of.
- We also have to remember to set the `openKeyboardOnSelectionChange` imePolicy and appropriate selectionPolicies.

**Comment by matthew-carroll** [comment]
@Jethro87 can you describe those items in terms of reproduction steps so that we can try to cause them/see them?

Also, would you like to provide any code-level recommendations on this PR based on your experience working around those issues?

**Comment by Jethro87** [comment]
@matthew-carroll Thinking about it more, most of the complexity is in properly sizing the panel and knowing whether the software keyboard is open or closed. This gets particularly annoying with iPads, because they have the "mini/floating" keyboard. 

I think the best way to test this would be to run the demo_panel_behind_keyboard on an iPad and then try:
1. Using an Apple Pencil and the "mini" software keyboard
2. Attaching a hardware keyboard

Here's some of the code I've written to try and understand the current state of the software/hardware/mini keyboard on iPad. This is in the "behind keyboard panel" widget itself:

```
// iPad's can "undock" the software keyboard and make it floating.
// This is the size of the floating software keyboard on every iPad model,
// with one additional pixel added to account for rounding errors.
// https://support.apple.com/en-ca/guide/ipad/ipad02663f08/ipados
const double _iPadFloatingSoftwareKeyboardHeight = 362;

// When Apple Pencil is enabled, there is an additional toolbar at the bottom right
// of the screen. This adds 17 pixels to the height of the floating software keyboard.
// I've added one additional pixel to account for rounding errors.
const double _iPadFloatingSoftwareKeyboardWithApplePencilEnabledHeight = 380;

// inside build
final keyboardHeight = MediaQuery.of(context).viewInsets.bottom;

final bottomPositionOffset = calculateBottomPositionOffset(
    keyboardHeight: keyboardHeight,
    screenHeight: widget.screenHeight,
);

// various functions
  /// iPads have a "mini" software keyboard that takes up less space than the full software keyboard,
  /// but more than zero.
  /// This "mini" software keyboard is only shown when a hardware keyboard is attached to the iPad.
  /// This function returns the offset that should be applied to the bottom position of the toolbar
  /// when the "mini" software keyboard is shown.
  double calculateBottomPositionOffset({required double keyboardHeight, required double screenHeight}) {
    if (widget.isIpad) {
      if (widget.maxBottomInsets - keyboardHeight == 0.0) {
        // Typical software keyboards take up > 28% of the screen height.
        // If the keyboard height is <= 20% of the screen height,
        // then we assume that a hardware keyboard is attached and the "mini" software keyboard is being shown.
        if (softwareKeyboardIsNotVisible(keyboardHeight: keyboardHeight, screenHeight: screenHeight)) {
          // While the "mini" software keyboard is shown, the formatting panel is still visible,
          // so we need to offset the bottom position by the height of the formatting panel.
          // This is the same as the height of the "mini" software keyboard.
          return -keyboardHeight;
        }
      }
    }

    // We don't need to offset the bottom position if the device is not an iPad.
    return 0.0;
  }

  bool softwareKeyboardIsNotVisible({required double keyboardHeight, required double screenHeight}) {
    if (widget.isIpad) {
      // The "mini" software keyboard is less than 20% of the screen height.
      // The "floating" software keyboard is a constant 362 pixels.
      // If either of these conditions are true, then we deem that the "normal" software keyboard is not visible.
      // This check allows the formatting panel to size its bottom padding correctly.
      return keyboardHeight <= screenHeight * 0.2 ||
          keyboardHeight == _iPadFloatingSoftwareKeyboardHeight ||
          (keyboardHeight >= _iPadFloatingSoftwareKeyboardWithApplePencilEnabledHeight - 1 &&
              keyboardHeight <= _iPadFloatingSoftwareKeyboardWithApplePencilEnabledHeight);
    }
    return keyboardHeight == 0.0;
  }
```

Additionally, people can attach hardware/bluetooth keyboards to their mobile devices. So when a user triggers my formatting panel with a keyboard attached, I have to choose a size for the panel and can't rely on bottom viewInsets, because they will be zero. In this case, I calculate the screen height and try to get it close to what it would have been if a keyboard wasn't attached and the software keyboard was used:

```
  /// If the software keyboard was not visible before calling _closeKeyboard(),
  /// a hardware keyboard is attached. Expand the panel.
  void _sizeBehindKeyboardPanelForHardwareKeyboardsOnOpen() {
    // [screenHeight] should not be 0. If it is, use a default value.
    final double screenHeight = _screenHeight == 0 ? 844 : _screenHeight;

    double bottomInsets = 0.0;

    // The following values are best guesses for the height of the software keyboard,
    // based on simulating multiple devices.
    if (_isIpad) {
      bottomInsets = _orientation == Orientation.portrait ? screenHeight * 0.286 : screenHeight * 0.43;
    } else {
      bottomInsets = screenHeight * 0.39;
    }

    setState(() {
      _maxBottomInsets = bottomInsets;
    });
  }
```

**Comment by matthew-carroll** [comment]
@justinmc - Can you take a look at the comment above from @Jethro87 and let us know where any of this on Flutter's radar? It sounds like there are a bunch of software keyboard variations that aren't understood at all by Flutter's view insets, or any other Flutter API. Can you confirm that Flutter lacks these insights? Were you guys aware of these variations? Are there any plans account for these details?
