### ISSUE TITLE
[BUG] - [SuperEditor] - Japanese IME input breaks document input

### ISSUE THREAD

**Issue by robertodoering** [superlistapp/super_editor#2218]
**Package Version**
super_editor / latest main at 440a9bcde0904d6f9b3ab3f9bdeea36a14494b90

**User Info**
superlist

**To Reproduce**
1. On macOS, enable Japanese input in the keyboard settings (`Japanese - Romaji` or `Japanese - Kana`) and switch to it (ctrl + space)
2. Run the example app
4. Start typing anything with the Japanese IME active
5. Delete the text using backspace until the node gets removed

**Actual behavior**
Any input is no longer recognized

https://github.com/user-attachments/assets/4a66859a-ee80-43ca-9194-49f3f64bc86a

**Expected behavior**
Typing in the document works as expected

**Platform**
macOS

**Flutter version**
Please list your Flutter and Dart version info. You can find this by running `flutter --version` at the command line.
```
Flutter 3.22.0-16.0.pre.213
Dart 3.5.0 (build 3.5.0-131.0.dev)
```

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll @angelosilvestre
