### ISSUE TITLE
[web] SuperEditor is hijacking browser keyboard shortcuts

### ISSUE THREAD

**Issue by bk-one** [superlistapp/super_editor#226]
Steps to reproduce:
 - go to https://superlist.com/SuperEditor/
 - press CMD+L (on Mac; this is usually to select the URL bar of your browser; at least Safari and Firefox)
 - but nothing happened, the CMD+L command is blocked

Some other cmd shortcuts like CMD+V or CMD+C works though

**Comment by venkatd** [comment]
@matthew-carroll I think you have this resolved in SuperTextField. You let the keyboard event "bubble up" if none of the actions handle it.

CMD+L works for us on SuperTextField Flutter web

**Comment by matthew-carroll** [comment]
@angelosilvestre can you see if this is still an issue?

**Comment by angelosilvestre** [comment]
@matthew-carroll CMD+L is working as expected.

**Comment by matthew-carroll** [comment]
Thanks. I'll close this as completed.
