### ISSUE TITLE
[BUG] -  Web site is not working

### ISSUE THREAD

**Issue by ramakrishna-veli** [superlistapp/super_editor#2311]
Hi super_editor I my self want to use your library but the web site is not working. it's just showing the green screen
![Screenshot 2024-09-12 102058](https://github.com/user-attachments/assets/63ff3f4d-3373-4207-8923-03a673a7053d)

**Comment by Muhammed-Rahif** [comment]
From browser console:
```js
TypeError: Instance of 'minified:ac': type 'minified:ac' is not a subtype of type 'minified:wq'
Another exception was thrown: Instance of 'minified:k8<erased>'
```

**Comment by matthew-carroll** [comment]
Looks like we have duplicates of this. I've assigned #2329 to @angelosilvestre - closing this one as a duplicate.
