### ISSUE TITLE
[SuperTextField] Allow access to SelectableTextState outside of keyboardHandler

### ISSUE THREAD

**Issue by venkatd** [superlistapp/super_editor#232]
Hi @matthew-carroll 

I'm trying to decoupling controller actions from keyboard shortcuts in our SuperTextField because `SelectableTextState` is an argument that I can't easily get a reference to.

For example:
```dart
  void moveCaretHorizontally({
    required SelectableTextState selectableTextState,
    required bool expandSelection,
    required bool moveLeft,
    Map<String, dynamic> movementModifiers = const {},
  }) 
```

Inside of `keyboardHandlers` we have access to `SelectableTextState` so I can easily pass this in to the `TextEditingController`. However, if I want to call `controller.moveCaretHorizontally(...)` in any other situation, I need to somehow get a reference to `SelectableTextState`.

**Comment by matthew-carroll** [comment]
I'm gonna leave a couple notes here:

1. Consider taking a `GlobalKey` into `SuperTextField` that gets connected to `SuperSelectableText`
2. Consider introducing the concept of a "client" in the controller API, similar to `ScrollController`, then the client can set appropriate references on the controller and callers won't need to pass the `SelectableTextState`

Also we need to rename `SelectableTextState` to `SuperSelectableTextState`.

**Comment by matthew-carroll** [comment]
@venkatd it looks like we have sense switched the handlers to receive a `ProseTextLayout` instead of a `State` object. Does this sufficiently handle the original goal of this ticket?

**Comment by venkatd** [comment]
@matthew-carroll yes we can close this ticket.

I've updated our own code to use the new `ProseTextLayout`.
