### ISSUE TITLE
[BUG] - [SuperEditor/SuperTextField] Caret heigh changes when inserting a space at the end of the text

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#2323]
**Package Version**
main branch (36376a5a9cc8569a0c89211c255773f96668e7db)

**User Info**
Superlist

**To Reproduce**
1. Go to `SuperEditor` demo
2. Place the selection at the end of a text node
3. Insert a space

The same happens in the `SuperTextField` demo

**Actual behavior**
Space is added and caret height changes (gets smaller)

**Expected behavior**
Space is added and caret height remains the same

**Platform**
Seems to be in all platforms

**Flutter version**
master

**Screenshots**

https://github.com/user-attachments/assets/a59e847b-c86b-4753-9968-348004083eca

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll @angelosilvestre

**Comment by angelosilvestre** [comment]
This seems to be a Flutter bug. I filed https://github.com/flutter/flutter/issues/155330
