### ISSUE TITLE
[BUG] - quickstart link is broken

### ISSUE THREAD

**Issue by makoConstruct** [superlistapp/super_editor#2330]
this link https://supereditor.dev/super-editor-guides/quickstart 404s
it's linked from here https://supereditor.dev/super-editor/guides/ the blue link, not the one in the sidebar. The one in the sidebar is https://supereditor.dev/super-editor/guides/quickstart/ which works, so I guess that's what that's the intended one.

**Comment by matthew-carroll** [comment]
@angelosilvestre can you update the link in the docs website? Apparently I changed the sidebar URLs but missed one of the links in the content.
