### ISSUE TITLE
[FEATURE] - Allow to configure block node to not be selectable and/or deletable

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#2334]
**Your Info**
Superlist

**User Behavior**
The request is to have a block node that once placed in the document, it can't be selected or deleted by means of keyboard interactions (e.g. pressing backspace/delete).

Perhaps both aspected can be configured separately, i.e. the node should not be selectable but deletable, and vice-versa.

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by matthew-carroll** [comment]
@angelosilvestre please start with this one by seeing if there are any places where a user can intervene to prevent something from being deleted. I'd be interested to first know whether it's currently even possible to prevent deletion of certain nodes (such as by overriding the hardware keyboard handler, and by providing a custom implementation for the IME deletion). If it's possible, I'd like to see how difficult it is. Then we can figure out a way to make this more convenient.

**Comment by matthew-carroll** [comment]
@angelosilvestre can you prioritize this?
