### ISSUE TITLE
[FEATURE] - Update dependencies - uuid, http, linkify

### ISSUE THREAD

**Issue by develocode777** [superlistapp/super_editor#2336]
Hello,

Please update dependencies for packages uuid, http and linkify, I get errors from many libraries that use newer versions of these packages.

used in super editor : uuid ^3.0.3; latest: uuid: ^4.5.0
used in super editor : http ^0.13.1; latest: http: ^1.2.2
used in super editor : linkify ^4.0.0; latest: linkify: ^5.0.0

Thank you

**Comment by matthew-carroll** [comment]
@angelosilvestre please update all our dependencies to the latest version, wherever you can.

If there are non-trivial blockers to upgrade a given dependency, then please note the blocker here, and skip that one.
