### ISSUE TITLE
[SuperEditor][SuperReader][SuperTextField] - Initial magnifier location is wrong on initial press

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#2344]
The magnifier appears in the wrong place, initially.

I found this problem on iOS. It probably happens on Android, but I'm not sure. I found the problem in Super Editor, but I assume it's happening in Super Reader and Super Text Field, too.

Repro steps:

- Types some text on line 1
- Insert a newline down to line 2, ensure the caret is sitting at the start of line 2
- Long-press on a word in line 1

Expected result:
Magnifier appears where finger is pressed

Actual result:
Magnifier appears where the caret sits.

https://github.com/user-attachments/assets/b81ac348-57ee-44af-a761-e9e6f4da2742

**Comment by angelosilvestre** [comment]
@matthew-carroll  I tested this and could not reproduce this issue. I checked out the revision immediately before the scrolling rework PR and I was able to reproduce that issue. It seems that PR fixed this issue.

**Comment by ismail-go** [comment]
I can still reproduce the bug while using SuperReader widget on ios . In the initial magnifier opening the location is wrong.

https://github.com/user-attachments/assets/bfd6bfd7-a644-490e-bd4c-e462ffc1e540

**Comment by matthew-carroll** [comment]
What version of super_editor? What version of Flutter?

**Comment by ismail-go** [comment]
Flutter (Channel stable, 3.29.3, on macOS 15.0.1 24A348 darwin-arm64, locale en-TR) [1,438ms]
    • Flutter version 3.29.3 on channel stable at /Users/ismail/Flutter/Sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea121f8859 (3 weeks ago), 2025-04-11 19:10:07 +0000
    • Engine revision cf56914b32
    • Dart version 3.7.2
    • DevTools version 2.42.3


  super_editor_markdown:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor_markdown

used last version of the super editor.

Padding(
      padding: const EdgeInsets.only(top: 16.0),
      child: SuperEditorUnsliverizer(
        child: SuperReader(
          document: viewModel.doc,
          documentLayoutKey: viewModel.docLayoutKey,
          documentOverlayBuilders: [],
          selectionLayerLinks: viewModel.selectionLayerLinks,
          selectionStyle: defaultSelectionStyle,
          stylesheet: defaultStylesheet.copyWith(
            addRulesAfter: [
              StyleRule(
                BlockSelector.all,
                (document, node) {
                  return {
                    "textStyle": TextStyle(
                      fontFamily: viewModel.project.transcriptionFont.name,
                      color: viewModel.project.transcriptionFontColor,
                      fontSize: viewModel.project.transcriptionSize.size,
                    ),
                    "padding": CascadingPadding.symmetric(horizontal: 16, vertical: 0),
                  };
                },
              )
            ],
          ),
          componentBuilders: [
            TaskComponentBuilder(viewModel.docEditor),
            ...defaultComponentBuilders,
          ],
          gestureMode: viewModel.gestureMode,
        ),
      ),
    );

I am using that widget inside of the CustomScrollView.
@matthew-carroll
