### ISSUE TITLE
Shift+click selection for editor

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#237]
When a user presses shift and taps/clicks on a text position (SuperTextField) or a content position (SuperEditor), the selection should move the extent to that position.

**Comment by AmitPr** [comment]
There's a debate to be had on how shift+click works with double- and triple-clicks. As far as I can tell, there's two possible ways to handle this behavior on desktop:
1. Default double and triple click behavior, even when shift is pressed
  * This would be no change to current double and triple clicking behavior, and is how browsers (or at least, Firefox on my macbook) do things.
2. Double click expands selection to include the entire word at the second position, Triple click collapses the selection back to a the original position (getting rid of the selection).
  * If the second position is in a different paragraph, the triple click expands the selection to include the second position's paragraph.
  * This is how it's done in Visual Studio Code

While the easy (and probably more "expected") behavior is the first option, playing around with how VSCode does it's text selection seems slightly more intuitive to me, although that's just personal opinion.

Thoughts?

**Comment by matthew-carroll** [comment]
The default behavior should probably match what is most commonly found in document editors, e.g., Word, Docs, Medium, etc. While it should be possible to use this package to write code editors, that isn't the default use-case.

Fortunately, package users have the opportunity to completely replace gesture and keyboard interactions, if desired. It's a little bit of work, but not a lot.

**Comment by AmitPr** [comment]
Great, less work to implement it like that anyway :)
