### ISSUE TITLE
Cmd+backspace for editor

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#238]
When the user presses cmd+backspace/cntl+backspace, everything from the current collapsed selection to the beginning of the line should be deleted.

**Comment by venkatd** [comment]
I believe this may be a Mac-only behavior.

On Windows ctrl+backspace deletes to the previous word. Similar to what alt+backspace does on Mac.

**Comment by bk-one** [comment]
keeping the comment from @britannio for reference here: 

When the user presses option+backspace on MacOS or ctrl+backspace on Windows/Linux, everything from the current collapsed selection to the beginning of the word should be deleted.

See https://github.com/flutter/engine/blob/70024475f41a7cb311e721bf10d95354510c57ab/lib/ui/text.dart#L2690-L2700 for the implementation used by EditableText.

**Comment by matthew-carroll** [comment]
@bk-one is this issue duplicated by #479 ?

**Comment by bk-one** [comment]
I believe it is

**Comment by matthew-carroll** [comment]
Ok, I'll close this issue as a duplicate of #479
