### ISSUE TITLE
Add category filters to logger

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#239]
The current logging solution doesn't work well because we get all or nothing.

Implement a robust logging solution.

**Comment by venkatd** [comment]
@matthew-carroll what is your opinion of using the [logging package](https://pub.dev/packages/logging)? It seems like a lot of libraries are using it so we ended up adopting it in our app.

It lets us also set log levels for sub-loggers which takes care of the all or nothing problem.

**Comment by matthew-carroll** [comment]
@venkatd do you have any thoughts about what makes that logging package preferable to others? Are there any shortcomings that you've come across?

**Comment by matthew-carroll** [comment]
@venkatd I'm gonna go checkout some videos/posts about logging and see if I can glean any general insights. I've never seen any good education on useful logging, so I guess now is the chance to try to figure it out. Feel free to jump in with any insights you may have.

**Comment by venkatd** [comment]
@matthew-carroll Happy to do a quick run-through of our logging setup on our next call

The reasons we settled on the logging package:
- Logging is pretty fragmented and the official one seems to have the most usage
- It's unopinionated on what you can log (any `Object`) and unopinionated on how to output the logs (could log to console, to a file, in memory to display a UI of the logs)
- If you enable hierarchical logging, you can configure the logging levels per logger so you can get pretty granular with what you turn on/off.

For expensive log operations you can pass in a callback like `_logger.fine(() => expensiveToString(obj))` so things will never get evaluated unless they're logged out.

We've hand-rolled a small widget in our app that serves as a frontend to the logger:

You can modify the levels at runtime:
![image](https://user-images.githubusercontent.com/220686/121787562-56f9bf00-cb8c-11eb-895b-dd33c71390b1.png)

Based on the type of the object that is logged, we may render different widgets to make the output easier to read:
![image](https://user-images.githubusercontent.com/220686/121787591-87415d80-cb8c-11eb-94eb-cf32319c7b09.png)

**Comment by bk-one** [comment]
@matthew-carroll where do we stand on this?

**Comment by matthew-carroll** [comment]
We're using the `logging` package. We've created a number of different loggers. We're still in the process of removing the old logging system, but we can close this.
