### ISSUE TITLE
[SuperEditor] - Add empty paragraph at the end of document when tapping on the empty area below it

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#2395]
**Your Info**
Superlist

**User Behavior**
When a user taps on the empty area below the document content, it will place the selection at the nearest position, ignoring any node that is configured as being visually non-selectable.

Instead, we would like to add an empty paragraph at the end. If the last node is already empty paragraph, then just place the selection there.

Since one option is not necessarily better than the other, just different, maybe `SuperEditor` can offer a way for the client code to implement a custom behaviour or offer a configuration field when the client code pick one or the other option.

**Feature Value**
The behaviour as described in this ticket is usual in tools like Notion, and is for users used to such tools the expected behaviour.

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by matthew-carroll** [comment]
I think it'll take a bit of thought to figure out how this should reasonably be integrated such that it's not a forced behavior. I'm trying to think where such an option might live without it feeling like a random add on. I'm not sure, yet.

@angelosilvestre any thoughts from your end?

**Comment by matthew-carroll** [comment]
Maybe this could be a reaction? Check for an attempt to move selection to the end of the document in an unselectable node, and then insert a new paragraph? That would be pluggable and wouldn't need to effect anyone who doesn't want it...

Thoughts everyone?

**Comment by angelosilvestre** [comment]
@matthew-carroll A reaction sounds reasonable to me.

**Comment by matthew-carroll** [comment]
@angelosilvestre can I assign this to you? Do you wanna give it a try?

**Comment by angelosilvestre** [comment]
@matthew-carroll Yeah, sure.
