### ISSUE TITLE
Fix marketing website compilation errors

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#240]
The marketing website still references `SelectableText` rather than `SuperSelectableText`.

Update the references so that CI passes again.

**Comment by salihgueler** [comment]
Duplicate of: https://github.com/superlistapp/super_editor/issues/230 ?

**Comment by matthew-carroll** [comment]
Looks like it. I'll close #230 because this ticket includes the reason for the build failure.
