### ISSUE TITLE
[BUG] - getDocumentPositionAfterExpandedDeletion with collapsed selection on block node returns TextPosition

### ISSUE THREAD

**Issue by knopp** [superlistapp/super_editor#2431]
Can be easily reproducible. The position should be `UpstreamDownstreamNodePosition` but is `TextPosition` instead.

```dart
test("getDocumentPositionAfterExpandedDeletion on block node", () {
  final node = HorizontalRuleNode(
    id: "1",
  );
  final document = MutableDocument(nodes: [
    node,
  ]);
  final selection = DocumentSelection.collapsed(
    position: DocumentPosition(
      nodeId: node.id,
      nodePosition: node.endPosition,
    ),
  );
  final position = CommonEditorOperations.getDocumentPositionAfterExpandedDeletion(
    document: document,
    selection: selection,
  );
  expect(position is UpstreamDownstreamNodePosition, isTrue);
});
```

**Comment by angelosilvestre** [comment]
@matthew-carroll @knopp `CommonEditorOperations.getDocumentPositionAfterExpandedDeletion` assumes that if a block node is being deleted, what actually happens is that the block node is converted to a `ParagraphNode`. That's why it returns a `TextNodePosition`.

@knopp Are you guys doing something different when deleting a block node?

**Comment by knopp** [comment]
@angelosilvestre, I updated the example. The original example was wrong - in that case the node would indeed be converted to paragraph. The problem we're having is collapsed selection at the end of block node. In which case there is no deletion happening, so the selection should probably remain same.

**Comment by angelosilvestre** [comment]
> The problem we're having is collapsed selection at the end of block node. In which case there is no deletion happening.

@knopp To confirm, is this node marked as non-deletable?

> The problem we're having is collapsed selection at the end of block node

If the node is non-deletable, then a collapsed or expanded selection would have the same effect. Are you using a custom command handler? I'm asking this because the built-in `DeleteSelectionCommand` already checks if it can't delete any nodes, and if that's the case it does not change the selection.

**Comment by knopp** [comment]
The node is deletable. But deleting collapsed selection should be noop. I think [here](https://github.com/superlistapp/super_editor/blob/d5d0f8da1e4dc9a9d300e54d295b218581054707/super_editor/lib/src/default_editor/multi_node_editing.dart#L1224) where the selection is changed despite being collapsed. I can double check tommorrow.

**Comment by angelosilvestre** [comment]
So maybe it's more appropriate to make `CommonEditorOperations.getDocumentPositionAfterExpandedDeletion` return `null` if the selection is collapsed.

**Comment by matthew-carroll** [comment]
> So maybe it's more appropriate to make CommonEditorOperations.getDocumentPositionAfterExpandedDeletion return null if the selection is collapsed.

@angelosilvestre `null` rarely makes sense for a selection. It means there is none - not even a caret. If the user passes a collapsed selection, why wouldn't you return that same selection?

**Comment by angelosilvestre** [comment]
@matthew-carroll `CommonEditorOperations.getDocumentPositionAfterExpandedDeletion` returns the new selection after an expanded deletion. If no deletion would occur I think it makes sense to return `null`, indicating that the selection shouldn't change. When all nodes in range are non-deletable, `CommonEditorOperations.getDocumentPositionAfterExpandedDeletion` already returns `null`. 

To keep consistency, we should either make both cases return `null` or both cases return the current selection.

**Comment by matthew-carroll** [comment]
> To keep consistency, we should either make both cases return null or both cases return the current selection.

Ok, we can try using `null` for both. I think that might result in a lot of needless if-statements, but we can see what happens.
