### ISSUE TITLE
Replace Color.withOpacity with Color.withValues

### ISSUE THREAD

**Issue by angelosilvestre** [superlistapp/super_editor#2437]
The CI is failing on the super_text_layout analysis due to `Color.withOpacity` being deprecated:

```console
Analyzing super_text_layout...                                  

   info • 'withOpacity' is deprecated and shouldn't be used. Use .withValues() to avoid precision loss • example/lib/main.dart:254:71 • deprecated_member_use
   info • 'withOpacity' is deprecated and shouldn't be used. Use .withValues() to avoid precision loss • example/lib/main.dart:4[8](https://github.com/superlistapp/super_editor/actions/runs/12129129760/job/33816940663?pr=2436#step:5:9)4:21 • deprecated_member_use
   info • 'withOpacity' is deprecated and shouldn't be used. Use .withValues() to avoid precision loss • example/lib/main.dart:502:30 • deprecated_member_use
   info • 'withOpacity' is deprecated and shouldn't be used. Use .withValues() to avoid precision loss • lib/src/caret_layer.dart:182:42 • deprecated_member_use
```

The migration guide is described here: https://docs.flutter.dev/release/breaking-changes/wide-gamut-framework#opacity

**Comment by angelosilvestre** [comment]
cc @matthew-carroll

**Comment by matthew-carroll** [comment]
Are you recommending that we update the code? Or are you filing this for the future?

**Comment by angelosilvestre** [comment]
I'm recommending that we update the code to make the analysis pass in the CI

**Comment by matthew-carroll** [comment]
Is this change on stable?

**Comment by angelosilvestre** [comment]
It's only on master at this moment.

**Comment by matthew-carroll** [comment]
Then we probably shouldn't do that, right? How would we ensure that we keep those changes away from `stable` if we happen to make changes to those same files in the meantime?

**Comment by angelosilvestre** [comment]
We could wait until this change lands on `stable`. We should get a new stable release soon.

**Comment by angelosilvestre** [comment]
@matthew-carroll It seems this change landed on stable.

**Comment by richanshah** [comment]
i am getting issue on Xcode build if I do this change with latest flutter version 3.27.0. 

Error (Xcode): 
 Error: The method 'withValues' isn't defined for the class 'Color'.


Encountered error while building for device.

**Comment by angelosilvestre** [comment]
@richanshah Did you tried running a `flutter clean` on your project? Maybe this is a cache issue.

**Comment by richanshah** [comment]
@angelosilvestre I  got the issue, issue was that, I have fvm in my project. and in ios root path in build setting it was taking 3.24.0 instead of 3.27.0. now it works. thanks. closing the issue.
