### ISSUE TITLE
[SuperTextField] entering/finding text in tests seems not possible

### ISSUE THREAD

**Issue by jvelezos** [superlistapp/super_editor#263]
testing with .enterText or find.text seems not possible since they use Text and EditableText

`setUpUI((tester) async {
          await tester.enterText(find.byType(SuperTextField), '');
          await tester.pump();
        });`

or
 
`testUI('then the task title is displayed', (tester) async {
          expect(find.text(newTitle), findsOneWidget);
        });`

**Comment by britannio** [comment]
`find.text` uses https://github.com/flutter/flutter/blob/master/packages/flutter_test/lib/src/finders.dart#L550-L571 which searches for a `Text` or `EditableText` widget. 

This package could declare an extension on `CommonFinders` so you could instead write:
```dart
expect(find.superText(), findsOneWidget);
```

**Comment by bk-one** [comment]
@jvelezos we discussed this with @jamessuperlist - please close this ticket if not relevant anymore, otherwise please update description.

**Comment by matthew-carroll** [comment]
We're in the process of introducing various testing tools for `SuperEditor` and `SuperTextField`. This is a broad issue, but it will be solved incrementally as we go, so I'm going to close this ticket.
