### ISSUE TITLE
Listeners to Document Transactions

### ISSUE THREAD

**Issue by jhlabs** [superlistapp/super_editor#269]
# Background

I want to store individual nodes of a SuperEditor `Document` in a database. I have explained more about my required use case in this discussion https://github.com/superlistapp/super_editor/discussions/265.

# Problem
To be able to synchronize changes of the in-memory nodes in a `MutableDocument` back to the database, I need to be able to listen to the transactions committed to the document. I need to be able to trigger a method based on when a node was inserted, replaced, deleted, and updated.

Currently, only updating a node is not implemented as a transaction. Is this planned as part of the undo/redo functionality?

And how do I listen to when transactions happened to a `MutableDocument`? I tried manually overriding the classes of the `super_editor` package. It is tedious and not a great solution for anyone that ones to stay up to date with this package.

I would be happy to contribute code as well but would need some guidance on how to implement such listeners. It seems that this will be a very common use case for many consumers of this library.

**Comment by matthew-carroll** [comment]
I commented on the linked the discussion. This work is blocked on our undo/redo implementation, which is our next priority after mobile support.

**Comment by bk-one** [comment]
@jhlabs We're currently working on this, if this is still relevant, feel free to join us on slack to discuss the details of our implementation.

**Comment by HayesGordon** [comment]
Hi @bk-one, I'm really interested in this as well.

Something that would be nice to add in the interim is serialization for individual nodes, instead of the whole document.

**Comment by bk-one** [comment]
@HayesGordon Happy to demonstrate the status quo - it does sync only changed nodes on the data layer, there are still some aspects required to also allow surgical updates to the in-memory document that SuperEditor is rendering. But we're getting there. I guess a package is at least another two or three months away, though.

**Comment by Mijawel** [comment]
Interested in this as well. Pretty much identical motivation to jhlabs. Just wondering if any progress has been made?

**Comment by matthew-carroll** [comment]
I'm in the middle of reworking the editor API to work with requests, commands, and events, which will serialize all changes in a central location. We should take another look at this issue after those APIs are available.

**Comment by Mijawel** [comment]
Just a heads up for anyone who is interested, I have put together an example project that implements discrete change notifications for super_editor as well as serialization of DocumentNodes to Map<String,dynamic> so that changes can be saved and reflected on Firebase (or for whatever purpose someone might require).

https://github.com/Mijawel/super_editor_serialization_and_notifier

Feel free to let me know if there are any issues here or something that could be improved!

**Comment by matthew-carroll** [comment]
@jhlabs We've added an edit pipeline to `SuperEditor`, which we also refer to as "atomic commands". As part of that pipeline, we've introduced listeners that are notified of changes at the end of the pipeline. We've also introduced `EditReaction`s which are notified of changes, and given an opportunity to make additional changes in response.

If you're still using `SuperEditor`, can you try these tools and let me know if they've resolved your issue? If you're not longer using `SuperEditor`, please let me know that, too, and I'll close this ticket with the assumption that it's resolved.

**Comment by matthew-carroll** [comment]
Closing due to non-response.
