### ISSUE TITLE
Incorrect Windows CTRL + Arrow Keys behavior

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [superlistapp/super_editor#275]
On web on Windows, the <kbd>CTRL</kbd> + arrow key behavior is incorrect.

This is what tapping the left arrow key + control **should** look like:

![image](https://user-images.githubusercontent.com/19204050/127349085-4b5fe3f9-948b-42d5-96fb-9f48a0363d5e.png)

And this is what it looks like in SuperEditor:

![image](https://user-images.githubusercontent.com/19204050/127349218-9e3b9b67-2e87-42e3-a026-2e1dc383c8b0.png)

The behavior that SuperEditor executes on CTRL + left arrow key should actually happen for <kbd>Pos1</kbd> or <kbd>Home</kbd> + left arrow key instead.

---

* CTRL + arrow key should select the next / previous word.
* Pos1 + arrow key should select the end / beginning of the line.

**Comment by bk-one** [comment]
@creativecreatorormaybenot I assume this is still an issue? If so, we're going to tackle it soon - please confirm.

**Comment by matthew-carroll** [comment]
@creativecreatorormaybenot can you try again with the latest version of `super_editor`? We recently merged some PRs related to word/line selection.

Also, can you explain which key `Pos1` refers to?

**Comment by creativecreatorormaybenot** [comment]
@matthew-carroll I tried it at https://superlist.com/SuperEditor/ again and it is still the same (broken) behavior.

`Pos1` is the `Home` key on (maybe German) Windows keyboards. I cannot see `Pos1` on my keyboard either, but I mean the button that says `Home`.

**Comment by matthew-carroll** [comment]
@creativecreatorormaybenot the version on the website shouldn't be used for any verification. Please use the example app in the repo on the `main` branch.

**Comment by creativecreatorormaybenot** [comment]
@matthew-carroll The `super_editor/example` app does not compile on any Flutter channel:

```
lib/demos/flutter_features/textinputclient/basic_text_input_client.dart:39:7: Error: The non-abstract class '_BareBonesTextFieldWithInputClientState' is missing implementations for these members:
 - TextInputClient.insertTextPlaceholder
 - TextInputClient.removeTextPlaceholder
 - TextInputClient.showToolbar
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _BareBonesTextFieldWithInputClientState extends State<_BareBonesTextFieldWithInputClient>
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../flutter/flutter/packages/flutter/lib/src/services/text_input.dart:1124:8: Context: 'TextInputClient.insertTextPlaceholder' is defined here.
  void insertTextPlaceholder(Size size) {}
       ^^^^^^^^^^^^^^^^^^^^^
../../../../flutter/flutter/packages/flutter/lib/src/services/text_input.dart:1127:8: Context: 'TextInputClient.removeTextPlaceholder' is defined here.
  void removeTextPlaceholder() {}
       ^^^^^^^^^^^^^^^^^^^^^
../../../../flutter/flutter/packages/flutter/lib/src/services/text_input.dart:1116:8: Context: 'TextInputClient.showToolbar' is defined here.
  void showToolbar() {}
       ^^^^^^^^^^^
../lib/src/default_editor/document_input_ime.dart:56:7: Error: The non-abstract class '_DocumentImeInteractorState' is missing implementations for these members:
 - TextInputClient.insertTextPlaceholder
 - TextInputClient.removeTextPlaceholder
 - TextInputClient.showToolbar
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _DocumentImeInteractorState extends State<DocumentImeInteractor> implements DeltaTextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../flutter/flutter/packages/flutter/lib/src/services/text_input.dart:1124:8: Context: 'TextInputClient.insertTextPlaceholder' is defined here.
  void insertTextPlaceholder(Size size) {}
       ^^^^^^^^^^^^^^^^^^^^^
../../../../flutter/flutter/packages/flutter/lib/src/services/text_input.dart:1127:8: Context: 'TextInputClient.removeTextPlaceholder' is defined here.
  void removeTextPlaceholder() {}
       ^^^^^^^^^^^^^^^^^^^^^
../../../../flutter/flutter/packages/flutter/lib/src/services/text_input.dart:1116:8: Context: 'TextInputClient.showToolbar' is defined here.
  void showToolbar() {}
       ^^^^^^^^^^^
../lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart:30:7: Error: The non-abstract class 'ImeAttributedTextEditingController' is missing implementations for these members:
 - TextInputClient.insertTextPlaceholder
 - TextInputClient.removeTextPlaceholder
 - TextInputClient.showToolbar
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ImeAttributedTextEditingController
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../flutter/flutter/packages/flutter/lib/src/services/text_input.dart:1124:8: Context: 'TextInputClient.insertTextPlaceholder' is defined here.
  void insertTextPlaceholder(Size size) {}
       ^^^^^^^^^^^^^^^^^^^^^
../../../../flutter/flutter/packages/flutter/lib/src/services/text_input.dart:1127:8: Context: 'TextInputClient.removeTextPlaceholder' is defined here.
  void removeTextPlaceholder() {}
       ^^^^^^^^^^^^^^^^^^^^^
../../../../flutter/flutter/packages/flutter/lib/src/services/text_input.dart:1116:8: Context: 'TextInputClient.showToolbar' is defined here.
  void showToolbar() {}
```

**Comment by matthew-carroll** [comment]
@justinmc - Did Flutter end up shipping those new text input client APIs to stable?

**Comment by creativecreatorormaybenot** [comment]
@matthew-carroll I was able to build now.

The current behavior is now _completely_ broken as in `CTRL`, `Home`, and `End` have no effect at all on Windows. It behaves as if I was just pressing the arrow keys.

**Comment by matthew-carroll** [comment]
@chimon2000 can you take a look at this behavior on Windows and see if you can determine what we should do to support this ticket?

**Comment by chimon2000** [comment]
@matthew-carroll what i am seeing on Windows:
- CTRL + Arrow keys cursor navigates to the end of the line
- ALT + Arrow Keys cursor navigates to the end of the next word

In both cases, the text is not selected.

**Environment**

Windows 11
Flutter 3.0

**Comment by matthew-carroll** [comment]
@chimon2000 I think @creativecreatorormaybenot was referring to the HOME and END keys. Can you two align on what the specific issue is here?

**Comment by chimon2000** [comment]
@creativecreatorormaybenot can you please describe the behavior that you are expecting for CTRL, Home, and End.

**Comment by bk-one** [comment]
@chimon2000 please also see https://github.com/superlistapp/super_editor/issues/351#issuecomment-1124525304 for HOME/END/PgUp/PgDwn

**Comment by creativecreatorormaybenot** [comment]
@chimon2000 I tested on *web* on Windows.

**Comment by matthew-carroll** [comment]
@creativecreatorormaybenot - which browser were you using?

**Comment by creativecreatorormaybenot** [comment]
@matthew-carroll `flutter run -d chrome`

**Comment by matthew-carroll** [comment]
@angelosilvestre it looks like we mis-implemented the Windows behavior for skipping a word. I think that we probably used the same behavior across Mac and Windows, which uses `alt`. This was a mistake. On Windows, we want to check for the `ctrl` key to skip a word.

Can you update the implementation to use `ctrl` for word-skipping on Windows, instead of `alt`? Can you also add appropriate tests for both the Mac and Windows versions of word skipping?
