### ISSUE TITLE
SuperTextField Caret stays hidden when typing starts during a blink animation

### ISSUE THREAD

**Issue by venkatd** [superlistapp/super_editor#301]
@matthew-carroll we're willing to sponsor prioritizing an enhancement here.

Steps to reproduce:
- Focus on a SuperTextField
- Wait for the caret to disappear, start typing immediately
- If you keep typing, the caret stays hidden

Expected behavior
The caret should stay visible while typing and the animation should restart once done typing.

I suppose if we reset the animation after each change, it could accomplish the behavior.

**Comment by matthew-carroll** [comment]
Sounds good. Can this wait until we merge mobile text field support to avoid conflicts?

**Comment by venkatd** [comment]
@matthew-carroll yes can definitely wait

**Comment by bk-one** [comment]
I guess this one is a duplicate https://github.com/superlistapp/super_editor/issues/318

**Comment by venkatd** [comment]
Looks like this is resolved on the latest
