### ISSUE TITLE
Numbered list is automatically created when typing a 1 at the beginning of a line

### ISSUE THREAD

**Issue by MarcelKaeding** [superlistapp/super_editor#339]
Reproducible on https://superlist.com/SuperEditor/

Current behavior: As soon as you start a line of text with "1" followed by a blank space, it will create a numbered list.

Expectation: A numbered list should get created if I type "1." followed by a blank space, similar to how it works for example in Apple Notes

![Kapture 2021-11-02 at 16 44 59](https://user-images.githubusercontent.com/1116227/139880922-43c186c6-f3a1-4630-a69d-a67cff261431.gif)

**Comment by matthew-carroll** [comment]
We can change this to match the desired behavior for now, but the more appropriate request is that the policy should be configurable. Most apps also interpret "1) " as the beginning of a list, too. But it should be up to the developer.

**Comment by matthew-carroll** [comment]
@wilsonowilson - would you like to give this change a try as a tiny step towards working on super_editor?

**Comment by wilsonowilson** [comment]
Sure! I'll work on this one in a bit
