### ISSUE TITLE
SuperTextField does not seem to call buildTextSpan. How to add a widget inline?

### ISSUE THREAD

**Issue by jamessuperlist** [superlistapp/super_editor#340]
A `TextEditingController` can be subclassed to override `buildTextSpan` in order to build a custom `TextSpan` (i.e. icon before or after the text).

When I subclassed `AttributedTextEditingController` and added the instance to `SuperTextField`, I noticed that `buildTextSpan` was not called. When looking closer into the code, it does not seem that `AttributedTextEditingController` calls `buildTextSpan` at all.

How should one go about prepending/appending a widget inline with `SuperTextField`?

**Comment by matthew-carroll** [comment]
Are we definitely talking about `SuperTextField`? We had a recent discussion about this behavior with text components in an editor. So you're looking for inline widgets in `SuperEditor` and `SuperTextField`?

**Comment by jamessuperlist** [comment]
@matthew-carroll Yes, these are two separate requests. 

With regard to `SuperTextField`, it was determined that when `AttributedText` is extended with an instance passed into `AttributedTextEditingController`, then `computeTextSpan` of extended `AttributedText` can be overriden.

```
class MyAttributedText extends AttributedText ....

MyAttributedText attributedText = MyAttributedText('MyText');
AttributedTextEditingController controller = AttributedTextEditingController(text: attributedText)
```
