### ISSUE TITLE
Errors appearing to run the Example App

### ISSUE THREAD

**Issue by JaveedIshaq** [superlistapp/super_editor#347]
Kindly help while running the example app following errors are appearing

1===
File: example/lib/demos/flutter_features/textinputclient/barebones_ios_text_input_client.dart
line: 197
Error:
The name 'TextEditingDelta' isn't a type so it can't be used as a type argument.
Try correcting the name to an existing type, or defining a type named 'TextEditingDelta'.

2===
File : example/lib/demos/flutter_features/textinputclient/basic_text_input_client.dart
line: 197
Error:
The name 'TextEditingDelta' isn't a type so it can't be used as a type argument.
Try correcting the name to an existing type, or defining a type named 'TextEditingDelta'.

3===
File: lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart
line: 31
Error:
Classes and mixins can only implement other classes and mixins.
Try specifying a class or mixin, or remove the name from the list.

4===
File: test/src/infrastructure/super_textfield/ime_attributed_text_editing_controller_test.dart
line: 17
Error:
The name 'TextEditingDeltaInsertion' isn't a class.
Try correcting the name to match an existing class.

**Comment by osaxma** [comment]
You may need to be in the latest `master` channel for flutter. 

Latest `super_editor` would not work with the stable channel since TextEditingDeltas are not implemented there yet.

**Comment by JaveedIshaq** [comment]
thanks, @osaxma  changing to flutter channel master, has resolved the issues, thanks for your kind response.
