### ISSUE TITLE
Pressing escape key replaces selected text with a space character

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#350]
Steps to reproduce:
* Run super_editor's demo app on macOS
* Select any piece of text (single character, multiple characters, multiple words, etc.)
* Press escape key

Expected: either collapse selection or do nothing (seen both behaviors in different tools)
Actual: selected text is replaced by a space `" "`
https://user-images.githubusercontent.com/31278849/141998731-3add3127-ebaa-4a51-b68c-1cb9643e7e05.mov

Note: on web nothing happens when pressing escape.

**Comment by bk-one** [comment]
@miguelcmedeiros dito

**Comment by miguelcmedeiros** [comment]
Still an issue in SuperEditor. 
For Superlist we implemented on our side one of the two proposed behaviours (collapse selection).

@matthew-carroll, in case SuperEditor should adopt the same behaviour by default, I can open a PR with it.

**Comment by matthew-carroll** [comment]
@miguelcmedeiros  Let's have Escape collapse the selection. 

@ThangVuNguyenViet would you like to take on this ticket? When the ESC key is pressed on a hardware keyboard, a `SuperEditor` should respond by collapsing an expanded selection, or doing nothing if the selection is already collapsed. This change should include appropriate tests.

**Comment by ThangVuNguyenViet** [comment]
@matthew-carroll sure, I'd love to work on this
