### ISSUE TITLE
Consider adding SuperEditor tests to Flutter Customer Test Registry

### ISSUE THREAD

**Issue by osaxma** [superlistapp/super_editor#361]
I believe it's a good idea to add SuperEditor tests to the [Flutter Customer Test Registry](https://github.com/flutter/tests) once they're fully written. This is especially important since SuperEditor uses low level APIs which sometimes change without following the [deprecation policy](https://docs.flutter.dev/resources/compatibility#deprecation-policy).   

> What is Flutter Customer Test Registry?
>
> This repository contains references to tests (in the `registry` directory) that are run with every commit to Flutter to verify that no breaking changes have been introduced (in the "customer_testing" shards). The tests referenced by this repository are typically maintained by people outside of the Flutter team, as part of the development of their applications. They are intended to give the Flutter team visibility into how their changes affect real-world developers using Flutter.

**Comment by bk-one** [comment]
That's a very valid suggestion - the question is, do we already know what kind of tests that should be? @matthew-carroll I would like to discuss this on our next call - and happy to help out with the heavy lifting of writing the tests. But if we're planning another release soon, we should try to tie that to the flutter test registry.

**Comment by matthew-carroll** [comment]
@bk-one we have about 300 tests, and more are added as I go.

**Comment by bk-one** [comment]
Ah, I wasn't aware that we're already submitting tests to the Flutter Customer Test Registry.

**Comment by matthew-carroll** [comment]
Sorry, I just meant that we have a lot of tests, so we probably don't need a concerted "test writing" effort. However, they're not yet submitted to the registry. Submitting them has been on my mind for a while. I think we need to breakdown the project first, e.g., create sub-projects for `attributed_text`, `super_selectable_text`, etc.

**Comment by matthew-carroll** [comment]
We added this whole mono-repo to Flutter's test registry a while ago. Closing this as complete.
