### ISSUE TITLE
Caret misplacement on SuperTextField when building app in profile/release mode

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#369]
Steps to reproduce:
* Build SuperEditor demo app in profile (or release) mode
* Go to SuperTextField demo
* Open "Single-line demo"

**Actual:**
https://user-images.githubusercontent.com/31278849/146419323-ee7faa60-4ace-44d6-b41e-f0a6217aeb01.mov

**Expected:** caret is placed properly

**Comment by matthew-carroll** [comment]
Here are some updates based on my investigation:

The root of the difference between running in debug mode and running in profile/release mode is that `assert`s are ignored in profile/release mode. For example, here is Flutter's implementation for calculating caret height:

```dart
Offset getOffsetForCaret(TextPosition position, Rect caretPrototype) {
    assert(!debugNeedsLayout);
    _layoutTextWithConstraints(constraints);
    return _textPainter.getOffsetForCaret(position, caretPrototype);
}
```

In debug mode, when `debugNeedsLayout` is `true`, this method throws an exception. super_editor's caret placement code catches that exception and schedules another build on the next frame to give the `RenderParagraph` an opportunity to finish its layout.

In profile/release mode, the above `assert` doesn't do anything. Instead a measurement is carried out, anyway. In our case, that measurement consistently results in a text width that's too short to fit the last word on the line. The text layout thinks the last word on the line is wrapped to a second line, which then results in the buggy placement of the caret below the line of text.

I have a hack that resolves this issue in the short term. The hack is to force the caret offset to be the same for at least 2 frames before drawing the caret. In other words, store the offset, draw nothing, schedule another frame, compare the offset again, if the offset hasn't changed, then draw the caret.

This hack causes the caret to blink in and out as the user types, but given that carets naturally blink, anyway, I think this side effect is probably acceptable.

I'll put up a PR with the hack and then file a followup ticket to find a deeper solution.

**Comment by matthew-carroll** [comment]
I filed #370 to find a deeper solution to this.
