### ISSUE TITLE
Spike: create minimal editor that implements selection and editing across components.

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#38]
Create minimal editor that implements selection and editing across components.

Do not worry about the document model.

The goal is to figure out where and how to delegate input in a way that allows arbitrary components to participate in input, selection, deletion, and eventually things like drag-and-drop.

**Comment by bk-one** [comment]
@matthew-carroll I think this can be closed?

**Comment by matthew-carroll** [comment]
Yeah. Closing.
