### ISSUE TITLE
Add cursor style support for SuperTextField

### ISSUE THREAD

**Issue by salihgueler** [superlistapp/super_editor#383]
Right now `SuperTextField` keeps the cursor style as a private value in the `SuperTextFieldGestureInteractor` as follows

```
final _cursorStyle = ValueNotifier<MouseCursor>(SystemMouseCursors.basic);
```

This causes the `SuperTextField` to only have the basic cursor if there isn't any text. On the other hand, as a user, I would expect to have a different cursor indicator time to time. 

Therefore I would suggest to add the basic cursor style to the SuperTextField as a field with default value of `SystemMouseCursors.basic` and give users a chance to change the cursor.

**Comment by matthew-carroll** [comment]
Based on the discussion in the associated PR, the root problem for this issue is unclear, and without further investigation, we shouldn't make any changes to this behavior. I'm going to move this ticket to the next milestone so that we're not holding up the mobile release.

**Comment by matthew-carroll** [comment]
@miguelcmedeiros do you remember what you wanted to do with this? Did you want the text-style cursor whenever the user hovers over a `SuperTextField`, regardless of whether it's hovering over text? If so, did you think it was important to make that choice customizable, or should we make it a default and unchangeable behavior?

**Comment by miguelcmedeiros** [comment]
@matthew-carroll 
I can't think of a case where the cursor should be different than the text-style when hovering the text field container. 

My proposal is to make have the cursor as text-style by default when hovering the text field container and not making it configurable.
