### ISSUE TITLE
Selection highlight when the node has no content is not supported for all text components

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#386]
Currently it is possible to control whether a thin selection highlight when the node has not content, but only by setting it directly in `TextComponent`, `TextWithHinComponent` or `SuperSelectableText`. `OrderedListItemComponent`, `UnorderedListItemComponent` and `BlockquoteComponent` currently don't support this preference.

Aside from being able to set this preference per component, it would be great to set this preference for the whole document as well.

**Comment by matthew-carroll** [comment]
@miguelcmedeiros do you know if this is fixed now, or is it still a problem?

**Comment by miguelcmedeiros** [comment]
@matthew-carroll 
Just checked and some components were missing some wiring to make it work. 
Opened a PR to fix it.
