### ISSUE TITLE
Option+backspace should delete an upstream word

### ISSUE THREAD

**Issue by britannio** [superlistapp/super_editor#387]
When the user presses option+backspace on MacOS or ctrl+backspace on Windows/Linux, everything from the current collapsed selection to the beginning of the word should be deleted. 

Similar to https://github.com/superlistapp/super_editor/issues/238

See https://github.com/flutter/engine/blob/70024475f41a7cb311e721bf10d95354510c57ab/lib/ui/text.dart#L2690-L2700 for the implementation used by `EditableText`.

**Comment by bk-one** [comment]
duplicate of #238

**Comment by bk-one** [comment]
@britannio true, but I assume it will be fixed in one go - but that's why I kept your remark in the other ticket.
