### ISSUE TITLE
Numbered list UI breaks as soon as you have double digit numbers

### ISSUE THREAD

**Issue by MarcelKaeding** [superlistapp/super_editor#402]
https://user-images.githubusercontent.com/1116227/151376205-2a1a16fe-66cb-4865-83f7-e8cb56746e14.mp4

- enter a number list using:
1.
2.
3.
etc
- as soon as you reach 10, you'll see the numbers shift their position on the line

**Comment by matthew-carroll** [comment]
I just checked Notion to see how they deal with this. It looks like Notion sets aside a fixed width for the list item number. If you get to "1000" in a Notion list, that number pushes into the list item content text.

I think I'm gonna do something similar here. The difficulty with offering an adjustable space for the number is that every item in the list will need to check every other number in the list to figure out how wide to make the space for the list item number. In practice, if we can fit up to "999" then we probably don't need to worry about bigger numbers.

**Comment by MarcelKaeding** [comment]
@MarcelKaeding can you double check this please, just to make sure text and numbers are correctly aligned with each other?
<img width="215" alt="Screenshot 2022-02-04 at 11 20 34" src="https://user-images.githubusercontent.com/1116227/152512745-5817507f-ffb5-4711-b0c0-967bf6d2ebc9.png">
