### ISSUE TITLE
Auto link URLs in Sample Editor

### ISSUE THREAD

**Issue by bk-one** [superlistapp/super_editor#406]
As a user, if I paste an URL into the editor, I expect that URL to be automatically converted (attributed) to be a link. This should be added to the sample editor.

**Comment by ThangVuNguyenViet** [comment]
Hi @matthew-carroll , I would love to work on this. As I understood, this requires getting the text from the clipboard, then checking for a valid url. If it is, then add the LinkAttribution to the attributions set of the to be inserted text.

For validating the url, I'll check if it has a scheme, as it is quite similar to what google doc is doing I think

**Comment by matthew-carroll** [comment]
@ThangVuNguyenViet would you like me to assign this ticket to you as well?

`super_editor` already supports link attributions, and I think it supports link recognition, too, so there must be something special about this situation. If you want to work on this, you should start by inspecting the existing code related to links to make sure you don't re-implement existing behavior.

**Comment by ThangVuNguyenViet** [comment]
@matthew-carroll could you specify what's link recognition? Does that mean converting an URL text into a link on typing and/or copying?

**Comment by matthew-carroll** [comment]
Yeah, link recognition means recognizing a URL in text. There's already some behavior for this in `super_editor`. You'll want to start there and see what makes sense to satisfy this ticket.

**Comment by ThangVuNguyenViet** [comment]
I couldn't find any existing behavior related to link recognition. I'm still not sure what this ticket should result in. How about we discuss some test cases as acceptance criteria for this ticket:

- When a text 'https://flutter.dev' is selected, choosing the link option should convert the selected text into a link.
- When the handle is at the last position in the text 'https://flutter.dev' (could usually be from the user typing the text or pasting it), pressing a space key or an enter should convert the text into a link.
- When the user pastes a block of text 'some text https://flutter.dev some text', the part 'https://flutter.dev' should be converted into a link.

I took the first two from the Google doc, and the last one is from @bk-one btw.

**Comment by matthew-carroll** [comment]
> When a text 'https://flutter.dev/' is selected, choosing the link option should convert the selected text into a link.

There is no "link option" in `SuperEditor`. I think you're referring to the example app.

> When the handle is at the last position in the text 'https://flutter.dev/' (could usually be from the user typing the text or pasting it), pressing a space key or an enter should convert the text into a link.

Yes, I think that makes sense.

> When the user pastes a block of text 'some text https://flutter.dev/ some text', the part 'https://flutter.dev/' should be converted into a link.

Yes, I think this should happen, too.

**Comment by ThangVuNguyenViet** [comment]
> There is no "link option" in SuperEditor. I think you're referring to the example app.

I mean the toolbar's link button, appears when you select some text

**Comment by matthew-carroll** [comment]
Are you talking about the example app? The example app isn't relevant for this ticket.

**Comment by ThangVuNguyenViet** [comment]
Ah yeah, I got it. The toolbar is not in the editor
