### ISSUE TITLE
Expose `autofocus` option on SuperEditor

### ISSUE THREAD

**Issue by osaxma** [superlistapp/super_editor#411]
## Issue
When using `SuperEditor` with other widgets, SuperEditor is either claiming focus automatically (keyboard mode) or it does not (IME mode). 

Since SuperEditor can be with other widgets within a given view, the option for autofocus should be left for the user. 

## Additional Context:
Currently the autofocus is not consistent between `IME` and `Keyboard`:

- For Keyboard, the default is `true`:
https://github.com/superlistapp/super_editor/blob/47e05fcfbc4f9e5e7a21357ef60dcb0ce48ee814/super_editor/lib/src/default_editor/document_input_keyboard.dart#L85-L92

- For IME, the default is `false`:
https://github.com/superlistapp/super_editor/blob/47e05fcfbc4f9e5e7a21357ef60dcb0ce48ee814/super_editor/lib/src/default_editor/document_input_ime.dart#L316-L323

**Comment by matthew-carroll** [comment]
I took a look at other Flutter widgets including `TextField`, `Checkbox`, `Radio`, `Slider`, and `EditableText`. They all take an `autofocus` property, so this seems like a reasonable expectation for `SuperEditor`.
