### ISSUE TITLE
DEL Key inserts question mark icon when used at the end of the page

### ISSUE THREAD

**Issue by MarcelKaeding** [superlistapp/super_editor#417]
- Hit the DEL key at the end of the page
- it will insert a question mark icon:
<img width="129" alt="Screenshot 2022-02-04 at 11 26 05" src="https://user-images.githubusercontent.com/1116227/152513353-4783ec58-b366-41da-88b9-a53ecf7fa550.png">

Expectation: Nothing should happen when hitting the DEL key when there is no input that could be deleted

**Comment by bk-one** [comment]
This seems to be fixed, can you please verify @MarcelKaeding?

**Comment by matthew-carroll** [comment]
@MarcelKaeding is this still a bug?
