### ISSUE TITLE
Example App: Localization support

### ISSUE THREAD

**Issue by bk-one** [superlistapp/super_editor#42]
The sample application for the editor should support localization right from the start to showcase where and how localization support should be positioned. The only sections where localization is needed are the icons for the inline-style change menu and the tooltips for these menus.

**Expectations:**
- [ ] Have the editor interface in English and Spanish 
- [ ] Have wiki page explaining how to add additional languages to the editor via the sample application

**Comment by matthew-carroll** [comment]
@bk-one @salihgueler let's figure out which aspects of this are product responsibilities vs package responsibilities.

super_editor might be missing some language capabilities, but generally speaking, internationalization is implemented on a per-app basis.

**Comment by matthew-carroll** [comment]
After discussion about this ticket, the goal here is specifically with regard to the example app.

The example app text format bar should display hints when hovering over the buttons. Those hints should be localized in English and Spanish.

Also, the various node types, e.g., "Header 1" and "Paragraph" should be localized as well.

**Comment by matthew-carroll** [comment]
I don't think there is any need to produce a wiki page because localizing application-level strings doesn't require anything special for this package.

**Comment by salihgueler** [comment]
If we are going to provide the base view for the text styling window (the window pops up to style the texts), I think we should have a way to handle localization and give proper documentation to the users. @bk-one we want to show the text styling window for all selected texts for the library, not only for the example app, right? So the text in it can be localized by anyone who wants.
