### ISSUE TITLE
Can't type fast on Android

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#444]
When I type fast (probably normal speed for some) on Android device, some key events seem to be lost:
![ezgif com-gif-maker-9](https://user-images.githubusercontent.com/31278849/155413773-af5b5487-1eba-4070-be85-2e520ccfafbd.gif)

In this GIF I was trying to type something like "Hi matt I am trying to type fast".
We identified this on different Android devices.

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by matthew-carroll** [comment]
Is this running in debug mode or profile mode? If debug mode, can you try again in profile mode?

**Comment by miguelcmedeiros** [comment]
It was in debug mode, but tried now with profile mode and got the same.

**Comment by britannio** [comment]
I'm also able to reproduce this by typing "the quick brown fox jumps over the lazy dog" with the example app (in release mode) as of https://github.com/superlistapp/super_editor/commit/5d17a60fd2c1f82b2c6116c817761e56ae6b6f7b. The logs are quite verbose but they are configurable via https://github.com/superlistapp/super_editor/blob/main/super_editor/example/lib/main.dart#L36-L44. Would logs from a particular logger or any other information be of use?

1x speed

https://user-images.githubusercontent.com/33752528/158473198-55c48ea0-7c99-4a06-9b02-3c561c579ad1.mp4

0.5x speed

https://user-images.githubusercontent.com/33752528/158474295-1f694fc0-10cd-463d-a978-6cce0deddae1.mp4

**Comment by matthew-carroll** [comment]
This is definitely an issue that we need to resolve. We'll need to look deeper at the information that Android is sending. Since this seems to only happen on Android, my guess is that Android is sending many more messages for the same operations as compared to iOS.

**Comment by britannio** [comment]
@matthew-carroll Is there anything I can do to further diagnose this?

**Comment by matthew-carroll** [comment]
@britannio one thing that would help is a comparison of deltas that Flutter sends us on Android vs iOS. You should be able to take a given sentence and type that sentence on both platforms in a `SuperEditor` and then grab the deltas from the logs. If we find that Android is sending a lot more deltas, then that might be part of the problem.

**Comment by transcendr** [comment]
@matthew-carroll  I'd like to try and get you this information as requested.  Could you provide me with details of how to access the logs you're referencing and perhaps an example of what I'm looking for in there?  Thanks!

**Comment by angelosilvestre** [comment]
Using a Samsung M51 with the default Samsung keyboard the issue doesn't happen. After I switched to GBoard I noticed it started happening.

@miguelcmedeiros Are you using GBoard ?

**Comment by britannio** [comment]
> Using a Samsung M51 with the default Samsung keyboard the issue doesn't happen. After I switched to GBoard I noticed it started happening.
> 
> @miguelcmedeiros Are you using GBoard ?
> 

I'm using Gboard and facing this issue.

**Comment by matthew-carroll** [comment]
Does anyone know if this is still an issue? Both Super Editor and Flutter have made a number of changes since this was filed, including our creation of an edit pipeline. I'm curious if this issue persists?

**Comment by miguelcmedeiros** [comment]
@MarcelKaeding are there any recent reports about this from Superlist users (iOS user here...)?

**Comment by MarcelKaeding** [comment]
> 

No, I haven't seen reports about this in particular and testing it on the device also feels good now.

**Comment by MarcelKaeding** [comment]
> @MarcelKaeding are there any recent reports about this from Superlist users (iOS user here...)?
No, I haven't seen reports about this in particular and testing it on the device also feels good now.

**Comment by miguelcmedeiros** [comment]
Closing it since it's not reproducible anymore.
