### ISSUE TITLE
Multipage view at Mobile

### ISSUE THREAD

**Issue by asa767** [superlistapp/super_editor#453]
Is there a way to show the document at separeted page views like Microsoft Word. 
I need this to show a document with hundreds of pages. If I show it in a single view it takes a couple of seconds to load. But scrolling the document has terrible fps' like 6.
Because of the issue as described abowe, I am planning to show each page in a listview line. So each page will be rendered when showed to user. 
Or may be you have another solution.
Thanks.

**Comment by matthew-carroll** [comment]
This isn't something that's directly supported right now. You might be able to define your own `DocumentLayout` that separates the pages, but that might still have the same performance problem.

Would you like to fund this capability? If not, then I don't think there's any plan to build this capability at this time.

We will continue to improve performance wherever we can over time. That's a perpetual requirement.

**Comment by matthew-carroll** [comment]
@asa767 is funding this behavior something that you're interested in? If not, I'll close this ticket as something that's not on our current roadmap.
