### ISSUE TITLE
Mobile support for Flutter Web

### ISSUE THREAD

**Issue by jonaird** [superlistapp/super_editor#457]
I've tested super_editor compiled for web on both iPadOS and iOS. Currently when the editor is focused, the software keyboard doesn't appear. I also tried a bluetooth keyboard connected to the iPad. I can type in the editor but selecting text doesn't bring up the drag handles.

**Comment by matthew-carroll** [comment]
Did you test on the `main` branch? 

Also, can you please provide what you actually tested? What is your widget configuration? And what do you mean by "compiled for web on both iPadOS and iOS"?

**Comment by jonaird** [comment]
I did test on the main branch just a few commits ago. 

Steps to reproduce:
1. Create a Flutter project with a Super Editor widget.
2. Build the project for the web i.e. `flutter build web` (I am using the HTML renderer not CanvasKit)
3. Deploy your web build to some form of hosting.
4. Visit the website of your Flutter build on an iOS device.
5. Tap on the Super Editor to give it focus and make the cursor appear.

The result is that the software keyboard does not appear. 

I also tested double tapping some text in the Super Editor. The text did become selected but there were no drag handles as one would expect on an iOS device.

Here is my configuration:
```
SuperEditor(
      componentBuilders: [...customComponentBuilders, ...defaultComponentBuilders],
      keyboardActions: [getSlashCommandKeyboardAction(context), ...defaultKeyboardActions],
      selectionStyle: SelectionStyle(
          selectionColor: Theme.of(context).primaryColorLight,
          textCaretColor: Theme.of(context).primaryColor),
      componentVerticalSpacing: 12,
      textStyleBuilder: textStyleBuilder,
      editor: _editor,
      composer: _composer,
      documentLayoutKey: _docLayoutKey,
      scrollController: _scrollController,
      focusNode: _focusNode,
      maxWidth: 600,
    );
```

**Comment by matthew-carroll** [comment]
@venkatd - If you're also seeing web-specific mobile problems, please consider posting them here.

**Comment by venkatd** [comment]
@matthew-carroll sure thing. We're going to do a pass on Android and iOS native first, then catalog mobile-web problems once the Android/iOS issues are resolved.

**Comment by matthew-carroll** [comment]
@angelosilvestre can you check if the issues mentioned in this ticket are still relevant?

**Comment by angelosilvestre** [comment]
@matthew-carroll The keyboard is opening correctly and the drag handles are being displayed. 

One issue I noticed is that the native text selection toolbar is also being displayed:

![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-16 at 21 02 09](https://github.com/superlistapp/super_editor/assets/7597082/3d5008a6-2e87-45c4-859b-8881bb91051f)

**Comment by matthew-carroll** [comment]
Ok, can you file a new issue for that toolbar problem?

Did auto-scroll work as expected?

**Comment by matthew-carroll** [comment]
@angelosilvestre can you follow up on my comment above?

**Comment by angelosilvestre** [comment]
@matthew-carroll Auto-scroll seems to work as expected. Filed https://github.com/superlistapp/super_editor/issues/1390 for the toolbar issue.

**Comment by matthew-carroll** [comment]
Thanks. I'll close this as complete and defer to #1390 for the toolbar.
