### ISSUE TITLE
Support for Chinese Input 

### ISSUE THREAD

**Issue by jonaird** [superlistapp/super_editor#461]
I've tested Chinese input on Mac and Web.
Steps to reproduce:
1. Enable Chinese keyboard input in system settings.
2. Try to input Chinese characters. 

Here's a video comparing the behavior of a standard TextField and Super Editor when trying to input Chinese:

https://user-images.githubusercontent.com/2141154/158316409-cedf683c-0760-4b48-8172-19e8cb572c1d.mov

**Comment by bk-one** [comment]
This is a duplicate of #348 - this should already work on mobile and is being worked on for Desktop / Web.
