### ISSUE TITLE
Allow CMD/ALT+BACKSPACE to delete words / lines

### ISSUE THREAD

**Issue by bk-one** [superlistapp/super_editor#479]
**To reproduce:**
- open e.g. https://superlist.com/SuperEditor/
- try to delete a word using OPTION+BACKSPACE (on Mac)
- tro to delete the whole line using CMD+BACKSPACE (on Mac)

Both only trigger a single backspace.

**Expected behavior (like in other editors)**
- OPTION+BACKSPACE (on Mac) to delete a word
- CMD+BACKSPACE (on Mac) to delete the whole line and place caret at the beginning of the line

**Comment by zurbrandon** [comment]
hello
