### ISSUE TITLE
Component Builder cannot reference document

### ISSUE THREAD

**Issue by jhlabs** [superlistapp/super_editor#481]
I am currently migrating my `HintComponentBuilder` to the new layout system. In the comment in the line below it is mentioned that the `componentContext` has access to the document. However, when I try to use the commented code lines the document is actually not in the `componentContext`.

https://github.com/superlistapp/super_editor/blob/57a7d72166272582cbbdedc752b6f328c0493f88/super_editor/example/lib/demos/components/demo_text_with_hint.dart#L135

Am I missing something in this reference?

Thanks for your help!

**Comment by matthew-carroll** [comment]
It looks like that comment needs to be updated. The `ComponentBuilder`s don't have access to the document. Instead, a layout phase in the new presenter has access to the document.

Putting aside the documentation, does the remainder of that code demonstrate what you need for your hint support? Or is there something special about your hint support that doesn't exist in the example app?

**Comment by matthew-carroll** [comment]
@jhlabs any update on this?
