### ISSUE TITLE
Default toolbar location is incorrect

### ISSUE THREAD

**Issue by hillelcoren** [superlistapp/super_editor#486]
By default the toolbar is shown in the wrong location.

![image](https://user-images.githubusercontent.com/4629496/159563867-24c09016-35d9-4f0b-89a2-53dfee84d437.png)

We were able to resolve the issue by changing this code in example_editor.dart from:

    docBox.localToGlobal(docBoundingBox.topLeft, ancestor: context.findRenderObject()),
    docBox.localToGlobal(docBoundingBox.bottomRight, ancestor: context.findRenderObject()),

To:

    docBox.localToGlobal(docBoundingBox.topLeft),
    docBox.localToGlobal(docBoundingBox.bottomRight),

Thanks for the great package!

**Comment by ThangVuNguyenViet** [comment]
Hi @hillelcoren . I couldn't get it reproduced. Can you provide code snippet or more information about this?

**Comment by hillelcoren** [comment]
Hi, thanks for looking into the issue!

I'm not sure, in the screenshot above I'm using a row which contains multiple Scaffolds. Maybe it's related?

**Comment by ThangVuNguyenViet** [comment]
```dart
@override
  Widget build(BuildContext context) {
    return Row(
      children: [
        const SizedBox(
          width: 200,
          child: Scaffold(
            backgroundColor: Colors.red,
          ),
        ),
        Expanded(
          child: Scaffold(
            body: Column(
              children: [
                Expanded(
                  child: _buildEditor(),
                ),
                if (_isMobile) _buildMountedToolbar(),
              ],
            ),
          ),
        ),
      ],
    );
  }
```

The code snippet above still doesn't produce the issue. It is modified from the `example_editor.dart` file. Do you mind giving me the widget's hierarchy related to this?

**Comment by ThangVuNguyenViet** [comment]
@hillelcoren do you have multiple editors on one screen? That could potentially lead to the issue.

**Comment by hillelcoren** [comment]
Yes, we're using two editors in a column.

**Comment by ThangVuNguyenViet** [comment]
It is true that the location of the toolbar is incorrect when having multiple editors on a screen, and your solution does fix that. 

Is there any issue you're having with the toolbar's location when using the solution you found?

**Comment by hillelcoren** [comment]
Not that I'm aware of.

Thanks for tracking down the issue.
