### ISSUE TITLE
Add support for links to markdown deserialization

### ISSUE THREAD

**Issue by hillelcoren** [superlistapp/super_editor#489]
The ExampleEditor toolbar includes an option to add links. The links are added correctly to the document however when using serializeDocumentToMarkdown the links aren't included.

Thanks for the excellent package!

**Comment by ThangVuNguyenViet** [comment]
hi @matthew-carroll . Thanks for assigning this to me

**Comment by matthew-carroll** [comment]
I'm re-opening because @hillelcoren says that deserializing doesn't recognize links. @GarettCooper is this something you'd like to look into, based on your original work on the PR that handled the serialization?

**Comment by GarettCooper** [comment]
@matthew-carroll Sure, looks like it should be pretty straighforward

**Comment by hillelcoren** [comment]
Thanks for the fix and excellent package!

**Comment by olegyablokov** [comment]
How do I call serializeDocumentToMarkdown? Where is it, in a file/class methods?..

**Comment by matthew-carroll** [comment]
Here's the API doc: https://pub.dev/documentation/super_editor_markdown/latest/super_editor_markdown/serializeDocumentToMarkdown.html
