### ISSUE TITLE
Add support for hint text

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#490]
Our app displays curated content in the form of rich text Q&A documents. We currently use hint text in empty text fields to help guide our users in completing the documents.

It would be great if the [hint text functionality in SuperTextField](https://github.com/superlistapp/super_editor/blob/main/super_editor/lib/src/infrastructure/super_textfield/infrastructure/hint_text.dart) would be extracted into super_editor.

**Comment by matthew-carroll** [comment]
@Jethro87 can you elaborate on what you're looking for with this ticket? You mentioned "We currently use hint text in empty text fields...", but then you mentioned "...extracted into super_editor".

Are you looking for hint text in a component that displays a paragraph in a `SuperEditor` document?

If so, we have a definition of that component in the example app. Are you saying that you'd like for us to move that into `super_editor` as part of the API?

**Comment by Jethro87** [comment]
@matthew-carroll Closing this issue in place of the email I just sent, thanks.
