### ISSUE TITLE
Ctrl+E & Ctrl+A support on Mac

### ISSUE THREAD

**Issue by kevmoo** [superlistapp/super_editor#491]
Only issue I hit hacking on the doc. I'm used to using

CTRL+E for end-of-line
CTRL+A for beginning-of-line

Would be great to have this support!

**Comment by matthew-carroll** [comment]
Hey look, its @kevmoo! Welcome to the content-heavy side of Flutter!

I'm sure we can add these shortcuts as long as it doesn't conflict with default expectations. @bk-one what do you think?

**Comment by bk-one** [comment]
Absolutely, one of my task is actually to check the full range of expected keyboard shortcuts and send you a list. So yeah, this should be done.
