### ISSUE TITLE
Undefined class 'SpanRange'

### ISSUE THREAD

**Issue by Patrick386** [superlistapp/super_editor#493]
Flutter web 
super_editor/example/.../example_editor/
_toolbar.dart code, I am getting compile error _Undefined class 'SpanRange'_ :

![스크린샷 2022-03-24 오후 10 32 16](https://user-images.githubusercontent.com/49754877/159930250-67abc2e1-a1a0-4fd1-b743-f2972c7d1c63.png)

**Comment by matthew-carroll** [comment]
I'm not sure why you're seeing that compilation error. Try running `flutter clean` and `flutter pub get` in your project. `SpanRange` should be imported with the rest of `super_editor.dart`.

**Comment by Patrick386** [comment]
> I'm not sure why you're seeing that compilation error. Try running `flutter clean` and `flutter pub get` in your project. `SpanRange` should be imported with the rest of `super_editor.dart`.

Thank you.
I've tried several times, but I don't know the cause either.


```
[✓] Flutter (Channel stable, 2.10.3, on Mac OS X 10.15.7 19H1615 darwin-x64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Comment by matthew-carroll** [comment]
Did you open your IDE at the root `/` of the repo, or did you open the `/super_editor` sub-directory?

**Comment by Patrick386** [comment]
> Did you open your IDE at the root `/` of the repo, or did you open the `/super_editor` sub-directory?


I'm just testing a sample.
Did the installation go wrong?
SpanRange < If you remove this part, it works.

import 'package:super_editor/super_editor.dart';


![스크린샷 2022-03-26 오후 2 10 01](https://user-images.githubusercontent.com/49754877/160225660-15baf87b-3f29-46a3-9a13-046c8d56cb32.png)

![스크린샷 2022-03-26 오후 2 00 56](https://user-images.githubusercontent.com/49754877/160225672-f86445a1-9fbb-4fb1-8684-8925262ba2d2.png)

**Comment by matthew-carroll** [comment]
@Patrick386 I thought you were running the `example` app inside the `super_editor` repository. Are you trying to use `super_editor` in your own project? If so, can you show how you wrote the dependency in your pubspec file?

**Comment by Patrick386** [comment]
I want to use super_editor in my project.
The goal is to add the ability to insert images to the toolbar.

**Pubspec file**

```
version: 1.0.0+2

environment:
sdk: ">=2.14.0 <3.0.0"


dependencies:
flutter:
sdk: flutter
flutter_localizations: 
sdk: flutter        
intl: ^0.17.0 

cupertino_icons: ^1.0.4
system_theme: ^1.0.1
flutter_acrylic: ^1.0.0+2
bitsdojo_window: ^0.1.1+1
url_strategy: ^0.2.0
google_sign_in: ^5.2.4
sliver_tools: ^0.2.5
firebase_core: ^1.14.0
firebase_auth: ^3.3.12
flutter_slidable: ^1.2.0
firebase_storage: ^10.2.10
cloud_firestore: ^3.1.11
cloud_functions: ^3.2.11

shared_preferences: ^2.0.13
image_picker: ^0.8.4+11
image_picker_for_web: ^2.1.6

transparent_image: ^2.0.0
video_player: any
html: ^0.15.0

clipboard: ^0.1.3
image_size_getter: ^1.1.0

flutter_spinkit: ^5.1.0

hooks_riverpod: ^1.0.3
flutter_riverpod: ^1.0.3

url_launcher: ^6.0.20

flutter_dropzone: ^3.0.5

path_provider: ^2.0.9
sprung: ^3.0.0
image: ^3.1.3
collection: ^1.15.0

websafe_svg: ^2.1.1

unsplash_client: ^2.1.0+3

beamer: ^1.4.0+1

permission_handler: ^9.2.0

freezed_annotation: any
json_annotation: any

share_plus: ^4.0.3
google_fonts: ^2.3.1

flex_color_picker: ^2.3.1
cached_network_image: ^3.2.0
universal_io: ^2.0.4
uuid: ^3.0.6
toggle_switch: ^1.4.0

flutter_focus_watcher: ^2.0.0
enum_to_string: ^2.0.1
context_menus: ^1.0.1

flutter_lorem: ^2.0.0
universal_platform: ^1.0.0+1


html_editor_enhanced: ^2.4.0+1

timeago: ^3.2.2

new_version: ^0.3.0

currency_formatter: ^1.2.0
email_validator: ^2.0.1

country_currency_pickers: ^2.0.0

file_picker: ^4.5.1
mime: ^1.0.1
open_file: ^3.2.1
animated_text_kit: ^4.2.1

super_editor: ^0.2.0. # <<<<<<<<<<<<

logging: ^1.0.2

dev_dependencies:
flutter_test:
sdk: flutter

flutter_lints: ^1.0.4


build_runner: any
freezed: any

build_verify: ^3.0.0
json_serializable: any
intl_generator: ^0.2.1


flutter:
uses-material-design: true
generate: true 
```

**Comment by matthew-carroll** [comment]
@Patrick386 if you create a brand new Flutter project and you add `super_editor: ^0.2.0` to your pubspec, do you still have this problem? Also, can you make sure that your Flutter stable channel is up to date?

**Comment by Patrick386** [comment]
Yes, I created and tested a new project, but it's the same

```
name: super_editor_sample
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  super_editor: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4


flutter:


  uses-material-design: true
```

![화면 캡처 2022-04-14 144209](https://user-images.githubusercontent.com/49754877/163321332-d77fc1fe-d2ba-4f08-a374-07d6636bfb2a.png)
.

**Comment by matthew-carroll** [comment]
Does your screenshotted file include `import "package:super_editor/super_editor.dart"`?

If so, can you also try explicitly adding `attributed_text` to your pubspec?

`attributed_text: ^0.2.1`

and then 

`import "package:attributed_text/attributed_text.dart"`

**Comment by Patrick386** [comment]
An additional problem has arisen.

```
import 'package:attributed_text/attributed_text.dart';
import 'package:flutter/material.dart';
import 'package:super_editor/super_editor.dart';
```

```
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  super_editor: ^0.2.0
  attributed_text: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
```

![화면 캡처 2022-04-14 151050](https://user-images.githubusercontent.com/49754877/163324540-970860df-062a-4a71-8e49-7a1c00fb6c25.png)

**Comment by matthew-carroll** [comment]
That looks like an issue in your code. Did the name resolution problem go away?

**Comment by Patrick386** [comment]
> That looks like an issue in your code. Did the name resolution problem go away?

I'll remove that part and make a toolbar that suits me.
We'll let you know if there's a problem.

**Comment by matthew-carroll** [comment]
This issue seems to be resolved, so I'm going to close it.
