### ISSUE TITLE
[SuperTextField] [iOS] Text is entered in reverse order

### ISSUE THREAD

**Issue by venkatd** [superlistapp/super_editor#504]
## Steps to reproduce
Code:
```dart
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Container(
            color: Colors.black,
            child: const SuperTextField(lineHeight: 16),
          ),
        ),
      ),
    );
  }
}
```

- Run the app
- Tap black rectangle (the text field)
- Type "abc" (can be done with physical keyboard or virtual keyboard)

## Actual behavior
While typing, the characters show up in reverse order like "cba"

https://user-images.githubusercontent.com/220686/160946830-6634be5b-5150-49c7-8ccb-82abdf0c0e09.mp4

## Expected behavior
The characters should show up in the correct order like "abc"

## Platforms
iOS simulator: iPhone SE (3rd generation)

```
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (4 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
```

CC @lucasarcouto who found and documented the original issue

**Comment by angelosilvestre** [comment]
I tested this on the latest main and the issue doesn't happen anymore. After some investigation, it seems to have been fixed in https://github.com/superlistapp/super_editor/pull/652

I'm going to close this.
