### ISSUE TITLE
[SuperTextField] [Android] Backspace not working

### ISSUE THREAD

**Issue by lucasarcouto** [superlistapp/super_editor#506]
# Steps to reproduce
Code:
```
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Container(
            color: Colors.black,
            child: const SuperTextField(
              lineHeight: 16,
            ),
          ),
        ),
      ),
    );
  }
}
```
- Run the app
- Tap black rectangle (the text field)
- Type "abc"
- Try to delete using either physical or virtual backspace

# Actual behavior
When pressing backspace, it does not remove any characters

https://user-images.githubusercontent.com/3801761/160953565-3258cb8e-0286-41f7-aa67-5a4791f7f098.mp4

# Expected behavior
Every backspace press should remove a character

# Platform
```
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (4 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
```

CC @venkatd

**Comment by gorkemsari** [comment]
Any updates?
