### ISSUE TITLE
[SuperTextField] [iOS] [Android] Typed text not visible during typing

### ISSUE THREAD

**Issue by lucasarcouto** [superlistapp/super_editor#510]
# Steps to reproduce
Code:
```
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Container(
            color: Colors.black,
            child: const SuperTextField(
              lineHeight: 16,
            ),
          ),
        ),
      ),
    );
  }
}
```
- Run the app
- Tap black rectangle (the text field)
- Type more than 1 line of text

# Actual behavior
When user types a text longer than the widget's starting size, they won't be able to see what's being typed, because the text goes outside of the widget's boundaries.

https://user-images.githubusercontent.com/3801761/160955954-aeb8d2d7-2c37-4160-bcca-d17783e05a9d.mp4

# Expected behavior
While typing, current cursor position should always be visible so the user can see what's being typed.

# Platform
```
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (4 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
```

CC @venkatd

**Comment by matthew-carroll** [comment]
FYI @angelosilvestre - The text field should auto-scroll horizontally, but it isn't. At one point this was working.
