### ISSUE TITLE
[Mobile] Selection handles are not easy to "grab" when the document is inside a CustomScrollView

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#525]
Steps to reproduce:
* Update "Sliver Demo Editor" so that it works on iOS:
```
inputSource: DocumentInputSource.ime,
gestureMode: DocumentGestureMode.iOS,
```
* Double-tap on a word to select it
* Drag one of the selection handles to change the selection

**Expected:** selection changes
**Actual:** document scrolls

https://user-images.githubusercontent.com/31278849/161970539-9406b176-bbe5-4eac-b850-f14f1d6fcc18.mp4

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by matthew-carroll** [comment]
I'm looking into this. The problem appears to be related to the use of a `SuperEditor` within an ancestor `Scrollable`.

When `SuperEditor` adds its own `Scrollable`, it disables the regular scrolling behavior and directly implements scrolling. However, `SuperEditor` doesn't have any control over its ancestor `Scrollable`. As a result, `SuperEditor` and the ancestor `Scrollable` are fighting for gesture dominance.

I'm not sure what the answer is to this, but I'll think about it.

**Comment by matthew-carroll** [comment]
The root problem seems to be that we're using a `PanGestureRecognizer` but `Scrollable` uses a `VerticalDragGestureRecognizer`. I thought maybe our `PanGestureRecognizer` is losing out in the gesture arena. So I changed our recognizer to also be a `VerticalDragGestureRecognizer` and it now seems to beat out the ancestor `Scrollable`.
