### ISSUE TITLE
Markdown serialization cannot handle attributions which share a starting index but end in different places

### ISSUE THREAD

**Issue by GarettCooper** [superlistapp/super_editor#526]
I spent a while trying to think of a title, this was unfortunately the best I could come up with.

Currently, the way attributed text to markdown serialization works is that at each point where the set of attributes changes, the serializer inserts the characters used to delimit that markdown formatting for *all* of the attributes on that text.

This works just fine for one off styles:
| Super Editor  | Serialized Markdown | Markdown Rendered
| ------------- | ------------- | ------------- |
| Plain **Bold** Plain| `Plain **Bold** Plain`  | Plain **Bold** Plain |
| Plain ~Strike~ Plain| `Plain ~Strike~ Plain`  | Plain  ~Strike~ Plain |

And can work in cases where a simple style is fully surrounded by a different style (despite some redundancy):
| Super Editor  | Serialized Markdown | Markdown Rendered
| ------------- | ------------- | ------------- |
| **Bold ***Bold and Italic*** Bold**| `**Bold *****Bold and Italic***** Bold**`  | **Bold *****Bold and Italic***** Bold** |
| **Bold **~Bold and Strike~** Bold**| `**Bold ****~Bold and Strike~**** Bold**`  | **Bold *****~Bold and Strike~***** Bold** |

But it breaks down when two attributes begin at the same point, but end at different ones:
| Super Editor  | Serialized Markdown | Markdown Rendered
| ------------- | ------------- | ------------- |
| ***Bold and Italic* Bold**| `***Bold and Italic***** Bold**`  | ***Bold and Italic***** Bold** |
| **~Bold and Strike~ Bold**| `**~Bold and Strike~**** Bold**`  | **~Bold and Strike~**** Bold** |

In this last example, the serializer inserts `**~` to begin the section of attributed text which is both bold and has a strikethrough. At the start of the next section, where the text no longer has a strikethrough, it closes off the previous section with the inverse set of characters (`~**`) and then immediately begins a new section with bold (`**`), which is then closed at the end of the text. The output is invalid markdown with unclosed tags, which isn't rendered correctly.

This issue is also signficant for attributed text with asymmetrical markdown, like links, which are split. Not a showstopper, but also not the behaviour a user would expect.
| Super Editor  | Serialized Markdown | Markdown Rendered
| ------------- | ------------- | ------------- |
| [**Bold and Link** Link](https://github.com)| `[**Bold and Link**](https://github.com)[ Link](https://github.com)`  | [**Bold and Link**](https://github.com)[ Link](https://github.com) |
| [Link **Bold and Link** Link](https://github.com)| `[Link ](https://github.com)[**Bold and Link**](https://github.com)[ Link](https://github.com)`  | [Link ](https://github.com)[**Bold and Link**](https://github.com)[ Link](https://github.com) |

To resolve this issue, the markdown serializer should be aware of attributions on the previous span and only insert style markers for the difference between the two attribution sets.

**Comment by GarettCooper** [comment]
#518 includes two (skipped) tests for this issue's resolution.

**Comment by matthew-carroll** [comment]
Thanks for filing this @GarettCooper
