### ISSUE TITLE
[SuperTextField] [web] Support IME input on desktop web

### ISSUE THREAD

**Issue by venkatd** [superlistapp/super_editor#529]
@matthew-carroll 

We would be interested to sponsor or co-sponsor IME input for Flutter web

Below is a video that shows TextField in action. It lets me use IME input to insert emojis. So we might be able to take a look at their implementation for inspiration.

We have had users complain about quote characters on various international keyboards and it would be the cleanest to allow entry in this way. I'm not sure how they're able to position the emoji picker right where the cursor is.

https://user-images.githubusercontent.com/220686/162496921-8159c4c2-c63e-43ad-baf0-9f0cfb84e026.mp4

**Comment by matthew-carroll** [comment]
Hi @venkatd - can you describe the individual details that would constitute "mobile web support" for `SuperTextField`?

**Comment by venkatd** [comment]
Hi @matthew-carroll I'll start adding them here as individual issues: https://github.com/superlistapp/super_editor/discussions/527

This ticket is not related to mobile web support, but improved support in "desktop web support". I'd consider this a different milestone.

So our users can enter accents, emojis, and other special characters.

**Comment by matthew-carroll** [comment]
Ah, ok, I guess I read the title too fast. Are these bug fixes, or new features? Because we already have a milestone for SuperTextField bugfixes.

**Comment by venkatd** [comment]
This would be a new feature, so it wouldn't fall under SuperTextField bugfixes. 

It's equivalent to https://github.com/superlistapp/super_editor/issues/499 except for the web platform.

I think it would involve integrating with a native html text input in the browser. I tried typing some text in a Flutter TextField and they have some ghost html element positioned over the textfield.

<img width="1512" alt="CleanShot 2022-04-11 at 15 03 58@2x" src="https://user-images.githubusercontent.com/220686/162811370-59525009-1c66-4c96-bc4c-f797450d6714.png">

The value attribute of this input appears to be kept in sync somehow:

<img width="340" alt="CleanShot 2022-04-11 at 15 04 40@2x" src="https://user-images.githubusercontent.com/220686/162811499-38be1528-58ee-456b-839f-fc661f52be94.png">

**Comment by matthew-carroll** [comment]
@venkatd I filed a milestone here: https://github.com/superlistapp/super_editor/discussions/535

**Comment by matthew-carroll** [comment]
I wrote #667 to figure out how Flutter includes the hidden inputs. We can figure out next steps after that.

**Comment by matthew-carroll** [comment]
@angelosilvestre based on your IME work, and your web text input investigation, can you check if any of this ticket is still relevant?

**Comment by angelosilvestre** [comment]
@matthew-carroll It seems the only thing missing is to position the IME panel at the correct location. We have a PR for this: https://github.com/superlistapp/super_editor/pull/1418

**Comment by matthew-carroll** [comment]
@angelosilvestre if that's the case, should we close this issue in favor for #1356? Is there any reason to keep this open?

**Comment by angelosilvestre** [comment]
@matthew-carroll Yes, we can close this issue.
