### ISSUE TITLE
[SuperDesktopTextField] collapse text selection on ESC pressed

### ISSUE THREAD

**Issue by CillianMyles** [superlistapp/super_editor#531]
`SuperEditor` handles the following scenario (desktop):
- User opens a document with content
- User highlights some text
- User presses `ESC` key 
- Text selection is collapsed

`SuperDesktopTextField` does not automatically handle this scenario.

I propose to add a `TextFieldKeyboardHandler` to the `defaultTextFieldKeyboardHandlers` in `desktop_textfield.dart` to handle this scenario by default for `SuperTextField` on desktop.

Since we already implemented this in our codebase, and to make the proposal more concrete than words, I provided a draft PR: #530. 

I can make any adjustments you desire, add tests etc., if you think this is something which would be beneficial to others, and `SuperTextField` in general.

**Comment by matthew-carroll** [comment]
@CillianMyles can you describe the various other places in a desktop environment where this behavior occurs? I poked around a couple places and I see conflicting results. For example, if I select the URL at the top of my browser and press ESC, nothing happens. On the other hand, if I select some text in this GitHub text area and press escape, then the selection collapses to the base of the selection.

Can you sample a half dozen different apps and post the results of those behaviors in this ticket? We don't want to push a default behavior on people that they aren't expecting, so we need to determine what the most common default behavior happens to be.

**Comment by CillianMyles** [comment]
Sorry for the delay but wanted to give this one some time to investigate :-) 

| app | category | platform tested | field | supports rich text (Y/N) | collapses (Y/N) | notes |
|---|---|---|---|---|---|---|
| Firefox | browser | macOS | URL input field | N | N |  |
| GitHub | website | macOS | issue/PR description field | Y | Y |  |
| Slack | chat app | macOS | message input field | Y | N | caret is removed once you select text, pressing ESC does nothing to the selection, but the caret is still gone |
| Todoist | task management | macOS | task creation description input field | Y | Y | triggers a 'do you want to cancel' dialog, when you cancel dialog selection is collapsed |
| Linear | project management | macOS | issue creation dialog input field | Y | Y | triggers a 'do you want to cancel' dialog, when you cancel dialog selection is collapsed |
| Notion | notes app | macOS | document editor | Y | N | text seletion is increased to have full node/block selected |
| Apple Notes | notes app | macOS | note editor | Y | N | text selection is preserved, while caret is removed (same as Slack) |
| Trello | project management | macOS | card input field | Y | N | when creating card, or editing existing card, card and input field dismissed |

So I guess it seems that this is not the default behaviour after all! 👍 

Is there anything point to having optional handlers defined outside of `defaultTextFieldKeyboardHandlers`, that users can use or import? Or is better to leave that implementation to the users who need it? :-)

**Comment by matthew-carroll** [comment]
I think that for now I'd leave this up to app developers. One of our primary goals is to provide tools that make it relatively easy to configure your own editing experience, rather than shipping a single, massively configurable solution. If you think that we have APIs that make this difficult for our users, please let me know.

At some point in the future, if we want to ship a collection of optional behaviors, we can do that when it rises to the appropriate backlog priority.

**Comment by matthew-carroll** [comment]
I'm going to close this issue based on the above discussion. If you see opportunities for API improvements to make it easier to customize such behavior, please let me know.
