### ISSUE TITLE
SuperDesktopTextField need support IME Vietnamese

### ISSUE THREAD

**Issue by letungcntt** [superlistapp/super_editor#532]
By TextField, the IME working. SuperDesktopTextField, the problem has existed

https://user-images.githubusercontent.com/46608407/162732197-bd0d6ef6-523e-497a-b84e-0527fbf4aa56.mov

**Comment by letungcntt** [comment]
I'm using Vietnamese - Simple Telex and typed xin␣chaof␣ in a text field, which managed to display "xin chào ".

**Comment by matthew-carroll** [comment]
This problem isn't specific to Vietnamese - the desktop version of `SuperTextField` doesn't an IME at all. It uses a hardware keyboard integration. Therefore, it's working as intended.

We're in the process of integrating IME support for desktop use-cases. If this is still a problem after we merge those changes, then please re-open an issue.
