### ISSUE TITLE
[Bug] Text selection behaves oddly when caret is shown

### ISSUE THREAD

**Issue by orestesgaolin** [superlistapp/super_editor#536]
# Steps to reproduce

1. Go to https://superlist.com/SuperEditor/
2. Place a caret inside of the main editor
3. Select a text starting from a first line
4. Observe the content up to the end to be selected

https://user-images.githubusercontent.com/16854239/163219738-7df2f8b7-856a-422f-980a-24b79ad80b05.mp4

**Expected behavior**

The text should start being selected from the mouse down point

https://user-images.githubusercontent.com/16854239/163220168-b12c4a69-92aa-4187-9825-6d8b89dcd7aa.mp4

**Comment by matthew-carroll** [comment]
@orestesgaolin does this behavior happen in the `super_editor` example app document?

It looks like you're screen-cap'ing the Super Editor website. We have known issues with that particular demo.

**Comment by orestesgaolin** [comment]
Thanks for the response. Yes, it was the website. I tried to check it on macOS using example application, but at first I was getting spammed by assertion errors when trying to run it
[super_editor_example_log.txt](https://github.com/superlistapp/super_editor/files/8499808/super_editor_example_log.txt)

If I disable breakpoints on uncaught exceptions I can run it mostly fine
<img width="224" alt="screenshot_2022-04-16_13 28 19@2x" src="https://user-images.githubusercontent.com/16854239/163673239-806dfd26-6859-4bc1-8fdc-8bcabcf11533.png">

And on macOS the selection works all right, so I think we can close the issue

<img width="1112" alt="screenshot_2022-04-16_13 28 44@2x" src="https://user-images.githubusercontent.com/16854239/163673253-09603a0f-4c55-42b2-8cfe-f9736ee94c3b.png">

**Comment by matthew-carroll** [comment]
@orestesgaolin can you post your Flutter version output related to those assertion errors?
