### ISSUE TITLE
Layout text decoration on same frame as text

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#537]
We're working on extracting `SuperSelectableText` into a new package, called `super_text`, where `SuperSelectableText` will become a widget called `SuperText`. That work is taking place in #534.

While extracting `super_text`, we'd like to solve the problem where painting a selection and caret always happen one frame after text layout. This is because we're only utilizing the widget tree, and the widget tree doesn't let us customize layout vs painting order, and pass things in between. Therefore, we're stuck scheduling a followup frame every time the text changes.

This ticket is to solve the extra frame problem by explicitly laying out layers above and beneath the text during the `SuperText` layout process.

**Comment by matthew-carroll** [comment]
CC @slightfoot

**Comment by slightfoot** [comment]
I am here

**Comment by matthew-carroll** [comment]
This is solved with the release of super_text_layout.
