### ISSUE TITLE
Caret gets misplaced when resizing (width) the app window

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#538]
Steps to reproduce:
* Place the editor with some content on the sides (e.g. a sidebar on the right side of the editor)
* Place the caret somewhere in the document
* Resize the width of the app window

Expected: caret position is updated to match the current selection
Actual: 

https://user-images.githubusercontent.com/31278849/164749483-7606cd10-282d-4454-85a5-042e5bcb88e1.mov

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by matthew-carroll** [comment]
@miguelcmedeiros do you know if that content on the side is relevant to the bug? Does the caret reposition correctly when there's no content on the side?

**Comment by matthew-carroll** [comment]
@angelosilvestre would you like investigate this issue and try to implement a fix? We'll want some tests that reproduce this problem, too.

**Comment by miguelcmedeiros** [comment]
> do you know if that content on the side is relevant to the bug? Does the caret reposition correctly when there's no content on the side?

Correct, this only happen when `SuperEditor` does not take the full width of the window (e.g. app uses has a sidebar menu instead of a drawer menu).

**Comment by angelosilvestre** [comment]
@matthew-carroll for sure, I would like to do this

**Comment by angelosilvestre** [comment]
@matthew-carroll  After some initial investigation I found that the `BlinkingTextCaret` is not rebuilt after window resizing, causing it to maintain the old `caretOffset`.

Putting a call to `MediaQuery.of(context)` in the `BlinkingTextCaret`'s build method or wraping the `BlinkingCaret` that is returned with a `Builder` forces the widget to rebuild when size changes and solves the issue.

Is there a better way to trigger a widget rebuild after window resizing?

**Comment by matthew-carroll** [comment]
We definitely don't want to reference `MediaQuery` from the caret. Where is the caret currently getting its offset? If someone is already giving the caret an offset, then it would seem logical to have that thing send the appropriate, updated offset.

**Comment by angelosilvestre** [comment]
The offset is calculated inside `_BlinkingTextCaretState` based on the `textPosition` that is passed to `BlinkingTextCaret`

**Comment by matthew-carroll** [comment]
Can you paste a link to the line in the source code?

**Comment by angelosilvestre** [comment]
https://github.com/superlistapp/super_editor/blob/bbcd232a3c8a791dfdc341e1dd9fc433073f5329/super_text/lib/src/caret.dart#L52-L56

**Comment by matthew-carroll** [comment]
Ok, so the next question is, why isn't `build()` re-running automatically when the screen size changes? Especially considering that Miguel says this problem only happens when there's content beside the editor. It seems like there's a deeper problem here that we need to understand.

**Comment by angelosilvestre** [comment]
Testing with the `SuperEditorDemoApp` the problem happens even without any other content

**Comment by angelosilvestre** [comment]
> Ok, so the next question is, why isn't `build()` re-running automatically when the screen size changes?

I will take a deep look and try to find out

**Comment by angelosilvestre** [comment]
The problem also happens on android when the device is rotated. The `AndroidDocumentTouchInteractor` is rebuilt due to this:

https://github.com/superlistapp/super_editor/blob/bbcd232a3c8a791dfdc341e1dd9fc433073f5329/super_editor/lib/src/default_editor/document_gestures_touch_android.dart#L235-L249

But the `SuperSelectableText` is not rebuilt

I will investigate further tomorrow

**Comment by angelosilvestre** [comment]
@matthew-carroll I'm trying to write a test to the current implementation without any fix based on `auto_scroll_test.dart`. I'm trying to get the topLeft of the `BlinkingCaret` and I added some print statements that showed this:

```
TEST -> pumping widget
BlinkingTextCaret -> build
BlinkingTextCaret -> caret offset: Offset(306.0, 24.8)
BlinkingTextCaret -> returning empty SizedBox
BlinkingTextCaret -> build
BlinkingTextCaret -> caret offset: Offset(306.0, 24.8)
BlinkingTextCaret -> returning BlinkingCaret
BlinkingCaret -> build
TEST -> initial BlinkingCaret topLeft: Offset(204.0, 24.0)
TEST -> resizing window
TEST -> final BlinkingCaret topLeft: Offset(24.0, 24.0)
```
I'm resizing the window using `tester.binding.window.physicalSizeTestValue = screenSizeSmaller` and I also tried to resize in a similar way that the `auto_scroll_test.dart` does, getting the same results

The relevant test lines are:

```
  await tester.pumpAndSettle();            
  Finder caretFinder = find.byType(BlinkingCaret);        
  final initialCaretTopLeft = tester.getTopLeft(caretFinder.last);        
  print('TEST -> initial BlinkingCaret topLeft: $initialCaretTopLeft');    
  print('TEST -> resizing window');          
  tester.binding.window.physicalSizeTestValue = screenSizeSmaller;
  await tester.pumpAndSettle();             
  caretFinder = find.byType(BlinkingCaret);
  final currentCaretTopLeft = tester.getTopLeft(caretFinder.last);        
  print('TEST -> final BlinkingCaret topLeft: $currentCaretTopLeft');    
```
I'm not sure why it's returning a diferent topLeft in the second call

Am I missing something?

**Comment by matthew-carroll** [comment]
@angelosilvestre Do you have any open questions for me, or are you still working through it?

**Comment by angelosilvestre** [comment]
@matthew-carroll I'm still working through it. I will make a PR soon
