### ISSUE TITLE
[BUG] AttributedTextEditingController removes all composing attributions when it should only remove some

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#540]
`AttributedTextEditingController` has a method called `removeComposingAttribution()`, which removes a `Set` of `Attribution`s from the controller's "composing attributions".

The implementation of this method inadvertently removes all composing attributions every time.

A line inside the method reads:

`_composingAttributions.removeWhere((attribution) => _composingAttributions.contains(attribution));`

When it should read:

`_composingAttributions.removeWhere((attribution) => attributions.contains(attribution));`

Fix the bug and write appropriate tests to ensure this method works as expected in the future.

**Comment by angelosilvestre** [comment]
Hello @matthew-carroll. I can work on this issue
