### ISSUE TITLE
Flutter 3 support

### ISSUE THREAD

**Issue by britannio** [superlistapp/super_editor#553]
`_DocumentImeInteractorState` and `ImeAttributedTextEditingController` are missing implementations of the following methods:
 - TextInputClient.insertTextPlaceholder
 - TextInputClient.removeTextPlaceholder
 - TextInputClient.showToolbar

Additionally, `WidgetsBinding.instance` and `GestureBinding.instance` are now non-nullable so the null-aware operation `!` need not be used.
```diff
-WidgetsBinding.instance!.addPostFrameCallback(...);
+WidgetsBinding.instance.addPostFrameCallback(...);
```

**Comment by britannio** [comment]
`dart fix --apply` will remove the unnecessary `!` operations. `dart fix --dry-run` will determine all changes without applying them.

**Comment by matthew-carroll** [comment]
These changes were made in #552 - I'm gonna close this ticket.
