### ISSUE TITLE
Fix broken keyboard auto-scroll test after Flutter 3 upgrade

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#555]
The upgrade to Flutter 3 caused a mysterious change to the expected scroll position within the keyboard auto-scroll tests.

I imagine that this difference could be caused by a change in the Ahem font, a pixel density change, or some other minor visual change that impacts our test.

Find what caused the breakage, fix the tests, and attempt to update the tests so that a similar breakage doesn't happen in the future.

The tests live in `auto_scroll_test.dart`.

**Comment by ThangVuNguyenViet** [comment]
Sure. I'll work on that
