### ISSUE TITLE
Fix mobile auto-scroll tests

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#568]
With my recent work on `SuperText`, I somehow ended up breaking the mobile auto-scroll tests. I didn't fix those tests because we needed to move forward with `SuperText`.

Here's one of the error messages:

```
SuperEditor auto-scroll on Android, keeps caret visible when keyboard appears
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: a value greater than or equal to <490.0>
  Actual: <464.79999923706055>
   Which: is not a value greater than or equal to <490.0>
```

It's possible that I inadvertently messed up @ThangVuNguyenViet's auto-scroll work when I rebased against `main`. Perhaps the issue is a failure for the caret to report its height?

**Comment by angelosilvestre** [comment]
The auto-scroll tests don’t appear to be skipped in the CI. I'm going to close this.
