### ISSUE TITLE
Underline composing region for special character composition

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#573]
When composing multi-key characters, there's a standard practice for apps to display some kind of indication that this composition is taking place, such as an underline. This ticket is to implement that behavior in super_editor.

Questions to answer:

1. What visual affordances do we want in super_editor?
2. What should developers be able to configure, or not?
3. What's the appropriate place in the layout/rendering pipeline to apply this decoration?

**Comment by bk-one** [comment]
I would suggest to follow the Chrome browser flow, which will show the initial character underlined. It should be configurable, MacOS recently changed the visual behavior for example. The configuration option can be added later, though. I'd rather make sure this is done in an opinionated way for now - to allow an early merge. Then we schedule the configuration option later.

**Comment by matthew-carroll** [comment]
Ok. Whenever we get to configuration, we'll need to know what it means to configure it. I don't know what you have in mind when you mention configuration. But we can build it first in a way that always applies and always looks the same.

**Comment by matthew-carroll** [comment]
This work was recently completed. I filed a different ticket for this because I forgot about this ticket.
