### ISSUE TITLE
Bump flutter_lints from 1.0.0 to 2.0.1

### ISSUE THREAD

**Issue by erf** [superlistapp/super_editor#576]
I get a build error with flutter_lints 1.0.0, because of my dependency to flutter_lints 2.0.1.

Would it be possible to bump this dependency?

**Comment by matthew-carroll** [comment]
I don't think you should get a build error no matter what happens with the lints. What error are you seeing? And are you using a pub.dev dependency, or a git dependency?

**Comment by erf** [comment]
If i add `  super_editor: ^0.2.0` as a dependency and i have `flutter_lints: ^2.0.1` as a `dev_dependency` and i run `flutter pub get`, i get the following error:

```
Because super_editor 0.2.0 depends on flutter_lints ^1.0.0 and no versions of super_editor match >0.2.0 <0.3.0, super_editor ^0.2.0 requires flutter_lints ^1.0.0.
So, because XXX depends on both super_editor ^0.2.0 and flutter_lints ^2.0.1, version solving failed.
Running "flutter pub get" in XXX...
pub get failed (1; So, because XXX depends on both super_editor ^0.2.0 and flutter_lints ^2.0.1, version solving failed.)
```

In `pubspec.yaml`i have:

```
environment:
  sdk: ">=2.17.0 <3.0.0"
```

**Comment by matthew-carroll** [comment]
I think we may have accidentally released with lints as a source dependency instead of dev dependency. If you switch your dependency to `git` instead of `0.2.0`, do you still get that error?

**Comment by erf** [comment]
If i set up the dependency like this:
```
  super_editor:
    git:
      url: git@github.com:superlistapp/super_editor.git
      path: super_editor
```

I get the following error:
```
Because every version of super_editor from git depends on attributed_text ^0.1.1 which depends on flutter_lints ^1.0.0, every version of super_editor from git requires flutter_lints ^1.0.0.
So, because XXX depends on both super_editor from git and flutter_lints ^2.0.1, version solving failed.
Running "flutter pub get" in XXX...
pub get failed (1; So, because XXX depends on both super_editor from git and flutter_lints ^2.0.1, version solving
failed.)
```

Yeah, so it looks like [attributed_text](https://pub.dev/packages/attributed_text) has a direct dependency to `flutter_lints`.

**Comment by matthew-carroll** [comment]
Ok. Well, I think this will be resolved with our next release, which should happen any day now. I'll see if we can upgrade the lints, but even if we don't, I think the upcoming `v0.2.1` should work for you.
