### ISSUE TITLE
Move test and flutter_test from dependencies to dev_dependencies

### ISSUE THREAD

**Issue by erf** [superlistapp/super_editor#581]
I noticed [attributed_text](https://github.com/superlistapp/super_editor/blob/main/attributed_text/pubspec.yaml) have `test` as a `dependency`, and [super_editor](https://github.com/superlistapp/super_editor/blob/main/super_editor/pubspec.yaml) have `flutter_test` as a `dependency`. These could be moved to `dev_dependecies` ?

**Comment by matthew-carroll** [comment]
Super Editor depends upon these test packages because we publish testing tools with the package. I'm going to close this ticket.
