### ISSUE TITLE
`[AttributedSpan addAttribution]` doesn't correctly expand existing attribution

### ISSUE THREAD

**Issue by knopp** [superlistapp/super_editor#582]
Hi might be missing something, but the following code

```dart
  final text = AttributedText(text: '01234567');
  text.spans
      .addAttribution(newAttribution: italicsAttribution, start: 0, end: 4);
  text.spans
      .addAttribution(newAttribution: italicsAttribution, start: 4, end: 8);
  print('text $text');
```
prints
```
text [AttributedText] - "01234567"
[AttributedSpans] (2 spans):
 - [SpanMarker] - attribution: [NamedAttribution]: italics, offset: 0, type: SpanMarkerType.start
 - [SpanMarker] - attribution: [NamedAttribution]: italics, offset: 4, type: SpanMarkerType.end
 - [SpanMarker] - attribution: [NamedAttribution]: italics, offset: 8, type: SpanMarkerType.end
```
Which is quite unexpected. Shouldn't the first `SpanMarkerType.end` be removed?

**Comment by matthew-carroll** [comment]
@knopp that definitely looks a bug at first glance. We'll wanna take a look at the current test suite and see why nothing is breaking there. Maybe we missed this test-case.

**Comment by knopp** [comment]
@matthew-carroll, any progress on this? It's currently blocking us.

**Comment by matthew-carroll** [comment]
Can you describe what you're trying to do that's triggering this issue?

**Comment by matthew-carroll** [comment]
BTW, I'm just now noticing that you accessed `text.spans`, and I did the same thing in the PR to fix this, because I reproduced the failure from the example. However, you shouldn't manipulate the `spans` object through `AttributedText`. Instead, you should use `AttributedText` methods, which then internally manipulate the `spans`.
