### ISSUE TITLE
Blockquote not working properly

### ISSUE THREAD

**Issue by kevindqc** [superlistapp/super_editor#583]
I ran the example app, and tried to change a paragraph to a blockquote. I expected the text to have a line on the left or some kind of border, and be able to style the text inside that blockquote.

Instead, the text loses all styles and becomes white (on a white background), and I can't change the style of any part of it.

<img src="https://user-images.githubusercontent.com/228313/169889817-0ad0da21-bcc2-4f06-a238-f1aed7e9b096.gif" width="400">

**Comment by matthew-carroll** [comment]
Thanks for reporting this. We'll look into it.

**Comment by angelosilvestre** [comment]
@matthew-carroll I could work on this issue
