### ISSUE TITLE
[Desktop IME] multi-character composition and backspace not as intended

### ISSUE THREAD

**Issue by bk-one** [superlistapp/super_editor#585]
To reproduce, on the SuperEditor example app / Desktop IME:
- press ALT-U to add the umlaut dots (¨) underlines
- press BACKSPACE, nothing happens
- you have to press BACKSPACE again to remove the dots

Expected behavior (as seen for example in this textarea on Github)
- press ALT-U to add the umlaut dots
- press BACKSPACE once to remove the umlaut dots

Other multi-character compositions (e.g. ALT-I and I) should also be fixed accordingly.

**Comment by matthew-carroll** [comment]
@bk-one I tried these steps with a regular Flutter text field and it also requires two backspace presses. The difference is that the built-in Flutter text field shows the underline for the composing character, which makes the two backspaces seem more appropriate. I think this is an IME behavior. Normally, when the user presses the `backspace` button, we get a key notification and we handle the key by deleting a character. However, when you're composing a character, it looks like that button press notification is suppressed. We don't get a key press notification, and the IME doesn't send us a deletion event.

At the moment, I don't see any signal that we could use to perform a deletion.

If we think this behavior should work the way you describe then we probably need to file a ticket against Flutter.

Let me know your thoughts.

**Comment by bk-one** [comment]
Then we can keep it like it is and should file an issue on Flutter as you suggest. The behavior seen in a textarea like here on Github is more appropriate. When pressing OPTION+U it should show two dots with an undersline, but they should be removed on a single backspace. The composition should be aborted and the two dots removed.

Can you file it? You probably now more about the details by now?

**Comment by matthew-carroll** [comment]
Sure. I filed https://github.com/flutter/flutter/issues/104950

**Comment by matthew-carroll** [comment]
I'm going to move this ticket out of the IME milestone because we're stuck waiting for Flutter to address this issue at the platform level.

**Comment by matthew-carroll** [comment]
@angelosilvestre can you see if this issue happens when editing with the IME, or whether it's just hardware keyboard?

**Comment by angelosilvestre** [comment]
@matthew-carroll It doesn't seem to happen using IME.

**Comment by matthew-carroll** [comment]
It appears that this issue only happens in keyboard mode, not IME mode. To fix this issue for pure keyboard entry would require that Super Editor build its own IME to identify things like compound characters and inject edit adjustments. This is far beyond anything that Super Editor can reasonably do (at least for the foreseeable future), so I'm going to close this.

Anyone impacted by this issue should switch to `SuperEditor`s IME configuration.
