### ISSUE TITLE
Expose padding property in SuperTextField

### ISSUE THREAD

**Issue by minikin** [superlistapp/super_editor#588]
We need to add/expose `padding` property to `SuperTextField`. 

`SuperDesktopTextField` already has [padding](https://github.com/superlistapp/super_editor/blob/d65376dce5cbfd0236f8406db3a1c922527012db/super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart#L87) but it's not available through `SuperTextField` public API.

Padding should be tappable for caret placement.

**With padding**

https://user-images.githubusercontent.com/4456735/170072322-d1633053-4f2d-43e8-a840-913aa1b974b3.mp4

**Without padding**

https://user-images.githubusercontent.com/4456735/170071896-8e029ae9-e5de-4640-a1c0-2d24ab7b999c.mp4

**Comment by minikin** [comment]
FYI @miguelcmedeiros

**Comment by iapicca** [comment]
@matthew-carroll can you assign this to me please
