### ISSUE TITLE
CMD+A Behavior is missing

### ISSUE THREAD

**Issue by salihgueler** [superlistapp/super_editor#59]
## Use Case

As a user, I would like to be able to select all paragraphs by tapping CMD+A key combination. 

## Proposal

A user should be able to select all paragraphs with similar metadata by clicking CMD+A key combination. Assume the following `MutableDocument` nodes are given:

```
ParagraphNode(
  id: 'Title',
  text: AttributedText(
    text: 'Example Document',
  ),
  metadata: {
    'blockType': 'header1',
  },
),
ParagraphNode(
  id: 'paragraph1',
  text: AttributedText(
    text:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sed sagittis urna. Aenean mattis ante justo, quis sollicitudin metus interdum id. Aenean ornare urna ac enim consequat mollis. In aliquet convallis efficitur. Phasellus convallis purus in fringilla scelerisque. Ut ac orci a turpis egestas lobortis. Morbi aliquam dapibus sem, vitae sodales arcu ultrices eu. Duis vulputate mauris quam, eleifend pulvinar quam blandit eget.',
  ),
),
ParagraphNode(
  id: 'paragraph2',
  text: AttributedText(
      text:
          'Cras vitae sodales nisi. Vivamus dignissim vel purus vel aliquet. Sed viverra diam vel nisi rhoncus pharetra. Donec gravida ut ligula euismod pharetra. Etiam sed urna scelerisque, efficitur mauris vel, semper arcu. Nullam sed vehicula sapien. Donec id tellus volutpat, eleifend nulla eget, rutrum mauris.'),
),
``` 

As a user, I would expect to select all `ParagraphNode`s above when I do CMD+A regardless of its metadata information.

**Comment by matthew-carroll** [comment]
It's not missing, it just doesn't exist yet ;)

Can you rewrite this ticket as a standard feature request, including any contextual or ancillary information about the desired behavior?

We will collect many such feature requests over time. They will need to be prioritized and then implemented in stack order.

**Comment by salihgueler** [comment]
@matthew-carroll I updated the description, please let me know if it is clearer :)
