### ISSUE TITLE
Store content on content change

### ISSUE THREAD

**Issue by bk-one** [superlistapp/super_editor#6]
**Context of use:** When content is changed
**Primary Actor:** Application
**Triggers:** When the user changes any content within the app

**Main Success Scenario:**
- [ ] 1. The user changed any content in the app
- [ ] 2. The app stores the content locally

**Additional Requirement:**
- [ ] Document the storage format in the GH Wiki for reference and discussion of future extensions

**Notes:**
- Saving should happen more or less instantly on change. Feel free to define the delays between user input and actual storing of content to whatever feels natural
- The stored content should be displayed on app start, this is a separate ticket

**Comment by matthew-carroll** [comment]
@salihgueler let's figure out which aspects of this belong in super_editor vs what belongs on the product side.
