### ISSUE TITLE
AttributeText with a Hint property

### ISSUE THREAD

**Issue by salihgueler** [superlistapp/super_editor#60]
## Use Case

As a user, I would like to see explanatory hint text for the paragraphs

## Proposal

As a developer, I can create a ParagraphNode like the following.

```
ParagraphNode(
  id: DocumentEditor.createNodeId(),
  text: AttributedText(),
```

For the ParagraphNode, I would like to have a property to show a "hint" text to explain what users can write and what can go to the field. If the behavior already exists, please create a new code snippet with an example with that either on the wiki page or in the project.

**Comment by matthew-carroll** [comment]
Let me know if I'm understanding what you're asking....

Let's say we have an empty document with nothing in it. You'd like, for example, to see a hint for the content, or maybe for a title and content? Something like this?

![Screen Shot 2021-03-22 at 10 49 54 PM](https://user-images.githubusercontent.com/7259036/112099534-f183cc80-8b60-11eb-857e-64900095634f.png)

If that's what you want, as you can see, the spike already supports that ability. I think the current state of the package does, too. So let me know if I correctly understand your goal.

If we're talking about the same thing then I can write a wiki guide that explains how to extend the editor with your own special visual needs.

The really important thing to understand here is that we don't want to build an editor package that provides an infinite number of features. Instead, we want to find the right abstractions that allow all of our users to make their own editors do whatever they want. The most critical part of what you're doing while you're integrating this editor is hopefully finding places where I made some bad assumptions. That way, we catch those bad assumptions early and we provide abstractions that are truly malleable for all use-cases.

**Comment by salihgueler** [comment]
Yes, that is exactly what I mean. I updated the issue explanation.

**Comment by matthew-carroll** [comment]
@salihgueler is this still an issue? If so, what specific responsibilities do you think super_editor needs to take with regard to this feature?

**Comment by salihgueler** [comment]
@matthew-carroll We can close this issue, it is possible to do it.
