### ISSUE TITLE
[IME] Document selection is cleared when document loses focus

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#609]
Steps to reproduce:
* Run demo app
* Select a word => toolbar is shown
* Tap on the link-button

**Expected:** toolbar remains open an input field is shown to introduce the link URL
**Actual:** toolbar is closed

https://user-images.githubusercontent.com/31278849/172638158-d5b80ebd-cd14-40e8-9552-5a8eb7aa36e4.mov

**Comment by miguelcmedeiros** [comment]
In the current implementation of `DocumentImeInteractor`, the selection is cleared when focus is taken away from `SuperEditor` and this is the expected behavior in some cases:
* User taps out side the editor
* User moves the focus to a text field
* Use "tab" to move to the next focus node
* etc.

But there are also cases where we should keep the selection in case the focus is taken away:
* Editing the link URL in a selection toolbar (this example use `SuperEditor` but without keyboard as the input source, not IME)
![Screenshot 2022-06-28 at 23 46 13](https://user-images.githubusercontent.com/31278849/176316856-c22ce214-d6d7-4cd6-980e-bffd6b6dedc4.png)

* Right-click on selected to show the context menu
![Screenshot 2022-06-28 at 23 49 08](https://user-images.githubusercontent.com/31278849/176317147-c8422558-0810-4a35-973d-5053affa5012.png)

* Press and hold character key that can be written with different accents depending on the language (e.g. Portuguese)
![Screenshot 2022-06-28 at 23 50 53](https://user-images.githubusercontent.com/31278849/176317259-b843e0b1-4f26-45eb-b663-51cbda418862.png)

**Comment by matthew-carroll** [comment]
Update: I've hacked a proof that we can solve this.

Here's a description of the problem:

- Two widgets **can** be considered "focused" simultaneously, **if** both widgets are in the same branch of the focus tree, i.e., a widget with primary focus, and the ancestors of that focus node in the focus tree.
- When using `Focus` widgets to configure `FocusNode`s, those `FocusNode`s are structured in the focus tree in a way that reflects the structure of the widget tree. `FocusNode`s don't **have to** be structured like the widget tree, but `Focus` widgets impose that structure.
- `SuperEditor` and the associated popovers, like the toolbar, do not exist in the same branch of the widget tree. Popovers usually sit in the app `Overlay`, which, by definition, is always in a different widget branch than the app's content. Therefore, when managing `FocusNode`s with `Focus` widgets in `SuperEditor` and popovers, it's impossible to share focus between `SuperEditor` and the popover. However, if we manage `FocusNode` attachment ourselves, we can explicitly connect a popover `FocusNode` to the `SuperEditor` `FocusNode`, and we can share focus.

I have a prototype that successfully lets me type a URL into the popover toolbar without stealing focus from `SuperEditor`.

I still need to figure out how best to generalize this behavior. Right now, I have to adjust the toolbar implementation to make this happen. As a result, anyone who uses this approach would have to take similar steps for their toolbars and popovers. I'm not sure if there's a generic way that `super_editor` can solve this problem on behalf of all of our users.

Moreover, I still have no idea how to deal with OS-level popovers. I asked this question in an associated Flutter ticket, but I haven't received an answer. If all the `SuperEditor` and `SuperTextField` popovers require manual intervention, and the OS-level popovers are uneditable by app developers, then it's unclear that any solution is available at this time.

I'll put up a PR when I've gotten things as clean as I can.
