### ISSUE TITLE
Example code at Wiki is outdated or APIs are not public yet

### ISSUE THREAD

**Issue by salihgueler** [superlistapp/super_editor#63]
The Example code at the Wiki page here -> https://github.com/superlistapp/rich_text_editor/wiki/Example-code-snippets is outdated or the APIs are not public yet. 

I suggest showing only public APIs and updating the wiki as they go available. 

Here are the snippets that are not working at the moment. 

ListItemNode is not exportable yet.
```
  ListItemNode.ordered(
    id: DocumentEditor.createNodeId(),
    text: AttributedText(text: 'This is the 1st list item.'),
  ),
```

HorizontalRuleNode is not exportable yet.
```
HorizontalRuleNode(id: DocumentEditor.createNodeId()),
```

ImageNode is not exportable yet.
```
ImageNode(
  id: DocumentEditor.createNodeId(),
  imageUrl:
      'https://images.unsplash.com/photo-1612099453097-26a809f51e96?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
),
```

attributions is obsolete now spans are used

```
AttributedText(
  text: _loremIpsum1,
  attributions: [
    SpanMarker(attribution: 'bold', offset: 20, markerType: SpanMarkerType.start),
    SpanMarker(attribution: 'bold', offset: 80, markerType: SpanMarkerType.end),
  ],
),
```

**Comment by matthew-carroll** [comment]
Can you post the mismatches that you found?

**Comment by matthew-carroll** [comment]
I'm going to close this because I think it's stale. If there are remaining issues, please open a new ticket with specifics.
