### ISSUE TITLE
Figure out how Flutter uses hidden inputs on web

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#667]
Flutter appears to use hidden `<input>` tags for their text fields. The goal of this ticket is to figure out what machinery they're using to do this. In other words, if we want to display hidden HTML fields for `super_editor` fields and documents, how can we do that?

Please post the results of the investigation in this issue.

This investigation is related to https://github.com/superlistapp/super_editor/issues/529

**Comment by angelosilvestre** [comment]
@matthew-carroll The hidden <input> tags are generated directly at the engine side by `DefaultTextEditingStrategy` at `text_editing.dart`, so it won't be possible to use the same classes.

We can, however, use `dart:html` to add arbitrary elements to the dom and keep the value in sync. Here's an example: 

```dart
import 'dart:html';

import 'package:flutter/material.dart';
import 'package:super_editor/super_editor.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(body: DomExample()),
    );
  }
}

class DomExample extends StatefulWidget {
  const DomExample({Key? key}) : super(key: key);

  @override
  State<DomExample> createState() => _DomExampleState();
}

class _DomExampleState extends State<DomExample> {
  late InputElement _domElement;
  late AttributedTextEditingController _textController;

  @override
  void initState() {
    super.initState();
    _domElement = InputElement()
      ..id = 'my-dom-element' // replace this
      ..autocomplete = 'off'
      ..className = 'custom-input'
      ..style.position = 'absolute'
      ..style.top = '-9999'
      ..style.left = '-9999';

    document.getElementsByTagName('flt-glass-pane').first.append(_domElement);

    _textController = AttributedTextEditingController();
    _textController.addListener(_onTextChanged);
  }

  @override
  void dispose() {
    _textController.dispose();
    _domElement.remove();
    super.dispose();
  }

  void _onTextChanged() {
    _domElement.value = _textController.text.text;
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.blue,
      child: Center(
        child: Container(
          color: Colors.white,
          width: 200,
          child: SuperTextField(
            textController: _textController,
          ),
        ),
      ),
    );
  }
}
```
![print](https://user-images.githubusercontent.com/7597082/180330315-21189500-3ed5-4c24-8c8b-61000a47a4b6.png)

I'm not sure if this can cause problems with other elements added by flutter.

**Comment by matthew-carroll** [comment]
Thanks. Can you link to where the engine and framework are making use of these HTML elements? If we're going to re-implement this behavior on our end, we also need to know how/when/why the framework is using those inputs.

**Comment by angelosilvestre** [comment]
The element is created when the text field attaches to the input client here:

https://github.com/flutter/engine/blob/48b6b5b3b10887ee6847e44a004518ef0f600f76/lib/web_ui/lib/src/engine/text_editing/text_editing.dart#L1137-L1166

The event handlers are added to the dom element here:

https://github.com/flutter/engine/blob/48b6b5b3b10887ee6847e44a004518ef0f600f76/lib/web_ui/lib/src/engine/text_editing/text_editing.dart#L1200-L1228

I will take another look to figure out why it's being used.

**Comment by angelosilvestre** [comment]
@matthew-carroll Some updates:

These elements are created by the engine when the IME connection is established. So, when we use `TextInput.attach`, it already creates these elements. The engine uses them to receive input from the operating system, then it infers the deltas that are sent to the app.

The inputs are transparent elements that are placed at the exact position of the text field using a css transform.

The position is updated in this method of `EditableText`:

```dart
void _updateSizeAndTransform() {
    if (_hasInputConnection) {
      final Size size = renderEditable.size;
      final Matrix4 transform = renderEditable.getTransformTo(null);
      _textInputConnection!.setEditableSizeAndTransform(size, transform);
      _updateSelectionRects();
      SchedulerBinding.instance.addPostFrameCallback((Duration _) => _updateSizeAndTransform());
    } else if (_placeholderLocation != -1) {
      removeTextPlaceholder();
    }
  }
```

If we use a `SuperAndroidTextField`, which uses IME, these elements are already being created. I could, for example, use the windows 11 emoji keyboard. However, it is not positioned at the correct position.

To position the keyboard, we need to replicate `_updateSizeAndTransform`. For example:

```dart
void _updateSizeAndTransform() {
    if (!_textEditingController.isAttachedToIme) {
      return;
    }

    final renderBox = context.findRenderObject() as RenderBox;
  
    // Implement this on ImeAttributedTextEditingController
    _textEditingController.setEditableSizeAndTransform(
      renderBox.size,
      renderBox.getTransformTo(null),
    );

    SchedulerBinding.instance.addPostFrameCallback((Duration _) => _updateSizeAndTransform());
  }
```

Using this method, the keyboard is displayed close to the text field, as seen in the video:

https://user-images.githubusercontent.com/7597082/186541235-b6da5364-603d-4fce-a5c1-807693546442.mp4

**Comment by matthew-carroll** [comment]
@angelosilvestre are popups displayed at the correct offsets now that we've added position and size reporting to `SuperEditor` and `SuperTextField`?

**Comment by angelosilvestre** [comment]
@matthew-carroll In macOS web it still doesn't seem to be displayed at the correct location.

**Comment by matthew-carroll** [comment]
@angelosilvestre Does that mean that all other combinations of OS and web work correctly? Or are you saying that you only tried one?

**Comment by angelosilvestre** [comment]
I tried now on windows and it doesn't work correctly either. But even Flutter's Textfield doesn't seem to be displayed at the correct position when running on Windows Desktop. I will test on mobile web to see how it is.

**Comment by angelosilvestre** [comment]
@matthew-carroll Windows on web will work the same as mac after https://github.com/superlistapp/super_editor/pull/1418 is merged.

On windows desktop, Flutter doesn't implement the `setCaretRect` method, so we can't display it at the correct position: https://github.com/flutter/flutter/issues/74547

**Comment by matthew-carroll** [comment]
Ok, where does that leave us for this ticket?

**Comment by angelosilvestre** [comment]
@matthew-carroll I think there is nothing left for us to do in this ticket. 

We should add a thumbs on the Flutter ticket to implement the remaining IME methods for windows.

**Comment by matthew-carroll** [comment]
@angelosilvestre do we need to file anything else on our side to track the windows issue?

**Comment by angelosilvestre** [comment]
We can file a ticket similar to https://github.com/superlistapp/super_editor/issues/1356 to track the windows issue and close this one.

I can do that.

**Comment by matthew-carroll** [comment]
Ok, thanks, please do. I'll close this.
