### ISSUE TITLE
[Example App] - Toolbar hides the alignment menu

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#670]
In the example app, the popover toolbar allows the user to select text alignment options with a drop down menu. The drop down menu appears beneath the toolbar, obscuring some of the options.

You can see a screenshot of the problem here: https://github.com/superlistapp/super_editor/issues/380

**Comment by angelosilvestre** [comment]
Checking this ticket I've found another issue:

Clicking to change the text alignment is not applying the new alignment until an attribution is toggled.
