### ISSUE TITLE
Trying to add the TextWithHintDemo to own project but caret not working as expected

### ISSUE THREAD

**Issue by Braj65** [superlistapp/super_editor#709]
Hi,

I ran the TextWithHintDemo as a standalone android app and it worked as expected. Then i added it to my project. Kept the code as it is in the demo app. One issue happening is the caret is not blinking. It blinks only once when i click on hint text and then disappears. Because the caret is not blinking so i am not able to type anything.

Let me know if any other details are required.

**Comment by matthew-carroll** [comment]
@Braj65 when you run the actual `example` app on Android, does the caret work as expected?

**Comment by Braj65** [comment]
> @Braj65 when you run the actual `example` app on Android, does the caret work as expected?

Yes. I extracted the actual example app, TextWithHintDemo,  into a widget and wrapped it with a MaterialApp. Then i ran it. In that case the caret worked as expected.
Now I took the same widget containing TextWithHintDemo and added it to a page of my app. The caret didn't worked.

**Comment by matthew-carroll** [comment]
>  into a widget and wrapped it with a MaterialApp

What I mean is, when you clone this repo, and run the example app as it exists in the repo, does the hint component work?

**Comment by Braj65** [comment]
No. When i clone the repo it and run the example app, the hint component doesn't works.

**Comment by matthew-carroll** [comment]
@angelosilvestre can you take a look at the example app and see if you can find out what's going on with the hint text component?

**Comment by angelosilvestre** [comment]
@Braj65 do you have a reproducible example where the issue happens?

**Comment by Braj65** [comment]
> @Braj65 do you have a reproducible example where the issue happens?

To create a reproducible example i have to add all the different components(materialapp-builder, nav 2, state mgmt, bottomnav bar etc) before reaching a screen where the caret is not working as expected. That will take some time.
I am closing the issue for now. I will revisit it again in the future.

**Comment by matthew-carroll** [comment]
@angelosilvestre it was stated earlier that the example app is broken. Please check that. If the component works as expected in the example app, and it's unclear what's wrong with it, then you can close this issue.

**Comment by angelosilvestre** [comment]
I tested the example app and it's working correctly. I also extracted `TextWithHintDemo` and added it to a new app with some widgets around and I wasn't able to reproduce the issue.

Also, looking at `TextWithHintDemo`, it doesn't seem to have anything that could cause problems with the caret.

It seems that a specific widget tree is needed to trigger this issue. I'm going to close this.
