### ISSUE TITLE
[super_editor_markdown] - Text alignment (textAlign) is ignored during serialization/deserialization

### ISSUE THREAD

**Issue by kostasoft** [superlistapp/super_editor#717]
Thanks for the plugin. 
Everything is very super. 
But I noticed a little problem: Metadata 'textAlign' is ignored during serialization/deserialization.

**Comment by kostasoft** [comment]
Addendum: Same problem with underlined text (serialize/deserialize) and strikethrough text (deserialize)

**Comment by matthew-carroll** [comment]
@kostasoft can you please include the version of `super_editor` and `super_editor_markdown` that you're using?

Also, please include relevant Markdown samples that we can run, which demonstrate the failure.
