### ISSUE TITLE
First two lines jumps when writing in gestureMode: DocumentGestureMode.iOS or DocumentGestureMode.android 

### ISSUE THREAD

**Issue by LuisMaGit** [superlistapp/super_editor#720]
I’m getting this jumps in the firsts lines of texts when using `gestureMode: DocumentGestureMode.iOS`, or `gestureMode: DocumentGestureMode.android`, is not happening for `DocumentGestureMode.mouse.

https://user-images.githubusercontent.com/70621340/182787320-61e1d2e9-30bf-4816-9ae3-a5a0bc27e76b.mov

`super_editor: 0.2.2`

Flutter doctor:
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
[✓] VS Code (version 1.69.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by abidex4yemi** [comment]
I'm experiencing the same issue. @matthew-carroll any idea? thank you.

**Comment by matthew-carroll** [comment]
@LuisMaGit which version of super_editor are you using?

**Comment by LuisMaGit** [comment]
@matthew-carroll super_editor: 0.2.2
