### ISSUE TITLE
correct refresh after changing node order or other properties that do not change DocumentSelection

### ISSUE THREAD

**Issue by JostSchenck** [superlistapp/super_editor#721]
I'm currently trying to use SuperEditor for a software that needs some outline style editing. First of all: Thanks a lot for such a general approach to such a huge problem, for the admirable quality of code and for up-to-date API documentation! Still it is hard for me to thoroughly understand the whole design, especially when working on something like outline editing, which is significantly different from the sequential data approach found in the examples. So my problem might come from unsufficient understanding of all this.

In my editor now, two things can happen which cause problems with a correct repaint: Nodes can be moved in the linear representation of my document, as a consequence of changes in the tree structure behind (the outline). And nodes can change indent. For some reasons, in both cases I do not manage to propagate this change up to the point where the caret then is repainted: The caret stays in place and will only update when I start typing text again (see gif).

![caret-not-updating](https://user-images.githubusercontent.com/12062873/182839262-b3ed818e-4bd1-4e02-8d6e-8a40089a2e86.gif)

Debugging output shows that my `DocumentNode`s correctly do notify their `Listener`s. Can you point me in the right direction? If the answer is "wait until API is stable and design documentation is finalized", I'm fine with that too :)

**Comment by matthew-carroll** [comment]
@JostSchenck - To help us understand your use-case, can you describe the order of nodes in your `MutableDocument`, then describe a change that takes place, and then describe the final node order in your `MutableDocument`? I'm not entirely sure what behavior you're describing.

As for listeners, the individual nodes don't know their index. So if you're interested in nodes moving around, you'll want to listen for changes to the `Document` and then check for specific node indices in the document.

**Comment by JostSchenck** [comment]
Thanks you very much for your reply. Being snowed under in other projects
right now I will need some time before I can dig into this. I will report
back!

Am Di., 9. Aug. 2022 um 23:47 Uhr schrieb Matt Carroll <
***@***.***>:
