### ISSUE TITLE
[SuperEditor] Caret not visible when document has selection and no interaction has taken place

### ISSUE THREAD

**Issue by britannio** [superlistapp/super_editor#722]
**To Reproduce**
Build a `SuperEditor` with autofocus set to `true`, a non-empty list of nodes and an initial collapsed selection.
The expected behaviour is for the caret to be visible however this isn't the case.

I attempted to figure out why:

[`CaretDocumentOverlay`](https://github.com/superlistapp/super_editor/blob/main/super_editor/lib/src/default_editor/document_caret_overlay.dart#L30) is initialised with a null caret rect. It rebuilds if the composer's [`selectionNotifier`]()https://github.com/superlistapp/super_editor/blob/main/super_editor/lib/src/default_editor/document_caret_overlay.dart#L37 notifies listeners of an update but this doesn't happen with the initial selection so the caret rect is never updated. Adding [`_onSelectionChange();`](https://github.com/superlistapp/super_editor/blob/main/super_editor/lib/src/default_editor/document_caret_overlay.dart#L58) to the end of `initState()` seems to fix the issue but I wasn't able to write a passing test to confirm it.

Failing test:
```dart
testWidgets('displays cursor when autofocus is true', (tester) async {
        // Configure and render a document.
        await tester //
            .createDocument()
            .withSingleParagraph()
            .withInputSource(_inputAndGestureVariants.currentValue!.inputSource)
            .withGestureMode(_inputAndGestureVariants.currentValue!.gestureMode)
            .autoFocus(true)
            .pump();

        // Wait for any post frame callbacks to complete
        await tester.pumpAndSettle();

        expect(find.byKey(primaryCaretKey), findsOneWidget); // "none were found but one was expected"
      }, variant: _inputAndGestureVariants);
```

**Comment by matthew-carroll** [comment]
@angelosilvestre - Please see if this is still an issue after your focus/selection PR is merged. If it's fixed, please feel free to close.
