### ISSUE TITLE
[super_editor] - The default gesture mode should be based on the platform

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#741]
Currently, the `SuperEditor` widget always configures itself for mouse input, regardless of platform.

`SuperEditor` should default to mouse input for Mac, Windows, Linux, and Web. But it should default to Android gestures on Android, and iOS gestures on iOS.

**Comment by debasmitasarkar** [comment]
Will check this

**Comment by matthew-carroll** [comment]
I'm assigning this ticket to @angelosilvestre so that we can get this fix in the next release.
