### ISSUE TITLE
[SuperTextField] [Desktop] Text cuts off when maxLine: 1

### ISSUE THREAD

**Issue by jvelezos** [superlistapp/super_editor#764]
From the example application, if you go to SuperTextField

`_interactive_demo.dart` file and make the following changes:

```
minLines: 1,
maxLines: 1,
```

Then both the Text and the hint are being cut off.

<img width="428" alt="Screen Shot 2022-08-30 at 7 12 32 PM" src="https://user-images.githubusercontent.com/11229242/187565429-8ed5738d-2dc0-432c-ad92-35eab18ba7c8.png">
<img width="419" alt="Screen Shot 2022-08-30 at 7 13 18 PM" src="https://user-images.githubusercontent.com/11229242/187565452-733a3d6d-5c16-4d00-872f-307f64765049.png">

This was not happening to our app with `ref: d1214e97d0c255b9ab2c5cb6d9b3ead40aced0c9` but now the hint in one of our usages is also being cut off.

Probable cause are some changes introduced in:
https://github.com/superlistapp/super_editor/pull/739

**Comment by matthew-carroll** [comment]
@angelosilvestre can you take a look at this ASAP and see if you can fix it?

**Comment by angelosilvestre** [comment]
@jvelezos In which platform are you testing? On windows and web it seems to be working.

**Comment by jvelezos** [comment]
> @jvelezos In which platform are you testing? On windows and web it seems to be working.

this happend testing in macos

**Comment by angelosilvestre** [comment]
@jvelezos The only changes needed to cause the issue are the minLines and maxLines? I also tested on macos and I couldn't reproduce the issue.

**Comment by jvelezos** [comment]
`  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      behavior: HitTestBehavior.opaque,
      onTap: () {
        // Remove focus from text field when the user taps anywhere else.
        _focusNode!.unfocus();
      },
      child: Center(
        child: SizedBox(
          width: 400,
          child: GestureDetector(
            onTap: () {
              // no-op. Prevents unfocus from happening when text field is tapped.
            },
            child: SizedBox(
              width: double.infinity,
              child: SuperDesktopTextField(
                textController: _textFieldController,
                focusNode: _focusNode,
                textStyleBuilder: _textStyleBuilder,
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                decorationBuilder: (context, child) {
                  return Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(4),
                      border: Border.all(
                        color: _focusNode!.hasFocus ? Colors.blue : Colors.grey.shade300,
                        width: 1,
                      ),
                    ),
                    child: child,
                  );
                },
                hintBuilder: (context) {
                  return const Text(
                    'please enter some text',
                    style: TextStyle(
                      color: Colors.grey,
                      fontSize: 18,
                      height: 28 / 20,
                    ),
                  );
                },
                hintBehavior: HintBehavior.displayHintUntilTextEntered,
                minLines: 1,
                maxLines: 1,
              ),
            ),
          ),
        ),
      ),
    );
  }

  TextStyle _textStyleBuilder(Set<Attribution> attributions) {
    TextStyle textStyle = const TextStyle(
      color: Colors.black,
      fontSize: 18,
      height: 28 / 20,
    );

    return textStyle;
  }`
  
  This is closer to our use case. Only the hint is cut off in this one, which is also our scenario.

**Comment by matthew-carroll** [comment]
@jvelezos can you please format the code sample as a runnable piece of code with the minimum details to cause the bug? That way, we don't risk make any false assumptions.

**Comment by jvelezos** [comment]
Sure. Replace the contents of _interactive_demo.dart in the with this. Once you delete the field text you'll notice that the hint cuts off.

```
import 'package:flutter/material.dart';
import 'package:super_editor/super_editor.dart';

class InteractiveTextFieldDemo extends StatefulWidget {
  @override
  _InteractiveTextFieldDemoState createState() => _InteractiveTextFieldDemoState();
}

class _InteractiveTextFieldDemoState extends State<InteractiveTextFieldDemo> {
  final _textFieldController = AttributedTextEditingController(
    text: AttributedText(
      text: 'Super Editor is an open source text editor for Flutter projects.',
    ),
  );

  FocusNode? _focusNode;

  @override
  void initState() {
    super.initState();
    _focusNode = FocusNode();
  }

  @override
  void dispose() {
    _focusNode!.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      behavior: HitTestBehavior.opaque,
      onTap: () {
        // Remove focus from text field when the user taps anywhere else.
        _focusNode!.unfocus();
      },
      child: Center(
        child: SizedBox(
          width: 400,
          child: GestureDetector(
            onTap: () {
              // no-op. Prevents unfocus from happening when text field is tapped.
            },
            child: SizedBox(
              width: double.infinity,
              child: SuperDesktopTextField(
                textController: _textFieldController,
                focusNode: _focusNode,
                textStyleBuilder: _textStyleBuilder,
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                decorationBuilder: (context, child) {
                  return Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(4),
                      border: Border.all(
                        color: _focusNode!.hasFocus ? Colors.blue : Colors.grey.shade300,
                        width: 1,
                      ),
                    ),
                    child: child,
                  );
                },
                hintBuilder: (context) {
                  return const Text(
                    'please enter some text',
                    style: TextStyle(
                      color: Colors.grey,
                      fontSize: 20,
                      height: 28 / 20,
                    ),
                  );
                },
                hintBehavior: HintBehavior.displayHintUntilTextEntered,
                minLines: 1,
                maxLines: 1,
              ),
            ),
          ),
        ),
      ),
    );
  }

  TextStyle _textStyleBuilder(Set<Attribution> attributions) {
    TextStyle textStyle = const TextStyle(
      color: Colors.black,
      fontSize: 20,
      height: 28 / 20,
    );

    return textStyle;
  }
}
```
