### ISSUE TITLE
Example app is broken in Flutter 3.3.0

### ISSUE THREAD

**Issue by jmatth** [superlistapp/super_editor#771]
- The mouse cursor does not stay as a text cursor but switches back to the default cursor. I haven't nailed down the exact cause but it seems to happen after clicking on the document for the first time
- Scrolling on a trackpad in macOS changes the selection instead of scrolling the document. I'm guessing the gesture system needs to be updated to support the new [trackpad gestures][1]

https://user-images.githubusercontent.com/1316184/187991830-590ed1fa-56b4-4f89-af20-cd83e0f60ee9.mov

[1]: https://flutter.dev/go/trackpad-gestures

**Comment by algusarov** [comment]
Not sure if it's an issue due to Flutter 3.3.0 upgrade, but I just built an example app on macOS and opening any menu in a hovering toolbar doesn't work as well currently.

https://user-images.githubusercontent.com/46132428/188264850-5aaaf31c-2652-4f89-9fff-475336da3f81.mov

**Comment by jmatth** [comment]
I think the toolbar issue is unrelated. It's also an issue for me on `3.0.5` and has its own issue at #731.

**Comment by matthew-carroll** [comment]
@angelosilvestre can you prioritize this?

**Comment by angelosilvestre** [comment]
The mouse cursor issue seems to be a flutter bug. 

I filled https://github.com/flutter/flutter/issues/111425
