### ISSUE TITLE
Caret misplaced when the indentation of a list item (ordered or unordered) changes

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#777]
Steps to reproduce:
* Create a list item node (unordered or ordered)
* Press TAB

Expected: List item node gets indented and caret moves to the new start position of the node
Actual: List item node gets indented but the caret remains in the old position

https://user-images.githubusercontent.com/31278849/189396028-a9233274-6be3-47a5-ad53-4bd587d3768e.mov

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by matthew-carroll** [comment]
@angelosilvestre can you take a look at this?
