### ISSUE TITLE
Text selection toolbar is far from the selected text (mobile)

### ISSUE THREAD

**Issue by abidex4yemi** [superlistapp/super_editor#793]
- The default behavior for text selection on mobile is by pressing down the text but that's not the case in the editor, double tapping text is the only way to select text currently in the editor.
- After selecting text in the editor, the toolbar is far from the selection
- Clicking outside of the selection doesn't undo the text selected
- The first paragraph or line in the editor can not be selected nor placed the caret at the beginning or end of the text.
- Text selection control behaves weirdly and can not be dragged for multi-line selection.

![IMG_7818](https://user-images.githubusercontent.com/23571838/192239227-2e0df708-c5c7-469d-ab92-6173f4886eb4.jpg)
![IMG_7819](https://user-images.githubusercontent.com/23571838/192239248-6d8aa767-8782-4f3a-971e-c525af470ff1.jpg)

**Comment by matthew-carroll** [comment]
Hi. What version of `super_editor` are you using? And what version of Flutter are you using? Does this issue happen when you run the Example app?

**Comment by abidex4yemi** [comment]
super_editor 0.2.2 and I also point to the latest main branch but still the same issue, my Flutter version is 3.0.5.

Yes I'm experiencing the same issues with the example app.

**Comment by angelosilvestre** [comment]
@abidex4yemi Can you try again on the lastest main? Please add a minimal reproducible example if the problem persists.

**Comment by abidex4yemi** [comment]
@angelosilvestre Yes, I did change it to the main branch but still experiencing the same problem.

**Comment by angelosilvestre** [comment]
@abidex4yemi Could you please share a minimal reproducible example? I couldn't reproduce the issues you mentioned.

**Comment by matthew-carroll** [comment]
@abidex4yemi I ran the example app on our `main` branch on my iPhone 7. I didn't notice any issues with the toolbar. We'll need additional information to reproduce the issue that you're experiencing.

![Screen Shot 2022-10-19 at 8 41 17 PM](https://user-images.githubusercontent.com/7259036/196851311-d3885b27-5be7-4a6d-acdf-7efcda9b2271.png)

**Comment by matthew-carroll** [comment]
@abidex4yemi do you have any further information about reproduction steps for us to debug this?

**Comment by abidex4yemi** [comment]
I'm having two major issues now, the `copy` and `cut` options of the toolbar are not working. Also, I can't scroll to see the bottom of the editor when the keyboard is up, I started experiencing all these issues after removing the `MaterialApp` from the root of the editor, see attachment.
![IMG_73A39F7C6219-1](https://user-images.githubusercontent.com/23571838/202387763-e01e4877-967c-428a-9d45-ebc5edc2c630.jpeg)
![IMG_1035D568F4CB-1](https://user-images.githubusercontent.com/23571838/202387774-67d9b67f-3778-46d1-8681-ca18ad915df2.jpeg)

https://user-images.githubusercontent.com/23571838/202387789-d78f6665-dcf6-4f56-835d-93155b761d84.mov

**Comment by matthew-carroll** [comment]
@abidex4yemi - To get to the bottom of any issues, it's important that we stay focused on the problem at hand. First, does your original problem still exist, or no? Second, if you're running into additional problems, please file tickets for those problems, and please include the code that we need to run to replicate those problems on our end.

**Comment by abidex4yemi** [comment]
@matthew-carroll Yes, the behaviors have changed, the toolbar now covers selected text(offset not working correctly), and clicking on copy or cut doesn’t close the toolbar.

**Comment by matthew-carroll** [comment]
Copy and cut functionality is probably an independent issue, and should be handled as such.

As for your toolbar positioning problems, we still need some way to reproduce this problem. We've tried a number of times to recreate the problem that you're experiencing, but we've been unable to do so. We're going to need some kind of information that we can act upon.

Also, you mentioned that you removed a `MaterialApp`. What did you replace it with? A `CupertinoApp`? A `WidgetsApp`?

**Comment by transcendr** [comment]
If I may, the toolbar dismissal issue has a separate issue #818 with a potential fix in a draft PR.

**Comment by abidex4yemi** [comment]
@matthew-carroll  Please let's close this as I no longer experience this bug.
