### ISSUE TITLE
[SuperTextField] Attempting to full screen on iOS and Android break the editor

### ISSUE THREAD

**Issue by domesticmouse** [superlistapp/super_editor#794]
I'm building a syntax highlighting text editor based on `SuperTextField` for a codelab. It works as intended on macOS, and basically works on web (with the expected issue around not being able to background parsing via `compute`), but when I run the code on Android and iOS the displayed text editor doesn't flow through the space that the Widget Inspector says it takes.

Reproduction repo: https://github.com/domesticmouse/super_text_editor_testing

Here it is on macOS:

<img width="816" alt="Screen Shot 2022-09-26 at 10 58 18 pm" src="https://user-images.githubusercontent.com/30503/192282521-2081329b-6e44-4708-8db4-1e9e6d095870.png">

Here it is on Android:

<img width="575" src="https://user-images.githubusercontent.com/30503/192283823-0768c615-f1ea-4dc6-9779-8bd58a34add7.png">

Here is the Widget Inspector for the above:

<img width="575" src="https://user-images.githubusercontent.com/30503/192284380-92d8e28c-9283-4eb0-b121-81e25d69ce4a.png">

And, of course, iPhone:

<img width="575" src="https://user-images.githubusercontent.com/30503/192286155-bb26c3ab-61a8-4234-b12a-ca4836b27f46.png">

For informational purposes: 

```console
$ [✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en)
    • Flutter version 3.3.2 on channel stable at /Users/brettmorgan/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision e3c29ec00c (12 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/brettmorgan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by matthew-carroll** [comment]
To clarify, based on the screenshots, this issue is not technically a "fullscreen" issue. I think Android and iOS define "fullscreen" as a window mode that removes all OS chrome. Rather, this problem looks like it's about a `SuperTextField` that's displayed very tall, with many lines. We'll look into it.

@domesticmouse BTW, my TODO list has included a minimal code editor for Dart, built with Flutter. I was planning to release that as a package. Would you be interested in co-oping on that? It sounds like you might already be familiar with how to run the analysis server and other tools. I can certainly bring the text rendering and user input capabilities. Maybe together we could accomplish more, with less?

**Comment by domesticmouse** [comment]
> To clarify, based on the screenshots, this issue is not technically a "fullscreen" issue. I think Android and iOS define "fullscreen" as a window mode that removes all OS chrome. Rather, this problem looks like it's about a `SuperTextField` that's displayed very tall, with many lines. We'll look into it.

Thanks!

> 
> @domesticmouse BTW, my TODO list has included a minimal code editor for Dart, built with Flutter. I was planning to release that as a package. Would you be interested in co-oping on that? It sounds like you might already be familiar with how to run the analysis server and other tools. I can certainly bring the text rendering and user input capabilities. Maybe together we could accomplish more, with less?

Sounds like a plan! I'm guessing we should start with a planning gDoc?

**Comment by matthew-carroll** [comment]
@domesticmouse 

> Sounds like a plan! I'm guessing we should start with a planning gDoc?

Sure, I'll draft something and share with your Google email.
