### ISSUE TITLE
[SuperEditor] Best practice for monitoring user-input changes

### ISSUE THREAD

**Issue by josephelliot-wk** [superlistapp/super_editor#797]
Hello! First off, this package is _awesome_. I've been experimenting with using it in a production environment and have a question about responding to updates.

First, let me provide some context. I'm limited to an API that works off of basic insertions and deletions. For example:
- `/add`
  - input: paragraph id (string), text offset (integer), text (string)
  - This is a basic, raw insertion of text at a fixed location. Edits would be batched and sent off every X milliseconds.
- `/remove`
  - input: paragraph id (start), paragraph id (end), text offset (start), text offset (end)
  - This is a basic, raw deletion of a text range (minimum size of 1). Range deletions are not batched, and single deletions are batched similar to `/add`
- `/replace`
  - input: paragraph id (start), paragraph id (end), text offset (start), text offset (end), text(string)
  - This is a `/remove` and `/add` bundled in as one (like pasting content over a range of text).
(These endpoints would be coupled with an update system to keep the client in sync with any remote changes.)

To facilitate this API, I need to capture changes as they're happening and mark their location, batch them as necessary, and send them off. However, when playing around with this package, I _think_ the only way to accomplish this is to compute the diff myself based off the change notifiers on the individual `MutableDocument` and `DocumentNode`s.

Do you have recommendations on how to handle this use case?

PS Here are some example scenarios to help illustrate our needs:

Adding basic text
```
Before:
  This is the first paragraph.
  This is the second paragraph.
After:
  This is the first paragraph and it has some words.
  This is the second paragraph.
Endpoint:
  /add (paragraph_id: 0, text_offset: 27, text: " and it has some words")
```

Adding a newline / paragraph
```
Before:
  This is the first paragraph.
  This is the second paragraph.
After:
  This is the first paragraph.

  This is the second paragraph.
Endpoint:
  /add (paragraph_id: 0, text_offset: 28, text: "\n") (still up in the air on how to handle this from the endpoint's perspective)
```

Deleting a paragraph
```
Before:
  This is the first paragraph.
  This is the second paragraph.
After:
  This is the first paragraph. This is the second paragraph.
Endpoint:
  /remove (paragraph_id_start: 0, paragraph_id_end: 1, text_offset_start: 28, text_offset_end: 0)
```

Replacing a text across paragraphs
```
Before:
  This is the first paragraph.
  This is the second paragraph.
After:
  This is the only paragraph.
Endpoint:
  /replace (paragraph_id_start: 0, paragraph_id_end: 1, text_offset_start: 12, text_offset_end: 18, text: "only")
```

**Comment by matthew-carroll** [comment]
@josephelliot-wk have you taken a look at how we process text editing deltas that come to use from Flutter? Those deltas are essentially the same messages that you've described.

**Comment by josephelliot-wk** [comment]
Sorry for the late response -- I had actually pivoted a bit and used this flutter sample as a reference for how to accomplish this.

https://flutter.github.io/samples/web/simplistic_editor/

Assuming super editor can accomplish the same as the above, then I don't think this issue needs to be open any longer.

Thanks!
