### ISSUE TITLE
Whether image is suppoted?

### ISSUE THREAD

**Issue by bestprize999** [superlistapp/super_editor#800]
no image icon found in example

**Comment by matthew-carroll** [comment]
It's unclear what this ticket is requesting. I'm going to close it. If you have a feature request, please file a ticket with all relevant details so that we can assess.

**Comment by bestprize999** [comment]
Can we insert images with the editor?in toolbar image-inserted icon is not found.

**Comment by matthew-carroll** [comment]
Are you asking about the example app?

In the example app, if you paste an image URL and press "enter", the image will be inserted.

We don't have a toolbar option to insert an image. But you could build that into your own toolbar. The example app is just for demonstration purposes. You're not limited to that behavior.
