### ISSUE TITLE
[super_editor] Inserting and deleting custom attributed text

### ISSUE THREAD

**Issue by abidex4yemi** [superlistapp/super_editor#808]
I'm trying to implement references and footnotes in the editor just like the way Wikipedia has it. The problem I'm having is how to insert and delete inserted footnotes in the editor. I have played around with the insertion but couldn’t figure out the right event to listen to when the user hit the back/delete button in the editor since I need to know deleted character in order to remove the appropriate reference in the document footnotes list.

PS: this is not necessarily a bug but a question about how this can be achieved using the super editor, thanks in advance.

![IMG_7951](https://user-images.githubusercontent.com/23571838/194029610-f3fc6dcd-b3be-44c9-82c2-aeeacf0f8396.jpg)

<img width="966" alt="Screenshot 2022-10-05 at 10 40 29 AM" src="https://user-images.githubusercontent.com/23571838/194033296-89ed21d2-64cc-470d-a308-3aabcdee7c7c.png">

**Comment by abidex4yemi** [comment]
@matthew-carroll @angelosilvestre Please any idea? thanks.

**Comment by matthew-carroll** [comment]
Your best bet is to wait for an upcoming refactor to the document editor, which will provide better tools for listening for document changes. I don't think we have a good answer to your question right now. We're planning another release of Super Editor within a week or so, and then we'll be working on merging that editor refactor after that.

You should watch https://github.com/superlistapp/super_editor/issues/748 and https://github.com/superlistapp/super_editor/issues/736

**Comment by abidex4yemi** [comment]
Thank you @matthew-carroll

**Comment by abidex4yemi** [comment]
@matthew-carroll Please any update on this, thanks.

**Comment by matthew-carroll** [comment]
I expect for us to start our round of breaking changes within the week. We hit a snag because Flutter broke us in two different places recently. As soon as we get that ironed out, we'll start merging our big updates.

**Comment by abidex4yemi** [comment]
Thank you for the update.

**Comment by matthew-carroll** [comment]
@abidex4yemi is this still a problem for you with the new request, command, reaction pipeline?

**Comment by matthew-carroll** [comment]
Closing due to non-response.
