### ISSUE TITLE
Scroll jumps to the image on selection

### ISSUE THREAD

**Issue by EugenePisotsky** [superlistapp/super_editor#812]
Scroll jumps to the image when there's a big one inside the content that I'm trying to select. I tried it on the current master branch (macos desktop)

![2022-10-06 03 46 59](https://user-images.githubusercontent.com/5047628/194189198-fe9bf22a-1c62-4a83-b281-fb135e5556f5.gif)

**Comment by matthew-carroll** [comment]
@EugenePisotsky I'm not sure what you're expecting to happen. What do you think Super Editor should do when selecting a large image?

**Comment by EugenePisotsky** [comment]
@matthew-carroll I think it should select the image it but not scroll to it. Here's a better example and the comparison with the native editor (left is native, right is supereditor): https://www.youtube.com/watch?v=zr5liW_aoaE

**Comment by EugenePisotsky** [comment]
upd. the problem is not an image, but a big caret
