### ISSUE TITLE
[super_text_editor] Text editing on `iOS` causes text to scroll up on key entry

### ISSUE THREAD

**Issue by domesticmouse** [superlistapp/super_editor#814]
I now have my [`super_text_editor_testing`](https://github.com/domesticmouse/super_text_editor_testing) running on iOS. However, when entering text, the text scrolls upwards on each keypress. Can we stop the gratuitous scrolling please? Thanks!

https://user-images.githubusercontent.com/30503/194784993-652b3c27-fb40-45ca-8524-8b16f7a34c3f.mp4

**Comment by matthew-carroll** [comment]
@angelosilvestre please take a look at this and see if we can fix whatever this viewport issue might be.

**Comment by angelosilvestre** [comment]
@domesticmouse Is there any step needed to reproduce this issue? I tried in both android and iOS and can't reproduce it.

**Comment by domesticmouse** [comment]
Ok, this is no longer reproducing for me. 

Should I raise a new feature request for mapping smart quotes to dumb quotes?

**Comment by matthew-carroll** [comment]
> Should I raise a new feature request for mapping smart quotes to dumb quotes?

Didn't you already file that?
