### ISSUE TITLE
[SuperEditor][SuperTextField] - Control IME character conversion

### ISSUE THREAD

**Issue by domesticmouse** [superlistapp/super_editor#815]
In running [`super_text_editor_testing`](https://github.com/domesticmouse/super_text_editor_testing) on iOS I notice that iOS automagically converts `"` to opening double quote `“`. It'd be a nice feature to be able to turn off this conversion for specific usecases (like editing code, say).

<img src="https://user-images.githubusercontent.com/30503/194785367-9edb0be7-fa47-4aa6-9920-dcb2a79e94c3.png" width="300"/>

In this sample interaction, the attribute value `"123"` should be syntax highlighted, but isn't because of the double quote mark replacement.

**Comment by matthew-carroll** [comment]
@angelosilvestre can you check whether this conversion is a Flutter IME configuration or not?

**Comment by angelosilvestre** [comment]
@matthew-carroll It doesn't seem that there is a conversion happening. On iOS, only the opening double quote is displayed on the software keyboard. To insert a normal double quote we need to press and hold the key.

https://github.com/superlistapp/super_editor/assets/7597082/819b0d45-b82b-4051-b27a-61203975af7b

**Comment by matthew-carroll** [comment]
@domesticmouse would you like to comment on Angelo's finding up above?

**Comment by domesticmouse** [comment]
Ugh, user error strikes again
