### ISSUE TITLE
Feature request: Expose AutoScrollController and allow manually enabling/disabling auto scrolling

### ISSUE THREAD

**Issue by roughike** [superlistapp/super_editor#816]
## Background
We're using SuperEditor for multi-user document collaboration.

One of the pieces that makes this work is _selection transformation_. Here's how document collaboration looks like without and with selection transformation:

### Without selection transformation
https://user-images.githubusercontent.com/13744304/194820924-84f9d22b-495c-46c5-bfaa-144ca65d3480.mov

### With selection transformation
https://user-images.githubusercontent.com/13744304/194820502-8f5e6c89-ce1b-4929-bcf5-4df7b051ca30.mov

## The problem we're trying to solve
See a screencast of the problem in this Slack thread: https://superlisthq.slack.com/archives/C0266J4T0MN/p1665390478643699

The pseudocode for selection transformation looks something like this:

```dart
// We're subscribing to a Stream of changes from the server.
//
// The Stream will emit every time some other user makes a change in the document.
_remoteUserChanges().listen((change) {
  // Tell SuperEditor to update the document contents with the change.
  _documentEditor.executeCommand(UpdateDocumentContentsCommand(change));

  // Update the selection, so that the user's selection will be after the same character even
  // if the other user added some content before our selection.
  _documentComposer.selection = _documentSelectionTransformer.transformSelection(change);
));
```

When updating `_documentComposer.selection`, some auto-scrolling logic kicks in from SuperEditor to bring document elements into view. If User A has selected the very first paragraph on the document and it's scrolled out of view, User B typing any character forcibly scrolls User A's document. Sometimes both User A and User B forcibly scroll each others' documents when typing in different positions of it. We don't want this, and we' like to have a way to disable scrolling temporarily.

We'd like to do something like this:

```dart
_remoteUserChanges().listen((change) {
  // Disable auto-scrolling, so that the document does not forcibly auto-scroll when other
  // remote users make changes in the document.
  _autoScrollController.disableScrolling();

  // Update the document.
  _documentEditor.executeCommand(UpdateDocumentContentsCommand(change));

  // Update the document selection.
  _documentComposer.selection = _documentSelectionTransformer.transformSelection(change);

  // Enable auto-scrolling again, so that it works for the cases where the user performs actions
  // that should scroll the current document selection into the view.
  _autoScrollController.enableScrolling();
));

// Later in the build() method:
return SuperEditor(
  editor: _documentEditor,
  composer: _documentComposer,

  // This is not exposed today - we'd like if it was.
  autoScrollController: _autoScrollController,
);
```

## What I think I want from SuperEditor
1. Make it so that we can pass `AutoScrollController` to `SuperEditor`.
2. If an `AutoScrollController` is passed to `SuperEditor`, it supersedes the internal `AutoScrollController`.
3. Calling `.disableScrolling()` on the `AutoScrollController` disables scrolling until `.enableScrolling()` is explicitly called again. The `ensureGlobalRectIsVisible()` method would also be disabled in this case - currently it isn't.

I made some changes in SuperEditor to expose the `AutoScrollController` as a property and to disable all scrolling APIs if `.disableScrolling()` is called. This solved the problem for us, but I'm not 100% sure if I'm breaking something else. Some tests failed.

**Comment by matthew-carroll** [comment]
@roughike can you elaborate on why User B's actions would impact User A's scroll position at all? User B's selection is stored somewhere completely different, right?

**Comment by roughike** [comment]
Hey @matthew-carroll!

In order to answer your question, let me first explain "document selection transformation". **Every time any client gets remote changes, they have to update their document selection**. Without it, collaboration would not work.

In a nutshell, here's what would happen if User A's changes to the document didn't affect User B's selection:
1. User A and User B have document open. The document contents is "abcdef".
2. User B has a collapsed selection after the letter "f". If `|` represents User B's collapsed selection, User B sees "abcdef|". It's equivalent to `TextNodePosition(offset: 6)`.
3. User A inserts "xxxx", making the document into "xxxxabcdef". This change gets broadcasted to User B.
4. User B's collapsed selection is still `TextNodePosition(offset: 6)`. This means that the user sees "xxxxab|cdef". From the User B's perspective, this is wrong. They should see "xxxxabcdef|" (where `|` represents the collapsed selection). So the selection should now be `TextNodePosition(offset: 10)`.

You can see this error happening in the "Scenario A: Without selection transformation" video I posted.

In order to solve this problem (as shown in the second video), every time User A makes changes to the document, User B needs to update his document selection.

Which means we'll have pseudocode like this:

```dart
// We are User B.
// We're listening a Stream, and every time it emits, it means that User A made a change.
_remoteUserChanges().listen((change) {
  // Update the document so that SuperEditor renders the correct stuff.
  _documentEditor.executeCommand(UpdateDocumentContentsCommand(change));

  // Update our document selection so that our selection will always be between the characters
  // that we left it at.
  _documentComposer.selection = _documentSelectionTransformer.transformSelection(change);
));
```

So, to answer your question (I flipped User A and User B so that it's consistent with my explanation and the videos I posted):

> can you elaborate on why User A's actions would impact User B's scroll position at all? User A's selection is stored somewhere completely different, right?

If User A makes a change, User B has to update their document selection when applying that change. And User B does so by calling `_documentComposer.selection = newSelection`.

And because updating `_documentComposer.selection` always auto-scrolls the document if the selected node is out of view, User A's changes will auto-scroll User B's document if User B left their document selection at the first paragraph and decided to scroll it out of view themselves.

**Comment by matthew-carroll** [comment]
@miguelcmedeiros brought this up on our call today. I mentioned that there might be a path here that solves the problem without having clients intervene with the standard behavior.

What we can do is introduce a "reason" for every selection change. That reason can either be something like "user intervention" and "reaction" and we can adjust the document interactor to only auto-scroll for "user intervention". The risks of this approach is that it adds complexity for all non-concurrent use-cases, and it's unclear how the concept of a "reason" might expand over time. However, my initial thought is that this approach is probably less risky than relying on developers to pause and start the auto-scroller, while also having the document interactor stop and start it, too.

If we go this route, my recommendation is to wait until after the release that we're trying to put together right now. This selection change will be a breaking change. We already have a bunch of breaking changes piling up, so we can add this to the list for the next release.

What do you think?

**Comment by roughike** [comment]
@matthew-carroll That would work for us as well.

**Comment by matthew-carroll** [comment]
I'm closing this ticket in favor of a new ticket focused on selection reasons: https://github.com/superlistapp/super_editor/issues/847
