### ISSUE TITLE
Web/Desktop - No Special Character menu on long presses (working on mobile)

### ISSUE THREAD

**Issue by transcendr** [superlistapp/super_editor#828]
When long pressing a key, it should bring up a menu with optional special characters, for example long pressing `a` to get `á`. On web and desktop this results in the character being repeating while on mobile and tablet, it works as expected.

![image](https://user-images.githubusercontent.com/37011672/195881282-5b9e983a-c012-4774-8e85-c9c65a75a307.png)

**Comment by matthew-carroll** [comment]
@transcendr after we merge https://github.com/superlistapp/super_editor/pull/1339 in the next day or two, can you verify whether this issue still exists on `main`?

**Comment by matthew-carroll** [comment]
@transcendr can you confirm whether or not this is still an issue?

**Comment by transcendr** [comment]
@matthew-carroll  sorry for the delay on this, we had a major release cycle deadline and then I was on vacation for a few weeks so I have been out of the loop here. Additionally, we were just recently finishing migration to null safe in an effort to get on the latest stable version of SE and Flutter and verify any current open issues that may have been resolved. I will be back to update all tickets which should need a response in short order.  As always, appreciate your efforts immensely.  Cheers!

**Comment by matthew-carroll** [comment]
I believe this has been working for a while. Please open a new issue with repro steps if it's not.
