### ISSUE TITLE
[SuperEditor][SuperTextField] - Implement new performSelector IME method

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#836]
We added a no-op declaration for `performSelector` when Flutter 3.3.4 was in Beta. We did this so that developers could begin to work with `super_editor` on Beta. However, we left the implementation as a no-op (https://github.com/superlistapp/super_editor/pull/835).

Once Flutter 3.3.4 moves to Stable, implement the appropriate behavior for `performSelector`.

**Comment by angelosilvestre** [comment]
Now that `TextInputClient` is a mixin (https://github.com/flutter/flutter/pull/104291), we should consider changing `SuperEditor` to mix it instead of implementing it, to avoid breaking the build when a new method is added to `TextInputClient`.

This, however, could cause the editor to break silently.

**Comment by matthew-carroll** [comment]
@angelosilvestre after your chat with Matej, let me know if we should move forward with this ticket.

**Comment by angelosilvestre** [comment]
@matthew-carroll We need to implement `performSelection` to be able to interact with native features like the accent panel.

For example, if we handle the key events, the OS won't close the accent panel when pressing backspace or move between the suggestions using the arrow keys.

For this to work, we need to let the OS handle the key events and we need to handle the "intents" in `performSelection`.

We have selectors like `deleteBackward`, `deleteWordBackward`, `moveLeft`, `moveLeftAndModifySelection`, and others.
