### ISSUE TITLE
[DemoApp] Clicking at a dropdown button closes the toolbar

### ISSUE THREAD

**Issue by angelosilvestre** [superlistapp/super_editor#838]
## Steps to Reproduce

1. Run the demo app
2. Double click to select a word
3. Click on the text alignment button

**Expected results:** The dropdown menu is displayed

**Actual results:** The toolbar is hidden and shown again.

This happens with `DocumentInputSource.keyboard`.

This seems to be introduced in https://github.com/superlistapp/super_editor/pull/807 with these lines:

https://github.com/superlistapp/super_editor/blob/87d922e326314aedcb2bd3136b48c9deb50658dc/super_editor/lib/src/default_editor/document_selection_on_focus_mixin.dart#L77-L81

Commenting the line `_selection?.value = null;` fixes the issue but causes other tests to fail.

Failed test: "removes caret when it loses focus"

**Comment by matthew-carroll** [comment]
Those lines look correct. The question is why are we losing focus when interacting with the toolbar. I'm pretty sure we've discussed this before. The dropdown popup displays in its own route, which adds a new `FocusNode` that we can't reparent into `SuperEditor`'s focus tree. 

I'm not sure if the Flutter team will ever change this, so the path forward is probably to use `follow_the_leader` to implement our own dropdown widget. Then we'll get to control the focus tree structure.

**Comment by angelosilvestre** [comment]
This issue is a duplicate of https://github.com/superlistapp/super_editor/issues/731. I'm going to close this.
