### ISSUE TITLE
Setup a CI server with PR test runs

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#84]
The project contains tests, but currently there is no CI integration to ensure that they continue to pass.

Setup a CI server and integrate with this project to ensure that tests pass on every PR that is created.

**Comment by matthew-carroll** [comment]
@salihgueler can you take up this ticket? or ask someone else on the Superlist side if they can handle it?

**Comment by salihgueler** [comment]
I got this, I will take care of it early next week.
