### ISSUE TITLE
[SuperEditor] - switch TextInputClient implementations to use "with" instead of "implements"

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#840]
We've implemented `TextInputClient` in a number of places. We `implements` the interface, because the interface is a fundamental contract between all platforms, Flutter, and Flutter apps about how text is edited. As such, it's important to implement all responsibilities.

Unfortunately, Flutter has established a pattern of throwing new methods into this interface that don't belong there. As a result, Flutter has broken us multiple times by adding methods that we don't need to implement.

This ticket is to switch our implementations from `implements` to mixins with `with`. This change creates the possibility that we don't know about new methods in the interface until long after they're added. This also means that we won't notice the change in time to push back on the Flutter team for adding the new method. But the Flutter team hasn't taken much of our push back seriously in the past, so it's more important that we stop letting them break us. It's an unfortunate situation all the way around, but it's out of our control.

**Comment by angelosilvestre** [comment]
@matthew-carroll  I think there is something missing in Flutter.

`DeltaTextInputClient` is declared as `implements TextInputClient`. When declaring the IME interactor as `with DeltaTextInputClient` we still need to implement all the methods of `TextInputClient`, even those with default stub implementations.

For example, I tried removing the implementation of `showToolbar` (it has a default implementation) from the IME interactor and I still got a build error: `Missing concrete implementation of 'TextInputClient.showToolbar'.`

`showToolbar` is implemented as:

```dart
void showToolbar() {}
```

**Comment by matthew-carroll** [comment]
Can you file an issue with Flutter?
