### ISSUE TITLE
SuperTextField doesn't work if FocusNode is already focused.

### ISSUE THREAD

**Issue by knopp** [superlistapp/super_editor#842]
We have a use-case where SuperTextField replaces another widget, re-using the focus node. When the focus node is already focused, text-input doesn't work. The reason is controller selection being initialized in `SuperDesktopTextFieldState._onFocusChange`, but that function is not called since the node is already focused when state is initialized.

[Changing the initialisation logic slightly](https://github.com/knopp/super_editor/commit/c7a0072323018759c03b6b815c0ec1c952da52a7) resolves the issue.

**Comment by knopp** [comment]
I added PR for desktop. The fix for mobile seems to be more involved and I'm not very familiar with the codebase.

**Comment by matthew-carroll** [comment]
@angelosilvestre let's have you take this over and implement the mobile adjustments

**Comment by knopp** [comment]
Is there any update on this?

**Comment by matthew-carroll** [comment]
I thought this was fixed. @angelosilvestre did we merge the fix for this, or am I misremembering?

**Comment by angelosilvestre** [comment]
The fix was already merged and cherry-picked to stable.

**Comment by angelosilvestre** [comment]
This was fixed in https://github.com/superlistapp/super_editor/pull/846
