### ISSUE TITLE
[SuperEditor][SuperTextField] - Try new FocusNode parenting ability

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#845]
@gspencergoog made a change to `FocusNode` parenting that will hopefully allow us to get rid of our custom focus parenting.

Try his change referenced here: https://github.com/flutter/flutter/issues/106923#issuecomment-1283133843

Report back with any issues or limitations.

**Comment by angelosilvestre** [comment]
Testing the toolbar, replacing the `FocusWithCustomParent` of the url field with a `Focus` with the new `parentNode` property seems to work correctly.

However, the `DropDownButton` seems to be stealing the focus.

I posted a code sample here: https://github.com/flutter/flutter/issues/106923#issuecomment-1304603937

**Comment by angelosilvestre** [comment]
@matthew-carroll  I think this ticket isn't relevant anymore, because we already merged the new popover widget.
