### ISSUE TITLE
[super_editor] how to get editor content height

### ISSUE THREAD

**Issue by abidex4yemi** [superlistapp/super_editor#859]
@matthew-carroll I'm trying to implement an expandable view if the content of the editor is more than 300 in terms of height and gives the user a button to expand the container height to see full content of the editor, is this currently possible with super_editor? @angelosilvestre please any idea? I think there are similarities with this opened [image awareness capability](https://github.com/superlistapp/super_editor/issues/851) issue by @matthew-carroll

**Comment by angelosilvestre** [comment]
@abidex4yemi To get the size you can assign a global key to the editor and then get its buildcontext by the key as a renderbox. You should be able to call `getDryLayout` to calculate the size. Note that the RenderBox won't be available on the first build. I'm not sure this will be sufficient for you.

You might need to use a custom `RenderObject` to wrap the editor. That way you can get the size of the child and layout properly.

**Comment by abidex4yemi** [comment]
Thank you for the suggestions, I will try it out and get back to you.

**Comment by abidex4yemi** [comment]
@angelosilvestre I tried the above suggestions but I'm always getting the same height values (389.77) which seems to be the editor’s height and not it's content height.

**Comment by angelosilvestre** [comment]
To get the correct content size you will need to pass a globalkey to
documentLayoutKey instead of the editor key.

Em sex., 11 de nov. de 2022 07:53, Yemi ***@***.***> escreveu:

**Comment by matthew-carroll** [comment]
@abidex4yemi did Angelo's most recent comment solve your problem?

**Comment by abidex4yemi** [comment]
@matthew-carroll Thanks for the follow ups, I'm able to get the content height using @angelosilvestre suggestions but only after it has render the editor and the other issue is that I can't seem to set a new height with the calculated value, the editor ignores the new value.

**Comment by matthew-carroll** [comment]
@abidex4yemi to understand what you mean when you say "only after it has render the editor" and "the editor ignores the new value", please post the relevant code that demonstrates these issues. That could mean many things.

**Comment by abidex4yemi** [comment]
@matthew-carroll We can close this issue now, I figured it out.
