### ISSUE TITLE
[SuperEditor] Bug: Showing a bottom sheet with the keyboard down raises the keyboard when sheet is dismissed

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#862]
When the keyboard is down in a super_editor document, and a bottom sheet is shown, upon dismissal of the bottom sheet, the keyboard automatically raises. I would expect the keyboard to stay down upon the dismissal of the sheet.

Here's what this looks like:

https://user-images.githubusercontent.com/6467808/202250408-f4881edd-eb04-41ca-985b-3e79e709f111.MP4

If instead, a bottom sheet is shown when the keyboard is up, I would expect the keyboard to be dismissed, the sheet to be shown, and upon dismissal of the sheet, the keyboard to be raised again (like what's happening above).

**Comment by angelosilvestre** [comment]
@Jethro87 This seems to be the same behavior as Flutter's `TextField`.

To prevent this, you need to release the focus before showing the sheet:

```dart
FocusScope.of(context).unfocus();
```

**Comment by Jethro87** [comment]
@angelosilvestre This resolved the issue. Thanks!
