### ISSUE TITLE
[SuperEditorMarkdown] Alignment for the header text

### ISSUE THREAD

**Issue by vnniz** [superlistapp/super_editor#865]
When using the `SuperEditorMarkdown` with `MarkdownSyntax.superEditor`, it can only save the alignment for the Paragraph (only `p` tag), I think that it would be nicer if it also supports the header text. I know that we can write a custom serializer to do it but I think it should be implemented by default to be compatible with the `SuperEditor`.

**Comment by vursin** [comment]
@darkCavalier11 when you `serializeDocumentToMarkdown(doc)` and `deserializeMarkdownToDocument(markdown)`, all the header alignments will be reset to the left alignment.

In the related code of the serialization below, there is no code that converts the header alignments to Markdown:
https://github.com/superlistapp/super_editor/blob/6c95044e7f83a43fc83d51ab0db313562b77ce6b/super_editor_markdown/lib/src/document_to_markdown_serializer.dart#L141-L173

And of the deserialization, also have no code that converts the header alignment back to Node:
https://github.com/superlistapp/super_editor/blob/6c95044e7f83a43fc83d51ab0db313562b77ce6b/super_editor_markdown/lib/src/markdown_to_document_parsing.dart#L89-L120

I can create a PR about this issue if you think it's helpful.

**Comment by matthew-carroll** [comment]
Is there an existing Markdown syntax for header alignment? Or are you asking us to add custom Markdown syntax?

Also, do you really need per-header control over alignment? Is there any reason that you didn't use the `SuperEditor` stylesheet to align your headers?

**Comment by vursin** [comment]
> Is there any reason that you didn't use the `SuperEditor` stylesheet to align your headers?

Is there any way other than markdown to convert all the text with styles to String so we can able to save it to the storage?

> do you really need per-header control over alignment?

Currently, I'm using markdown to save the text to the cloud and convert it back to SuperEditor when the user reopens it (such as a diary app), so it's yes.

> Is there an existing Markdown syntax for header alignment? Or are you asking us to add custom Markdown syntax?

I have created a branch to serve the purpose [here](https://github.com/vursin/super_editor/tree/markdown_header_alignment).

Please let me know if there is any better way to do this. Thank you!

**Comment by matthew-carroll** [comment]
@vnniz is there an existing Markdown syntax that represents per-header alignment?

**Comment by vnniz** [comment]
@matthew-carroll I'm using the default alignment patterns of the paragraph for the header. Here is the syntax:

``` dart
/// Parses a header preceded by an alignment token.
class _HeaderWithAlignmentSyntax extends md.BlockSyntax {
  /// This pattern matches the text alignment notation.
  ///
  /// Possible values are `:---`, `:---:`, `---:` and `-::-`.
  static final _alignmentNotationPattern = RegExp(r'^:-{3}|:-{3}:|-{3}:|-::-$');

  /// Use internal HeaderSyntax
  final _headerSyntax = const md.HeaderSyntax();

  @override
  RegExp get pattern => RegExp('');

  @override
  bool canEndBlock(md.BlockParser parser) => false;

  @override
  bool canParse(md.BlockParser parser) {
    //
    if (!_alignmentNotationPattern.hasMatch(parser.current)) {
      return false;
    }

    final nextLine = parser.peek(1);

    // We found a match for a paragraph alignment token. However, the alignment token is the last
    // line of content in the document. Therefore, it's not really a paragraph alignment token, and we
    // should treat it as regular content.
    if (nextLine == null) return false;

    // Only parse if the next line is header
    if (!_headerSyntax.pattern.hasMatch(nextLine)) {
      return false;
    }

    return true;
  }

  @override
  md.Node? parse(md.BlockParser parser) {
    final match = _alignmentNotationPattern.firstMatch(parser.current);

    // We've parsed the alignment token on the current line. We know a paragraph starts on the
    // next line. Move the parser to the next line so that we can parse the paragraph.
    parser.advance();

    final headerNode = _headerSyntax.parse(parser);

    // Use markdown alignment converter from [_ParagraphWithAlignmentSyntax]
    if (headerNode is md.Element) {
      headerNode.attributes.addAll({'textAlign': _convertMarkdownAlignmentTokenToSuperEditorAlignment(match!.input)});
    }

    return headerNode;
  }

  /// Converts a markdown alignment token to the textAlign metadata used to configure
  /// the [ParagraphNode] alignment.
  String _convertMarkdownAlignmentTokenToSuperEditorAlignment(String alignmentToken) {
    switch (alignmentToken) {
      case ':---':
        return 'left';
      case ':---:':
        return 'center';
      case '---:':
        return 'right';
      case '-::-':
        return 'justify';
      // As we already check that the input matches the notation,
      // we shouldn't reach this point.
      default:
        return 'left';
    }
  }
}
```
And here is the serializer:

``` dart
/// [DocumentNodeMarkdownSerializer] for serializing [ParagraphNode]s as standard Markdown
/// paragraphs.
///
/// Includes support for headers, blockquotes, and code blocks.
class HeaderNodeSerializer extends NodeTypedDocumentNodeMarkdownSerializer<ParagraphNode> {
  const HeaderNodeSerializer(this.markdownSyntax);

  final MarkdownSyntax markdownSyntax;

  @override
  String? serialize(Document document, DocumentNode node) {
    if (node is! ParagraphNode) {
      return null;
    }

    // Only serialize this node when this is a header node
    final Attribution? blockType = node.getMetadataValue('blockType');
    if (blockType == header1Attribution ||
        blockType == header2Attribution ||
        blockType == header3Attribution ||
        blockType == header4Attribution ||
        blockType == header5Attribution ||
        blockType == header6Attribution) {
      // this node is a header node

    } else {
      // this node is not a header node
      return null;
    }

    return doSerialization(document, node);
  }

  @override
  String doSerialization(Document document, ParagraphNode node) {
    final buffer = StringBuffer();

    final Attribution? blockType = node.getMetadataValue('blockType');
    final String? textAlign = node.getMetadataValue('textAlign');

    // Left alignment is the default, so there is no need to add the alignment token.
    if (markdownSyntax == MarkdownSyntax.superEditor && textAlign != null && textAlign != 'left') {
      final alignmentToken = _convertAlignmentToMarkdown(textAlign);
      if (alignmentToken != null) {
        buffer.writeln(alignmentToken);
      }
    }

    if (blockType == header1Attribution) {
      buffer.write('# ${node.text.toMarkdown()}');
    } else if (blockType == header2Attribution) {
      buffer.write('## ${node.text.toMarkdown()}');
    } else if (blockType == header3Attribution) {
      buffer.write('### ${node.text.toMarkdown()}');
    } else if (blockType == header4Attribution) {
      buffer.write('#### ${node.text.toMarkdown()}');
    } else if (blockType == header5Attribution) {
      buffer.write('##### ${node.text.toMarkdown()}');
    } else if (blockType == header6Attribution) {
      buffer.write('###### ${node.text.toMarkdown()}');
    }

    // We're not at the end of the document yet. Add a blank line after the
    // paragraph so that we can tell the difference between separate
    // paragraphs vs. newlines within a single paragraph.
    final nodeIndex = document.getNodeIndexById(node.id);
    if (nodeIndex != document.nodes.length - 1) {
      buffer.writeln();
    }

    return buffer.toString();
  }
}
```
I also need to modify the `_addHeader` method to add the `textAlign` parameter:

``` dart
  void _addHeader(md.Element element, {required int level}) {
    [...]
    final textAlign = element.attributes['textAlign'];
    _content.add(
      ParagraphNode(
        id: Editor.createNodeId(),
        text: _parseInlineText(element),
        metadata: {
          'blockType': headerAttribution,
          'textAlign': textAlign,
        },
      ),
    );
  }
```

**Comment by matthew-carroll** [comment]
@vnniz Please just show some examples of the Markdown syntax that you're proposing. There's no need to paste lots of code for this conversation. Please show me some examples of your Markdown syntax for headers with different alignments.

**Comment by vnniz** [comment]
@matthew-carroll Sorry for misunderstanding your point. I'll describe my idea in more detail.

The `SuperEditor` already supported the header alignments, so we just need to add the `textAlign` parameter into the `ParagraphNode` `metadata`. 

Here is how the `ParagraphNode` looks like:

``` dart
ParagraphNode(
      id: Editor.createNodeId(),
      text: _parseInlineText(element),
      metadata: {
            'block type': headerAttribution,
            'textAlign': textAlign,
      },
),
```

Here is how the alignment syntaxes look like (just like normal paragraph alignment):

`:---\n# Header` or `# Header` => Left Alignment
`:---:\n# Header` => Center Alignment
`---:\n# Header` => Right Alignment
`-::-\n# Header` => Justify Alignment

This alignment will work the same as the normal paragraph alignment, so we only mark it as a header alignment when the next line is a header. This syntax has to be put before the normal paragraph parser.

Here is the flow of the syntax:
```
Loop:
        Check if the current line matches the alignment annotation
        If true:
              Check if the next line is the header
              If true:
                     Convert it back to the header ParagraphNode with the `textAlign` parameter
                     Continue loop

       Normal paragraph parser
```

There is a more convenient way to do this is by modifying the current paragraph parser, so we don't need to worry about the order of the syntax parsers. I created a separate class just to avoid the conflict when I need to update the `SuperEditorMarkdown` to a new version. I already noted the code that needs to be modified in [this comment](https://github.com/superlistapp/super_editor/issues/865#issuecomment-1332378497) to make it work.

**Comment by matthew-carroll** [comment]
@angelosilvestre you implemented paragraph alignment. Do you have any thoughts on the syntax proposed here for header alignment?

**Comment by angelosilvestre** [comment]
@matthew-carroll The syntax seems to be the same as we use for paragraph alignment, so it should work.

We should have tests for paragraphs with alignment, so this shouldn't break anything.

**Comment by matthew-carroll** [comment]
@angelosilvestre do you think this syntax is a good choice? Would you choose a different approach?

**Comment by angelosilvestre** [comment]
@matthew-carroll 

Maybe we could avoid the line break and and place the alignment token in the same line as the header:

`:--- # Header` or `# Header` => Left Alignment
`:---: # Header` => Center Alignment
`---: # Header` => Right Alignment
`-::- # Header` => Justify Alignment

Or we could add the alignment token after the `#`.

`#:--- Header` or `# Header` => Left Alignment
`#:---: Header` => Center Alignment
`#---: Header` => Right Alignment
`#-::- Header` => Justify Alignment

Placing the alignment in the same line would make more clear the distinction between a paragraph with alignment and a header with alignment.

**Comment by matthew-carroll** [comment]
I think I like the 2nd version, e.g., `#:---:` because we can greedily identify it as a header. Although, it would mean that you can't literally start a header with content of ":---:", right? Is there some Markdown escape hatch for situations like that?

**Comment by angelosilvestre** [comment]
We can, because there should be a whitespace between the `#` and the text.

**Comment by angelosilvestre** [comment]
Inserting the text `:---:` as a header would be represented as `# :---:`

**Comment by matthew-carroll** [comment]
Ok. Let's try that approach. Can you take a look at the open PR is see whether it will be faster to rework that one or have you create a new one?

**Comment by angelosilvestre** [comment]
@matthew-carroll Reworking that one seems to be faster. But the PR is missing tests for parsing, we definitely need tests for that.

**Comment by matthew-carroll** [comment]
Ok. @angelosilvestre do you wanna see if you can review that PR and guide it to where it needs to be and then I can review when you think it looks good?

**Comment by angelosilvestre** [comment]
Ok, will do.

**Comment by vnniz** [comment]
@matthew-carroll @angelosilvestre Do you think it will make the Syntax look more complicated and inconsistent? 

For instance, in the current syntax, the only difference between the standard Markdown and the SuperEditorMarkdown is the alignment line so if you want to use this .MD somewhere else, you can easily cut off the alignment line (or not) and the header will still show as expected.


> Placing the alignment in the same line would make more clear the distinction between a paragraph with alignment and a header with alignment.

I think it will be easier to understand when you look at the MD and see the `alignment annotation` then you will know the `next paragraph` (any kind of paragraph) will be applied by the current alignment. The header doesn't need to be excluded from this syntax I think.

**Comment by matthew-carroll** [comment]
@vnniz I think that rationale makes sense. @angelosilvestre  do you have any counterpoints?

**Comment by angelosilvestre** [comment]
I don't have any other objections. We'll only need some tests mixing paragraphs with alignment and headers with alignment to ensure we are parsing them correctly.
