### ISSUE TITLE
Issue running the app locally

### ISSUE THREAD

**Issue by darkCavalier11** [superlistapp/super_editor#869]
Multiple static issues found on code while running locally

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 13.0.1 22A400 darwin-arm, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.73.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

### Issues

![Screenshot 2022-11-25 at 11 19 57 PM](https://user-images.githubusercontent.com/57953014/204035810-221e3ad6-1b6a-40b5-adc5-8ee8f1a00b45.png)
![Screenshot 2022-11-25 at 11 20 12 PM](https://user-images.githubusercontent.com/57953014/204035817-fa959cab-3afc-457b-a6b0-607501824499.png)

**Comment by angelosilvestre** [comment]
@darkCavalier11 Could you please try to run it using the stable branch?

The main branch targets flutter master branch.

**Comment by angelosilvestre** [comment]
Also, do you need to use Flutter 3.0 or could you update to 3.3?

**Comment by darkCavalier11** [comment]
@angelosilvestre working now, Thanks!
