### ISSUE TITLE
Single Line Breaks are Removed Between Paragraphs on Paste

### ISSUE THREAD

**Issue by transcendr** [superlistapp/super_editor#871]
When pasting multiple paragraphs into a document and when there is a single line break in between each paragraph, upon paste, the line breaks are removed. However, if there are two or more line breaks between paragraphs, all line breaks except one are removed.

<img width="613" alt="Screenshot 2022-11-29 at 19 34 15" src="https://user-images.githubusercontent.com/37011672/204616747-6948213f-60ae-4d80-b64a-417aba357931.png">

Illustrated above, copying and pasting the red text into a document results in empty lines between paragaphs being entirely removed.  Copying and pasting the blue text results in what would be the expected result of copying and pasting the red text, one empty line between remains between each paragraph.

Notably, if you copy the text from the same document after having pasted the blue block of text and then paste it directly back into the document, all line breaks are removed.  However, if you manually add the extra two lines between paragraphs from within the editor itself and then copy and paste the paragraphs with a single line break remaining, the line breaks are retained on subsequent pastes, but only if you add two extra lines. Adding a single empty line break between paragraphs within the editor itself and then copying and pasting that text again removes that single line breaks. I hope that's clear enough.

It appears as though when you paste paragraphs of text into the editor, it removes all line breaks between paragraphs unless you have two or more empty lines between paragraphs, in which case it removes all line breaks except one.  This feels like it may be intended behavior but it doesn't feel like standard or expected behavior for an editor. I wouldn't expect to have to advise users to add an extra line break between paragraphs.

Is there a suggested way of handling this?

**Comment by matthew-carroll** [comment]
@angelosilvestre can you look into this and see if there was a reason that we were combining multiple lines into single paragraphs? If not, let's update the paste behavior to create new paragraphs per line of content.
