### ISSUE TITLE
[SuperEditor][SuperTextField] - Expose CaretStyle attributes in SuperTextField

### ISSUE THREAD

**Issue by robertodoering** [superlistapp/super_editor#884]
If the user wants to style the caret on desktop, they have to use a `SuperDesktopTextField` instead of the platform adaptive `SuperTextField`.

Since all other attributes are already exposed, it might make sense to allow callers of `SuperTextField` to modify the `CaretStyle.width` and `CaretStyle.borderRadius` as well.

**Comment by matthew-carroll** [comment]
@angelosilvestre can you see if there's an obvious way to describe caret styles for both desktop and mobile? I'm not sure that there is a meaningful style in common, but it's worth taking a look.
