### ISSUE TITLE
[SuperTextfield] Special characers (ñ è ä ü ö) not working when triggered from US keyboard

### ISSUE THREAD

**Issue by MarcelKaeding** [superlistapp/super_editor#892]
Certain special characters can't be entered anymore from US keyboard layouts, for example
ñ
ä
è

If they are a combination of two key inputs (for example Option+n and n to create ñ)

**Comment by MarcelKaeding** [comment]
@miguelcmedeiros fyi

**Comment by transcendr** [comment]
For reference #828 may be connected.

**Comment by miguelcmedeiros** [comment]
@matthew-carroll, we don't see this issue with `SuperEditor`, only with `SuperTextField`.  
The demo app shows the same issue.

**Comment by matthew-carroll** [comment]
@miguelcmedeiros are we talking about hardware keyboard, software keyboard, or both?

@angelosilvestre can you take a look at this?

**Comment by miguelcmedeiros** [comment]
@matthew-carroll, in my case I was running the demo app on macOS using a hardware keyboard.

**Comment by angelosilvestre** [comment]
@miguelcmedeiros @MarcelKaeding, this is also happening on Super Editor when using keyboard input source.

At first look, this seems to be a flutter issue. For example, in a Brazilian keyboard, to type the character `ã` we type a `~` followed by an `a`. This produces the character `ã`. I would expect the flutter only reports the `ã`  character. Instead, it reports a `~`  character followed by an `ã` character. There are some similar issues that are already closed in the flutter repo.

I filed https://github.com/flutter/flutter/issues/117294

I will open a PR enabling IME for super textfield on desktop.
