### ISSUE TITLE
[SuperEditor] Carat, selection handles, and overlays should hide behind above-keyboard toolbars

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#893]
They are also visible above the "panel_behind_keyboard" in #876.

https://user-images.githubusercontent.com/6467808/207709646-d90d1f59-fd89-4858-b417-b88c8970fc8e.mov

**Comment by angelosilvestre** [comment]
Currently, for Android and iOS we display the caret and the drag handles in an `OverlayEntry`. We will need to replace the mobile interactor with the layer system, which is already used on desktop.

**Comment by Jethro87** [comment]
@matthew-carroll Now that #1256 has merged, is it possible to show the carat, selection handles, and overlays below a mobile keyboard toolbar?

**Comment by matthew-carroll** [comment]
@Jethro87 we should have at least a couple options. I mentioned those in this ticket: https://github.com/superlistapp/super_editor/issues/398

I think the primary question is whether we want app-level overlays, document overlays, or both.
