### ISSUE TITLE
Incompatibility with the latest version of build_runner

### ISSUE THREAD

**Issue by LincolnJota** [superlistapp/super_editor#894]
Pub get conflicting dependencies, specifically between super_editor and build_runner, had to downgrade to ^2.3.0, I was currently using ^2.3.2.

**Comment by angelosilvestre** [comment]
@LincolnJota Could you please share how your super_editor dependency is configured and the output of `flutter pub get`?

**Comment by angelosilvestre** [comment]
@LincolnJota This seems to be resolved with the new Flutter stable release `3.7.0`.

**Comment by matthew-carroll** [comment]
I assume that this issue is resolved, so I'm going to close it.
