### ISSUE TITLE
[SuperTextField] ability to specify/request light or dark theme soft keyboard for mobile (iOS)

### ISSUE THREAD

**Issue by CillianMyles** [superlistapp/super_editor#897]
Material's `TextField` has a `Brightness? keyboardAppearance` field which is used to tell iOS whether we want to show a light or dark themed virtual keyboard. It would be nice if we could do the same for mobile `SuperTextField`.

Docs:
https://api.flutter.dev/flutter/material/TextField/keyboardAppearance.html

**Comment by matthew-carroll** [comment]
@angelosilvestre let's see how we can work this into `SuperTextField`.
