### ISSUE TITLE
Cursor Position in Nested Bullet Lists (Web & Desktop)

### ISSUE THREAD

**Issue by transcendr** [superlistapp/super_editor#904]
When user creates a bullet list and tries to do a second hierarchy of bullets, the cursor goes to the wrong side of the bullets. To note, the cursor only appears there until you begin to type characters on the new bullet line at which point it snaps into place.

Here is a screenshot of the issue:
![image](https://user-images.githubusercontent.com/37011672/209341035-c6c1df42-22b0-451b-a54b-026ef8b8f718.png)

**Comment by angelosilvestre** [comment]
@matthew-carroll Tested on desktop and web and this seems to be solved. Probably because of content layers.

**Comment by matthew-carroll** [comment]
Thanks. I'm going to close this. @transcendr please re-open if the problem persists.
