### ISSUE TITLE
[SuperEditor] - Text components don't display text cursor when expected

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#926]
Repro: Launch the example app, place the caret in a paragraph.

Expected: The cursor looks like an I-beam whenever hovering over text.

Actual: The cursor stops looking like an I-beam as soon as the cursor is placed. It doesn't matter where the cursor is moved. You can get the I-beam back by scrolling the document.

**Comment by angelosilvestre** [comment]
@matthew-carroll Is this happening using the main branch?

There was a bug in flutter (https://github.com/flutter/flutter/issues/111425) that is already fixed in the master branch.

**Comment by matthew-carroll** [comment]
Yeah, looks like I must have been on `stable` when I ran into that. On `master` it seems OK. Gonna close this.
