### ISSUE TITLE
[SuperEditor] - Move mobile gesture recognition under document, like desktop

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#927]
On desktop, we recognize gestures from an area that sits under the document content. This allows inner component widgets, such as checkboxes, to receive and consume touches before the document gesture take over.

On mobile, we're still recognizing gestures above the document content, which means that tapping a checkbox activates the checkbox, and moves the caret. 

The mobile gesture system wasn't updated with the desktop gesture system, because the mobile layout is currently using a `SingleChildScrollView` to scroll the document. That widget consumes gestures and forces a particular structure on us.

Refactor mobile to implement our own scrolling, and then move all gesture handling beneath the document content.

Also, when that's complete, reactivate and refactor the Task component tests that are currently skipped for mobile.

**Comment by robertodoering** [comment]
Hey @matthew-carroll,
is this related to the issue where a user goes into edit mode when they tap on the document while the scrollable is still scrolling (instead of the tap stopping the scrolling)?

**Comment by matthew-carroll** [comment]
@robertodoering that might the be the cause but it's probably a good idea for you to file a new ticket for that particular problem so that we can track it, explicitly.

**Comment by matthew-carroll** [comment]
@angelosilvestre can you verify whether or not the above scrolling issue is due to the location of the gesture system vs something else?

**Comment by angelosilvestre** [comment]
@matthew-carroll It seems to be related to the location of the gesture system. The `onTapUp` of the gesture system is being called.
