### ISSUE TITLE
[SuperTextField] flicker on initial display (iOS)

### ISSUE THREAD

**Issue by knopp** [superlistapp/super_editor#939]
In the video below we replace Text widges with `SuperTextField` upon entering edit mode. You can see that the text is missing for 1-2 frames. This does not happen on desktop.

https://user-images.githubusercontent.com/96958/212548613-c5fd706d-72eb-4aa8-86bf-14699d6927b4.mov

The culprit seems to be `TextScrollView.build`:

https://github.com/superlistapp/super_editor/blob/73990b7a72675aa730840b095e458dcde0c778f6/super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart#L466-L476

The layout is not calculated synchronously, so for several frames there is no content. But in this particular case calling `_updateViewportHeight();` directly from the build method seem to work without issues and resolves the flicker.

Is the asynchronous layout necessary? If so, can we determine cases where it's not a do it synchronously?

**Comment by matthew-carroll** [comment]
We can look into this. But one question I have is, why not always show `SuperTextField`s instead of switching out for regular `Text` widgets?

**Comment by knopp** [comment]
We have a separate edit mode. Unless enabled, the items in list are focusable but not editable.

**Comment by matthew-carroll** [comment]
Don't we already have a property to disable editing on a `SuperTextField`? If not, and we added that, would it remove your need to switch out widgets?

**Comment by knopp** [comment]
It would remove the need to switch widgets, but that just seems like hiding the issue. If I call `_updateViewportHeight();` in the build method directly everything works as expected. I get no errors and no flicker. So clearly for our use-case the layout works synchronously just fine

**Comment by matthew-carroll** [comment]
I agree that we should look into this problem. Independent of that, I think the most natural way to accomplish your desired UX would be to show the text field in an uneditable state. It's pretty lucky that there's no other visual artifact when switching out the two widgets. You may not be able to maintain that fidelity forever, depending on how `SuperTextField` and `Text` might diverge.

**Comment by knopp** [comment]
One possible difference - when not in editing mode we want to show max 3 lines with trailing ..., while editing the field should be scrollable. How hard would this be to achieve with uneditable state?

**Comment by matthew-carroll** [comment]
I think `SuperTextField` already has a `maxLines` property that you can change on-demand, right? 

The trailing "..." probably needs some thought and work.

If you think going in/out of editing mode on a `SuperTextField` would make sense, can you file an issue for that, including the specifics of what you need to control?

**Comment by matthew-carroll** [comment]
@angelosilvestre can you take a look at this?

**Comment by angelosilvestre** [comment]
@matthew-carroll Will take a look
