### ISSUE TITLE
Allow non-ASCII characters

### ISSUE THREAD

**Issue by bk-one** [superlistapp/super_editor#95]
As a user I want to be able to enter non-ASCII characters that I need for my language, e.g.

German: äöüß
Spanish: ñ
Swedish: ø
etc.

So the editor should allow any UTF8 character that I need to use in my language. We can keep left-to-right and right-to-left directions of typing to a separate ticket.

**Expectations:**
- [ ] Open Editor
- [ ] I can enter at least western-language based characters (as seen above; as a first step before supporting all UTF8/16)

**Comment by salihgueler** [comment]
@matthew-carroll After discussing with @bk-one, it is decided that this has the highest priority. Please take a look into it when you can :)
