### ISSUE TITLE
[SuperEditor] First character typed doesn't respect selection position

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#957]
Repro: Launch the example app, place the carat anywhere other than the beginning of the document, then type a character.

Expected: The character is inserted where the carat was placed.

Actual: The character is inserted at the beginning of the document.

https://user-images.githubusercontent.com/6467808/212807164-73c75852-a0c8-46af-8d2c-a8c922e4b05b.mp4

**Comment by Jethro87** [comment]
Possible duplicate: #954

**Comment by matthew-carroll** [comment]
@Jethro87 can you try to reproduce this on latest master or stable?

**Comment by Jethro87** [comment]
@matthew-carroll I can't reproduce it. I'll re-open this if I manage to. Thanks.
