### ISSUE TITLE
[SuperEditor] Collapsed selections do not return correct attributions

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#958]
Repro: Launch the example app, select some text, then add an attribution (i.e., bold, italic, underline, etc.). Move the selection away, then insert the carat into the middle of the initial attributed text.

Expected: The attributed text icon should show as "active." The method `composer.preferences.currentAttributions.containsAll(attributions)` returns false when it should return true. Here's where that line is called:

```
  bool _doesSelectionHaveAttributions(Set<Attribution> attributions) {
    final selection = composer.selection;
    if (selection == null) {
      return false;
    }

    if (selection.isCollapsed) {
      return composer.preferences.currentAttributions.containsAll(attributions);
    }

    return document.doesSelectedTextContainAttributions(selection, attributions);
  }
```

Actual: The attributed text icon is shown as "inactive", and `composer.preferences.currentAttributions.containsAll(attributions)` returns false.

https://user-images.githubusercontent.com/6467808/212807899-3d94a7c0-c650-47ea-8e0a-546f4b28f694.mp4

**Comment by Jethro87** [comment]
#982 / #989 might be the same issue.

**Comment by angelosilvestre** [comment]
This seems to be solved by https://github.com/superlistapp/super_editor/pull/989.

I'm going to close this.
