### ISSUE TITLE
[SuperEditor] Floating toolbar extends towards edge of screen

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#959]
Repro: Launch the example app and double-tap to highlight a word near the right or left edge of the screen.

Expected: The floating toolbar appears and is a uniform rounded rectangle.

Actual: The floating toolbar appears and extends to the edge of the screen.

![Simulator Screen Shot - iPhone 14 - 2023-01-16 at 20 14 39](https://user-images.githubusercontent.com/6467808/212809021-180a3d4a-b367-4302-9b86-562e9384f5e1.png)

**Comment by matthew-carroll** [comment]
@Jethro87 I didn't understand the "expected" behavior here. It sounds like two different things are being compared. What's the behavior that you'd like?

**Comment by Jethro87** [comment]
@matthew-carroll I initially thought that the border-radius around "Paste" in the above screenshot was greater than around "Cut," but after digging into this more, I think it's an optical illusion in light mode. Weird.

To solve this, the toolbar should not touch the edge of the screen. This will bring it in line with iOS:

![IMG_1405](https://user-images.githubusercontent.com/6467808/213083190-85ea37e5-6545-4c99-9a11-3895aeacb4a4.jpg)

Perhaps this and #963 should be merged.

**Comment by matthew-carroll** [comment]
I just added edge-of-screen spacing to #963 so I'm gonna close this ticket.
