### ISSUE TITLE
[SuperEditor] Update design of mobile floating toolbar

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#963]
EDIT (Matt): in addition to toolbar visuals below, also ensure the toolbars don't get too close to the screen.

### Current iOS
![Simulator Screen Shot - iPhone 14 - 2023-01-17 at 09 04 52](https://user-images.githubusercontent.com/6467808/212968119-9da759a5-ef01-4698-8b09-eaa318edd4b2.png)

### Desired iOS
![IMG_1150](https://user-images.githubusercontent.com/6467808/212968159-21bf35c0-a4b0-4442-8409-9fab431426d2.jpg)

### Current Android
![IMG_1149](https://user-images.githubusercontent.com/6467808/212968222-3c1e1a99-1afc-4f19-9f43-dcab3af740cb.jpg)

### Desired Android
![Screenshot_20230117-091546](https://user-images.githubusercontent.com/6467808/212968259-f3cebfe8-7ec3-4522-9f6a-49fce2e47863.png)

### Extra
Additionally, the iOS toolbar shows additional options and scrolls between them, as per the video below:

https://user-images.githubusercontent.com/6467808/212968373-299f2b5d-87b5-4868-bb9c-c77908628ce8.MP4

While the above functionality is beyond a simple design refresh, it would be nice to eventually have it in super editor.

**Comment by matthew-carroll** [comment]
We have an iOS style toolbar in the `overlord` package. I'd like to bring the `follow_the_leader` package into `super_editor`, first, so that its easier to implement bounds on where hovering things can go. Then it should be easy to integrate the iOS style toolbar.

**Comment by matthew-carroll** [comment]
@Jethro87 do you know if there's a public spec for the Android and iOS toolbar designs?

**Comment by Jethro87** [comment]
@matthew-carroll It looks like, for iOS, the Flutter team has a new toolbar/context menu in master https://github.com/flutter/flutter/pull/117234 that you can review for design. I haven't had a chance to run the example app to verify the design, as the screenshot looks close but a bit off.

The `AdaptiveTextSelectionToolbar` class in master may be helpful as well: https://api.flutter.dev/flutter/material/AdaptiveTextSelectionToolbar-class.html

**Comment by matthew-carroll** [comment]
@angelosilvestre I was planning to bring in `follow_the_leader` for this, but I think we can have you take a stab at it without that. Feel free to bring in `overlord` for the iOS style toolbar, and let's see if you can use that toolbar, and introduce screen-edge spacing rules, without `follow_the_leader` for now.

**Comment by Jethro87** [comment]
For reference, there's a demo of the new floating toolbars under **Custom Context Menus** in the Flutter 3.7 article here: https://medium.com/flutter/whats-new-in-flutter-3-7-38cbea71133c

The demo under **Text magnifier** might be useful too.

**Comment by matthew-carroll** [comment]
@miguelcmedeiros would Superlist also like to have updated toolbars? Would this be relevant for Superlist use-cases?

**Comment by matthew-carroll** [comment]
@Jethro87 that magnifier demo was a big ambiguous. Do you think they mean that Flutter now uses the platform magnifier, i.e., the `FlutterActivity` on Android tells the OS to magnifier the Flutter pixels?

**Comment by Jethro87** [comment]
@matthew-carroll It doesn't look like it. Here's the relevant widgets:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/magnifier.dart

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/magnifier.dart

**Comment by angelosilvestre** [comment]
@Jethro87 Is the "Desired Android" from a specific Android version?

I'm testing on a Samsung M51 running Android 11 and this is what I get:

**Flutter regular `TextField`:**

![regular](https://user-images.githubusercontent.com/7597082/214956078-6235d600-a749-4bea-a145-80f86eca0154.png)

**Chrome**: 

![chrome](https://user-images.githubusercontent.com/7597082/214956250-56b8286c-6f99-40d0-89a9-78fb1b0d5c11.png)

Other apps seem to match the chrome screenshot.

**Comment by Jethro87** [comment]
@angelosilvestre I had tested with the Google Keep app, but it appears that Material guidelines are in line with what you're seeing (the rectangular version). That'll work fine for us. Thanks.
