### ISSUE TITLE
[SuperEditor] Ability to display layers below the document

### ISSUE THREAD

**Issue by jmatth** [superlistapp/super_editor#965]
SuperEditor currently supports displaying widgets above the document contents, which is useful for displaying things such as toolbars. However, there are certain cases where it may be necessary to display content below the document but above the gesture handling system. As an example, the current usecase I have is to display a box that allows selecting multiple blocks within a document. Doing so with the existing overlay system tints the text and caret slightly:

<img width="631" alt="Screenshot 2023-01-17 at 16 14 11" src="https://user-images.githubusercontent.com/1316184/213013935-eed07305-5b19-43cf-a9df-9bc423d503d8.png">

The tinting issue is resolved if there is a way to place a document layer behind the document:

<img width="631" alt="Screenshot 2023-01-17 at 16 13 58" src="https://user-images.githubusercontent.com/1316184/213014139-71a87283-4268-455b-b443-f32a6776f20c.png">

I already implemented a trivial working solution in my fork (https://github.com/BringingFire/super_editor/commit/0d5f1cd05b70c0d6bac036b1fb610c63844ec39f). If there is interest in having this functionality merged in I'm happy to add tests and open a PR.

It's also possible there is a way to accomplish the same effect using the existing overlay system combined with blend modes or some other functionality within Flutter, but my attempts to do so were unsuccessful.

**Comment by matthew-carroll** [comment]
Looking at your example, is there a reason that this layer needs to sit above the gesture system?

I'm wondering, if we stick a layer between the gestures and content, will someone also ask for a layer below everything? Will there be more layers added beyond that? It would be a simpler world if we said that there's one layer on top of everything, and another layer beneath everything...

**Comment by jmatth** [comment]
> is there a reason that this layer needs to sit above the gesture system?

We will need a way to have widgets on this layer block input to the gesture system. The most obvious way I see to do this is to have it sit above the gesture system and use some combination of opaque mouse regions and `HitTestBehavior.opaque`. If there is a way to accomplish the same same thing with a layer underneath everything then that's fine too. Glancing at the code that might require changing the behavior of the `RawGestureDetector` in `DocumentMouseInteractor`, which is currently set to `translucent`.

**Comment by matthew-carroll** [comment]
These widgets behind the content, can they truly span any type of content? Or will the background widgets be relegated to specific types of content?

I'm wondering if what we're really identifying here is a new type of node and component, which happen to contain other nodes and components...

**Comment by jmatth** [comment]
The plan is for this widget to span any type of content. Our specific use case is for the user to be able to select one or more blocks in their entirety, then extract them into a new document.

**Comment by matthew-carroll** [comment]
Ok. Makes sense. Seems like something we should let you do.

**Comment by matthew-carroll** [comment]
@jmatth can you let me know if this behavior is now possible with the latest widget tree structure in `SuperEditor`?

**Comment by jmatth** [comment]
Sorry, thought I responded to this. This works for me in the latest version of super_editor. I think we can close this.

**Comment by raulmabe-labhouse** [comment]
Hi! @jmatth is the original implementation still the one you are using, now that SuperEditor has changed the widget tree?

I am trying to achieve the same effect as you, so I am highly interested on how did you manage, as I can't seem to find a way
