### ISSUE TITLE
[SuperEditor][Question] How to execute Keyboard Actions on a SoftwareKeyboard

### ISSUE THREAD

**Issue by raulmabe-labhouse** [superlistapp/super_editor#972]
I tried adding custom functions to `keyboardActions` property, but can't get them to be executed with a Software Keyboard

**Comment by raulmabe-labhouse** [comment]
I have the IME configuration enabled for iOS, but `keyboardActions` is not executed yet. 
```
              inputSource: TextInputSource.ime,
              gestureMode: DocumentGestureMode.iOS,
```

Is this the expected behaviour? @matthew-carroll.  I am on stable branch.

**Comment by matthew-carroll** [comment]
Can you provide a full reproduction of the issue? I don't think we have enough information to assess the problem.

**Comment by raulmabe-labhouse** [comment]
When a hardware keyboard is connected, you can customise some keyboard actions through `keyboardActions` property, that is wired to a `Focus` widget; which only works on hardware keyboards.

I intend to customize the experience of the editor (i.e. insert a new bullet point automatically after each header) for all platforms, but as `keyboardActions` do not work on software keyboards I can't.

Maybe it will be possible after adding https://github.com/superlistapp/super_editor/issues/748 we can add this feature for software keyboards?

**Comment by raulmabe-labhouse** [comment]
As this started issue started as a doubt and has evolved since, I will open another issue with a more clear goal: #994
