### ISSUE TITLE
[SuperEditor][SuperReader] Empty ParagraphNode's don't adhere to stylesheet rules

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#973]
It seems that no matter the stylesheet I supply to SuperEditor or SuperReader, if there is an empty ParagraphNode, it takes up something like 16px space (rather than applying the corresponding `StyleRule` that targets `BlockSelector('paragraph')`.

Here's what I'm doing:

I supply a stylesheet to our main `SuperEditor` widget where users write. The paragraph rule looks something like this:

```
StyleRule(
          const BlockSelector('paragraph'),
          (doc, docNode) {
            return {
              'padding': const CascadingPadding.only(top: 12),
              'textStyle': TextStyle(
                    fontSize: 18,
                    height: 1.6,
                  ),
            };
          },
        ),
```

However, in another part of our app, we use `SuperReader` to display a "mini" view of documents. I supply a separate "mini" stylesheet where the paragraph rule looks something like this:

```
StyleRule(
          const BlockSelector('paragraph'),
          (doc, docNode) {
            return {
              'padding': const CascadingPadding.only(top: 6),
              'textStyle': TextStyle(
                    fontSize: 6,
                    height: 1.5,
                  ),
            };
          },
        ),
```

Here's a series of screenshots showing what's happening:

### 1. SuperEditor with full-size stylesheet and empty paragraph nodes
![super_editor_full_stylesheet_with_spaces](https://user-images.githubusercontent.com/6467808/213530903-44228033-25fd-4e19-8625-9b4524745e9b.png)

### 2. SuperReader with mini stylesheet and empty paragraph nodes
![super_reader_mini_stylesheet_with_spaces](https://user-images.githubusercontent.com/6467808/213531110-525a7b63-c58c-41ce-b0dd-58a05d891a26.png)

### 3. SuperEditor with full-size stylesheet and no empty paragraph nodes
![super_editor_full_stylesheet_with_no_spaces](https://user-images.githubusercontent.com/6467808/213531382-949c15a8-ba93-44f2-a9e0-2b3d3709d825.png)

### 4. SuperReader with mini stylesheet and no empty paragraph nodes
![super_reader_mini_stylesheet_with_no_spaces](https://user-images.githubusercontent.com/6467808/213531522-0fa73303-4e2d-4ebd-8b2a-d66b29e37c14.png)

If you compare 2 and 4, you can see that the empty nodes take up far more space than they do when they contain characters.

The next comparison is two `SuperReader` widgets with the same "mini" stylesheet side-by-side. They contain precisely the same document, except that, in the right image, there is a single empty space in the `ParagraphNode` after the first "Hello".

![super_reader_compare_mini_stylesheet_spaces](https://user-images.githubusercontent.com/6467808/213533322-c227c3d7-a6bd-4793-8593-77d5808d14cc.png)

As you can see, even adding a single character to the otherwise empty `ParagraphNode` drastically changes the size of the node.

Is there an "empty TextNode" stylesheet rule I can apply, or a way to override whatever default styling is being set to empty nodes?

**Comment by angelosilvestre** [comment]
@Jethro87 Could you please share a minimal code sample? I wasn't able to reproduce the issue.

**Comment by Jethro87** [comment]
@angelosilvestre Will do. It will take a couple of days, so I'll close this ticket for now. When I have the repro ready I'll open it back up. Thanks.
