### ISSUE TITLE
[SuperEditor] Combination "+s results in jumpy caret

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#979]
Steps to reproduce:
* Open Demo app (IME)
* In the editor type`"s`

Result: 

https://user-images.githubusercontent.com/31278849/213761108-7861f943-af07-49aa-a002-81de454dcf1b.mov

**Comment by miguelcmedeiros** [comment]
This will happen with other combinations like `'s`, `~s`, `"r`, `~r`, etc.

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by matthew-carroll** [comment]
We believe that this issue is now solved with Angelo's recent work. @miguelcmedeiros can you check again and close the ticket if it's resolved?

**Comment by miguelcmedeiros** [comment]
@angelosilvestre it's fixed!!
Great work 🙌
