### ISSUE TITLE
[SuperEditor][BUG] Installation problem

### ISSUE THREAD

**Issue by bynicodevelop** [superlistapp/super_editor#986]
When integrating SuperEditor on an existing project, I get the following error.

<img width="622" alt="CleanShot 2023-01-21 at 07 57 51@2x" src="https://user-images.githubusercontent.com/32275195/213848010-47967195-7a17-4627-9b9b-72732883b64a.png">

Here are the dependencies already installed.

![CleanShot 2023-01-21 at 08 01 37@2x](https://user-images.githubusercontent.com/32275195/213848045-271e5a4a-a5c8-4f1b-bf33-afdcc34a871a.png)

My configuration : 

<img width="620" alt="CleanShot 2023-01-21 at 08 03 52@2x" src="https://user-images.githubusercontent.com/32275195/213848126-6575a480-5d24-46b0-bcb6-179bffb5cf0c.png">

I also tried to install directly via Github on the main branch, but I have the same problem.

I hope this information can help you. I am available if you have any other questions.

**Comment by matthew-carroll** [comment]
@bynicodevelop can you confirm whether this issue is still happening with the latest Super Editor from GitHub and the latest Flutter stable release?

**Comment by matthew-carroll** [comment]
I'm going to close this issue due to inactivity.
